import { NextRequest,NextResponse } from "next/server";
import { requireRole } from "../../auth/security";
import { validateAiModel,type AiModelStatus } from "@/app/ai/model-inventory";
import { cleanAiText,redactSensitiveText } from "@/app/ai/security";
import { aiRuntime,getAiSettings,recordAiEvent } from "@/app/ai/storage";
const json=(data:unknown,status=200)=>NextResponse.json(data,{status,headers:{"cache-control":"no-store"}});
const map=(r:Record<string,unknown>)=>({id:r.id,systemName:r.system_name,modelName:r.model_name,vendor:r.vendor,purpose:r.purpose,owner:r.owner,deployment:r.deployment,region:r.region,dataClassification:r.data_classification,autonomy:r.autonomy,affectedUsers:Number(r.affected_users||0),impact:Number(r.impact),likelihood:Number(r.likelihood),dataSensitivity:Number(r.data_sensitivity),autonomyRisk:Number(r.autonomy_risk),controlMaturity:Number(r.control_maturity),inherentScore:Number(r.inherent_score),residualScore:Number(r.residual_score),riskTier:r.risk_tier,controls:r.controls,status:r.status,reviewDate:r.review_date,overdue:String(r.review_date)<new Date().toISOString().slice(0,10)&&r.status==="approved",createdBy:r.created_by,updatedBy:r.updated_by,updatedAt:r.updated_at,approvedBy:r.approved_by,approvedAt:r.approved_at,decisionNote:r.decision_note});
const csv=(rows:ReturnType<typeof map>[])=>{const cell=(v:unknown)=>{const raw=String(v??""),safe=/^[=+\-@]/.test(raw)?`'${raw}`:raw;return `"${safe.replace(/"/g,'""')}"`;};return [["Sistem","Model","Sağlayıcı","Sorumlu","Dağıtım","Bölge","Veri Sınıfı","Otonomi","Risk","Skor","Durum","İnceleme"],...rows.map(r=>[r.systemName,r.modelName,r.vendor,r.owner,r.deployment,r.region,r.dataClassification,r.autonomy,r.riskTier,r.residualScore,r.status,r.reviewDate])].map(row=>row.map(cell).join(",")).join("\n");};

export async function GET(req:NextRequest){const access=await requireRole(req,["Admin"]);if(access.response)return access.response;const {DB}=await aiRuntime(),result=await DB.prepare("SELECT * FROM ai_model_inventory ORDER BY CASE risk_tier WHEN 'Critical' THEN 0 WHEN 'High' THEN 1 WHEN 'Medium' THEN 2 ELSE 3 END,review_date LIMIT 500").all<Record<string,unknown>>(),models=(result.results||[]).map(map);if(req.nextUrl.searchParams.get("format")==="csv")return new NextResponse(`\uFEFF${csv(models)}`,{headers:{"content-type":"text/csv; charset=utf-8","content-disposition":"attachment; filename=fornost-ai-model-inventory.csv","cache-control":"no-store"}});const settings=await getAiSettings(DB);return json({models,configuredProvider:settings?{provider:settings.provider,model:settings.model,enabled:!!settings.enabled}:null,summary:{total:models.length,approved:models.filter(m=>m.status==="approved").length,highRisk:models.filter(m=>["High","Critical"].includes(String(m.riskTier))).length,overdue:models.filter(m=>m.overdue).length}});}

export async function POST(req:NextRequest){const access=await requireRole(req,["Admin"]);if(access.response)return access.response;if(Number(req.headers.get("content-length")||0)>24_576)return json({error:"Model envanteri isteği çok büyük."},413);const body=await req.json().catch(()=>({}));let v;try{v=validateAiModel(body);}catch(error){return json({error:error instanceof Error?error.message:"Model doğrulanamadı."},400);}const {DB}=await aiRuntime(),id=`AIM-${crypto.randomUUID()}`,now=new Date().toISOString();await DB.prepare(`INSERT INTO ai_model_inventory(id,system_name,model_name,vendor,purpose,owner,deployment,region,data_classification,autonomy,affected_users,impact,likelihood,data_sensitivity,autonomy_risk,control_maturity,inherent_score,residual_score,risk_tier,controls,status,review_date,created_by,created_at,updated_by,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(id,v.systemName,v.modelName,v.vendor,v.purpose,v.owner,v.deployment,v.region,v.dataClassification,v.autonomy,v.affectedUsers,v.impact,v.likelihood,v.dataSensitivity,v.autonomyRisk,v.controlMaturity,v.inherentScore,v.residualScore,v.riskTier,v.controls,"draft",v.reviewDate,access.actor.email,now,access.actor.email,now).run();await recordAiEvent(DB,{actor:access.actor.email,action:"model-inventory-create",status:"success",detail:`${id} created; residual risk ${v.riskTier} (${v.residualScore})`});return json({id,riskTier:v.riskTier,residualScore:v.residualScore},201);}

export async function PUT(req:NextRequest){const access=await requireRole(req,["Admin"]);if(access.response)return access.response;const body=await req.json().catch(()=>({})),id=cleanAiText(body.id,100);let v;try{v=validateAiModel(body);}catch(error){return json({error:error instanceof Error?error.message:"Model doğrulanamadı."},400);}const {DB}=await aiRuntime(),now=new Date().toISOString(),result=await DB.prepare(`UPDATE ai_model_inventory SET system_name=?,model_name=?,vendor=?,purpose=?,owner=?,deployment=?,region=?,data_classification=?,autonomy=?,affected_users=?,impact=?,likelihood=?,data_sensitivity=?,autonomy_risk=?,control_maturity=?,inherent_score=?,residual_score=?,risk_tier=?,controls=?,review_date=?,updated_by=?,updated_at=? WHERE id=? AND status='draft'`).bind(v.systemName,v.modelName,v.vendor,v.purpose,v.owner,v.deployment,v.region,v.dataClassification,v.autonomy,v.affectedUsers,v.impact,v.likelihood,v.dataSensitivity,v.autonomyRisk,v.controlMaturity,v.inherentScore,v.residualScore,v.riskTier,v.controls,v.reviewDate,access.actor.email,now,id).run();if(Number(result.meta?.changes||0)!==1)return json({error:"Yalnız taslak model kayıtları düzenlenebilir."},409);await recordAiEvent(DB,{actor:access.actor.email,action:"model-inventory-edit",status:"success",detail:`${id} rescored ${v.riskTier} (${v.residualScore})`});return json({ok:true});}

export async function PATCH(req:NextRequest){const access=await requireRole(req,["Admin"]);if(access.response)return access.response;const body=await req.json().catch(()=>({})),id=cleanAiText(body.id,100),status=cleanAiText(body.status,20) as AiModelStatus,note=redactSensitiveText(body.note,800),confirmation=cleanAiText(body.confirmation,30);const expected:Record<AiModelStatus,string>={draft:"",approved:"ONAYLA",suspended:"ASKIYA AL",retired:"EMEKLİ ET"};if(!id||!["approved","suspended","retired"].includes(status)||note.length<5||confirmation!==expected[status])return json({error:"Karar notu ve doğru onay metni gereklidir."},400);const {DB}=await aiRuntime(),now=new Date().toISOString(),existing=await DB.prepare("SELECT risk_tier,control_maturity FROM ai_model_inventory WHERE id=?").bind(id).first<Record<string,unknown>>();if(!existing)return json({error:"Model kaydı bulunamadı."},404);if(status==="approved"&&String(existing.risk_tier)==="Critical"&&Number(existing.control_maturity)<4)return json({error:"Kritik riskli model, kontrol olgunluğu en az 4 olmadan onaylanamaz."},409);const result=await DB.prepare("UPDATE ai_model_inventory SET status=?,approved_by=?,approved_at=?,decision_note=?,updated_by=?,updated_at=? WHERE id=? AND status<>?").bind(status,status==="approved"?access.actor.email:null,status==="approved"?now:null,note,access.actor.email,now,id,status).run();if(Number(result.meta?.changes||0)!==1)return json({error:"Model zaten bu durumda."},409);await recordAiEvent(DB,{actor:access.actor.email,action:`model-inventory-${status}`,status:"success",detail:`${id} ${status}`});return json({ok:true});}

export async function DELETE(req:NextRequest){const access=await requireRole(req,["Admin"]);if(access.response)return access.response;const body=await req.json().catch(()=>({})),id=cleanAiText(body.id,100);if(body.confirmation!=="SİL")return json({error:"SİL onayı gereklidir."},400);const {DB}=await aiRuntime(),result=await DB.prepare("DELETE FROM ai_model_inventory WHERE id=? AND status='draft'").bind(id).run();if(Number(result.meta?.changes||0)!==1)return json({error:"Yalnız taslak model kayıtları silinebilir."},409);await recordAiEvent(DB,{actor:access.actor.email,action:"model-inventory-delete",status:"success",detail:`${id} deleted`});return json({ok:true});}
