import { createAiModel } from "@/app/ai/model-drafts";
import { aiRecordQueryId,readAiRecords } from "@/app/ai/record-reads";
import { NextRequest,NextResponse } from "next/server";
import { requireRole } from "../../auth/security";
import { editAiModelDraft,deleteAiModelDraft } from "@/app/ai/model-drafts";
import { applyAiModelDecision } from "@/app/ai/model-decisions";
import { validateAiModel } from "@/app/ai/model-inventory";
import { cleanAiText,redactSensitiveText } from "@/app/ai/security";
import { aiRuntime,getAiSettings } from "@/app/ai/storage";
const json=(data:unknown,status=200)=>NextResponse.json(data,{status,headers:{"cache-control":"no-store"}});
const map=(r:Record<string,unknown>)=>({id:r.id,systemName:r.system_name,modelName:r.model_name,vendor:r.vendor,purpose:r.purpose,owner:r.owner,deployment:r.deployment,region:r.region,dataClassification:r.data_classification,autonomy:r.autonomy,affectedUsers:Number(r.affected_users||0),impact:Number(r.impact),likelihood:Number(r.likelihood),dataSensitivity:Number(r.data_sensitivity),autonomyRisk:Number(r.autonomy_risk),controlMaturity:Number(r.control_maturity),inherentScore:Number(r.inherent_score),residualScore:Number(r.residual_score),riskTier:r.risk_tier,controls:r.controls,status:r.status,reviewDate:r.review_date,overdue:String(r.review_date)<new Date().toISOString().slice(0,10)&&r.status==="approved",createdBy:r.created_by,updatedBy:r.updated_by,updatedAt:r.updated_at,approvedBy:r.approved_by,approvedAt:r.approved_at,decisionNote:r.decision_note});
const csv=(rows:ReturnType<typeof map>[])=>{const cell=(v:unknown)=>{const raw=String(v??""),safe=/^[=+\-@]/.test(raw)?`'${raw}`:raw;return `"${safe.replace(/"/g,'""')}"`;};return [["Sistem","Model","Sağlayıcı","Sorumlu","Dağıtım","Bölge","Veri Sınıfı","Otonomi","Risk","Skor","Durum","İnceleme"],...rows.map(r=>[r.systemName,r.modelName,r.vendor,r.owner,r.deployment,r.region,r.dataClassification,r.autonomy,r.riskTier,r.residualScore,r.status,r.reviewDate])].map(row=>row.map(cell).join(",")).join("\n");};

export async function GET(req:NextRequest){const access=await requireRole(req,["Admin"]);if(access.response)return access.response;let recordId:string|null;try{recordId=aiRecordQueryId(req.nextUrl.searchParams);}catch{return json({error:"Geçerli bir kayıt kimliği gereklidir."},400);}const {DB}=await aiRuntime(),result=await readAiRecords(DB,"models",recordId),models=(result.results||[]).map(map);if(req.nextUrl.searchParams.get("format")==="csv")return new NextResponse(`\uFEFF${csv(models)}`,{headers:{"content-type":"text/csv; charset=utf-8","content-disposition":"attachment; filename=fornost-ai-model-inventory.csv","cache-control":"no-store"}});const settings=await getAiSettings(DB);return json({models,configuredProvider:settings?{provider:settings.provider,model:settings.model,enabled:!!settings.enabled}:null,summary:{total:models.length,approved:models.filter(m=>m.status==="approved").length,highRisk:models.filter(m=>["High","Critical"].includes(String(m.riskTier))).length,overdue:models.filter(m=>m.overdue).length}});}

export async function POST(req:NextRequest){const access=await requireRole(req,["Admin"]);if(access.response)return access.response;if(Number(req.headers.get("content-length")||0)>24_576)return json({error:"Model envanteri isteği çok büyük."},413);const body=await req.json().catch(()=>({}));let v;try{v=validateAiModel(body);}catch(error){return json({error:error instanceof Error?error.message:"Model doğrulanamadı."},400);}const {DB}=await aiRuntime();try{return json(await createAiModel(DB,v,access.actor.email),201);}catch{return json({error:"Model oluşturulamadı. Güncel listeyi kontrol edip tekrar deneyin."},503);}}

export async function PUT(req:NextRequest){const access=await requireRole(req,["Admin"]);if(access.response)return access.response;const body=await req.json().catch(()=>null);if(!body||typeof body!=="object"||Array.isArray(body))return json({error:"Geçerli işlem gövdesi gereklidir."},400);const id=cleanAiText(body.id,100);let v;try{v=validateAiModel(body);}catch(error){return json({error:error instanceof Error?error.message:"Model doğrulanamadı."},400);}const {DB}=await aiRuntime();try{const result=await editAiModelDraft(DB,{id,value:v,actor:access.actor.email,expectedUpdatedAt:cleanAiText(body.expectedUpdatedAt,40)});if(result.status!==200)return json({error:result.error},result.status);return json({ok:true});}catch{return json({error:"Model kaydedilemedi. Güncel kaydı kontrol edip tekrar deneyin."},503);}}

export async function PATCH(req:NextRequest){
 const access=await requireRole(req,["Admin"]);if(access.response)return access.response;
 const body=await req.json().catch(()=>null);if(!body||typeof body!=="object"||Array.isArray(body))return json({error:"Geçerli işlem gövdesi gereklidir."},400);const id=cleanAiText(body.id,100),status=cleanAiText(body.status,20),note=redactSensitiveText(body.note,800),confirmation=cleanAiText(body.confirmation,30);
 if(!id||!["approved","suspended"].includes(status)||note.length<5||confirmation!==(status==="approved"?"ONAYLA":"ASKIYA AL"))return json({error:status==="retired"?"Model yalnız doğrulanmış emeklilik planı üzerinden emekli edilebilir.":"Karar notu ve doğru onay metni gereklidir."},400);
 const {DB}=await aiRuntime();
 // Critical-risk policy and lifecycle checks also hold at the write boundary.
 try{const result=await applyAiModelDecision(DB,{id,status:status as "approved"|"suspended",expectedUpdatedAt:cleanAiText(body.expectedUpdatedAt,40),note,actor:access.actor.email});
 if(result.status!==200)return json({error:result.error},result.status);
 return json({ok:true,updatedAt:result.updatedAt});}
 catch{return json({error:"Model kararı kaydedilemedi. Güncel kaydı kontrol edip tekrar deneyin."},503);}
}

export async function DELETE(req:NextRequest){const access=await requireRole(req,["Admin"]);if(access.response)return access.response;const body=await req.json().catch(()=>null);if(!body||typeof body!=="object"||Array.isArray(body))return json({error:"Geçerli işlem gövdesi gereklidir."},400);const id=cleanAiText(body.id,100);if(body.confirmation!=="SİL")return json({error:"SİL onayı gereklidir."},400);const {DB}=await aiRuntime();try{const result=await deleteAiModelDraft(DB,{id,actor:access.actor.email,expectedUpdatedAt:cleanAiText(body.expectedUpdatedAt,40)});if(result.status!==200)return json({error:result.error},result.status);return json({ok:true});}catch{return json({error:"Model silinemedi. Güncel kaydı kontrol edip tekrar deneyin."},503);}}
