import { NextRequest,NextResponse } from "next/server";
import { requireRole } from "../../auth/security";
import { aiRuntime,getAiSettings } from "@/app/ai/storage";
import {getAiOperatingPolicy} from "@/app/ai/operating-policy";

const number=(value:unknown)=>Number(value||0);
const metricWindow=(value:string|null)=>{const days=Number(value);return [7,30,90].includes(days)?days:7;};
export async function GET(req:NextRequest){
  const access=await requireRole(req,["Admin"]);if(access.response)return access.response;
  const {DB}=await aiRuntime(),windowDays=metricWindow(req.nextUrl.searchParams.get("days")),since=new Date(Date.now()-windowDays*86400000).toISOString();
  const [settings,activity,drafts,published,tickets,daily,models,errors,governance,evaluations,evaluationCurrent,failover,providerHealth,agents,agentDrafts,knowledge,feedback,usage,operatingPolicy]=await Promise.all([
    getAiSettings(DB),
    DB.prepare(`SELECT COUNT(*) total,SUM(CASE WHEN status='success' THEN 1 ELSE 0 END) success,SUM(CASE WHEN status='error' THEN 1 ELSE 0 END) errors,SUM(CASE WHEN status='denied' THEN 1 ELSE 0 END) denied,ROUND(AVG(CASE WHEN latency_ms>0 THEN latency_ms END)) average_latency FROM ai_activity_logs WHERE created_at>=?`).bind(since).first<Record<string,unknown>>(),
    DB.prepare(`SELECT COUNT(*) total,SUM(CASE WHEN status='pending' THEN 1 ELSE 0 END) pending,SUM(CASE WHEN status='approved' THEN 1 ELSE 0 END) approved,SUM(CASE WHEN status='rejected' THEN 1 ELSE 0 END) rejected FROM ai_action_drafts`).first<Record<string,unknown>>(),
    DB.prepare("SELECT COUNT(*) total FROM ai_draft_publications WHERE published_at>=?").bind(since).first<Record<string,unknown>>(),
    DB.prepare("SELECT COUNT(*) total,SUM(CASE WHEN status='created' THEN 1 ELSE 0 END) created,SUM(CASE WHEN status='failed' THEN 1 ELSE 0 END) failed FROM ai_draft_tickets WHERE created_at>=?").bind(since).first<Record<string,unknown>>(),
    DB.prepare(`SELECT substr(created_at,1,10) day,COUNT(*) total,SUM(CASE WHEN status='success' THEN 1 ELSE 0 END) success,SUM(CASE WHEN status='error' THEN 1 ELSE 0 END) errors FROM ai_activity_logs WHERE created_at>=? GROUP BY substr(created_at,1,10) ORDER BY day`).bind(since).all<Record<string,unknown>>(),
    DB.prepare(`SELECT provider,model,COUNT(*) requests,SUM(CASE WHEN status='success' THEN 1 ELSE 0 END) success FROM ai_activity_logs WHERE created_at>=? GROUP BY provider,model ORDER BY requests DESC LIMIT 10`).bind(since).all<Record<string,unknown>>(),
    DB.prepare(`SELECT action,provider,model,detail,created_at FROM ai_activity_logs WHERE status='error' AND created_at>=? ORDER BY created_at DESC LIMIT 8`).bind(since).all<Record<string,unknown>>(),
    DB.prepare(`SELECT COUNT(*) total,SUM(CASE WHEN status='approved' THEN 1 ELSE 0 END) approved,SUM(CASE WHEN status='approved' AND review_date<date('now') THEN 1 ELSE 0 END) overdue FROM ai_use_cases`).first<Record<string,unknown>>(),
    DB.prepare(`SELECT COUNT(*) total,SUM(CASE WHEN status='passed' THEN 1 ELSE 0 END) passed FROM ai_eval_runs WHERE created_at>=?`).bind(since).first<Record<string,unknown>>(),
    DB.prepare(`SELECT COUNT(*) total,SUM(CASE WHEN latest.status='passed' THEN 1 ELSE 0 END) passed,SUM(CASE WHEN latest.id IS NULL THEN 1 ELSE 0 END) untested,SUM(CASE WHEN latest.status IN ('failed','error') THEN 1 ELSE 0 END) failing FROM ai_eval_cases c LEFT JOIN ai_eval_runs latest ON latest.id=(SELECT id FROM ai_eval_runs WHERE case_id=c.id ORDER BY created_at DESC LIMIT 1) WHERE c.enabled=1`).first<Record<string,unknown>>(),
    DB.prepare(`SELECT COUNT(*) total FROM ai_provider_health WHERE profile='fallback' AND status='success' AND created_at>=?`).bind(since).first<Record<string,unknown>>(),
    DB.prepare(`SELECT SUM(CASE WHEN status IN ('success','error') THEN 1 ELSE 0 END) total,SUM(CASE WHEN status='success' THEN 1 ELSE 0 END) success,SUM(CASE WHEN status='error' THEN 1 ELSE 0 END) errors,ROUND(AVG(CASE WHEN status IN ('success','error') AND latency_ms>0 THEN latency_ms END)) average_latency FROM ai_provider_health WHERE created_at>=?`).bind(since).first<Record<string,unknown>>(),
    DB.prepare(`SELECT COUNT(*) total,SUM(CASE WHEN status='approved' THEN 1 ELSE 0 END) approved,SUM(CASE WHEN status='failed' THEN 1 ELSE 0 END) failed FROM ai_agent_runs WHERE created_at>=?`).bind(since).first<Record<string,unknown>>(),
    DB.prepare(`SELECT COUNT(*) total FROM ai_agent_draft_links WHERE created_at>=?`).bind(since).first<Record<string,unknown>>(),
    DB.prepare(`SELECT COUNT(*) total,SUM(CASE WHEN s.status='approved' THEN 1 ELSE 0 END) approved,SUM(CASE WHEN s.status='draft' THEN 1 ELSE 0 END) drafts,SUM(CASE WHEN s.status='archived' THEN 1 ELSE 0 END) archived,SUM(CASE WHEN s.classification='Restricted' THEN 1 ELSE 0 END) restricted,SUM(CASE WHEN s.status='approved' THEN s.chunk_count ELSE 0 END) chunks,SUM(CASE WHEN s.status='approved' AND ((g.review_due_at IS NOT NULL AND g.review_due_at<date('now')) OR (g.review_due_at IS NULL AND s.approved_at<datetime('now','-180 days'))) THEN 1 ELSE 0 END) stale FROM ai_knowledge_sources s LEFT JOIN ai_knowledge_governance g ON g.source_id=s.id`).first<Record<string,unknown>>(),
    DB.prepare(`SELECT COUNT(*) total,SUM(CASE WHEN status IN ('open','in_review') THEN 1 ELSE 0 END) unresolved,SUM(CASE WHEN status IN ('open','in_review') AND severity IN ('high','critical') THEN 1 ELSE 0 END) high_risk,SUM(CASE WHEN status='resolved' THEN 1 ELSE 0 END) resolved FROM ai_feedback`).first<Record<string,unknown>>(),
    DB.prepare(`SELECT COUNT(*) calls,COALESCE(SUM(prompt_tokens+completion_tokens),0) tokens,COALESCE(SUM(estimated_cost_microunits),0) cost,SUM(CASE WHEN metered=0 THEN 1 ELSE 0 END) unmetered,(SELECT COUNT(*) FROM ai_budget_policies) policies,(SELECT COUNT(*) FROM ai_budget_policies p WHERE p.hard_limit=1 AND p.monthly_token_limit>0 AND COALESCE((SELECT SUM(l.prompt_tokens+l.completion_tokens) FROM ai_usage_ledger l WHERE l.profile=p.profile AND l.created_at>=date('now','start of month')),0)>=p.monthly_token_limit) exceeded FROM ai_usage_ledger WHERE created_at>=date('now','start of month')`).first<Record<string,unknown>>(),
    getAiOperatingPolicy(DB),
  ]);
  const total=number(activity?.total),success=number(activity?.success),reviewed=number(drafts?.approved)+number(drafts?.rejected);
  const evalTotal=number(evaluations?.total),evalPassed=number(evaluations?.passed),currentEvalTotal=number(evaluationCurrent?.total),currentEvalPassed=number(evaluationCurrent?.passed),currentEvalUntested=number(evaluationCurrent?.untested),currentEvalFailing=number(evaluationCurrent?.failing);
  const controls=[
    {id:"operating-policy",label:"AI operasyon politikası",status:operatingPolicy.emergencyStop?"attention":"ready",detail:operatingPolicy.emergencyStop?"Global acil durdurma etkin.":`Chat ${operatingPolicy.chatEnabled?"açık":"kapalı"} · Taslak ${operatingPolicy.draftsEnabled?"açık":"kapalı"} · Agent ${operatingPolicy.agentsEnabled?"açık":"kapalı"}`},
    {id:"provider",label:"AI sağlayıcısı",status:settings?.enabled?"ready":"missing",detail:settings?.enabled?`${settings.provider} · ${settings.model}`:"Etkin sağlayıcı yapılandırılmadı."},
    {id:"inventory",label:"Kullanım senaryosu envanteri",status:number(governance?.approved)>0&&number(governance?.overdue)===0?"ready":"attention",detail:`${number(governance?.approved)}/${number(governance?.total)} onaylı · ${number(governance?.overdue)} gecikmiş`},
    {id:"evaluations",label:"Model güvenlik testleri",status:currentEvalTotal>0&&currentEvalPassed===currentEvalTotal?"ready":"attention",detail:currentEvalTotal?`${currentEvalPassed}/${currentEvalTotal} etkin testin son koşumu başarılı · ${currentEvalFailing} başarısız · ${currentEvalUntested} çalıştırılmamış`:"Etkin test bulunmuyor."},
    {id:"knowledge",label:"Bilgi tabanı güncelliği",status:number(knowledge?.approved)>0&&number(knowledge?.stale)===0?"ready":"attention",detail:`${number(knowledge?.approved)} onaylı · ${number(knowledge?.stale)} gecikmiş · ${number(knowledge?.drafts)} taslak`},
    {id:"feedback",label:"AI geri bildirim triage",status:number(feedback?.high_risk)===0?"ready":"attention",detail:`${number(feedback?.unresolved)} açık/incelemede · ${number(feedback?.high_risk)} yüksek veya kritik`},
    {id:"budget",label:"AI kullanım bütçesi",status:number(usage?.exceeded)===0&&number(usage?.policies)>0?"ready":"attention",detail:`${number(usage?.tokens)} aylık token · ${number(usage?.policies)} yapılandırılmış profil · ${number(usage?.exceeded)} aşım`},
    {id:"operations",label:"Operasyon hataları",status:number(activity?.errors)===0&&number(tickets?.failed)===0&&number(agents?.failed)===0?"ready":"attention",detail:`${number(activity?.errors)} çağrı · ${number(tickets?.failed)} ticket · ${number(agents?.failed)} agent hatası`},
  ];
  return NextResponse.json({windowDays,activity:{total,success,errors:number(activity?.errors),denied:number(activity?.denied),successRate:total?Math.round(success*1000/total)/10:0,averageLatencyMs:number(activity?.average_latency)},providerHealth:{total:number(providerHealth?.total),success:number(providerHealth?.success),errors:number(providerHealth?.errors),successRate:number(providerHealth?.total)?Math.round(number(providerHealth?.success)*1000/number(providerHealth?.total))/10:0,averageLatencyMs:number(providerHealth?.average_latency)},drafts:{total:number(drafts?.total),pending:number(drafts?.pending),approved:number(drafts?.approved),rejected:number(drafts?.rejected),approvalRate:reviewed?Math.round(number(drafts?.approved)*1000/reviewed)/10:0},outputs:{recordPublications:number(published?.total),ticketsCreated:number(tickets?.created),ticketFailures:number(tickets?.failed)},governance:{total:number(governance?.total),approved:number(governance?.approved),overdue:number(governance?.overdue),evaluationRuns:evalTotal,evaluationPassRate:evalTotal?Math.round(evalPassed*1000/evalTotal)/10:0,evaluationCurrent:{total:currentEvalTotal,passed:currentEvalPassed,failing:currentEvalFailing,untested:currentEvalUntested},fallbackActivations:number(failover?.total)},agents:{runs:number(agents?.total),approved:number(agents?.approved),failed:number(agents?.failed),draftsCreated:number(agentDrafts?.total)},knowledge:{total:number(knowledge?.total),approved:number(knowledge?.approved),drafts:number(knowledge?.drafts),archived:number(knowledge?.archived),restricted:number(knowledge?.restricted),stale:number(knowledge?.stale),chunks:number(knowledge?.chunks)},feedback:{total:number(feedback?.total),unresolved:number(feedback?.unresolved),highRisk:number(feedback?.high_risk),resolved:number(feedback?.resolved)},usage:{calls:number(usage?.calls),tokens:number(usage?.tokens),estimatedCost:number(usage?.cost)/1_000_000,unmetered:number(usage?.unmetered),policies:number(usage?.policies),exceeded:number(usage?.exceeded)},controls,daily:daily.results||[],models:(models.results||[]).map(row=>({...row,successRate:number(row.requests)?Math.round(number(row.success)*1000/number(row.requests))/10:0})),recentErrors:(errors.results||[]).map(row=>({action:row.action,provider:row.provider,model:row.model,detail:row.detail,createdAt:row.created_at}))},{headers:{"cache-control":"no-store"}});
}
