/** Reviewed against vendor documentation on 2026-10-01. No secrets belong in this registry. */
export type LocalText = {tr:string;en:string};
export type ConnectorField = {key:string;label:LocalText;placeholder?:string;options?:string[]};
export type Dataset = {id:string;label:LocalText;path:string;permission:string;docs:string;root:string;pagination:"odata"|"link"|"cloudflare"|"gitlab"|"crowdstrike"|"offset"|"none";hint:LocalText};
export type ConnectorProfile = {id:string;name:string;category:string;auth:"microsoft"|"crowdstrike"|"bearer"|"gitlab"|"tenable"|"okta";origin:string;fields:ConnectorField[];secrets:ConnectorField[];datasets:Dataset[];setup:LocalText;limitations:LocalText};
const t=(tr:string,en:string):LocalText=>({tr,en});
const field=(key:string,label:string,placeholder?:string):ConnectorField=>({key,label:t(label,label),placeholder});
const msFields=[field("tenantId","Directory (Tenant) ID","00000000-0000-0000-0000-000000000000"),field("clientId","Application (Client) ID")];
const msSecret=[field("clientSecret","Client secret VALUE")];
const msSetup=t("Entra yönetim merkezinde tek kiracılı App registration oluşturun. Aşağıdaki API uygulama iznini ekleyip Grant admin consent uygulayın. Client secret değerini (Secret ID değil) girin. Redirect URI gerekmez.","Create a single-tenant Entra app registration. Add the application permission below and grant admin consent. Enter the client secret VALUE, not its ID. No redirect URI is needed.");
const msLimits=t("Bu profil Microsoft global bulut içindir. İlgili ürün lisansı gerekir. Sertifika, managed identity ve ulusal bulutlar bu akışta desteklenmez.","This profile targets Microsoft global cloud and requires the relevant product licence. Certificates, managed identity and national clouds are not supported by this flow.");
const ds=(id:string,tr:string,en:string,path:string,permission:string,docs:string,root="value",pagination:Dataset["pagination"]="odata",hint=t("İzin verilen kapsamın salt okunur anlık görüntüsü; tek başına uyumluluk kararı değildir.","Read-only snapshot of the authorised scope; not a compliance verdict.")):Dataset=>({id,label:t(tr,en),path,permission,docs,root,pagination,hint});
const ms=(id:string,name:string,category:string,datasets:Dataset[],origin="https://graph.microsoft.com",fields=msFields):ConnectorProfile=>({id,name,category,auth:"microsoft",origin,fields,secrets:msSecret,datasets,setup:origin==="https://management.azure.com"?t("Entra üzerinde tek kiracılı App registration oluşturun. Servis sorumlusuna aşağıdaki kapsamda Azure RBAC rolünü atayın. Client secret VALUE girin. Graph API izni veya redirect URI gerekmez.","Create a single-tenant Entra app registration. Assign its service principal the Azure RBAC role below at the specified scope. Enter the client secret VALUE. No Graph API permission or redirect URI is required."):msSetup,limitations:msLimits});
const scoped=t("Yalnızca bu uygulamanın okuyabildiği kayıtlar toplanır. En fazla 20 sayfa / 1 MB; sınır aşılırsa kısmi veri başarılı sayılmaz.","Only records visible to this application are collected. Maximum 20 pages / 1 MB; exceeding a limit fails rather than passing partial data.");
export const connectorProfiles:ConnectorProfile[]=[
 ms("microsoft-graph","Microsoft 365 / Graph","Cloud & SaaS",[
  ds("secure-scores","Secure Score geçmişi","Secure Score history","/v1.0/security/secureScores","SecurityEvents.Read.All","https://learn.microsoft.com/en-us/graph/api/security-list-securescores?view=graph-rest-1.0"),
  ds("score-controls","Secure Score kontrol profilleri","Secure Score control profiles","/v1.0/security/secureScoreControlProfiles","SecurityEvents.Read.All","https://learn.microsoft.com/en-us/graph/api/security-list-securescorecontrolprofiles?view=graph-rest-1.0")]),
 ms("entra-id","Microsoft Entra ID","IAM, PAM & IGA",[ds("conditional-access","Conditional Access politikaları","Conditional Access policies","/v1.0/identity/conditionalAccess/policies","Policy.Read.All","https://learn.microsoft.com/en-us/graph/api/conditionalaccessroot-list-policies?view=graph-rest-1.0")]),
 ms("intune","Microsoft Intune","Cloud & SaaS",[ds("managed-devices","Cihaz uyumluluk envanteri","Managed-device compliance inventory","/v1.0/deviceManagement/managedDevices?$select=id,deviceName,operatingSystem,osVersion,complianceState,lastSyncDateTime,isEncrypted","DeviceManagementManagedDevices.Read.All","https://learn.microsoft.com/en-us/graph/api/intune-devices-manageddevice-list?view=graph-rest-1.0")]),
 ms("defender-xdr","Microsoft Defender XDR","XDR, EDR & SIEM",[ds("incidents","Güvenlik olayları","Security incidents","/v1.0/security/incidents","SecurityIncident.Read.All","https://learn.microsoft.com/en-us/graph/api/security-list-incidents?view=graph-rest-1.0")]),
 ms("defender-endpoint","Microsoft Defender for Endpoint","XDR, EDR & SIEM",[ds("machines","Endpoint sağlık envanteri","Endpoint health inventory","/api/machines?$top=1000&$skip=0","WindowsDefenderATP → Machine.Read.All","https://learn.microsoft.com/en-us/defender-endpoint/api/get-machines","value","offset")],"https://api.security.microsoft.com"),
 ms("sentinel","Microsoft Sentinel","XDR, EDR & SIEM",[ds("incidents","Workspace olayları","Workspace incidents","/subscriptions/{subscriptionId}/resourceGroups/{resourceGroup}/providers/Microsoft.OperationalInsights/workspaces/{workspace}/providers/Microsoft.SecurityInsights/incidents?api-version=2025-09-01","Azure RBAC: Microsoft Sentinel Reader (workspace scope)","https://learn.microsoft.com/en-us/rest/api/securityinsights/incidents/list?view=rest-securityinsights-2025-09-01")],"https://management.azure.com",[...msFields,field("subscriptionId","Subscription ID"),field("resourceGroup","Resource group"),field("workspace","Log Analytics workspace")]),
 ms("azure-resources","Azure Resource Manager","Cloud & SaaS",[ds("resources","Abonelik varlık envanteri","Subscription resource inventory","/subscriptions/{subscriptionId}/resources?api-version=2021-04-01","Azure RBAC: Reader (subscription scope)","https://learn.microsoft.com/en-us/rest/api/resources/resources/list?view=rest-resources-2021-04-01")],"https://management.azure.com",[...msFields,field("subscriptionId","Subscription ID")]),
 {id:"cloudflare",name:"Cloudflare",category:"Cloud & SaaS",auth:"bearer",origin:"https://api.cloudflare.com",fields:[],secrets:[field("token","API token")],datasets:[ds("zones","Zone envanteri","Zone inventory","/client/v4/zones?per_page=50","Zone → Zone → Read","https://developers.cloudflare.com/api/resources/zones/methods/list/","result","cloudflare")],setup:t("Profil > API Tokens üzerinden yalnızca seçili zone'larda Zone Read yetkili token oluşturun. Global API Key kullanmayın.","Create an API token with Zone Read for selected zones. Do not use the Global API Key."),limitations:scoped},
 {id:"github",name:"GitHub",category:"Cloud & SaaS",auth:"bearer",origin:"https://api.github.com",fields:[field("organization","Organization")],secrets:[field("token","Fine-grained PAT")],datasets:[ds("repositories","Organizasyon depo envanteri","Organisation repository inventory","/orgs/{organization}/repos?per_page=100","Repository Metadata: Read","https://docs.github.com/en/rest/repos/repos#list-organization-repositories","$","link")],setup:t("Organizasyon ve depolarla sınırlandırılmış fine-grained PAT oluşturun; kurum onayını/SSO gereksinimini tamamlayın.","Create a fine-grained PAT scoped to the organisation and repositories; complete organisation approval/SSO requirements."),limitations:t("Depo envanteri alınır; kod taraması, branch protection veya tüm depolara erişim garantisi değildir. Token süresini kurumunuz yönetin.","Collects repository inventory, not code scans or branch protection. It cannot prove access to every repository. Manage token expiry in your organisation.")},
 {id:"gitlab",name:"GitLab.com",category:"Cloud & SaaS",auth:"gitlab",origin:"https://gitlab.com",fields:[],secrets:[field("token","Personal / group access token")],datasets:[ds("projects","Erişilebilir proje envanteri","Accessible project inventory","/api/v4/projects?membership=true&per_page=100","read_api","https://docs.gitlab.com/api/projects/#list-all-projects","$","gitlab")],setup:t("En az yetkili servis hesabı veya grup token'ı ve read_api kapsamı kullanın.","Use a least-privilege service account or group token with read_api scope."),limitations:t("Bu profil GitLab.com içindir. Self-managed kurulumlar için özel HTTPS collector gerekir.","This profile targets GitLab.com. Self-managed deployments require a custom HTTPS collector.")},
 {id:"tenable",name:"Tenable Vulnerability Management",category:"Data, DB & Application",auth:"tenable",origin:"https://cloud.tenable.com",fields:[],secrets:[field("accessKey","Access key"),field("secretKey","Secret key")],datasets:[ds("scans","Tarama envanteri ve son durum","Scan inventory and last status","/scans","CAN VIEW scan permission","https://developer.tenable.com/reference/scans-list","scans","none")],setup:t("Tenable kullanıcı profilinde API Keys oluşturun. Access key ve secret key birlikte, şifreli saklanır. Hesaba yalnızca ilgili taramaları görüntüleme izni verin.","Generate API keys in the Tenable user profile. Both keys are stored encrypted. Grant the account view access only to relevant scans."),limitations:t("Bu profil bulut VM tarama listesidir; Nessus/SC/Enclave veya tüm zafiyet export'u değildir.","This profile lists cloud VM scans; it is not Nessus/SC/Enclave or a full vulnerability export.")},
 {id:"crowdstrike",name:"CrowdStrike Falcon",category:"XDR, EDR & SIEM",auth:"crowdstrike",origin:"https://api.crowdstrike.com",fields:[{...field("region","Region"),options:["us-1","us-2","eu-1"]},field("clientId","Client ID")],secrets:[field("clientSecret","Client secret")],datasets:[ds("hosts","Host kimlik envanteri","Host ID inventory","/devices/queries/devices/v1?limit=100","Hosts: READ","https://developer.crowdstrike.com/api-reference/collections/hosts/","resources","crowdstrike")],setup:t("Falcon > API clients and keys altında Hosts READ kapsamlı client oluşturun ve tenant bölgesini seçin. Erişim token'ını sistem alır.","Create a Falcon API client with Hosts READ and select the tenant region. The server obtains the access token."),limitations:t("Bu veri seti host ID'lerini toplar; sensor ayrıntıları, prevention politikaları ve detections içermez.","This dataset collects host IDs, not sensor details, prevention policies or detections.")},
 {id:"okta",name:"Okta",category:"IAM, PAM & IGA",auth:"okta",origin:"",fields:[field("serviceUrl","Okta org URL","https://example.okta.com")],secrets:[field("token","SSWS API token")],datasets:[ds("users","Kullanıcı yaşam döngüsü envanteri","User lifecycle inventory","/api/v1/users?limit=200","Read-only admin, scoped to required users","https://developer.okta.com/docs/api/openapi/okta-management/management/tags/user/","$","link")],setup:t("En az yetkili salt okunur yöneticiye ait API token oluşturun; org URL'sini girin. Token kullanıcının yetkilerini devralır.","Create an API token owned by a least-privilege read-only admin and enter the org URL. The token inherits its owner's privileges."),limitations:t("SSWS token akışı desteklenir; private_key_jwt tabanlı OAuth service app bu sürümde desteklenmez. Kullanıcı envanteri hassas veri içerebilir.","Supports SSWS tokens; OAuth service apps using private_key_jwt are not supported here. User inventory may contain personal data.")},
 {id:"sonarqube",name:"SonarQube Server",category:"Data, DB & Application",auth:"bearer",origin:"",fields:[field("serviceUrl","SonarQube URL","https://sonarqube.example.com"),field("projectKey","Project key")],secrets:[field("token","User token")],datasets:[ds("quality-gate","Proje quality gate sonucu","Project quality gate status","/api/qualitygates/project_status?projectKey={projectKey}","Browse project","https://docs.sonarsource.com/sonarqube-server/extension-guide/web-api","projectStatus","none")],setup:t("Proje için Browse yetkili kullanıcı token'ı oluşturun. Bu profil sunucunun Web API quality gate sonucunu okur.","Create a user token with Browse permission on the project. This profile reads the server Web API quality gate result."),limitations:t("Sunucunuzda bu Web API'nin bulunduğunu /web_api sayfasında doğrulayın. Kök URL kullanılır; alt dizin kurulumu desteklenmez. SonarQube Cloud ayrı bir üründür.","Verify this Web API exists on your server's /web_api page. Root URL deployments only; context paths are unsupported. SonarQube Cloud is a separate product.")},
];
export const connectorProfile=(id:unknown)=>connectorProfiles.find(p=>p.id===id);
export type ConnectorDraft={name:string;vendor:string;category:string;driver:string;baseUrl:string;authType:string;headerName:string;secret:string;providerId?:string;dataset?:string;providerConfig?:Record<string,string>;credentials?:Record<string,string>};
export function newConnectorDraft(id=""):ConnectorDraft {const p=connectorProfile(id);return {name:p?.name||"",vendor:p?.name||"Generic REST / JSON API",category:p?.category||"Work & Custom",driver:p?"provider-v1":"rest-json",baseUrl:"",authType:"bearer",headerName:"x-api-key",secret:"",providerId:p?.id||"",dataset:p?.datasets[0]?.id||"",providerConfig:p?.id==="crowdstrike"?{region:"us-1"}:{},credentials:{}};}
