"use client";
import { connectorProfile, connectorProfiles, newConnectorDraft, type ConnectorDraft } from './catalog';
import './setup.css';
export default function ConnectorFields({value,onChange,lang,existing=false,choose=true}:{value:ConnectorDraft;onChange:(value:ConnectorDraft)=>void;lang:'tr'|'en';existing?:boolean;choose?:boolean}){
 const tr=lang==='tr',p=connectorProfile(value.providerId),d=p?.datasets.find(x=>x.id===value.dataset);
 return <>
 {choose&&<label className="wide"><span>{tr?'Ürün':'Product'}</span><select value={value.providerId||''} onChange={e=>onChange(newConnectorDraft(e.target.value))}><option value="">{tr?'Özel REST / HTTPS collector':'Custom REST / HTTPS collector'}</option>{connectorProfiles.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>}
 <label className="wide"><span>{tr?'Kaynak adı':'Source name'}</span><input required value={value.name} onChange={e=>onChange({...value,name:e.target.value})}/></label>
 {p?<>
 <label className="wide"><span>{tr?'Toplanacak veri':'Dataset to collect'}</span><select value={value.dataset} onChange={e=>onChange({...value,dataset:e.target.value})}>{p.datasets.map(x=><option key={x.id} value={x.id}>{x.label[lang]}</option>)}</select></label>
 <div className="connector-guide wide"><b>{tr?'Kurulum ve gerekli yetki':'Setup and required permission'}</b><p>{p.setup[lang]}</p>{p.origin==='https://management.azure.com'&&<p>{tr?'Azure kaynaklarında Graph izni yerine servis sorumlusuna aşağıdaki Azure RBAC rolünü atayın.':'For Azure resources, assign the service principal the Azure RBAC role below instead of a Graph permission.'}</p>}<code>{d?.permission}</code><p>{d?.hint[lang]}</p><details><summary>{tr?'Kapsam ve API belgesi':'Scope and API documentation'}</summary><p>{p.limitations[lang]}</p><p>{tr?'Toplama sınırı: 20 sayfa, toplam 1 MB, 30 saniye. Sınır aşılırsa çalışma başarısız olur.':'Collection limit: 20 pages, 1 MB total, 30 seconds. Exceeding a limit fails the run.'}</p><code>{p.origin||'{service URL}'}{d?.path}</code><p><a href={d?.docs} target="_blank" rel="noreferrer">{tr?'Resmi ürün belgesi ↗':'Official product documentation ↗'}</a></p></details></div>
 {p.fields.map(f=><label key={f.key}><span>{f.label[lang]}</span>{f.options?<select value={value.providerConfig?.[f.key]||f.options[0]} onChange={e=>onChange({...value,providerConfig:{...value.providerConfig,[f.key]:e.target.value}})}>{f.options.map(o=><option key={o}>{o}</option>)}</select>:<input required autoComplete="off" placeholder={f.placeholder} value={value.providerConfig?.[f.key]||''} onChange={e=>onChange({...value,providerConfig:{...value.providerConfig,[f.key]:e.target.value}})}/>}</label>)}
 {p.secrets.map(f=><label key={f.key}><span>{f.label[lang]}</span><input type="password" required={!existing} autoComplete="new-password" value={value.credentials?.[f.key]||''} placeholder={existing?(tr?'Değişmediyse boş bırakın':'Leave blank to keep unchanged'):tr?'Şifreli saklanır':'Stored encrypted'} onChange={e=>onChange({...value,credentials:{...value.credentials,[f.key]:e.target.value}})}/></label>)}
 <p className="connector-note wide">{tr?'Token alma ve API çağrıları sunucuda yapılır. Kaydetmek bağlantıyı doğrulamaz; Bağlantıyı Test Et ile izin ve veri erişimini kontrol edin.':'Token acquisition and API requests run on the server. Saving does not verify connectivity; use Test Connection to check permissions and data access.'}</p>
 </>:<>
 <label className="wide"><span>HTTPS JSON URL</span><input required type="url" value={value.baseUrl} placeholder="https://collector.example.com/evidence" onChange={e=>onChange({...value,baseUrl:e.target.value})}/></label>
 <label><span>{tr?'Kimlik doğrulama':'Authentication'}</span><select value={value.authType} onChange={e=>onChange({...value,authType:e.target.value})}><option value="bearer">Bearer token</option><option value="api-key">API key header</option><option value="basic">Basic (username:password)</option><option value="none">{tr?'Yok':'None'}</option></select></label>
 {value.authType==='api-key'&&<label><span>{tr?'Header adı':'Header name'}</span><input required value={value.headerName} onChange={e=>onChange({...value,headerName:e.target.value})}/></label>}
 {value.authType!=='none'&&<label><span>{tr?'Kimlik bilgisi':'Credential'}</span><input type="password" autoComplete="new-password" value={value.secret} onChange={e=>onChange({...value,secret:e.target.value})}/></label>}
 <p className="connector-note wide">{tr?'Özel collector tek bir GET/JSON yanıtı okur. Ürüne özel oturum, imzalama ve sayfalama işlemleri köprü tarafından tamamlanmalıdır.':'The custom collector reads one GET/JSON response. Product sessions, signing and pagination must be completed by the bridge.'}</p>
 </>}
 </>;
}
