import {NextRequest,NextResponse} from "next/server";
import {requireRole} from "../../auth/security";
import {clean} from "../../integrations/security";
import {ensureAssuranceNotificationDeliverySchema,readAssuranceDeliveryData,readAssuranceNotificationPolicy,readAssuranceNotificationPolicyEvents,resetAssuranceNotificationRetry,summarizeAssuranceDelivery,type AssuranceNotificationPolicy} from "../../../assurance-notification-delivery";
import {dispatchAssuranceNotifications,readAssuranceNotificationDispatchRuns,summarizeAssuranceSchedulerHealth} from "../../../assurance-notification-dispatch";
import {activeStormDeferrals,readAssuranceNotificationDeferrals,readAssuranceNotificationStormPolicy,readAssuranceNotificationStormPolicyEvents,saveAssuranceNotificationStormPolicy,type AssuranceNotificationStormPolicy} from "../../../assurance-notification-storm";

type Env=Record<string,unknown>&{DB:D1Database};
const json=(data:unknown,status=200)=>NextResponse.json(data,{status,headers:{"cache-control":"no-store"}});
async function runtime(){const{env}=await import("cloudflare:workers");return env as unknown as Env}

export async function GET(req:NextRequest){const access=await requireRole(req,["Admin","Editor","Viewer"]);if(access.response)return access.response;const env=await runtime();await ensureAssuranceNotificationDeliverySchema(env.DB);const now=new Date(),p=await readAssuranceNotificationPolicy(env.DB),data=await readAssuranceDeliveryData(env.DB),policyEvents=await readAssuranceNotificationPolicyEvents(env.DB),dispatchRuns=await readAssuranceNotificationDispatchRuns(env.DB,100),summary=summarizeAssuranceDelivery(data.outbox,data.deliveries,p,now,data.retryResets),health=summarizeAssuranceSchedulerHealth(dispatchRuns,now,15),stormPolicy=await readAssuranceNotificationStormPolicy(env.DB),stormDeferrals=await readAssuranceNotificationDeferrals(env.DB,300),stormPolicyEvents=await readAssuranceNotificationStormPolicyEvents(env.DB,50),activeDeferrals=activeStormDeferrals(stormDeferrals,now);return json({policy:p,summary,schedule:{enabled:true,cadenceMinutes:15,health},storm:{policy:stormPolicy,activeCount:activeDeferrals.length,activeDeferrals:activeDeferrals.slice(0,100).map(item=>({outboxId:item.outbox_id,recipient:item.recipient,severity:item.severity,reason:item.reason,firstDeferredAt:item.first_deferred_at,lastDeferredAt:item.last_deferred_at,deferCount:item.defer_count,nextEligibleAt:item.next_eligible_at})),policyEvents:stormPolicyEvents.map(event=>({id:event.id,actor:event.actor,before:JSON.parse(event.before_json||"{}"),after:JSON.parse(event.after_json||"{}"),createdAt:event.created_at}))},dispatchRuns:dispatchRuns.slice(0,25),retryResets:data.retryResets.slice(0,100).map(event=>({id:event.id,outboxId:event.outbox_id,actor:event.actor,reason:event.reason,priorFailedAttempts:event.prior_failed_attempts,createdAt:event.created_at})),policyEvents:policyEvents.map(event=>({id:event.id,actor:event.actor,before:JSON.parse(event.before_json||"{}"),after:JSON.parse(event.after_json||"{}"),createdAt:event.created_at})),deliveries:data.deliveries.slice(0,100).map(item=>({id:item.id,outboxId:item.outbox_id,attempt:item.attempt,provider:item.provider,state:item.state,detail:item.detail,recipient:item.recipient,attemptedBy:item.attempted_by,attemptedAt:item.attempted_at}))})}

export async function PUT(req:NextRequest){const access=await requireRole(req,["Admin"]);if(access.response)return access.response;if(Number(req.headers.get("content-length")||0)>16_384)return json({error:"İstek boyutu çok büyük."},413);const body=await req.json().catch(()=>({})) as Record<string,unknown>,section=clean(body.section,40),value=(key:string,min:number,max:number)=>{const n=Number(body[key]);if(!Number.isInteger(n)||n<min||n>max)throw new Error(`${key} geçersiz.`);return n},env=await runtime();if(section==="storm"){let next:AssuranceNotificationStormPolicy;try{next={windowMinutes:value("windowMinutes",15,1440),highMaxPerRecipient:value("highMaxPerRecipient",1,100),mediumMaxPerRecipient:value("mediumMaxPerRecipient",1,100)};const saved=await saveAssuranceNotificationStormPolicy(env.DB,next,access.actor.email);return json({ok:true,stormPolicy:saved.after,updatedBy:saved.updatedBy,updatedAt:saved.updatedAt})}catch(error){return json({error:error instanceof Error?error.message:"Storm-control policy geçersiz."},400)}}let next:AssuranceNotificationPolicy;try{next={criticalSlaMinutes:value("criticalSlaMinutes",15,10080),highSlaMinutes:value("highSlaMinutes",30,20160),mediumSlaMinutes:value("mediumSlaMinutes",60,43200),maxAttempts:value("maxAttempts",1,10)}}catch(error){return json({error:error instanceof Error?error.message:"Policy geçersiz."},400)}if(!(next.criticalSlaMinutes<=next.highSlaMinutes&&next.highSlaMinutes<=next.mediumSlaMinutes))return json({error:"SLA sırası critical ≤ high ≤ medium olmalıdır."},400);await ensureAssuranceNotificationDeliverySchema(env.DB);const before=await readAssuranceNotificationPolicy(env.DB),stamp=new Date().toISOString();await env.DB.prepare("INSERT INTO continuous_assurance_notification_policy(id,critical_sla_minutes,high_sla_minutes,medium_sla_minutes,max_attempts,updated_by,updated_at) VALUES('default',?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET critical_sla_minutes=excluded.critical_sla_minutes,high_sla_minutes=excluded.high_sla_minutes,medium_sla_minutes=excluded.medium_sla_minutes,max_attempts=excluded.max_attempts,updated_by=excluded.updated_by,updated_at=excluded.updated_at").bind(next.criticalSlaMinutes,next.highSlaMinutes,next.mediumSlaMinutes,next.maxAttempts,access.actor.email,stamp).run();if(JSON.stringify(before)!==JSON.stringify(next))await env.DB.prepare("INSERT INTO continuous_assurance_notification_policy_events(id,actor,before_json,after_json,created_at) VALUES(?,?,?,?,?)").bind(crypto.randomUUID(),access.actor.email,JSON.stringify(before),JSON.stringify(next),stamp).run();return json({ok:true,policy:next,updatedBy:access.actor.email,updatedAt:stamp})}

export async function POST(req:NextRequest){const access=await requireRole(req,["Admin"]);if(access.response)return access.response;if(Number(req.headers.get("content-length")||0)>16_384)return json({error:"İstek boyutu çok büyük."},413);const body=await req.json().catch(()=>({})) as Record<string,unknown>,action=clean(body.action,40),env=await runtime();if(action==="dispatch"){const result=await dispatchAssuranceNotifications(env.DB,env,{actor:access.actor.email,trigger:"manual",limit:Math.max(1,Math.min(50,Number(body.limit)||20))});if(!result.transportConfigured)return json({error:"Etkin e-posta entegrasyonu bulunamadı. E-posta ve Bildirimler ayarlarından yapılandırın.",...result},409);return json({ok:true,...result})}if(action==="reset-retry"){const outboxId=clean(body.outboxId,160),reason=clean(body.reason,1000);try{const event=await resetAssuranceNotificationRetry(env.DB,outboxId,access.actor.email,reason);return json({ok:true,retryReset:{id:event.id,outboxId:event.outbox_id,actor:event.actor,reason:event.reason,priorFailedAttempts:event.prior_failed_attempts,createdAt:event.created_at}})}catch(error){const message=error instanceof Error?error.message:"Retry recovery failed.",status=/required|reason/i.test(message)?400:409;return json({error:message},status)}}return json({error:"Geçersiz işlem."},400)}
