import {NextRequest,NextResponse} from "next/server";
import {requireRole} from "../../auth/security";
import {clean} from "../../integrations/security";
import {deliverConfiguredEmail} from "../../integrations/email-transport";
import {ensureAssuranceNotificationSchema} from "../../../assurance-executive-operations";

type Env=Record<string,unknown>&{DB:D1Database};
type Outbox={id:string;escalation_id:string;recipient:string;route:string;subject:string;body:string;severity:string;status:string;reason:string;created_at:string;updated_at:string};
type Delivery={id:string;outbox_id:string;attempt:number;provider:string;state:string;detail:string;recipient:string;attempted_by:string;attempted_at:string};
type Policy={criticalSlaMinutes:number;highSlaMinutes:number;mediumSlaMinutes:number;maxAttempts:number};
const defaults:Policy={criticalSlaMinutes:240,highSlaMinutes:1440,mediumSlaMinutes:4320,maxAttempts:3};
const schema=[
 `CREATE TABLE IF NOT EXISTS continuous_assurance_notification_deliveries(id TEXT PRIMARY KEY,outbox_id TEXT NOT NULL,attempt INTEGER NOT NULL,provider TEXT NOT NULL,state TEXT NOT NULL,detail TEXT NOT NULL,recipient TEXT NOT NULL,attempted_by TEXT NOT NULL,attempted_at TEXT NOT NULL)`,
 `CREATE INDEX IF NOT EXISTS ca_notification_delivery_outbox_idx ON continuous_assurance_notification_deliveries(outbox_id,attempted_at)`,
 `CREATE TABLE IF NOT EXISTS continuous_assurance_notification_policy(id TEXT PRIMARY KEY,critical_sla_minutes INTEGER NOT NULL,high_sla_minutes INTEGER NOT NULL,medium_sla_minutes INTEGER NOT NULL,max_attempts INTEGER NOT NULL,updated_by TEXT NOT NULL,updated_at TEXT NOT NULL)`,
];
const json=(data:unknown,status=200)=>NextResponse.json(data,{status,headers:{"cache-control":"no-store"}});
async function runtime(){const{env}=await import("cloudflare:workers");return env as unknown as Env}
async function ready(db:D1Database){await ensureAssuranceNotificationSchema(db);for(const sql of schema)await db.prepare(sql).run()}
async function policy(db:D1Database):Promise<Policy>{const row=await db.prepare("SELECT critical_sla_minutes,high_sla_minutes,medium_sla_minutes,max_attempts FROM continuous_assurance_notification_policy WHERE id='default'").first<{critical_sla_minutes:number;high_sla_minutes:number;medium_sla_minutes:number;max_attempts:number}>();return row?{criticalSlaMinutes:row.critical_sla_minutes,highSlaMinutes:row.high_sla_minutes,mediumSlaMinutes:row.medium_sla_minutes,maxAttempts:row.max_attempts}:defaults}
const slaFor=(severity:string,p:Policy)=>severity==="critical"?p.criticalSlaMinutes:severity==="high"?p.highSlaMinutes:p.mediumSlaMinutes;
const ageMinutes=(value:string,now:Date)=>Math.max(0,Math.floor((now.getTime()-new Date(value).getTime())/60_000));
async function rows(db:D1Database){const outbox=(await db.prepare("SELECT id,escalation_id,recipient,route,subject,body,severity,status,reason,created_at,updated_at FROM continuous_assurance_notification_outbox ORDER BY updated_at DESC LIMIT 2000").all<Outbox>()).results||[],deliveries=(await db.prepare("SELECT id,outbox_id,attempt,provider,state,detail,recipient,attempted_by,attempted_at FROM continuous_assurance_notification_deliveries ORDER BY attempted_at DESC LIMIT 5000").all<Delivery>()).results||[];return{outbox,deliveries}}
function summarize(outbox:Outbox[],deliveries:Delivery[],p:Policy,now=new Date()){
 const byOutbox=new Map<string,Delivery[]>();for(const item of deliveries)byOutbox.set(item.outbox_id,[...(byOutbox.get(item.outbox_id)||[]),item]);
 const queue=outbox.filter(item=>item.status==="queued"&&item.recipient),pending=queue.filter(item=>!(byOutbox.get(item.id)||[]).some(x=>x.state==="sent")),sent=queue.filter(item=>(byOutbox.get(item.id)||[]).some(x=>x.state==="sent")),failed=pending.filter(item=>(byOutbox.get(item.id)||[]).some(x=>x.state==="failed")),slaBreaches=pending.filter(item=>ageMinutes(item.created_at,now)>slaFor(item.severity,p));
 return{pending:pending.length,sent:sent.length,failed:failed.length,inAppOnly:outbox.filter(item=>item.status==="queued"&&!item.recipient).length,slaBreaches:slaBreaches.length,breaches:slaBreaches.slice(0,50).map(item=>({id:item.id,severity:item.severity,recipient:item.recipient,subject:item.subject,ageMinutes:ageMinutes(item.created_at,now),slaMinutes:slaFor(item.severity,p)}))};
}

export async function GET(req:NextRequest){const access=await requireRole(req,["Admin","Editor","Viewer"]);if(access.response)return access.response;const env=await runtime();await ready(env.DB);const p=await policy(env.DB),data=await rows(env.DB);return json({policy:p,summary:summarize(data.outbox,data.deliveries,p),deliveries:data.deliveries.slice(0,100).map(item=>({id:item.id,outboxId:item.outbox_id,attempt:item.attempt,provider:item.provider,state:item.state,detail:item.detail,recipient:item.recipient,attemptedBy:item.attempted_by,attemptedAt:item.attempted_at}))})}

export async function PUT(req:NextRequest){const access=await requireRole(req,["Admin"]);if(access.response)return access.response;if(Number(req.headers.get("content-length")||0)>16_384)return json({error:"İstek boyutu çok büyük."},413);const body=await req.json().catch(()=>({})) as Record<string,unknown>;const value=(key:string,min:number,max:number)=>{const n=Number(body[key]);if(!Number.isInteger(n)||n<min||n>max)throw new Error(`${key} geçersiz.`);return n};let next:Policy;try{next={criticalSlaMinutes:value("criticalSlaMinutes",15,10080),highSlaMinutes:value("highSlaMinutes",30,20160),mediumSlaMinutes:value("mediumSlaMinutes",60,43200),maxAttempts:value("maxAttempts",1,10)}}catch(error){return json({error:error instanceof Error?error.message:"Policy geçersiz."},400)}if(!(next.criticalSlaMinutes<=next.highSlaMinutes&&next.highSlaMinutes<=next.mediumSlaMinutes))return json({error:"SLA sırası critical ≤ high ≤ medium olmalıdır."},400);const env=await runtime();await ready(env.DB);const stamp=new Date().toISOString();await env.DB.prepare("INSERT INTO continuous_assurance_notification_policy(id,critical_sla_minutes,high_sla_minutes,medium_sla_minutes,max_attempts,updated_by,updated_at) VALUES('default',?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET critical_sla_minutes=excluded.critical_sla_minutes,high_sla_minutes=excluded.high_sla_minutes,medium_sla_minutes=excluded.medium_sla_minutes,max_attempts=excluded.max_attempts,updated_by=excluded.updated_by,updated_at=excluded.updated_at").bind(next.criticalSlaMinutes,next.highSlaMinutes,next.mediumSlaMinutes,next.maxAttempts,access.actor.email,stamp).run();return json({ok:true,policy:next,updatedBy:access.actor.email,updatedAt:stamp})}

export async function POST(req:NextRequest){const access=await requireRole(req,["Admin"]);if(access.response)return access.response;if(Number(req.headers.get("content-length")||0)>16_384)return json({error:"İstek boyutu çok büyük."},413);const body=await req.json().catch(()=>({})) as Record<string,unknown>,action=clean(body.action,40);if(action!=="dispatch")return json({error:"Geçersiz işlem."},400);const requested=Math.max(1,Math.min(50,Number(body.limit)||20)),env=await runtime();await ready(env.DB);const configured=await env.DB.prepare("SELECT provider,enabled FROM integration_settings WHERE kind='email'").first<{provider:string;enabled:number}>().catch(()=>null);if(!configured||!configured.enabled)return json({error:"Etkin e-posta entegrasyonu bulunamadı. E-posta ve Bildirimler ayarlarından yapılandırın."},409);const p=await policy(env.DB),data=await rows(env.DB),history=new Map<string,Delivery[]>();for(const item of data.deliveries)history.set(item.outbox_id,[...(history.get(item.outbox_id)||[]),item]);const candidates=data.outbox.filter(item=>item.status==="queued"&&item.recipient&&!(history.get(item.id)||[]).some(x=>x.state==="sent")&&(history.get(item.id)||[]).filter(x=>x.state==="failed").length<p.maxAttempts).sort((a,b)=>({critical:0,high:1,medium:2}[a.severity as "critical"|"high"|"medium"]??3)-({critical:0,high:1,medium:2}[b.severity as "critical"|"high"|"medium"]??3)||a.created_at.localeCompare(b.created_at)).slice(0,requested);let sent=0,failed=0;const results=[];for(const item of candidates){const prior=(history.get(item.id)||[]).filter(x=>x.state==="failed"||x.state==="sent").length,attempt=prior+1,result=await deliverConfiguredEmail(env.DB,env,{to:item.recipient,subject:`[Fornost ${item.severity.toUpperCase()}] ${item.subject}`,text:`${item.body}\n\nFornost Continuous Assurance\nEscalation: ${item.escalation_id}\nReason: ${item.reason}`}),stamp=new Date().toISOString();await env.DB.prepare("INSERT INTO continuous_assurance_notification_deliveries(id,outbox_id,attempt,provider,state,detail,recipient,attempted_by,attempted_at) VALUES(?,?,?,?,?,?,?,?,?)").bind(crypto.randomUUID(),item.id,attempt,result.provider,result.state,result.detail,item.recipient,access.actor.email,stamp).run();if(result.sent)sent++;else failed++;results.push({outboxId:item.id,recipient:item.recipient,state:result.state,provider:result.provider,attempt})}return json({ok:true,requested,candidates:candidates.length,sent,failed,results})}
