import {NextRequest,NextResponse} from "next/server";
import {requireRole} from "../../auth/security";
import {clean} from "../../integrations/security";
import {deliverConfiguredEmail} from "../../integrations/email-transport";
import {ensureAssuranceNotificationDeliverySchema,readAssuranceDeliveryData,readAssuranceNotificationPolicy,readAssuranceNotificationPolicyEvents,summarizeAssuranceDelivery,type AssuranceDeliveryRecord,type AssuranceNotificationPolicy} from "../../../assurance-notification-delivery";

type Env=Record<string,unknown>&{DB:D1Database};
const json=(data:unknown,status=200)=>NextResponse.json(data,{status,headers:{"cache-control":"no-store"}});
async function runtime(){const{env}=await import("cloudflare:workers");return env as unknown as Env}

export async function GET(req:NextRequest){const access=await requireRole(req,["Admin","Editor","Viewer"]);if(access.response)return access.response;const env=await runtime();await ensureAssuranceNotificationDeliverySchema(env.DB);const p=await readAssuranceNotificationPolicy(env.DB),data=await readAssuranceDeliveryData(env.DB),policyEvents=await readAssuranceNotificationPolicyEvents(env.DB);return json({policy:p,summary:summarizeAssuranceDelivery(data.outbox,data.deliveries,p),policyEvents:policyEvents.map(event=>({id:event.id,actor:event.actor,before:JSON.parse(event.before_json||"{}"),after:JSON.parse(event.after_json||"{}"),createdAt:event.created_at})),deliveries:data.deliveries.slice(0,100).map(item=>({id:item.id,outboxId:item.outbox_id,attempt:item.attempt,provider:item.provider,state:item.state,detail:item.detail,recipient:item.recipient,attemptedBy:item.attempted_by,attemptedAt:item.attempted_at}))})}

export async function PUT(req:NextRequest){const access=await requireRole(req,["Admin"]);if(access.response)return access.response;if(Number(req.headers.get("content-length")||0)>16_384)return json({error:"İstek boyutu çok büyük."},413);const body=await req.json().catch(()=>({})) as Record<string,unknown>;const value=(key:string,min:number,max:number)=>{const n=Number(body[key]);if(!Number.isInteger(n)||n<min||n>max)throw new Error(`${key} geçersiz.`);return n};let next:AssuranceNotificationPolicy;try{next={criticalSlaMinutes:value("criticalSlaMinutes",15,10080),highSlaMinutes:value("highSlaMinutes",30,20160),mediumSlaMinutes:value("mediumSlaMinutes",60,43200),maxAttempts:value("maxAttempts",1,10)}}catch(error){return json({error:error instanceof Error?error.message:"Policy geçersiz."},400)}if(!(next.criticalSlaMinutes<=next.highSlaMinutes&&next.highSlaMinutes<=next.mediumSlaMinutes))return json({error:"SLA sırası critical ≤ high ≤ medium olmalıdır."},400);const env=await runtime();await ensureAssuranceNotificationDeliverySchema(env.DB);const before=await readAssuranceNotificationPolicy(env.DB),stamp=new Date().toISOString();await env.DB.prepare("INSERT INTO continuous_assurance_notification_policy(id,critical_sla_minutes,high_sla_minutes,medium_sla_minutes,max_attempts,updated_by,updated_at) VALUES('default',?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET critical_sla_minutes=excluded.critical_sla_minutes,high_sla_minutes=excluded.high_sla_minutes,medium_sla_minutes=excluded.medium_sla_minutes,max_attempts=excluded.max_attempts,updated_by=excluded.updated_by,updated_at=excluded.updated_at").bind(next.criticalSlaMinutes,next.highSlaMinutes,next.mediumSlaMinutes,next.maxAttempts,access.actor.email,stamp).run();if(JSON.stringify(before)!==JSON.stringify(next))await env.DB.prepare("INSERT INTO continuous_assurance_notification_policy_events(id,actor,before_json,after_json,created_at) VALUES(?,?,?,?,?)").bind(crypto.randomUUID(),access.actor.email,JSON.stringify(before),JSON.stringify(next),stamp).run();return json({ok:true,policy:next,updatedBy:access.actor.email,updatedAt:stamp})}

export async function POST(req:NextRequest){const access=await requireRole(req,["Admin"]);if(access.response)return access.response;if(Number(req.headers.get("content-length")||0)>16_384)return json({error:"İstek boyutu çok büyük."},413);const body=await req.json().catch(()=>({})) as Record<string,unknown>,action=clean(body.action,40);if(action!=="dispatch")return json({error:"Geçersiz işlem."},400);const requested=Math.max(1,Math.min(50,Number(body.limit)||20)),env=await runtime();await ensureAssuranceNotificationDeliverySchema(env.DB);const configured=await env.DB.prepare("SELECT provider,enabled FROM integration_settings WHERE kind='email'").first<{provider:string;enabled:number}>().catch(()=>null);if(!configured||!configured.enabled)return json({error:"Etkin e-posta entegrasyonu bulunamadı. E-posta ve Bildirimler ayarlarından yapılandırın."},409);const p=await readAssuranceNotificationPolicy(env.DB),data=await readAssuranceDeliveryData(env.DB),history=new Map<string,AssuranceDeliveryRecord[]>();for(const item of data.deliveries)history.set(item.outbox_id,[...(history.get(item.outbox_id)||[]),item]);const candidates=data.outbox.filter(item=>item.status==="queued"&&item.recipient&&!(history.get(item.id)||[]).some(x=>x.state==="sent")&&(history.get(item.id)||[]).filter(x=>x.state==="failed").length<p.maxAttempts).sort((a,b)=>({critical:0,high:1,medium:2}[a.severity as "critical"|"high"|"medium"]??3)-({critical:0,high:1,medium:2}[b.severity as "critical"|"high"|"medium"]??3)||a.created_at.localeCompare(b.created_at)).slice(0,requested);let sent=0,failed=0;const results=[];for(const item of candidates){const prior=(history.get(item.id)||[]).filter(x=>x.state==="failed"||x.state==="sent").length,attempt=prior+1,result=await deliverConfiguredEmail(env.DB,env,{to:item.recipient,subject:`[Fornost ${item.severity.toUpperCase()}] ${item.subject}`,text:`${item.body}\n\nFornost Continuous Assurance\nEscalation: ${item.escalation_id}\nReason: ${item.reason}`}),stamp=new Date().toISOString();await env.DB.prepare("INSERT INTO continuous_assurance_notification_deliveries(id,outbox_id,attempt,provider,state,detail,recipient,attempted_by,attempted_at) VALUES(?,?,?,?,?,?,?,?,?)").bind(crypto.randomUUID(),item.id,attempt,result.provider,result.state,result.detail,item.recipient,access.actor.email,stamp).run();if(result.sent)sent++;else failed++;results.push({outboxId:item.id,recipient:item.recipient,state:result.state,provider:result.provider,attempt})}return json({ok:true,requested,candidates:candidates.length,sent,failed,results})}
