import { observeAiAlert } from "@/app/ai/alert-observations";
import { aiAlertRevision,transitionAiAlert } from "@/app/ai/alert-transitions";
import { aiRecordQueryId,readAiRecords } from "@/app/ai/record-reads";
import {NextRequest,NextResponse} from "next/server";
import {requireRole} from "../../auth/security";
import {assuranceAlertCandidates,validateAlertAction} from "@/app/ai/assurance-alerts";
import {cleanAiText} from "@/app/ai/security";
import {aiRuntime,recordAiEvent} from "@/app/ai/storage";
const json=(data:unknown,status=200)=>NextResponse.json(data,{status,headers:{"cache-control":"no-store"}}),cell=(value:unknown)=>{const raw=String(value??""),safe=/^[=+\-@]/.test(raw)?`'${raw}`:raw;return `"${safe.replace(/"/g,'""')}"`;},map=async(r:Record<string,unknown>)=>({revision:await aiAlertRevision(r),id:r.id,modelId:r.model_id,policyId:r.policy_id,monitoringRef:r.monitoring_ref,metric:r.metric,title:r.title,severity:r.severity,observedValue:r.observed_value,thresholdValue:r.threshold_value,occurrenceCount:Number(r.occurrence_count),status:r.status,owner:r.owner,actionNote:r.action_note,findingId:r.finding_id,firstSeenAt:r.first_seen_at,lastSeenAt:r.last_seen_at});
export async function GET(req:NextRequest){const access=await requireRole(req,["Admin"]);if(access.response)return access.response;let recordId:string|null;try{recordId=aiRecordQueryId(req.nextUrl.searchParams);}catch{return json({error:"Geçerli bir kayıt kimliği gereklidir."},400);}const{DB}=await aiRuntime(),result=await readAiRecords(DB,"alerts",recordId),alerts=await Promise.all((result.results||[]).map(map));if(req.nextUrl.searchParams.get("format")==="csv"){const rows=[["Alarm","Model","Metrik","Başlık","Önem","Gözlenen","Eşik","Tekrar","Durum","Sorumlu","CAPA"],...alerts.map(a=>[a.id,a.modelId,a.metric,a.title,a.severity,a.observedValue??"",a.thresholdValue??"",a.occurrenceCount,a.status,a.owner||"",a.findingId||""])];await recordAiEvent(DB,{actor:access.actor.email,action:"ai-assurance-alert-export",contextRefs:alerts.map(a=>String(a.id)).slice(0,80),status:"success",detail:`${alerts.length} bounded records; formula-safe csv`});return new NextResponse(`\uFEFF${rows.map(row=>row.map(cell).join(",")).join("\n")}`,{headers:{"cache-control":"no-store","content-type":"text/csv; charset=utf-8","content-disposition":"attachment; filename=fornost-ai-assurance-alerts.csv"}});}return json({alerts,summary:{total:alerts.length,open:alerts.filter(a=>a.status!=="resolved").length,critical:alerts.filter(a=>a.status!=="resolved"&&a.severity==="Critical").length,high:alerts.filter(a=>a.status!=="resolved"&&a.severity==="High").length,escalated:alerts.filter(a=>a.status==="escalated").length,resolved:alerts.filter(a=>a.status==="resolved").length}});}
export async function POST(req:NextRequest){const access=await requireRole(req,["Admin"]);if(access.response)return access.response;const{DB}=await aiRuntime(),rows=await DB.prepare("SELECT p.*,i.risk_tier,m.id monitoring_ref,m.accuracy,m.error_rate,m.drift_score,m.bias_score,m.p95_latency_ms,m.sample_size,m.recorded_at FROM ai_assurance_policies p JOIN ai_model_inventory i ON i.id=p.model_id LEFT JOIN ai_model_monitoring m ON m.id=(SELECT id FROM ai_model_monitoring WHERE model_id=p.model_id ORDER BY recorded_at DESC,id DESC LIMIT 1) WHERE i.status!='retired' AND p.status='approved' AND p.review_date>=date('now') LIMIT 500").all<Record<string,unknown>>(),now=new Date().toISOString();let created=0,updated=0,unchanged=0;try{for(const row of rows.results||[]){const policy={minAccuracy:Number(row.min_accuracy),maxErrorRate:Number(row.max_error_rate),maxDriftScore:Number(row.max_drift_score),maxBiasScore:Number(row.max_bias_score),maxP95LatencyMs:Number(row.max_p95_latency_ms),minSampleSize:Number(row.min_sample_size),frequencyDays:Number(row.frequency_days)},snapshot=row.monitoring_ref?{accuracy:Number(row.accuracy),errorRate:Number(row.error_rate),driftScore:Number(row.drift_score),biasScore:Number(row.bias_score),p95LatencyMs:Number(row.p95_latency_ms),sampleSize:Number(row.sample_size),recordedAt:String(row.recorded_at)}:null;for(const candidate of assuranceAlertCandidates(policy,snapshot,String(row.risk_tier),now)){const outcome=await observeAiAlert(DB,row,candidate,access.actor.email,now);if(outcome==='created')created++;else if(outcome==='updated')updated++;else unchanged++;}}await recordAiEvent(DB,{actor:access.actor.email,action:"ai-assurance-alert-sync",contextRefs:(rows.results||[]).map(r=>String(r.model_id)).slice(0,80),status:"success",detail:`${created} created; ${updated} distinct updates; ${unchanged} unchanged or skipped`});return json({created,updated,unchanged});}catch{return json({error:"Alarm taraması tamamlanamadı. Güncel listeyi kontrol edin; tamamlanan ölçümler tekrar sayılmaz."},503);}}
export async function PATCH(req:NextRequest){
 const access=await requireRole(req,["Admin"]);if(access.response)return access.response;
 const body=await req.json().catch(()=>null);if(!body||typeof body!=="object"||Array.isArray(body))return json({error:"Geçerli işlem gövdesi gereklidir."},400);
 const id=cleanAiText(body.id,100);
 try{validateAlertAction(body);}catch(error){return json({error:error instanceof Error?error.message:"Alarm işlemi geçersiz."},400);}
 const{DB}=await aiRuntime();
 try{const result=await transitionAiAlert(DB,id,body,access.actor.email);return json(result.code===200?{ok:true,status:result.status,findingId:result.findingId}:{error:result.error},result.code);}
 catch{return json({error:"Alarm işlemi tamamlanamadı. Güncel kaydı kontrol edip tekrar deneyin."},503);}
}
