import {NextRequest,NextResponse} from "next/server";
import {requireRole} from "../auth/security";
import {clean} from "../integrations/security";
import {exerciseAssessment,validateContinuityPlan,validateDecision,validateExercise,validateExerciseResult} from "../../continuity/domain";
type Env=Record<string,unknown>&{DB:D1Database};
const schema=[
`CREATE TABLE IF NOT EXISTS enterprise_continuity_plans(id TEXT PRIMARY KEY NOT NULL,code TEXT NOT NULL UNIQUE,name TEXT NOT NULL,process TEXT NOT NULL,bia_ref TEXT NOT NULL,criticality TEXT NOT NULL,owner TEXT NOT NULL,reviewer TEXT NOT NULL,crisis_lead TEXT NOT NULL,rto_hours REAL NOT NULL,rpo_hours REAL NOT NULL,mtpd_hours REAL NOT NULL,dependencies TEXT NOT NULL,recovery_strategy TEXT NOT NULL,communication_plan TEXT NOT NULL,alternate_site TEXT,supplier_dependencies TEXT,minimum_staff INTEGER NOT NULL,review_date TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'draft',version INTEGER NOT NULL DEFAULT 1,created_by TEXT NOT NULL,created_at TEXT NOT NULL,updated_by TEXT NOT NULL,updated_at TEXT NOT NULL,approved_by TEXT,approved_at TEXT,activated_at TEXT,retired_at TEXT)`,
`CREATE INDEX IF NOT EXISTS enterprise_continuity_plan_status_idx ON enterprise_continuity_plans(status,criticality,review_date)`,
`CREATE TABLE IF NOT EXISTS enterprise_continuity_exercises(id TEXT PRIMARY KEY NOT NULL,code TEXT NOT NULL UNIQUE,plan_id TEXT NOT NULL,type TEXT NOT NULL,scheduled_date TEXT NOT NULL,scenario TEXT NOT NULL,facilitator TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'planned',outcome TEXT,actual_recovery_hours REAL,actual_data_loss_hours REAL,rto_breached INTEGER NOT NULL DEFAULT 0,rpo_breached INTEGER NOT NULL DEFAULT 0,observations TEXT,root_cause TEXT,evidence_reference TEXT,evidence_sha256 TEXT,created_by TEXT NOT NULL,created_at TEXT NOT NULL,completed_by TEXT,completed_at TEXT)`,
`CREATE INDEX IF NOT EXISTS enterprise_continuity_exercise_plan_idx ON enterprise_continuity_exercises(plan_id,scheduled_date,status)`,
`CREATE TABLE IF NOT EXISTS enterprise_continuity_gaps(id TEXT PRIMARY KEY NOT NULL,exercise_id TEXT NOT NULL,plan_id TEXT NOT NULL,severity TEXT NOT NULL,title TEXT NOT NULL,owner TEXT NOT NULL,reviewer TEXT NOT NULL,due_date TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'open',evidence_reference TEXT,evidence_sha256 TEXT,created_at TEXT NOT NULL,closed_by TEXT,closed_at TEXT)`,
`CREATE INDEX IF NOT EXISTS enterprise_continuity_gap_status_idx ON enterprise_continuity_gaps(status,severity,due_date)`,
`CREATE TABLE IF NOT EXISTS enterprise_continuity_events(id TEXT PRIMARY KEY NOT NULL,entity_type TEXT NOT NULL,entity_id TEXT NOT NULL,action TEXT NOT NULL,detail TEXT NOT NULL,actor TEXT NOT NULL,created_at TEXT NOT NULL)`,
`CREATE INDEX IF NOT EXISTS enterprise_continuity_event_idx ON enterprise_continuity_events(entity_id,created_at)`];
async function runtime(){const{env}=await import("cloudflare:workers");return env as unknown as Env}async function ready(db:D1Database){for(const sql of schema)await db.prepare(sql).run()}
const json=(data:unknown,status=200)=>NextResponse.json(data,{status,headers:{"cache-control":"no-store"}}),csv=(v:unknown)=>{const x=String(v??""),safe=/^[=+\-@]/.test(x)?`'${x}`:x;return`"${safe.replace(/"/g,'""')}"`};
async function event(db:D1Database,type:string,id:string,action:string,detail:string,actor:string){await db.prepare("INSERT INTO enterprise_continuity_events(id,entity_type,entity_id,action,detail,actor,created_at) VALUES(?,?,?,?,?,?,?)").bind(crypto.randomUUID(),type,id,action,detail.slice(0,3000),actor,new Date().toISOString()).run()}
const plan=(x:Record<string,unknown>)=>({id:x.id,code:x.code,name:x.name,process:x.process,biaRef:x.bia_ref,criticality:x.criticality,owner:x.owner,reviewer:x.reviewer,crisisLead:x.crisis_lead,rtoHours:Number(x.rto_hours),rpoHours:Number(x.rpo_hours),mtpdHours:Number(x.mtpd_hours),dependencies:x.dependencies,recoveryStrategy:x.recovery_strategy,communicationPlan:x.communication_plan,alternateSite:x.alternate_site,supplierDependencies:x.supplier_dependencies,minimumStaff:Number(x.minimum_staff),reviewDate:x.review_date,status:x.status,version:Number(x.version),updatedAt:x.updated_at});
const exercise=(x:Record<string,unknown>)=>({id:x.id,code:x.code,planId:x.plan_id,type:x.type,scheduledDate:x.scheduled_date,scenario:x.scenario,facilitator:x.facilitator,status:x.status,outcome:x.outcome,actualRecoveryHours:x.actual_recovery_hours==null?null:Number(x.actual_recovery_hours),actualDataLossHours:x.actual_data_loss_hours==null?null:Number(x.actual_data_loss_hours),rtoBreached:Boolean(x.rto_breached),rpoBreached:Boolean(x.rpo_breached),observations:x.observations});
const gap=(x:Record<string,unknown>)=>({id:x.id,exerciseId:x.exercise_id,planId:x.plan_id,severity:x.severity,title:x.title,owner:x.owner,reviewer:x.reviewer,dueDate:x.due_date,status:x.status});
export async function GET(req:NextRequest){const access=await requireRole(req,["Admin","Editor","Viewer"]);if(access.response)return access.response;const env=await runtime();await ready(env.DB);const[p,e,g,ev]=await Promise.all([env.DB.prepare("SELECT * FROM enterprise_continuity_plans ORDER BY updated_at DESC LIMIT 2000").all<Record<string,unknown>>(),env.DB.prepare("SELECT * FROM enterprise_continuity_exercises ORDER BY scheduled_date DESC LIMIT 2000").all<Record<string,unknown>>(),env.DB.prepare("SELECT * FROM enterprise_continuity_gaps ORDER BY due_date ASC LIMIT 2000").all<Record<string,unknown>>(),env.DB.prepare("SELECT * FROM enterprise_continuity_events ORDER BY created_at DESC LIMIT 500").all<Record<string,unknown>>()]);const plans=p.results.map(plan),exercises=e.results.map(exercise),gaps=g.results.map(gap),today=new Date().toISOString().slice(0,10),summary={activePlans:plans.filter(x=>x.status==="active").length,overdueReviews:plans.filter(x=>x.status==="active"&&String(x.reviewDate)<today).length,dueExercises:exercises.filter(x=>x.status==="planned"&&String(x.scheduledDate)<=today).length,failedExercises:exercises.filter(x=>x.outcome==="failed"||x.outcome==="partial").length,rtoBreaches:exercises.filter(x=>x.rtoBreached).length,openGaps:gaps.filter(x=>x.status==="open").length};
 if(req.nextUrl.searchParams.get("format")==="csv"){if(access.actor.role!=="Admin")return json({error:"Dayanıklılık çıktısını yalnız Admin alabilir."},403);const rows=[["Kod","Plan","Süreç","BIA","Kritiklik","Durum","RTO","RPO","MTPD","Sahip","Reviewer","Review"],...plans.map(x=>[x.code,x.name,x.process,x.biaRef,x.criticality,x.status,x.rtoHours,x.rpoHours,x.mtpdHours,x.owner,x.reviewer,x.reviewDate])];await event(env.DB,"export","EXPORT","continuity-export",`${plans.length} kayıt`,access.actor.email);return new NextResponse(`\uFEFF${rows.map(r=>r.map(csv).join(",")).join("\n")}`,{headers:{"content-type":"text/csv; charset=utf-8","content-disposition":"attachment; filename=fornost-continuity-plans.csv","cache-control":"no-store"}})}
 return json({plans,exercises,gaps,events:ev.results.map(x=>({id:x.id,entityType:x.entity_type,entityId:x.entity_id,action:x.action,detail:x.detail,actor:x.actor,createdAt:x.created_at})),summary})}

export async function POST(req:NextRequest){if(Number(req.headers.get("content-length")||0)>262144)return json({error:"İstek boyutu çok büyük."},413);const body=await req.json().catch(()=>({})) as Record<string,unknown>,action=clean(body.action,40),access=await requireRole(req,["Admin","Editor"]);if(access.response)return access.response;const env=await runtime();await ready(env.DB);try{
 if(action==="create-plan"){const x=validateContinuityPlan(body),id=`BCP-${crypto.randomUUID()}`,code=`BCP-${new Date().getUTCFullYear()}-${crypto.randomUUID().replace(/-/g,"").slice(0,8).toUpperCase()}`,now=new Date().toISOString();await env.DB.prepare("INSERT INTO enterprise_continuity_plans(id,code,name,process,bia_ref,criticality,owner,reviewer,crisis_lead,rto_hours,rpo_hours,mtpd_hours,dependencies,recovery_strategy,communication_plan,alternate_site,supplier_dependencies,minimum_staff,review_date,status,created_by,created_at,updated_by,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,'draft',?,?,?,?)").bind(id,code,x.name,x.process,x.biaRef,x.criticality,x.owner,x.reviewer,x.crisisLead,x.rtoHours,x.rpoHours,x.mtpdHours,x.dependencies,x.recoveryStrategy,x.communicationPlan,x.alternateSite||null,x.supplierDependencies||null,x.minimumStaff,x.reviewDate,access.actor.email,now,access.actor.email,now).run();await event(env.DB,"plan",id,"create",`${code}; ${x.process}; ${x.biaRef}`,access.actor.email);return json({message:"İş sürekliliği planı oluşturuldu.",id},201)}
 if(["approve-plan","activate-plan","retire-plan"].includes(action)){const id=clean(body.planId,100),kind=action==="approve-plan"?"approve":action==="activate-plan"?"activate":"retire",d=validateDecision(body,kind),x=await env.DB.prepare("SELECT * FROM enterprise_continuity_plans WHERE id=?").bind(id).first<Record<string,unknown>>();if(!x)return json({error:"Plan bulunamadı."},404);const transitions:{[k:string]:[string,string]}={approve:["draft","approved"],activate:["approved","active"],retire:["active","retired"]},[from,to]=transitions[kind];if(x.status!==from)return json({error:"Plan yaşam döngüsü geçişi geçersiz."},409);if(kind==="approve"&&(access.actor.role!=="Admin"||x.reviewer!==access.actor.email))return json({error:"Planı yalnız atanmış bağımsız Admin reviewer onaylayabilir."},403);if(kind==="approve"&&[x.created_by,x.owner,x.crisis_lead].includes(access.actor.email))return json({error:"Maker-checker ayrımı ihlal edildi."},409);if(kind!=="approve"&&access.actor.role!=="Admin"&&![x.owner,x.crisis_lead].includes(access.actor.email))return json({error:"İşlemi yalnız atanmış ekip veya Admin yapabilir."},403);const now=new Date().toISOString(),stamp=kind==="approve"?",approved_by=?,approved_at=?":kind==="activate"?",activated_at=?":",retired_at=?",bind=kind==="approve"?[to,access.actor.email,now,access.actor.email,now,id]:[to,access.actor.email,now,now,id];await env.DB.prepare(`UPDATE enterprise_continuity_plans SET status=?,updated_by=?,updated_at=?${stamp} WHERE id=?`).bind(...bind).run();await event(env.DB,"plan",id,kind,d.note,access.actor.email);return json({message:"Plan yaşam döngüsü güncellendi."})}
 if(action==="schedule-exercise"){const x=validateExercise(body),p=await env.DB.prepare("SELECT * FROM enterprise_continuity_plans WHERE id=?").bind(x.planId).first<Record<string,unknown>>();if(!p||p.status!=="active")return json({error:"Tatbikat yalnız etkin plan için zamanlanabilir."},409);const id=`BCE-${crypto.randomUUID()}`,code=`BCE-${new Date().getUTCFullYear()}-${crypto.randomUUID().replace(/-/g,"").slice(0,8).toUpperCase()}`,now=new Date().toISOString();await env.DB.prepare("INSERT INTO enterprise_continuity_exercises(id,code,plan_id,type,scheduled_date,scenario,facilitator,status,created_by,created_at) VALUES(?,?,?,?,?,?,?,'planned',?,?)").bind(id,code,x.planId,x.type,x.scheduledDate,x.scenario,x.facilitator,access.actor.email,now).run();await event(env.DB,"exercise",id,"schedule",`${code}; ${x.type}; ${x.scheduledDate}`,access.actor.email);return json({message:"Tatbikat zamanlandı."},201)}
 if(action==="complete-exercise"){const id=clean(body.exerciseId,100),r=validateExerciseResult(body),x=await env.DB.prepare("SELECT e.*,p.rto_hours,p.rpo_hours,p.owner,p.reviewer,p.criticality FROM enterprise_continuity_exercises e JOIN enterprise_continuity_plans p ON p.id=e.plan_id WHERE e.id=?").bind(id).first<Record<string,unknown>>();if(!x)return json({error:"Tatbikat bulunamadı."},404);if(x.status!=="planned")return json({error:"Tatbikat daha önce tamamlanmış."},409);if(access.actor.role!=="Admin"&&x.facilitator!==access.actor.email)return json({error:"Tatbikatı yalnız facilitator veya Admin tamamlayabilir."},403);const a=exerciseAssessment({rtoHours:Number(x.rto_hours),rpoHours:Number(x.rpo_hours)},r),now=new Date().toISOString();await env.DB.prepare("UPDATE enterprise_continuity_exercises SET status='completed',outcome=?,actual_recovery_hours=?,actual_data_loss_hours=?,rto_breached=?,rpo_breached=?,observations=?,root_cause=?,evidence_reference=?,evidence_sha256=?,completed_by=?,completed_at=? WHERE id=?").bind(r.outcome,r.actualRecoveryHours,r.actualDataLossHours,a.rtoBreached?1:0,a.rpoBreached?1:0,r.observations,r.rootCause||null,r.evidenceReference,r.evidenceSha256,access.actor.email,now,id).run();if(a.needsGap){const due=new Date(Date.now()+(["critical","high"].includes(String(x.criticality))?30:60)*86400000).toISOString().slice(0,10),severity=a.rtoBreached||a.rpoBreached?"high":"medium";await env.DB.prepare("INSERT INTO enterprise_continuity_gaps(id,exercise_id,plan_id,severity,title,owner,reviewer,due_date,status,created_at) VALUES(?,?,?,?,?,?,?,?, 'open',?)").bind(`BCG-${crypto.randomUUID()}`,id,x.plan_id,severity,`Tatbikat iyileştirmesi: ${x.code}`,x.owner,x.reviewer,due,now).run()}await event(env.DB,"exercise",id,"complete",`${r.outcome}; RTO breach=${a.rtoBreached}; RPO breach=${a.rpoBreached}`,access.actor.email);return json({message:a.needsGap?"Tatbikat tamamlandı; iyileştirme açığı otomatik oluşturuldu.":"Tatbikat başarıyla tamamlandı."})}
 if(action==="close-gap"){const id=clean(body.gapId,100),d=validateDecision(body,"close-gap"),x=await env.DB.prepare("SELECT * FROM enterprise_continuity_gaps WHERE id=?").bind(id).first<Record<string,unknown>>();if(!x)return json({error:"Açık bulunamadı."},404);if(x.status!=="open")return json({error:"Açık zaten kapalı."},409);if(access.actor.role!=="Admin"||x.reviewer!==access.actor.email)return json({error:"Açığı yalnız atanmış bağımsız Admin reviewer kapatabilir."},403);if(x.owner===access.actor.email)return json({error:"Açık sahibi kendi aksiyonunu kapatamaz."},409);const now=new Date().toISOString();await env.DB.prepare("UPDATE enterprise_continuity_gaps SET status='closed',evidence_reference=?,evidence_sha256=?,closed_by=?,closed_at=? WHERE id=?").bind(d.evidenceReference,d.evidenceSha256,access.actor.email,now,id).run();await event(env.DB,"gap",id,"close",d.note,access.actor.email);return json({message:"Dayanıklılık açığı bağımsız olarak kapatıldı."})}
 return json({error:"Geçersiz işlem."},400)}catch(error){return json({error:error instanceof Error?error.message:"İşlem tamamlanamadı."},400)}}
