import {NextRequest,NextResponse} from "next/server";
import {requireRole} from "../../auth/security";
import {buildExecutiveOperationsSummary,buildOwnerAccountability,enrichAssuranceEscalationOwners,syncAssuranceNotificationOutbox,type AssuranceEscalationRecord} from "../../../assurance-executive-operations";
import {ensureAssuranceNotificationDeliverySchema,readAssuranceDeliveryData,readAssuranceNotificationPolicy,readAssuranceNotificationPolicyEvents,summarizeAssuranceDelivery} from "../../../assurance-notification-delivery";
import {buildAuditorAssurancePackHtml,buildAuditorManifest,type AuditorOperationsSnapshot} from "../../../auditor-assurance-pack";
import type {AssuranceRow} from "../../../control-assurance";

type Env=Record<string,unknown>&{DB:D1Database};
const parse=(value:string)=>{try{return JSON.parse(value||"{}") as Record<string,unknown>}catch{return {}}};
async function runtime(){const{env}=await import("cloudflare:workers");return env as unknown as Env}
async function settings(db:D1Database){let remindersEnabled=true;try{const row=await db.prepare("SELECT config_json FROM platform_settings WHERE id='default'").first<{config_json:string}>();if(row&&parse(row.config_json).remindersEnabled===false)remindersEnabled=false}catch{}return{remindersEnabled}}
const canonical=(value:unknown):string=>{if(Array.isArray(value))return`[${value.map(canonical).join(",")}]`;if(value&&typeof value==="object")return`{${Object.entries(value as Record<string,unknown>).sort(([a],[b])=>a.localeCompare(b)).map(([key,item])=>`${JSON.stringify(key)}:${canonical(item)}`).join(",")}}`;return JSON.stringify(value)??"null"};
async function digest(value:unknown){const data=new TextEncoder().encode(canonical(value)),hash=await crypto.subtle.digest("SHA-256",data);return Array.from(new Uint8Array(hash)).map(byte=>byte.toString(16).padStart(2,"0")).join("")}

export async function GET(req:NextRequest){
 const access=await requireRole(req,["Admin","Editor","Viewer"]);if(access.response)return access.response;
 const env=await runtime(),generatedAt=new Date().toISOString(),config=await settings(env.DB);
 let rawEscalations:AssuranceEscalationRecord[]=[];try{rawEscalations=(await env.DB.prepare("SELECT id,kind,severity,subject_ref,owner,title,detail,status,first_seen_at,last_seen_at,acknowledged_by,acknowledged_at,resolved_at,source_json FROM continuous_assurance_escalations ORDER BY last_seen_at DESC LIMIT 3000").all<AssuranceEscalationRecord>()).results||[]}catch{}const escalationRows=await enrichAssuranceEscalationOwners(env.DB,rawEscalations);
 await ensureAssuranceNotificationDeliverySchema(env.DB);await syncAssuranceNotificationOutbox(env.DB,escalationRows,config.remindersEnabled);const deliveryData=await readAssuranceDeliveryData(env.DB),deliveryPolicy=await readAssuranceNotificationPolicy(env.DB),policyEvents=await readAssuranceNotificationPolicyEvents(env.DB),deliverySummary=summarizeAssuranceDelivery(deliveryData.outbox,deliveryData.deliveries,deliveryPolicy,new Date(generatedAt));
 let rows:AssuranceRow[]=[];try{const records=(await env.DB.prepare("SELECT id,module,data_json FROM simple_grc_records ORDER BY updated_at DESC LIMIT 8000").all<{id:string;module:string;data_json:string}>()).results||[];rows=records.map(record=>{const data=parse(record.data_json);return{id:record.id,code:String(data.code||data.controlRef||data.requirementRef||""),module:record.module,data}})}catch{}
 const operations:AuditorOperationsSnapshot={summary:buildExecutiveOperationsSummary(escalationRows,deliveryData.outbox,new Date(generatedAt)),owners:buildOwnerAccountability(escalationRows,new Date(generatedAt)),escalations:escalationRows.filter(row=>row.status!=="resolved").slice(0,300).map(row=>({id:row.id,kind:row.kind,severity:row.severity,subjectRef:row.subject_ref,owner:row.owner,title:row.title,status:row.status,firstSeenAt:row.first_seen_at,lastSeenAt:row.last_seen_at})),outbox:deliveryData.outbox.slice(0,300).map(row=>({id:row.id,escalationId:row.escalation_id,recipient:row.recipient,route:row.route,subject:row.subject,severity:row.severity,status:row.status,reason:row.reason,createdAt:row.created_at,updatedAt:row.updated_at})),delivery:{policy:deliveryPolicy,summary:{pending:deliverySummary.pending,sent:deliverySummary.sent,failed:deliverySummary.failed,retryExhausted:deliverySummary.retryExhausted,attempts30d:deliverySummary.attempts30d,deliveryRate30d:deliverySummary.deliveryRate30d,inAppOnly:deliverySummary.inAppOnly,slaBreaches:deliverySummary.slaBreaches},policyEvents:policyEvents.map(event=>({id:event.id,actor:event.actor,before:parse(event.before_json),after:parse(event.after_json),createdAt:event.created_at})),records:deliveryData.deliveries.slice(0,300).map(item=>({id:item.id,outboxId:item.outbox_id,attempt:item.attempt,provider:item.provider,state:item.state,detail:item.detail,recipient:item.recipient,attemptedBy:item.attempted_by,attemptedAt:item.attempted_at}))}};
 const snapshotSeed={generatedAt,rows:rows.map(row=>({id:row.id,code:row.code||"",module:row.module,data:row.data})),operations},snapshotId=`SHA256:${await digest(snapshotSeed)}`,manifest=buildAuditorManifest(rows,operations,generatedAt,snapshotId),format=req.nextUrl.searchParams.get("format")||"html";
 if(format==="json")return NextResponse.json(manifest,{headers:{"cache-control":"no-store","content-disposition":`attachment; filename="fornost-assurance-${generatedAt.slice(0,10)}.json"`}});
 const tr=req.nextUrl.searchParams.get("lang")!=="en",html=buildAuditorAssurancePackHtml(rows,operations,tr,generatedAt,snapshotId);return new NextResponse(html,{headers:{"content-type":"text/html; charset=utf-8","cache-control":"no-store","content-disposition":`attachment; filename="fornost-auditor-assurance-${generatedAt.slice(0,10)}.html"`}});
}
