import test from 'node:test';
import assert from 'node:assert/strict';
import { DatabaseSync } from 'node:sqlite';
import { readFileSync } from 'node:fs';
import { aiAlertRevision,transitionAiAlert } from '../app/ai/alert-transitions';
function fixture(){
 const sqlite=new DatabaseSync(':memory:');
 for(const file of ['0063_fornost_ai_findings.sql','0064_fornost_ai_assurance_alerts.sql'])sqlite.exec(readFileSync('drizzle/'+file,'utf8'));
 sqlite.exec("CREATE TABLE ai_activity_logs(id TEXT PRIMARY KEY,actor TEXT,action TEXT,provider TEXT,model TEXT,prompt_hash TEXT,context_refs_json TEXT,status TEXT,latency_ms INTEGER,detail TEXT,created_at TEXT); INSERT INTO ai_assurance_alerts(id,model_id,policy_id,metric,title,severity,fingerprint,first_seen_at,last_seen_at) VALUES('ALERT','MODEL','POLICY','drift','Drift alert','High','unique','2090-01-01T00:00:00.000Z','2090-01-01T00:00:00.000Z')");
 let beforeBatch:(()=>void)|undefined;
 function prepare(sql:string,args:(string|number|null)[]=[]){return{bind(...values:(string|number|null)[]){return prepare(sql,values);},async first(){return sqlite.prepare(sql).get(...args)||null;},exec(){return {meta:{changes:Number(sqlite.prepare(sql).run(...args).changes)}};}};}
 const db={prepare,async batch(statements:ReturnType<typeof prepare>[]){const hook=beforeBatch;beforeBatch=undefined;hook?.();sqlite.exec('BEGIN');try{const results=statements.map(s=>s.exec());sqlite.exec('COMMIT');return results;}catch(e){sqlite.exec('ROLLBACK');throw e;}}} as unknown as D1Database;
 const row=()=>sqlite.prepare('SELECT * FROM ai_assurance_alerts').get()!;
 const count=(table:string)=>Number(sqlite.prepare(`SELECT count(*) n FROM ${table}`).get()!.n);
 const run=async(action='escalate',version?:string)=>transitionAiAlert(db,'ALERT',{action,expectedRevision:version??await aiAlertRevision(row()),owner:'owner@example.test',note:'Reviewed current measurement',confirmation:{escalate:'CAPA OLUŞTUR',acknowledge:'ALARMI KABUL ET',resolve:'ALARMI ÇÖZ',reopen:'ALARMI YENİDEN AÇ'}[action]},'admin@example.test');
 return {sqlite,row,count,run,beforeBatch:(fn:()=>void)=>{beforeBatch=fn;}};
}
test('alert escalation commits exactly one linked finding and audit; replay cannot create another',async()=>{const f=fixture();try{const revision=await aiAlertRevision(f.row());assert.equal((await f.run()).code,200);assert.equal(f.row().status,'escalated');assert.equal(f.count('ai_findings'),1);assert.equal(f.count('ai_activity_logs'),1);assert.equal(f.sqlite.prepare('SELECT id FROM ai_findings').get()!.id,f.row().finding_id);assert.ok(String(f.row().escalated_at)>'2090-01-01T00:00:00.000Z');assert.equal((await f.run('escalate',revision)).code,409);await f.run('resolve');await f.run('reopen');assert.equal((await f.run()).code,409);assert.equal(f.count('ai_findings'),1);}finally{f.sqlite.close();}});
test('missing or stale revisions and concurrent measurements or decisions have no dependent writes',async()=>{for(const change of ["owner='different'","severity='Medium'","observed_value=42","occurrence_count=occurrence_count+1","status='resolved'"]){const f=fixture();try{assert.equal((await f.run('escalate','')).code,409);assert.equal((await f.run('escalate','old')).code,409);f.beforeBatch(()=>f.sqlite.exec(`UPDATE ai_assurance_alerts SET ${change}`));assert.equal((await f.run()).code,409);assert.equal(f.count('ai_findings'),0);assert.equal(f.count('ai_activity_logs'),0);}finally{f.sqlite.close();}}});
test('finding or audit insertion failures roll back the alert claim and all dependent writes',async()=>{for(const table of ['ai_findings','ai_activity_logs']){const f=fixture();try{const original=f.row();f.sqlite.exec(`CREATE TRIGGER fail_write BEFORE INSERT ON ${table} BEGIN SELECT RAISE(ABORT,'injected failure'); END`);await assert.rejects(f.run(),/injected failure/);assert.deepEqual(f.row(),original);assert.equal(f.count('ai_findings'),0);assert.equal(f.count('ai_activity_logs'),0);}finally{f.sqlite.close();}}});
test('acknowledge resolve reopen preserve the CAPA link and reject stale lifecycle loops',async()=>{const f=fixture();try{const old=await aiAlertRevision(f.row());for(const action of ['acknowledge','resolve','reopen'])assert.equal((await f.run(action)).code,200);assert.equal(f.row().status,'open');assert.equal(f.count('ai_findings'),0);assert.equal(f.count('ai_activity_logs'),3);assert.equal((await f.run('acknowledge',old)).code,409);}finally{f.sqlite.close();}});
test('an existing unresolved source finding blocks escalation without changing the alert',async()=>{const f=fixture();try{await f.run();f.sqlite.exec("UPDATE ai_assurance_alerts SET status='open',finding_id=NULL");const original=f.row();assert.equal((await f.run()).code,409);assert.deepEqual(f.row(),original);assert.equal(f.count('ai_findings'),1);assert.equal(f.count('ai_activity_logs'),1);}finally{f.sqlite.close();}});
