import test from 'node:test';
import assert from 'node:assert/strict';
import { DatabaseSync } from 'node:sqlite';
import { readFileSync,readdirSync } from 'node:fs';
import { observeAiAlert } from '../app/ai/alert-observations';
import { aiAlertRevision } from '../app/ai/alert-transitions';
const now='2026-10-05T00:00:00.000Z',later='2026-10-06T00:00:00.000Z';
const candidate={metric:'drift' as const,title:'Drift breach',severity:'High' as const,observed:12,threshold:10};
function fixture(){
 const sqlite=new DatabaseSync(':memory:');for(const prefix of ['0043_','0045_','0060_','0064_'])sqlite.exec(readFileSync('drizzle/'+readdirSync('drizzle').find(n=>n.startsWith(prefix)),'utf8'));
 sqlite.exec('CREATE TABLE ai_activity_logs(id TEXT PRIMARY KEY,actor TEXT,action TEXT,provider TEXT,model TEXT,prompt_hash TEXT,context_refs_json TEXT,status TEXT,latency_ms INTEGER,detail TEXT,created_at TEXT)');
 function seed(table:string,values:Record<string,string|number>){const cols=sqlite.prepare(`PRAGMA table_info(${table})`).all().filter(c=>c.notnull||c.pk);sqlite.prepare(`INSERT INTO ${table}(${cols.map(c=>c.name).join(',')}) VALUES(${cols.map(()=>'?').join(',')})`).run(...cols.map(c=>values[String(c.name)]??(/INTEGER|REAL/.test(String(c.type))?1:'fixture')));}
 seed('ai_model_inventory',{id:'MODEL',status:'approved',risk_tier:'High'});seed('ai_assurance_policies',{id:'POLICY',model_id:'MODEL',status:'approved',updated_at:now,review_date:'2090-01-01'});seed('ai_model_monitoring',{id:'MON-1',model_id:'MODEL',recorded_at:now});
 const source={id:'POLICY',model_id:'MODEL',monitoring_ref:'MON-1',updated_at:now,risk_tier:'High'};
 let beforeBatch:(()=>void)|undefined;
 function prepare(sql:string,args:(string|number|null)[]=[]){return{bind(...values:(string|number|null)[]){return prepare(sql,values);},exec(){const stmt=sqlite.prepare(sql),results=stmt.all(...args);return {results,meta:{changes:Number(sqlite.prepare('SELECT changes() n').get()!.n)}};}};}
 const db={prepare,async batch(statements:ReturnType<typeof prepare>[]){const hook=beforeBatch;beforeBatch=undefined;hook?.();sqlite.exec('BEGIN');try{const results=statements.map(s=>s.exec());sqlite.exec('COMMIT');return results;}catch(e){sqlite.exec('ROLLBACK');throw e;}}} as unknown as D1Database;
 const row=()=>sqlite.prepare('SELECT * FROM ai_assurance_alerts').get()!;
 return {sqlite,source,row,seed,run:(sourceOverride=source,c=candidate,at=now)=>observeAiAlert(db,sourceOverride,c,'admin',at),beforeBatch:(fn:()=>void)=>{beforeBatch=fn;}};
}
test('repeated and concurrent identical scans leave count timestamp revision and observation audit unchanged',async()=>{const f=fixture();try{assert.deepEqual((await Promise.all([f.run(),f.run()])).sort(),['created','unchanged']);const original=f.row(),revision=await aiAlertRevision(original);assert.equal(await f.run(undefined,undefined,later),'unchanged');assert.deepEqual(f.row(),original);assert.equal(await aiAlertRevision(f.row()),revision);assert.equal(f.sqlite.prepare('SELECT count(*) n FROM ai_activity_logs').get()!.n,1);}finally{f.sqlite.close();}});
test('a distinct measurement increments once while retaining human ownership and CAPA link',async()=>{const f=fixture();try{await f.run();f.sqlite.exec("UPDATE ai_assurance_alerts SET status='escalated',owner='owner',finding_id='FINDING',action_note='Human review'");f.seed('ai_model_monitoring',{id:'MON-2',model_id:'MODEL',recorded_at:later});const source={...f.source,monitoring_ref:'MON-2'};assert.equal(await f.run(source,candidate,later),'updated');assert.equal(await f.run(source,candidate,later),'unchanged');assert.equal(f.row().occurrence_count,2);assert.equal(f.row().finding_id,'FINDING');assert.equal(f.row().action_note,'Human review');assert.equal(f.row().owner,'owner');assert.equal(f.row().status,'escalated');assert.equal(f.row().first_seen_at,now);}finally{f.sqlite.close();}});
test('new observations cannot alter resolved alerts or replace newer measurement snapshots',async()=>{const f=fixture();try{await f.run();f.seed('ai_model_monitoring',{id:'MON-2',model_id:'MODEL',recorded_at:later});const source={...f.source,monitoring_ref:'MON-2'};await f.run(source,candidate,later);const latest=f.row();assert.equal(await f.run(), 'unchanged');assert.deepEqual(f.row(),latest);f.sqlite.exec("UPDATE ai_assurance_alerts SET status='resolved'");const resolved=f.row();assert.equal(await f.run(source,{...candidate,observed:20},later),'unchanged');assert.deepEqual(f.row(),resolved);}finally{f.sqlite.close();}});
test('policy changes retirement and a newer measurement before commit reject stale scan input',async()=>{for(const change of ["UPDATE ai_model_inventory SET status='retired'","UPDATE ai_assurance_policies SET status='draft'","UPDATE ai_assurance_policies SET updated_at='changed'","UPDATE ai_assurance_policies SET review_date='2025-01-01'","UPDATE ai_model_monitoring SET id='MON-2'"]){const f=fixture();try{f.beforeBatch(()=>f.sqlite.exec(change));assert.equal(await f.run(),'unchanged');assert.equal(f.row(),undefined);assert.equal(f.sqlite.prepare('SELECT count(*) n FROM ai_activity_logs').get()!.n,0);}finally{f.sqlite.close();}}});
test('observation audit failure rolls back new and updated alerts',async()=>{for(const existing of [false,true]){const f=fixture();try{if(existing)await f.run();const original=f.row();f.sqlite.exec("CREATE TRIGGER fail_audit BEFORE INSERT ON ai_activity_logs BEGIN SELECT RAISE(ABORT,'injected observation audit failure'); END");await assert.rejects(f.run(undefined,{...candidate,observed:20},later),/injected observation audit failure/);assert.deepEqual(f.row(),original);}finally{f.sqlite.close();}}});
test('missing measurements are deduplicated with null-safe equality',async()=>{const f=fixture();try{f.sqlite.exec('DELETE FROM ai_model_monitoring');const source={...f.source,monitoring_ref:''};assert.equal(await f.run(source),'created');assert.equal(await f.run(source),'unchanged');assert.equal(f.row().monitoring_ref,null);assert.equal(f.row().occurrence_count,1);}finally{f.sqlite.close();}});
