import test from "node:test";
import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import {alertFingerprint,assuranceAlertCandidates,validateAlertAction} from "../app/ai/assurance-alerts";
const policy={minAccuracy:85,maxErrorRate:5,maxDriftScore:15,maxBiasScore:10,maxP95LatencyMs:1000,minSampleSize:100,frequencyDays:30};
test("assurance alerts deterministically classify every baseline breach",()=>{const alerts=assuranceAlertCandidates(policy,{accuracy:60,errorRate:9,driftScore:30,biasScore:20,p95LatencyMs:2000,sampleSize:50,recordedAt:"2026-01-01T00:00:00Z"},"Critical","2026-03-01T00:00:00Z");assert.deepEqual(new Set(alerts.map(a=>a.metric)),new Set(["measurement","accuracy","error-rate","drift","bias","latency","sample-size"]));assert.ok(alerts.some(a=>a.severity==="Critical"));});
test("missing measurements are critical for high-risk models and fingerprints deduplicate",async()=>{assert.equal(assuranceAlertCandidates(policy,null,"Critical")[0].severity,"Critical");assert.equal(await alertFingerprint("AIM-1","AICA-1","drift"),await alertFingerprint("AIM-1","AICA-1","drift"));assert.notEqual(await alertFingerprint("AIM-1","AICA-1","drift"),await alertFingerprint("AIM-1","AICA-1","bias"));});
test("alarm actions require exact human confirmation and ownership",()=>{assert.equal(validateAlertAction({action:"acknowledge",note:"The owner will investigate",owner:"mlops@example.com",confirmation:"ALARMI KABUL ET"}).action,"acknowledge");assert.throws(()=>validateAlertAction({action:"acknowledge",note:"The owner will investigate",owner:"",confirmation:"ALARMI KABUL ET"}),/sorumlusu/);assert.equal(validateAlertAction({action:"escalate",note:"Open CAPA for material breach",confirmation:"CAPA OLUŞTUR"}).action,"escalate");});
test("assurance alert lifecycle is audited, CAPA-linked and integrated everywhere",async()=>{const[route,migration,storage,ui,copilot,layout,gate,portfolio,dossier,readme,architecture]=await Promise.all([readFile("app/api/ai/assurance-alerts/route.ts","utf8"),readFile("drizzle/0064_fornost_ai_assurance_alerts.sql","utf8"),readFile("app/ai/storage.ts","utf8"),readFile("app/fornost-ai-assurance-alerts.tsx","utf8"),readFile("app/fornost-ai-copilot.tsx","utf8"),readFile("app/layout.tsx","utf8"),readFile("app/api/ai/release-gate/route.ts","utf8"),readFile("app/api/ai/portfolio/route.ts","utf8"),readFile("app/api/ai/dossier/route.ts","utf8"),readFile("README.md","utf8"),readFile("docs/AI-ARCHITECTURE.md","utf8")]);assert.match(route,/ai-assurance-alert-sync/);assert.match(route,/CAPA'ya dönüştürülebilir/);assert.match(route,/formula-safe csv/);assert.match(migration,/fingerprint TEXT NOT NULL UNIQUE/);assert.match(storage,/aiAssuranceAlertsSql/);assert.match(ui,/AI Güvence Alarmları/);assert.match(copilot,/AI Alarmlar/);assert.match(layout,/fornost-ai-assurance-alerts\.css/);assert.match(gate,/ai_assurance_alerts/);assert.match(portfolio,/blockingAssuranceAlerts/);assert.match(dossier,/assuranceAlerts/);assert.match(readme,/tekilleştirilmiş güvence alarmları/);assert.match(architecture,/Raw prompts and model responses are never stored/);});
