import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { calculateAiModelRisk,validateAiModel } from "../app/ai/model-inventory";
const valid={systemName:"Fornost Copilot",modelName:"qwen3:14b",vendor:"Internal AI",purpose:"GRC kayıtlarını kaynaklı biçimde analiz etmek",owner:"security@example.com",deployment:"On-Prem",region:"Türkiye",dataClassification:"Confidential",autonomy:"Advisory",affectedUsers:50,impact:4,likelihood:3,dataSensitivity:4,autonomyRisk:2,controlMaturity:4,controls:"RBAC, audit, human approval",reviewDate:"2027-03-01"};

test("model inventory calculates deterministic inherent and residual risk",()=>{assert.deepEqual(calculateAiModelRisk({impact:4,likelihood:3,dataSensitivity:4,autonomyRisk:2,controlMaturity:4}),{inherentScore:18,residualScore:8,riskTier:"Medium"});const value=validateAiModel(valid);assert.equal(value.riskTier,"Medium");assert.equal(value.affectedUsers,50);});
test("model policy rejects restricted external SaaS and critical autonomous systems",()=>{assert.throws(()=>validateAiModel({...valid,deployment:"External SaaS",dataClassification:"Restricted"}),/Restricted/);assert.throws(()=>validateAiModel({...valid,autonomy:"Autonomous",impact:5,likelihood:5,dataSensitivity:5,autonomyRisk:5,controlMaturity:1}),/Autonomous/);});
test("model inventory lifecycle is Admin-only, controlled, audited and exportable",async()=>{const [route,migration,storage,ui,copilot]=await Promise.all([readFile("app/api/ai/models/route.ts","utf8"),readFile("drizzle/0043_fornost_ai_model_inventory.sql","utf8"),readFile("app/ai/storage.ts","utf8"),readFile("app/fornost-ai-model-inventory.tsx","utf8"),readFile("app/fornost-ai-copilot.tsx","utf8")]);assert.match(route,/requireRole\(req,\["Admin"\]\)/);assert.match(route,/Kritik riskli model/);assert.match(route,/format.*csv/);assert.match(route,/^[\s\S]*\^\[=\+\\-@\]/);assert.match(migration,/ai_model_inventory_status_risk_idx/);assert.match(storage,/modelInventorySql/);assert.match(ui,/AI Sistem ve Model Envanteri/);assert.match(copilot,/AI Envanteri/);});
