import test from "node:test";
import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {DEFAULT_AI_OPERATING_POLICY,evaluateAiAccess,mapAiOperatingPolicy} from "../app/ai/operating-policy";

test("default policy preserves existing AI access",()=>{for(const role of ["Admin","Editor","Viewer"] as const)assert.equal(evaluateAiAccess(DEFAULT_AI_OPERATING_POLICY,role,"chat").allowed,true);for(const operation of ["drafts","agents","retrieval","evaluations"] as const)assert.equal(evaluateAiAccess(DEFAULT_AI_OPERATING_POLICY,"Admin",operation).allowed,true);});
test("emergency stop denies every role and operation with bounded message",()=>{const policy={...DEFAULT_AI_OPERATING_POLICY,emergencyStop:true,maintenanceMessage:"Security review"};for(const role of ["Admin","Editor","Viewer"] as const)for(const operation of ["chat","drafts","agents","retrieval","evaluations"] as const){const result=evaluateAiAccess(policy,role,operation);assert.equal(result.allowed,false);assert.equal(result.code,"emergency-stop");assert.equal(result.message,"Security review");}});
test("operation switches are independently enforced",()=>{const policy={...DEFAULT_AI_OPERATING_POLICY,agentsEnabled:false,retrievalEnabled:false};assert.equal(evaluateAiAccess(policy,"Admin","chat").allowed,true);assert.equal(evaluateAiAccess(policy,"Admin","agents").code,"operation-disabled");assert.equal(evaluateAiAccess(policy,"Editor","retrieval").allowed,false);});
test("chat role switches do not lock administrators",()=>{const policy={...DEFAULT_AI_OPERATING_POLICY,viewerChat:false,editorChat:false};assert.equal(evaluateAiAccess(policy,"Viewer","chat").code,"role-denied");assert.equal(evaluateAiAccess(policy,"Editor","chat").code,"role-denied");assert.equal(evaluateAiAccess(policy,"Admin","chat").allowed,true);});
test("stored policy mapping is strict and bounds maintenance text",()=>{const policy=mapAiOperatingPolicy({emergency_stop:1,chat_enabled:0,drafts_enabled:1,agents_enabled:1,retrieval_enabled:1,evaluations_enabled:0,viewer_chat:0,editor_chat:1,maintenance_message:`Review${"x".repeat(500)}`,updated_by:"admin@example.com",updated_at:"2026-09-11T00:00:00Z"});assert.equal(policy.emergencyStop,true);assert.equal(policy.chatEnabled,false);assert.equal(policy.evaluationsEnabled,false);assert.equal(policy.maintenanceMessage.length,300);});
test("every inference and retrieval route enforces the central policy",()=>{for(const [file,operation] of [["chat","chat"],["drafts","drafts"],["agents","agents"],["evaluations","evaluations"],["knowledge/search","retrieval"]]){const source=readFileSync(new URL(`../app/api/ai/${file}/route.ts`,import.meta.url),"utf8");assert.match(source,new RegExp(`checkAiAccess\\(.*\\"${operation}\\"`),`${file} must enforce ${operation}`);assert.match(source,/policy-denied/);}});
test("policy persistence is available in migrations and runtime self-heal",()=>{const migration=readFileSync(new URL("../drizzle/0041_fornost_ai_operating_policy.sql",import.meta.url),"utf8"),storage=readFileSync(new URL("../app/ai/storage.ts",import.meta.url),"utf8"),api=readFileSync(new URL("../app/api/ai/policy/route.ts",import.meta.url),"utf8");assert.match(migration,/CREATE TABLE IF NOT EXISTS ai_operating_policy/);assert.match(storage,/runtime\.DB\.prepare\(operatingPolicySql\)/);assert.match(api,/requireRole\(req,\["Admin"\]\)/);assert.match(api,/POLİTİKAYI UYGULA/);});
