import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { obligationAttention, validateAiObligation, validateObligationAction } from "../app/ai/obligations";

const base={modelId:"AIM-1",profileId:"AIRG-1",framework:"EU AI Act",obligationCode:"EU-AIA-26.2",title:"Human oversight controls",description:"Maintain effective and competent human oversight for production decisions.",owner:"ai-owner@example.com",reviewer:"legal@example.com",dueDate:"2027-06-01",priority:"High",evidencePlan:"Approved operating procedure and sampled override records",recurringDays:90};

test("regulatory obligations require accountable and independent owners",()=>{const value=validateAiObligation(base,"2027-01-01");assert.equal(value.recurringDays,90);assert.throws(()=>validateAiObligation({...base,reviewer:base.owner},"2027-01-01"),/farklı/);assert.throws(()=>validateAiObligation({...base,dueDate:"2026-12-31"},"2027-01-01"),/ileri tarihli/);});
test("obligation evidence workflow uses exact confirmation and SHA-256",()=>{assert.equal(validateObligationAction({action:"submit",note:"Implementation is ready for independent verification",evidenceReference:"EVD-12345",evidenceSha256:"a".repeat(64),confirmation:"DOĞRULAMAYA GÖNDER"}).action,"submit");assert.throws(()=>validateObligationAction({action:"verify",note:"Verified independently",evidenceReference:"EVD-2",evidenceSha256:"bad",confirmation:"YÜKÜMLÜLÜĞÜ DOĞRULA"}),/SHA-256/);assert.equal(obligationAttention("open","High","2026-12-01","2027-01-01"),"overdue");});
test("obligations are maker-checker, audited, export-safe and assurance-integrated",async()=>{const[route,migration,storage,ui,layout,regulatory,gate,portfolio,dossier,readme,architecture,copilot]=await Promise.all([readFile("app/api/ai/obligations/route.ts","utf8"),readFile("drizzle/0065_fornost_ai_regulatory_obligations.sql","utf8"),readFile("app/ai/storage.ts","utf8"),readFile("app/fornost-ai-obligations.tsx","utf8"),readFile("app/layout.tsx","utf8"),readFile("app/fornost-ai-regulatory.tsx","utf8"),readFile("app/api/ai/release-gate/route.ts","utf8"),readFile("app/api/ai/portfolio/route.ts","utf8"),readFile("app/api/ai/dossier/route.ts","utf8"),readFile("README.md","utf8"),readFile("docs/AI-ARCHITECTURE.md","utf8"),readFile("app/fornost-ai-copilot.tsx","utf8")]);assert.match(route,/oluşturan veya doğrulamaya gönderen kişi/);assert.match(route,/formula-safe csv/);assert.match(route,/recordAiEvent/);assert.match(migration,/WHERE status!='completed'/);assert.match(storage,/aiRegulatoryObligationsSql/);assert.match(ui,/AI Yükümlülük Takibi/);assert.match(layout,/fornost-ai-obligations\.css/);assert.match(regulatory,/FornostAiObligations/);assert.match(gate,/blockingRegulatoryObligations/);assert.match(portfolio,/blockingRegulatoryObligations/);assert.match(dossier,/regulatoryObligations/);assert.match(readme,/operasyonel regülasyon yükümlülük/);assert.match(architecture,/independent verification/);assert.match(copilot,/AI Alarmlar/);});
