import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readAiRecordHistory} from '../app/ai/record-history';
function fixture(){const sqlite=new DatabaseSync(':memory:');sqlite.exec('CREATE TABLE ai_activity_logs(id TEXT PRIMARY KEY,actor TEXT,action TEXT,provider TEXT,model TEXT,prompt_hash TEXT,context_refs_json TEXT,status TEXT,latency_ms INTEGER,detail TEXT,created_at TEXT)');function prepare(sql:string,args:(string|number)[]=[]){return{bind(...values:(string|number)[]){return prepare(sql,values);},async all(){return{results:sqlite.prepare(sql).all(...args)};}};}const db={prepare} as unknown as D1Database;
 const add=(id:string,refs:string,action='ai-finding-resolve',detail='Reviewed evidence',at='2026-10-05T00:00:00.000Z')=>sqlite.prepare("INSERT INTO ai_activity_logs VALUES(?,'admin',?,'','',NULL,?,'success',0,?,?)").run(id,action,refs,detail,at);
 return{sqlite,add,read:async(id:string|null,limit=50)=>(await readAiRecordHistory(db,id,limit)).results};}
test('history filters exact JSON string references before applying its display limit',async()=>{const f=fixture();try{f.add('target','["AIF-1"]',undefined,undefined,'2025-01-01');for(let i=0;i<105;i++)f.add('unrelated'+i,'["AIF-10"]');assert.deepEqual((await f.read('AIF-1'))?.map(r=>r.id),['target']);assert.equal((await f.read(null,30))?.length,31);assert.deepEqual(await f.read("' OR 1=1 --"),[]);}finally{f.sqlite.close();}});
test('legacy model history matches a complete ID prefix and only known model inventory actions',async()=>{const f=fixture();try{f.add('legacy','[]','model-inventory-approved','AIM-1 approved');f.add('prefix','[]','model-inventory-approved','AIM-10 approved');f.add('free','[]','chat','AIM-1 appears in text');f.add('middle','[]','model-inventory-edit','Text AIM-1 edited');assert.deepEqual((await f.read('AIM-1'))?.map(r=>r.id),['legacy']);}finally{f.sqlite.close();}});
test('malformed scalar and non-string references cannot leak into record history',async()=>{const f=fixture();try{for(const [i,refs] of ['invalid','"AIF-1"','{"value":"AIF-1"}','[42,null,{}]'].entries())f.add(String(i),refs);f.add('real','["AIF-1","AIM-1"]');assert.deepEqual((await f.read('AIF-1'))?.map(r=>r.id),['real']);assert.equal((await f.read(null))?.length,5);}finally{f.sqlite.close();}});
test('history uses deterministic latest-first ordering and one extra row for truncation detection',async()=>{const f=fixture();try{for(const id of ['a','b','c'])f.add(id,'["AIM-1"]');assert.deepEqual((await f.read('AIM-1',1))?.map(r=>r.id),['c','b']);assert.deepEqual(await f.read('missing'),[]);}finally{f.sqlite.close();}});
