export const assets = [
  {
    id: '22222222-2222-4222-8222-222222222222',
    name: 'Müşteri Portalı',
    type: 'Uygulama',
    owner: 'Dijital Kanallar',
    classification: 'Gizli',
    criticality: 'Kritik',
    risks: 3,
    controls: '18/24',
  },
  {
    id: 'erp',
    name: 'Finans ERP',
    type: 'Uygulama',
    owner: 'Finans Teknolojileri',
    classification: 'Çok Gizli',
    criticality: 'Yüksek',
    risks: 2,
    controls: '21/22',
  },
  {
    id: 'lake',
    name: 'Analitik Veri Gölü',
    type: 'Veri',
    owner: 'Veri Platformu',
    classification: 'Gizli',
    criticality: 'Yüksek',
    risks: 4,
    controls: '14/20',
  },
];
export const risks = [
  {
    id: '33333333-3333-4333-8333-333333333333',
    title: 'Yetkisiz müşteri verisi erişimi',
    asset: 'Müşteri Portalı',
    owner: 'Uygulama Güvenliği',
    level: 'Kritik',
    score: 15,
    status: 'Açık',
    due: '18 Ağu',
  },
  {
    id: 'r2',
    title: 'Yedekleme geri dönüş testinin gecikmesi',
    asset: 'Finans ERP',
    owner: 'Altyapı',
    level: 'Yüksek',
    score: 12,
    status: 'İşleniyor',
    due: '24 Ağu',
  },
  {
    id: 'r3',
    title: 'Veri saklama politikasının eksik uygulanması',
    asset: 'Analitik Veri Gölü',
    owner: 'Veri Platformu',
    level: 'Orta',
    score: 8,
    status: 'Açık',
    due: '03 Eyl',
  },
];
export const controls = [
  {
    id: '44444444-4444-4444-8444-444444444444',
    code: 'UCL-IAM-01',
    title: 'Erişim haklarının periyodik gözden geçirilmesi',
    owner: 'IAM Ekibi',
    maturity: 3,
    status: 'İşleniyor',
    coverage: 74,
    frameworks: ['ISO 27001', 'NIST CSF'],
  },
  {
    id: 'c2',
    code: 'UCL-BCM-04',
    title: 'Yedeklerin geri dönüş testleri',
    owner: 'Altyapı',
    maturity: 2,
    status: 'Açık',
    coverage: 58,
    frameworks: ['ISO 27001', 'CIS'],
  },
  {
    id: 'c3',
    code: 'UCL-LOG-02',
    title: 'Güvenlik olay kayıtlarının izlenmesi',
    owner: 'SOC',
    maturity: 4,
    status: 'İşliyor',
    coverage: 91,
    frameworks: ['SOC 2', 'PCI DSS'],
  },
];
export const evidence = [
  {
    name: '2026 Q2 erişim gözden geçirme raporu',
    control: 'UCL-IAM-01',
    owner: 'IAM Ekibi',
    status: 'Uygun',
    valid: '30 Eyl 2026',
    type: 'PDF',
  },
  {
    name: 'Yedek geri dönüş test tutanağı',
    control: 'UCL-BCM-04',
    owner: 'Altyapı',
    status: 'İncelemede',
    valid: '—',
    type: 'PDF',
  },
  {
    name: 'SIEM kapsam dışa aktarımı',
    control: 'UCL-LOG-02',
    owner: 'SOC',
    status: 'Uygun',
    valid: '31 Ağu 2026',
    type: 'CSV',
  },
];
export const findings = [
  {
    id: '77777777-7777-4777-8777-777777777777',
    title: 'Ayrılan kullanıcı hesabı zamanında kapatılmamış',
    source: 'ISO 27001 İç Denetim',
    owner: 'IAM Ekibi',
    severity: 'Yüksek',
    status: 'Açık',
    due: '20 Ağu',
  },
  {
    id: 'f2',
    title: 'Yedek test örneklemi kapsamı yetersiz',
    source: 'BCP Masa Başı Testi',
    owner: 'Altyapı',
    severity: 'Orta',
    status: 'Aksiyon alındı',
    due: '29 Ağu',
  },
];
export const audits = [
  {
    name: 'ISO 27001 İç Denetim 2026',
    lead: 'Selin Aksoy',
    period: '01 Ağu — 16 Eyl',
    progress: 46,
    status: 'Sahada',
  },
  {
    name: 'KVKK Teknik Tedbirler İncelemesi',
    lead: 'Mert Demir',
    period: '22 Ağu — 12 Eyl',
    progress: 18,
    status: 'Planlama',
  },
];
