export type AssuranceNotificationStormPolicy={windowMinutes:number;highMaxPerRecipient:number;mediumMaxPerRecipient:number};
export type AssuranceNotificationStormPolicyEvent={id:string;actor:string;before_json:string;after_json:string;created_at:string};
export type AssuranceNotificationDeferral={outbox_id:string;recipient:string;severity:string;reason:string;first_deferred_at:string;last_deferred_at:string;defer_count:number;next_eligible_at:string;cleared_at:string|null};

export const defaultAssuranceNotificationStormPolicy:AssuranceNotificationStormPolicy={windowMinutes:60,highMaxPerRecipient:6,mediumMaxPerRecipient:3};
export const assuranceNotificationStormSchema=[
 `CREATE TABLE IF NOT EXISTS continuous_assurance_notification_storm_policy(id TEXT PRIMARY KEY,window_minutes INTEGER NOT NULL,high_max_per_recipient INTEGER NOT NULL,medium_max_per_recipient INTEGER NOT NULL,updated_by TEXT NOT NULL,updated_at TEXT NOT NULL)`,
 `CREATE TABLE IF NOT EXISTS continuous_assurance_notification_storm_policy_events(id TEXT PRIMARY KEY,actor TEXT NOT NULL,before_json TEXT NOT NULL,after_json TEXT NOT NULL,created_at TEXT NOT NULL)`,
 `CREATE INDEX IF NOT EXISTS ca_notification_storm_policy_events_idx ON continuous_assurance_notification_storm_policy_events(created_at)`,
 `CREATE TABLE IF NOT EXISTS continuous_assurance_notification_deferrals(outbox_id TEXT PRIMARY KEY,recipient TEXT NOT NULL,severity TEXT NOT NULL,reason TEXT NOT NULL,first_deferred_at TEXT NOT NULL,last_deferred_at TEXT NOT NULL,defer_count INTEGER NOT NULL,next_eligible_at TEXT NOT NULL,cleared_at TEXT)`,
 `CREATE INDEX IF NOT EXISTS ca_notification_deferrals_active_idx ON continuous_assurance_notification_deferrals(cleared_at,next_eligible_at,severity)`,
 `CREATE TABLE IF NOT EXISTS continuous_assurance_notification_recipient_leases(recipient TEXT PRIMARY KEY,lease_token TEXT NOT NULL,leased_until TEXT NOT NULL,updated_at TEXT NOT NULL)`,
 `CREATE INDEX IF NOT EXISTS ca_notification_recipient_leases_until_idx ON continuous_assurance_notification_recipient_leases(leased_until)`,
];

export async function ensureAssuranceNotificationStormSchema(db:D1Database){for(const sql of assuranceNotificationStormSchema)await db.prepare(sql).run()}
export async function readAssuranceNotificationStormPolicy(db:D1Database):Promise<AssuranceNotificationStormPolicy>{await ensureAssuranceNotificationStormSchema(db);const row=await db.prepare("SELECT window_minutes,high_max_per_recipient,medium_max_per_recipient FROM continuous_assurance_notification_storm_policy WHERE id='default'").first<{window_minutes:number;high_max_per_recipient:number;medium_max_per_recipient:number}>();return row?{windowMinutes:row.window_minutes,highMaxPerRecipient:row.high_max_per_recipient,mediumMaxPerRecipient:row.medium_max_per_recipient}:defaultAssuranceNotificationStormPolicy}
export async function readAssuranceNotificationStormPolicyEvents(db:D1Database,limit=50){await ensureAssuranceNotificationStormSchema(db);return (await db.prepare("SELECT id,actor,before_json,after_json,created_at FROM continuous_assurance_notification_storm_policy_events ORDER BY created_at DESC LIMIT ?").bind(Math.max(1,Math.min(100,Math.floor(limit)||50))).all<AssuranceNotificationStormPolicyEvent>()).results||[]}
export async function readAssuranceNotificationDeferrals(db:D1Database,limit=200){await ensureAssuranceNotificationStormSchema(db);return (await db.prepare("SELECT outbox_id,recipient,severity,reason,first_deferred_at,last_deferred_at,defer_count,next_eligible_at,cleared_at FROM continuous_assurance_notification_deferrals ORDER BY last_deferred_at DESC LIMIT ?").bind(Math.max(1,Math.min(1000,Math.floor(limit)||200))).all<AssuranceNotificationDeferral>()).results||[]}
export function stormLimitForSeverity(severity:string,policy:AssuranceNotificationStormPolicy){if(severity==="critical")return Number.POSITIVE_INFINITY;return severity==="high"?policy.highMaxPerRecipient:policy.mediumMaxPerRecipient}
export function activeStormDeferrals(rows:AssuranceNotificationDeferral[],now=new Date()){const stamp=now.getTime();return rows.filter(row=>!row.cleared_at&&new Date(row.next_eligible_at).getTime()>stamp)}

export async function saveAssuranceNotificationStormPolicy(db:D1Database,next:AssuranceNotificationStormPolicy,actor:string,now=new Date()){
 await ensureAssuranceNotificationStormSchema(db);const before=await readAssuranceNotificationStormPolicy(db),stamp=now.toISOString(),identity=String(actor||"").trim().slice(0,320);if(!identity)throw new Error("Actor is required.");
 if(!Number.isInteger(next.windowMinutes)||next.windowMinutes<15||next.windowMinutes>1440)throw new Error("Storm-control window must be between 15 and 1440 minutes.");
 if(!Number.isInteger(next.highMaxPerRecipient)||next.highMaxPerRecipient<1||next.highMaxPerRecipient>100)throw new Error("High recipient limit must be between 1 and 100.");
 if(!Number.isInteger(next.mediumMaxPerRecipient)||next.mediumMaxPerRecipient<1||next.mediumMaxPerRecipient>100)throw new Error("Medium recipient limit must be between 1 and 100.");
 if(next.mediumMaxPerRecipient>next.highMaxPerRecipient)throw new Error("Medium recipient limit cannot exceed High recipient limit.");
 await db.prepare("INSERT INTO continuous_assurance_notification_storm_policy(id,window_minutes,high_max_per_recipient,medium_max_per_recipient,updated_by,updated_at) VALUES('default',?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET window_minutes=excluded.window_minutes,high_max_per_recipient=excluded.high_max_per_recipient,medium_max_per_recipient=excluded.medium_max_per_recipient,updated_by=excluded.updated_by,updated_at=excluded.updated_at").bind(next.windowMinutes,next.highMaxPerRecipient,next.mediumMaxPerRecipient,identity,stamp).run();
 if(JSON.stringify(before)!==JSON.stringify(next))await db.prepare("INSERT INTO continuous_assurance_notification_storm_policy_events(id,actor,before_json,after_json,created_at) VALUES(?,?,?,?,?)").bind(crypto.randomUUID(),identity,JSON.stringify(before),JSON.stringify(next),stamp).run();return{before,after:next,updatedBy:identity,updatedAt:stamp};
}

export async function acquireAssuranceRecipientLease(db:D1Database,recipient:string,now=new Date()){
 await ensureAssuranceNotificationStormSchema(db);const key=String(recipient||"").trim().toLowerCase().slice(0,320),token=crypto.randomUUID(),stamp=now.toISOString(),leasedUntil=new Date(now.getTime()+120_000).toISOString();if(!key)return{key:"",token:""};
 await db.prepare(`INSERT INTO continuous_assurance_notification_recipient_leases(recipient,lease_token,leased_until,updated_at) VALUES(?,?,?,?) ON CONFLICT(recipient) DO UPDATE SET lease_token=excluded.lease_token,leased_until=excluded.leased_until,updated_at=excluded.updated_at WHERE continuous_assurance_notification_recipient_leases.leased_until<=?`).bind(key,token,leasedUntil,stamp,stamp).run();const row=await db.prepare("SELECT lease_token FROM continuous_assurance_notification_recipient_leases WHERE recipient=?").bind(key).first<{lease_token:string}>();return{key,token:row?.lease_token===token?token:""};
}
export async function releaseAssuranceRecipientLease(db:D1Database,recipient:string,token:string){if(recipient&&token)await db.prepare("DELETE FROM continuous_assurance_notification_recipient_leases WHERE recipient=? AND lease_token=?").bind(recipient,token).run()}

export async function recipientStormDecision(db:D1Database,recipient:string,severity:string,policy:AssuranceNotificationStormPolicy,now=new Date()){
 const limit=stormLimitForSeverity(severity,policy);if(!Number.isFinite(limit))return{allowed:true,count:0,limit,nextEligibleAt:""};const cutoff=new Date(now.getTime()-policy.windowMinutes*60_000).toISOString(),rows=(await db.prepare("SELECT attempted_at FROM continuous_assurance_notification_deliveries WHERE state='sent' AND lower(recipient)=lower(?) AND attempted_at>? ORDER BY attempted_at ASC LIMIT 500").bind(recipient,cutoff).all<{attempted_at:string}>()).results||[],count=rows.length;if(count<limit)return{allowed:true,count,limit,nextEligibleAt:""};const releaseIndex=Math.max(0,count-limit),releaseAt=new Date(rows[Math.min(releaseIndex,rows.length-1)]?.attempted_at||now.toISOString()).getTime(),nextEligibleAt=new Date((Number.isFinite(releaseAt)?releaseAt:now.getTime())+policy.windowMinutes*60_000).toISOString();return{allowed:false,count,limit,nextEligibleAt};
}
export async function recordAssuranceStormDeferral(db:D1Database,outboxId:string,recipient:string,severity:string,nextEligibleAt:string,now=new Date()){
 await ensureAssuranceNotificationStormSchema(db);const stamp=now.toISOString(),reason="recipient-rate-limit";await db.prepare("INSERT INTO continuous_assurance_notification_deferrals(outbox_id,recipient,severity,reason,first_deferred_at,last_deferred_at,defer_count,next_eligible_at,cleared_at) VALUES(?,?,?,?,?,?,?,?,NULL) ON CONFLICT(outbox_id) DO UPDATE SET recipient=excluded.recipient,severity=excluded.severity,reason=excluded.reason,last_deferred_at=excluded.last_deferred_at,defer_count=continuous_assurance_notification_deferrals.defer_count+1,next_eligible_at=excluded.next_eligible_at,cleared_at=NULL").bind(outboxId,recipient,severity,reason,stamp,stamp,1,nextEligibleAt).run()}
export async function clearAssuranceStormDeferral(db:D1Database,outboxId:string,now=new Date()){await ensureAssuranceNotificationStormSchema(db);await db.prepare("UPDATE continuous_assurance_notification_deferrals SET cleared_at=? WHERE outbox_id=? AND cleared_at IS NULL").bind(now.toISOString(),outboxId).run()}
