"use client";

import {FormEvent,useCallback,useEffect,useState} from "react";
import {withBasePath} from "./base-path";
import "./assurance-notification-settings.css";

type Lang="tr"|"en";
type Policy={criticalSlaMinutes:number;highSlaMinutes:number;mediumSlaMinutes:number;maxAttempts:number};
type Summary={pending:number;sent:number;sent30d:number;failed:number;failedAttempts30d:number;retryExhausted:number;attempts30d:number;deliveryRate30d:number;inAppOnly:number;slaBreaches:number;breaches:Array<{id:string;severity:string;recipient:string;subject:string;ageMinutes:number;slaMinutes:number}>};
type Delivery={id:string;outboxId:string;attempt:number;provider:string;state:string;detail:string;recipient:string;attemptedBy:string;attemptedAt:string};
type PolicyEvent={id:string;actor:string;before:Policy;after:Policy;createdAt:string};
type Payload={policy:Policy;summary:Summary;policyEvents:PolicyEvent[];deliveries:Delivery[]};
const defaults:Policy={criticalSlaMinutes:240,highSlaMinutes:1440,mediumSlaMinutes:4320,maxAttempts:3};

export default function AssuranceNotificationSettings({lang}:{lang:Lang}){
 const tr=lang==="tr",[data,setData]=useState<Payload|null>(null),[policy,setPolicy]=useState<Policy>(defaults),[busy,setBusy]=useState(""),[message,setMessage]=useState("");
 const load=useCallback(async()=>{const response=await fetch(withBasePath("/api/continuous-assurance/notifications"),{cache:"no-store",headers:{accept:"application/json"}}).catch(()=>null),body=await response?.json().catch(()=>null);if(response?.ok&&body){setData(body);setPolicy(body.policy||defaults)}else if(response)setMessage(String(body?.error||(tr?"Notification operasyon verisi okunamadı.":"Notification operations could not be loaded.")))},[tr]);
 useEffect(()=>{let active=true;fetch(withBasePath("/api/continuous-assurance/notifications"),{cache:"no-store",headers:{accept:"application/json"}}).then(async response=>({response,body:await response.json().catch(()=>null)})).then(({response,body})=>{if(!active)return;if(response.ok&&body){setData(body);setPolicy(body.policy||defaults)}else setMessage(String(body?.error||(tr?"Notification operasyon verisi okunamadı.":"Notification operations could not be loaded.")))}).catch(()=>{});return()=>{active=false}},[tr]);
 async function savePolicy(e:FormEvent){e.preventDefault();if(busy)return;setBusy("save");setMessage("");const response=await fetch(withBasePath("/api/continuous-assurance/notifications"),{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify(policy)}).catch(()=>null),body=await response?.json().catch(()=>({}))||{};setBusy("");setMessage(response?.ok?(tr?"Notification SLA policy kaydedildi.":"Notification SLA policy saved."):String(body.error||(tr?"Policy kaydedilemedi.":"Policy could not be saved.")));if(response?.ok)await load()}
 async function dispatch(){if(busy)return;setBusy("dispatch");setMessage("");const response=await fetch(withBasePath("/api/continuous-assurance/notifications"),{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"dispatch",limit:20})}).catch(()=>null),body=await response?.json().catch(()=>({}))||{};setBusy("");setMessage(response?.ok?(tr?`${body.sent||0} gönderim kabul edildi, ${body.failed||0} deneme başarısız.`:`${body.sent||0} deliveries accepted, ${body.failed||0} attempts failed.`):String(body.error||(tr?"Dispatch çalıştırılamadı.":"Dispatch could not run.")));if(response?.ok)await load()}
 const summary=data?.summary,lastPolicyEvent=data?.policyEvents?.[0];
 return <section className="assurance-notification-console">
  <header><div><small>CONTINUOUS ASSURANCE NOTIFICATIONS</small><h3>{tr?"Notification operasyonları ve SLA":"Notification operations & SLA"}</h3><p>{tr?"Owner/governance routing kuyruğunu, gerçek e-posta transport denemelerini ve severity bazlı teslim SLA'larını yönetin.":"Manage owner/governance routing, real email transport attempts and severity-based delivery SLAs."}</p></div><button type="button" className="primary" disabled={!!busy} onClick={dispatch}>{busy==="dispatch"?(tr?"Gönderiliyor…":"Dispatching…"):(tr?"Bekleyenleri Gönder":"Dispatch Pending")}</button></header>
  {message&&<div className="assurance-notification-message">{message}</div>}
  <div className="assurance-notification-kpis">
   <article className={summary?.pending?"attention":""}><small>{tr?"Gönderim bekleyen":"Pending delivery"}</small><b>{summary?.pending??0}</b><span>{tr?"Harici transport bekliyor":"Awaiting external transport"}</span></article>
   <article><small>{tr?"30g transport sent":"30d transport sent"}</small><b>{summary?.sent30d??summary?.sent??0}</b><span>{summary?.deliveryRate30d??100}% {tr?"attempt başarı oranı":"attempt success rate"}</span></article>
   <article className={summary?.failed?"critical":""}><small>{tr?"Hatalı kuyruk":"Failed queue"}</small><b>{summary?.failed??0}</b><span>{summary?.retryExhausted??0} {tr?"retry limiti dolu":"retry exhausted"}</span></article>
   <article><small>{tr?"Yalnız in-app":"In-app only"}</small><b>{summary?.inAppOnly??0}</b><span>{tr?"Harici alıcı yok":"No external recipient"}</span></article>
   <article className={summary?.slaBreaches?"critical":""}><small>{tr?"SLA ihlali":"SLA breach"}</small><b>{summary?.slaBreaches??0}</b><span>{tr?"Severity süresi aşıldı":"Severity deadline exceeded"}</span></article>
  </div>
  <div className="assurance-notification-grid">
   <form className="assurance-notification-policy" onSubmit={savePolicy}><header><div><small>DELIVERY POLICY</small><b>{tr?"Severity bazlı SLA ve retry":"Severity SLA & retry"}</b></div><span>{lastPolicyEvent?(tr?`Son değişiklik ${lastPolicyEvent.actor}`:`Last changed by ${lastPolicyEvent.actor}`):(tr?"Admin kontrollü":"Admin governed")}</span></header><div>
    <label><span>{tr?"Critical SLA (dk)":"Critical SLA (min)"}</span><input type="number" min="15" max="10080" value={policy.criticalSlaMinutes} onChange={e=>setPolicy(x=>({...x,criticalSlaMinutes:Number(e.target.value)}))}/></label>
    <label><span>{tr?"High SLA (dk)":"High SLA (min)"}</span><input type="number" min="30" max="20160" value={policy.highSlaMinutes} onChange={e=>setPolicy(x=>({...x,highSlaMinutes:Number(e.target.value)}))}/></label>
    <label><span>{tr?"Medium SLA (dk)":"Medium SLA (min)"}</span><input type="number" min="60" max="43200" value={policy.mediumSlaMinutes} onChange={e=>setPolicy(x=>({...x,mediumSlaMinutes:Number(e.target.value)}))}/></label>
    <label><span>{tr?"Maks. deneme":"Max attempts"}</span><input type="number" min="1" max="10" value={policy.maxAttempts} onChange={e=>setPolicy(x=>({...x,maxAttempts:Number(e.target.value)}))}/></label>
   </div><footer><small>{tr?"Critical ≤ High ≤ Medium olmalıdır. Başarılı provider kabulü delivery olarak kaydedilir; okunma iddiası yapılmaz.":"Critical ≤ High ≤ Medium is required. Provider acceptance is recorded as delivery; message-read status is not claimed."}</small><button className="primary" disabled={!!busy}>{busy==="save"?(tr?"Kaydediliyor…":"Saving…"):(tr?"Policy Kaydet":"Save Policy")}</button></footer></form>
   <section className="assurance-notification-breaches"><header><div><small>SLA BREACH REGISTER</small><b>{tr?"Geciken bildirimler":"Overdue notifications"}</b></div><span>{summary?.slaBreaches??0}</span></header><div>{summary?.breaches?.length?summary.breaches.slice(0,8).map(item=><article key={item.id}><div><b>{item.subject}</b><small>{item.recipient}</small></div><strong>{item.severity}</strong><span>{Math.floor(item.ageMinutes/60)}h / {Math.floor(item.slaMinutes/60)}h</span></article>):<p>{tr?"SLA ihlali yok.":"No SLA breaches."}</p>}</div></section>
  </div>
  <section className="assurance-delivery-register"><header><div><small>DELIVERY AUDIT TRAIL</small><b>{tr?"Son transport denemeleri":"Recent transport attempts"} · {summary?.attempts30d??0} / 30d</b></div><button type="button" className="ghost" disabled={!!busy} onClick={()=>void load()}>{tr?"Yenile":"Refresh"}</button></header><div className="table-scroll"><table><thead><tr><th>{tr?"Durum":"State"}</th><th>Provider</th><th>{tr?"Alıcı":"Recipient"}</th><th>{tr?"Deneme":"Attempt"}</th><th>{tr?"Detay":"Detail"}</th><th>Actor</th><th>{tr?"Zaman":"Time"}</th></tr></thead><tbody>{data?.deliveries?.length?data.deliveries.slice(0,30).map(item=><tr key={item.id}><td><span className={`delivery-state ${item.state}`}>{item.state}</span></td><td>{item.provider||"—"}</td><td>{item.recipient||"—"}</td><td>{item.attempt}</td><td>{item.detail||"—"}</td><td>{item.attemptedBy||"system"}</td><td>{new Date(item.attemptedAt).toLocaleString(tr?"tr-TR":"en-GB")}</td></tr>):<tr><td colSpan={7}>{tr?"Henüz transport denemesi yok.":"No transport attempts yet."}</td></tr>}</tbody></table></div></section>
 </section>;
}
