import {ensureAssuranceNotificationDeliverySchema,failedAttemptsSinceReset,latestRetryResetByOutbox,readAssuranceDeliveryData,readAssuranceNotificationPolicy,summarizeAssuranceDelivery,type AssuranceDeliveryOutbox,type AssuranceDeliveryRecord,type AssuranceNotificationPolicy,type AssuranceNotificationRetryReset} from "./assurance-notification-delivery";
import {readAssuranceNotificationDispatchRuns,summarizeAssuranceSchedulerHealth} from "./assurance-notification-dispatch";
import {activeStormDeferrals,readAssuranceNotificationDeferrals,readAssuranceNotificationStormPolicy} from "./assurance-notification-storm";
import type {AssuranceEscalationSeverity,AssuranceEscalationSignal} from "./assurance-escalation-store";

export const notificationGovernanceKinds=["notification-transport-unconfigured","notification-delivery-sla","notification-delivery-exhausted","notification-scheduler-stale","notification-storm-pressure"] as const;
const severityOf=(value:string):AssuranceEscalationSeverity=>value==="critical"?"critical":value==="high"?"high":"medium";
const exhaustedSeverity=(value:string):AssuranceEscalationSeverity=>value==="critical"?"critical":"high";

export function buildNotificationGovernanceSignalsFromData(outbox:AssuranceDeliveryOutbox[],deliveries:AssuranceDeliveryRecord[],policy:AssuranceNotificationPolicy,emailConfigured:boolean,now=new Date(),retryResets:AssuranceNotificationRetryReset[]=[]):AssuranceEscalationSignal[]{
 const signals:AssuranceEscalationSignal[]=[],externalQueue=outbox.filter(item=>item.status==="queued"&&item.recipient),history=new Map<string,AssuranceDeliveryRecord[]>(),resetMap=latestRetryResetByOutbox(retryResets);for(const item of deliveries)history.set(item.outbox_id,[...(history.get(item.outbox_id)||[]),item]);
 const exhausted=new Set<string>();for(const item of externalQueue){const attempts=history.get(item.id)||[],sent=attempts.some(attempt=>attempt.state==="sent"),failed=failedAttemptsSinceReset(attempts,resetMap.get(item.id)).length;if(!sent&&failed>=policy.maxAttempts){exhausted.add(item.id);signals.push({fingerprint:`notification-retry:${item.id}`,kind:"notification-delivery-exhausted",severity:exhaustedSeverity(item.severity),subjectRef:item.id,owner:"",title:"Notification delivery retry exhausted",detail:`${item.severity} notification to ${item.recipient} exhausted ${failed}/${policy.maxAttempts} delivery attempts in the current retry budget.`,source:{outboxId:item.id,escalationId:item.escalation_id,recipient:item.recipient,severity:item.severity,failedAttempts:failed,maxAttempts:policy.maxAttempts,governanceOnly:true}})}}
 const summary=summarizeAssuranceDelivery(outbox,deliveries,policy,now,retryResets);for(const breach of summary.breaches){if(exhausted.has(breach.id))continue;const item=outbox.find(row=>row.id===breach.id);signals.push({fingerprint:`notification-sla:${breach.id}`,kind:"notification-delivery-sla",severity:severityOf(breach.severity),subjectRef:breach.id,owner:"",title:"Notification delivery SLA breached",detail:`${breach.severity} notification to ${breach.recipient} is ${breach.ageMinutes} minute(s) old; SLA is ${breach.slaMinutes} minute(s).`,source:{outboxId:breach.id,escalationId:item?.escalation_id||"",recipient:breach.recipient,severity:breach.severity,ageMinutes:breach.ageMinutes,slaMinutes:breach.slaMinutes,governanceOnly:true}})}
 if(externalQueue.length&&!emailConfigured)signals.push({fingerprint:"notification-transport:unconfigured",kind:"notification-transport-unconfigured",severity:"high",subjectRef:"email-integration",owner:"",title:"Notification transport is not configured",detail:`${externalQueue.length} external Continuous Assurance notification(s) are queued without an enabled email transport.`,source:{queued:externalQueue.length,governanceOnly:true}});
 return signals;
}

export async function buildNotificationGovernanceSignals(db:D1Database,now=new Date()){
 await ensureAssuranceNotificationDeliverySchema(db);const [policy,data]=await Promise.all([readAssuranceNotificationPolicy(db),readAssuranceDeliveryData(db)]);let emailConfigured=false;try{const row=await db.prepare("SELECT enabled FROM integration_settings WHERE kind='email'").first<{enabled:number}>();emailConfigured=!!row?.enabled}catch{}
 const signals=buildNotificationGovernanceSignalsFromData(data.outbox,data.deliveries,policy,emailConfigured,now,data.retryResets),runs=await readAssuranceNotificationDispatchRuns(db,100),health=summarizeAssuranceSchedulerHealth(runs,now,15);
 if(health.state==="stale"||(health.state==="degraded"&&health.lastScheduledStatus==="failed")){const severity:AssuranceEscalationSeverity=health.state==="stale"&&Number(health.ageMinutes||0)>=180?"critical":"high";signals.push({fingerprint:"notification-scheduler:stale",kind:"notification-scheduler-stale",severity,subjectRef:"continuous-assurance-scheduler",owner:"",title:health.state==="stale"?"Continuous Assurance notification scheduler is stale":"Continuous Assurance notification scheduler is degraded",detail:health.ageMinutes===null?`Latest scheduled dispatch status is ${health.lastScheduledStatus||"unknown"}.`:`Latest scheduled dispatch was ${health.ageMinutes} minute(s) ago with status ${health.lastScheduledStatus||"unknown"}.`,source:{governanceOnly:true,schedulerState:health.state,lastScheduledAt:health.lastScheduledAt,ageMinutes:health.ageMinutes,lastScheduledStatus:health.lastScheduledStatus,cadenceMinutes:health.cadenceMinutes}})}
 const [stormPolicy,deferrals]=await Promise.all([readAssuranceNotificationStormPolicy(db),readAssuranceNotificationDeferrals(db,1000)]),active=activeStormDeferrals(deferrals,now);if(active.length){const high=active.filter(item=>item.severity==="high").length,severity:AssuranceEscalationSeverity=high?"high":"medium",recipients=new Set(active.map(item=>item.recipient)).size,next=active.map(item=>item.next_eligible_at).sort()[0]||"";signals.push({fingerprint:"notification-storm:active",kind:"notification-storm-pressure",severity,subjectRef:"continuous-assurance-notification-storm",owner:"",title:"Continuous Assurance notification storm protection is active",detail:`${active.length} notification(s) for ${recipients} recipient(s) are deferred by the ${stormPolicy.windowMinutes}-minute rolling delivery budget; ${high} are High severity.`,source:{governanceOnly:true,activeDeferrals:active.length,recipients,highSeverityDeferred:high,nextEligibleAt:next,windowMinutes:stormPolicy.windowMinutes,highMaxPerRecipient:stormPolicy.highMaxPerRecipient,mediumMaxPerRecipient:stormPolicy.mediumMaxPerRecipient}})}
 return signals;
}
