"use client";

import {FormEvent,useCallback,useEffect,useState} from "react";
import {withBasePath} from "./base-path";
import "./assurance-notification-settings.css";

type Lang="tr"|"en";
type Policy={criticalSlaMinutes:number;highSlaMinutes:number;mediumSlaMinutes:number;maxAttempts:number};
type Exhausted={id:string;severity:string;recipient:string;subject:string;failedAttempts:number;maxAttempts:number};
type Summary={pending:number;sent:number;sent30d:number;failed:number;failedAttempts30d:number;retryExhausted:number;retryResetEvents:number;attempts30d:number;deliveryRate30d:number;inAppOnly:number;slaBreaches:number;exhausted:Exhausted[];breaches:Array<{id:string;severity:string;recipient:string;subject:string;ageMinutes:number;slaMinutes:number}>};
type Delivery={id:string;outboxId:string;attempt:number;provider:string;state:string;detail:string;recipient:string;attemptedBy:string;attemptedAt:string};
type PolicyEvent={id:string;actor:string;before:Policy;after:Policy;createdAt:string};
type DispatchRun={id:string;trigger:"manual"|"scheduled";actor:string;startedAt:string;completedAt:string;status:string;requestedLimit:number;candidates:number;sent:number;failed:number;skipped:number;detail:string};
type SchedulerHealth={state:"healthy"|"degraded"|"stale"|"unknown";cadenceMinutes:number;lastScheduledAt:string;ageMinutes:number|null;lastScheduledStatus:string};
type RetryReset={id:string;outboxId:string;actor:string;reason:string;priorFailedAttempts:number;createdAt:string};
type Payload={policy:Policy;summary:Summary;schedule:{enabled:boolean;cadenceMinutes:number;health:SchedulerHealth};dispatchRuns:DispatchRun[];retryResets:RetryReset[];policyEvents:PolicyEvent[];deliveries:Delivery[]};
const defaults:Policy={criticalSlaMinutes:240,highSlaMinutes:1440,mediumSlaMinutes:4320,maxAttempts:3};

export default function AssuranceNotificationSettings({lang}:{lang:Lang}){
 const tr=lang==="tr",[data,setData]=useState<Payload|null>(null),[policy,setPolicy]=useState<Policy>(defaults),[busy,setBusy]=useState(""),[message,setMessage]=useState(""),[recoveryId,setRecoveryId]=useState(""),[recoveryReason,setRecoveryReason]=useState("");
 const load=useCallback(async()=>{const response=await fetch(withBasePath("/api/continuous-assurance/notifications"),{cache:"no-store",headers:{accept:"application/json"}}).catch(()=>null),body=await response?.json().catch(()=>null);if(response?.ok&&body){setData(body);setPolicy(body.policy||defaults)}else if(response)setMessage(String(body?.error||(tr?"Notification operasyon verisi okunamadı.":"Notification operations could not be loaded.")))},[tr]);
 useEffect(()=>{let active=true;fetch(withBasePath("/api/continuous-assurance/notifications"),{cache:"no-store",headers:{accept:"application/json"}}).then(async response=>({response,body:await response.json().catch(()=>null)})).then(({response,body})=>{if(!active)return;if(response.ok&&body){setData(body);setPolicy(body.policy||defaults)}else setMessage(String(body?.error||(tr?"Notification operasyon verisi okunamadı.":"Notification operations could not be loaded.")))}).catch(()=>{});return()=>{active=false}},[tr]);
 async function savePolicy(e:FormEvent){e.preventDefault();if(busy)return;setBusy("save");setMessage("");const response=await fetch(withBasePath("/api/continuous-assurance/notifications"),{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify(policy)}).catch(()=>null),body=await response?.json().catch(()=>({}))||{};setBusy("");setMessage(response?.ok?(tr?"Notification SLA policy kaydedildi.":"Notification SLA policy saved."):String(body.error||(tr?"Policy kaydedilemedi.":"Policy could not be saved.")));if(response?.ok)await load()}
 async function dispatch(){if(busy)return;setBusy("dispatch");setMessage("");const response=await fetch(withBasePath("/api/continuous-assurance/notifications"),{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"dispatch",limit:20})}).catch(()=>null),body=await response?.json().catch(()=>({}))||{};setBusy("");setMessage(response?.ok?(tr?`${body.sent||0} gönderim kabul edildi, ${body.failed||0} deneme başarısız.`:`${body.sent||0} deliveries accepted, ${body.failed||0} attempts failed.`):String(body.error||(tr?"Dispatch çalıştırılamadı.":"Dispatch could not run.")));if(response?.ok)await load()}
 async function resetRetry(outboxId:string){if(busy)return;if(recoveryReason.trim().length<20){setMessage(tr?"Retry recovery gerekçesi en az 20 karakter olmalıdır.":"Retry recovery reason must be at least 20 characters.");return}setBusy(`reset:${outboxId}`);setMessage("");const response=await fetch(withBasePath("/api/continuous-assurance/notifications"),{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"reset-retry",outboxId,reason:recoveryReason})}).catch(()=>null),body=await response?.json().catch(()=>({}))||{};setBusy("");setMessage(response?.ok?(tr?"Retry bütçesi audit kaydıyla yeniden açıldı.":"Retry budget reopened with an audit record."):String(body.error||(tr?"Retry recovery uygulanamadı.":"Retry recovery could not be applied.")));if(response?.ok){setRecoveryId("");setRecoveryReason("");await load()}}
 const summary=data?.summary,lastPolicyEvent=data?.policyEvents?.[0],cadence=data?.schedule?.cadenceMinutes||15,health=data?.schedule?.health||{state:"unknown",cadenceMinutes:cadence,lastScheduledAt:"",ageMinutes:null,lastScheduledStatus:""};
 const healthLabel=health.state==="healthy"?(tr?"Sağlıklı":"Healthy"):health.state==="degraded"?(tr?"Bozulmuş":"Degraded"):health.state==="stale"?(tr?"Gecikmiş":"Stale"):(tr?"Bilinmiyor":"Unknown");
 return <section className="assurance-notification-console">
  <header><div><small>CONTINUOUS ASSURANCE NOTIFICATIONS</small><h3>{tr?"Notification operasyonları ve SLA":"Notification operations & SLA"}</h3><p>{tr?"Owner/governance routing kuyruğunu, gerçek e-posta transport denemelerini ve severity bazlı teslim SLA'larını yönetin.":"Manage owner/governance routing, real email transport attempts and severity-based delivery SLAs."}</p></div><button type="button" className="primary" disabled={!!busy} onClick={dispatch}>{busy==="dispatch"?(tr?"Gönderiliyor…":"Dispatching…"):(tr?"Bekleyenleri Gönder":"Dispatch Pending")}</button></header>
  {message&&<div className="assurance-notification-message">{message}</div>}
  <div className="assurance-notification-kpis">
   <article className={summary?.pending?"attention":""}><small>{tr?"Gönderim bekleyen":"Pending delivery"}</small><b>{summary?.pending??0}</b><span>{tr?"Harici transport bekliyor":"Awaiting external transport"}</span></article>
   <article><small>{tr?"30g transport sent":"30d transport sent"}</small><b>{summary?.sent30d??summary?.sent??0}</b><span>{summary?.deliveryRate30d??100}% {tr?"attempt başarı oranı":"attempt success rate"}</span></article>
   <article className={summary?.failed?"critical":""}><small>{tr?"Hatalı kuyruk":"Failed queue"}</small><b>{summary?.failed??0}</b><span>{summary?.retryExhausted??0} {tr?"retry limiti dolu":"retry exhausted"}</span></article>
   <article><small>{tr?"Yalnız in-app":"In-app only"}</small><b>{summary?.inAppOnly??0}</b><span>{tr?"Harici alıcı yok":"No external recipient"}</span></article>
   <article className={summary?.slaBreaches?"critical":""}><small>{tr?"SLA ihlali":"SLA breach"}</small><b>{summary?.slaBreaches??0}</b><span>{tr?"Severity süresi aşıldı":"Severity deadline exceeded"}</span></article>
  </div>
  <section className={`assurance-scheduler-status ${health.state}`}><div><small>AUTOMATED DISPATCH</small><b>{healthLabel} · {tr?`her ${cadence} dk`:`every ${cadence} min`}</b><span>{tr?"Scheduled worker heartbeat ve dispatch sonucu izlenir":"Scheduled worker heartbeat and dispatch outcome are monitored"}</span></div><div className="scheduler-last-run"><small>{tr?"Son scheduled çalışma":"Last scheduled run"}</small><b>{health.lastScheduledStatus||"—"}</b><span>{health.lastScheduledAt?`${new Date(health.lastScheduledAt).toLocaleString(tr?"tr-TR":"en-GB")} · ${health.ageMinutes??0}m`:(tr?"Henüz heartbeat yok":"No heartbeat yet")}</span></div></section>
  <div className="assurance-notification-grid">
   <form className="assurance-notification-policy" onSubmit={savePolicy}><header><div><small>DELIVERY POLICY</small><b>{tr?"Severity bazlı SLA ve retry":"Severity SLA & retry"}</b></div><span>{lastPolicyEvent?(tr?`Son değişiklik ${lastPolicyEvent.actor}`:`Last changed by ${lastPolicyEvent.actor}`):(tr?"Admin kontrollü":"Admin governed")}</span></header><div>
    <label><span>{tr?"Critical SLA (dk)":"Critical SLA (min)"}</span><input type="number" min="15" max="10080" value={policy.criticalSlaMinutes} onChange={e=>setPolicy(x=>({...x,criticalSlaMinutes:Number(e.target.value)}))}/></label>
    <label><span>{tr?"High SLA (dk)":"High SLA (min)"}</span><input type="number" min="30" max="20160" value={policy.highSlaMinutes} onChange={e=>setPolicy(x=>({...x,highSlaMinutes:Number(e.target.value)}))}/></label>
    <label><span>{tr?"Medium SLA (dk)":"Medium SLA (min)"}</span><input type="number" min="60" max="43200" value={policy.mediumSlaMinutes} onChange={e=>setPolicy(x=>({...x,mediumSlaMinutes:Number(e.target.value)}))}/></label>
    <label><span>{tr?"Maks. deneme":"Max attempts"}</span><input type="number" min="1" max="10" value={policy.maxAttempts} onChange={e=>setPolicy(x=>({...x,maxAttempts:Number(e.target.value)}))}/></label>
   </div><footer><small>{tr?"Critical ≤ High ≤ Medium olmalıdır. Başarılı provider kabulü delivery olarak kaydedilir; okunma iddiası yapılmaz.":"Critical ≤ High ≤ Medium is required. Provider acceptance is recorded as delivery; message-read status is not claimed."}</small><button className="primary" disabled={!!busy}>{busy==="save"?(tr?"Kaydediliyor…":"Saving…"):(tr?"Policy Kaydet":"Save Policy")}</button></footer></form>
   <section className="assurance-notification-breaches"><header><div><small>SLA BREACH REGISTER</small><b>{tr?"Geciken bildirimler":"Overdue notifications"}</b></div><span>{summary?.slaBreaches??0}</span></header><div>{summary?.breaches?.length?summary.breaches.slice(0,8).map(item=><article key={item.id}><div><b>{item.subject}</b><small>{item.recipient}</small></div><strong>{item.severity}</strong><span>{Math.floor(item.ageMinutes/60)}h / {Math.floor(item.slaMinutes/60)}h</span></article>):<p>{tr?"SLA ihlali yok.":"No SLA breaches."}</p>}</div></section>
  </div>
  <section className="assurance-recovery-register"><header><div><small>DEAD-LETTER RECOVERY</small><b>{tr?"Retry limiti dolan bildirimler":"Retry-exhausted notifications"}</b></div><span>{summary?.retryExhausted??0}</span></header><div className="recovery-list">{summary?.exhausted?.length?summary.exhausted.map(item=><article key={item.id}><div className="recovery-row"><div><b>{item.subject}</b><small>{item.recipient} · {item.severity} · {item.failedAttempts}/{item.maxAttempts} failed</small></div><button type="button" className="ghost" disabled={!!busy} onClick={()=>{setRecoveryId(recoveryId===item.id?"":item.id);setRecoveryReason("")}}>{recoveryId===item.id?(tr?"Kapat":"Close"):(tr?"Retry Aç":"Recover")}</button></div>{recoveryId===item.id&&<div className="recovery-form"><textarea value={recoveryReason} maxLength={1000} onChange={e=>setRecoveryReason(e.target.value)} placeholder={tr?"Transport sorununun giderildiğini ve neden retry bütçesinin yeniden açıldığını açıklayın (min. 20 karakter)…":"Explain why the retry budget should be reopened after transport remediation (min. 20 characters)…"}/><div><small>{tr?"Eski failure kayıtları silinmez; yalnız yeni retry bütçesi açılır.":"Historical failures are preserved; only a new retry budget is opened."}</small><button type="button" className="primary" disabled={!!busy||recoveryReason.trim().length<20} onClick={()=>void resetRetry(item.id)}>{busy===`reset:${item.id}`?(tr?"Açılıyor…":"Recovering…"):(tr?"Gerekçeli Retry Aç":"Reopen Retry Budget")}</button></div></div>}</article>):<p>{tr?"Retry limiti dolmuş bildirim yok.":"No retry-exhausted notifications."}</p>}</div></section>
  <section className="assurance-dispatch-register"><header><div><small>DISPATCH RUN AUDIT</small><b>{tr?"Scheduled ve manuel çalıştırmalar":"Scheduled & manual runs"}</b></div><span>{tr?`Her ${cadence} dk otomatik`:`Automatic every ${cadence} min`}</span></header><div className="table-scroll"><table><thead><tr><th>Trigger</th><th>{tr?"Durum":"Status"}</th><th>{tr?"Aday":"Candidates"}</th><th>Sent</th><th>Failed</th><th>Skipped</th><th>Actor</th><th>{tr?"Başlangıç":"Started"}</th></tr></thead><tbody>{data?.dispatchRuns?.length?data.dispatchRuns.slice(0,12).map(item=><tr key={item.id}><td>{item.trigger}</td><td><span className={`dispatch-state ${item.status}`}>{item.status}</span></td><td>{item.candidates}</td><td>{item.sent}</td><td>{item.failed}</td><td>{item.skipped}</td><td>{item.actor}</td><td>{new Date(item.startedAt).toLocaleString(tr?"tr-TR":"en-GB")}</td></tr>):<tr><td colSpan={8}>{tr?"Henüz dispatch çalışması kaydedilmedi.":"No dispatch run has been recorded yet."}</td></tr>}</tbody></table></div></section>
  <section className="assurance-reset-register"><header><div><small>RETRY RESET AUDIT</small><b>{tr?"Kontrollü recovery geçmişi":"Governed recovery history"}</b></div><span>{summary?.retryResetEvents??0}</span></header><div className="table-scroll"><table><thead><tr><th>Outbox</th><th>Actor</th><th>{tr?"Önceki failure":"Prior failures"}</th><th>{tr?"Gerekçe":"Reason"}</th><th>{tr?"Zaman":"Time"}</th></tr></thead><tbody>{data?.retryResets?.length?data.retryResets.slice(0,20).map(item=><tr key={item.id}><td><code>{item.outboxId}</code></td><td>{item.actor}</td><td>{item.priorFailedAttempts}</td><td>{item.reason}</td><td>{new Date(item.createdAt).toLocaleString(tr?"tr-TR":"en-GB")}</td></tr>):<tr><td colSpan={5}>{tr?"Henüz retry reset kaydı yok.":"No retry reset has been recorded yet."}</td></tr>}</tbody></table></div></section>
  <section className="assurance-delivery-register"><header><div><small>DELIVERY AUDIT TRAIL</small><b>{tr?"Son transport denemeleri":"Recent transport attempts"} · {summary?.attempts30d??0} / 30d</b></div><button type="button" className="ghost" disabled={!!busy} onClick={()=>void load()}>{tr?"Yenile":"Refresh"}</button></header><div className="table-scroll"><table><thead><tr><th>{tr?"Durum":"State"}</th><th>Provider</th><th>{tr?"Alıcı":"Recipient"}</th><th>{tr?"Deneme":"Attempt"}</th><th>{tr?"Detay":"Detail"}</th><th>Actor</th><th>{tr?"Zaman":"Time"}</th></tr></thead><tbody>{data?.deliveries?.length?data.deliveries.slice(0,30).map(item=><tr key={item.id}><td><span className={`delivery-state ${item.state}`}>{item.state}</span></td><td>{item.provider||"—"}</td><td>{item.recipient||"—"}</td><td>{item.attempt}</td><td>{item.detail||"—"}</td><td>{item.attemptedBy||"system"}</td><td>{new Date(item.attemptedAt).toLocaleString(tr?"tr-TR":"en-GB")}</td></tr>):<tr><td colSpan={7}>{tr?"Henüz transport denemesi yok.":"No transport attempts yet."}</td></tr>}</tbody></table></div></section>
 </section>;
}
