"use client";
import {useEffect,useState} from 'react';
import {auditPlanFields,emptyAuditPlan,validateAuditPlan,type AuditPlan} from './audit-plan';
import {withBasePath} from './base-path';
import './audit-plan-panel.css';
const labels:Record<keyof AuditPlan,[string,string]>={objective:['Denetimin amacı','Audit objective'],scope:['Kapsam içi süreç, varlık ve birimler','In-scope processes, assets and units'],exclusions:['Kapsam dışı ve gerekçesi','Exclusions and rationale'],lead:['Baş denetçi','Lead auditor'],team:['Denetim ekibi ve rolleri','Audit team and roles'],methodology:['Yöntem ve örnekleme yaklaşımı','Methodology and sampling approach'],deliverables:['Rapor ve teslimatlar','Reports and deliverables'],milestones:['Kilometre taşları / sorumlu / hedef tarih','Milestones / owner / target date'],periodStart:['İncelenen dönem başlangıcı','Review period start'],periodEnd:['İncelenen dönem sonu','Review period end'],fieldworkStart:['Saha çalışması başlangıcı','Fieldwork start'],fieldworkEnd:['Saha çalışması sonu','Fieldwork end']};
export function AuditPlanPanel({auditId,canWrite,lang}:{auditId:string;canWrite:boolean;lang:string}){
 const[open,setOpen]=useState(false),[activated,setActivated]=useState(false),en=lang==='en';
 return <section className="audit-plan-panel"><button type="button" aria-expanded={open} onClick={()=>{setActivated(true);setOpen(!open);}}>{en?'Audit plan & scope':'Denetim planı ve kapsamı'}</button>{activated&&<div hidden={!open}><Plan key={auditId} auditId={auditId} canWrite={canWrite} en={en}/></div>}</section>;
}
function Plan({auditId,canWrite,en}:{auditId:string;canWrite:boolean;en:boolean}){
 const[plan,setPlan]=useState<AuditPlan>({...emptyAuditPlan}),[revision,setRevision]=useState(''),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[loaded,setLoaded]=useState(false),[refresh,setRefresh]=useState(0),[saved,setSaved]=useState(''),[dirty,setDirty]=useState(false);
 useEffect(()=>{let active=true;const controller=new AbortController();void(async()=>{try{const response=await fetch(withBasePath(`/api/audits/plan?id=${encodeURIComponent(auditId)}`),{cache:'no-store',signal:controller.signal}),body=await response.json();if(!response.ok||typeof body.revision!=='string')throw new Error();const next=validateAuditPlan(body.plan);if(active){setPlan(next);setRevision(body.revision);setLoaded(true);setDirty(false);setSaved(body.updatedAt?`${body.updatedAt} · ${body.updatedBy}`:'');}}catch{if(active)setError('load');}finally{if(active)setLoading(false);}})();return()=>{active=false;controller.abort();};},[auditId,refresh]);
 async function save(){setSaving(true);setError('');try{const response=await fetch(withBasePath('/api/audits/plan'),{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({id:auditId,expectedRevision:revision,plan})}),body=await response.json();if(!response.ok)throw new Error(en?(response.status===409?'Plan changed or audit was removed. Your draft is retained. Reload to review the latest version.':'Could not save. Your draft is retained.'):body.error);setRevision(body.revision);setSaved(`${body.updatedAt} · ${body.updatedBy}`);setDirty(false);}catch(err){setError(err instanceof Error?err.message:(en?'Could not save.':'Kaydedilemedi.'));}finally{setSaving(false);}}
 return <div aria-busy={loading||saving}><p>{en?'Define the engagement, review period and expected output. Requirement-level tests and evidence remain in the audit register.':'Denetimin amacını, incelenecek dönemi ve beklenen çıktıları tanımlayın. Madde bazlı test ve kanıtlar denetim kayıtlarında yönetilir.'}</p>{error&&<p role="alert">{error==='load'?(en?'Plan could not be loaded. Retry.':'Plan yüklenemedi. Yeniden deneyin.'):error}</p>}{loading?<p role="status">{en?'Loading…':'Yükleniyor…'}</p>:<><div className="audit-plan-fields">{auditPlanFields.map(key=><label key={key}>{labels[key][en?1:0]}{key.endsWith('Start')||key.endsWith('End')?<input aria-label={labels[key][en?1:0]} type="date" value={plan[key]} disabled={!loaded||!canWrite||saving} onChange={e=>{setPlan({...plan,[key]:e.target.value});setDirty(true);}}/>:<textarea aria-label={labels[key][en?1:0]} rows={key==='lead'?1:3} maxLength={4000} value={plan[key]} disabled={!loaded||!canWrite||saving} onChange={e=>{setPlan({...plan,[key]:e.target.value});setDirty(true);}}/>}</label>)}</div><footer><button type="button" disabled={saving} onClick={()=>{if(dirty&&!window.confirm(en?'Discard your unsaved draft and reload?':'Kaydedilmemiş taslağı bırakıp güncel plan yüklensin mi?'))return;setLoading(true);setError('');setLoaded(false);setRefresh(x=>x+1);}}>{en?'Reload':'Yeniden yükle'}</button>{canWrite&&<button type="button" disabled={!loaded||saving||!dirty} onClick={()=>void save()}>{saving?(en?'Saving…':'Kaydediliyor…'):(en?'Save plan':'Planı kaydet')}</button>}<small role="status">{dirty?(en?'Unsaved changes':'Kaydedilmemiş değişiklikler'):saved?(en?'Saved: ':'Kaydedildi: ')+saved:''}</small></footer></>}</div>;
}
