"use client";
import {useCallback,useEffect,useState} from "react";
import {withBasePath} from "./base-path";
import "./continuous-assurance-governance.css";

type Lang="tr"|"en";
type Risk={id:string;title:string;owner:string;riskLevel:string;assuranceState:string;lastAssuranceRunRef:string;reason:string;requestedAt:string;reviewAgeDays:number;reviewUrgency:string;reminderDue:boolean;escalationDue:boolean};
type Review={id:string;riskId:string;status:string;proposal:Record<string,unknown>;submittedBy:string;submittedAt:string;reviewedBy:string};
type Exception={id:string;findingId:string;ruleId:string;controlRef:string;riskRef:string;reason:string;expiresAt:string;status:string;submittedBy:string;submittedAt:string;retestRequired:boolean;retestWorkItemId:string;lifecycleUpdatedAt:string};
type Summary={reviewRequired:number;pendingRiskReviews:number;riskReviewOverdue:number;riskReviewCritical:number;oldestRiskReviewDays:number;avgRiskReviewAgeDays:number;activeExceptions:number;expiringExceptions:number;expiredExceptions:number;retestRequiredExceptions:number;effective:number;degraded:number;ineffective:number;pendingWork:number;failedRetest:number;openFindings:number};
type Trend={riskReviewsSubmitted:number;riskReviewsApproved:number;exceptionsSubmitted:number;exceptionsEnded:number;retestCompleted:number;retestFailed:number};
const empty:Summary={reviewRequired:0,pendingRiskReviews:0,riskReviewOverdue:0,riskReviewCritical:0,oldestRiskReviewDays:0,avgRiskReviewAgeDays:0,activeExceptions:0,expiringExceptions:0,expiredExceptions:0,retestRequiredExceptions:0,effective:0,degraded:0,ineffective:0,pendingWork:0,failedRetest:0,openFindings:0};
const emptyTrend:Trend={riskReviewsSubmitted:0,riskReviewsApproved:0,exceptionsSubmitted:0,exceptionsEnded:0,retestCompleted:0,retestFailed:0};

export default function ContinuousAssuranceGovernance({lang}:{lang:Lang}){
 const tr=lang==="tr",[summary,setSummary]=useState<Summary>(empty),[trend,setTrend]=useState<Trend>(emptyTrend),[risks,setRisks]=useState<Risk[]>([]),[reviews,setReviews]=useState<Review[]>([]),[exceptions,setExceptions]=useState<Exception[]>([]),[role,setRole]=useState("Viewer"),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[risk,setRisk]=useState<Risk|null>(null),[riskForm,setRiskForm]=useState({residualLikelihood:"",residualImpact:"",rationale:"",evidenceReference:"",evidenceSha256:""}),[exceptionOpen,setExceptionOpen]=useState(false),[exceptionForm,setExceptionForm]=useState({findingId:"",ruleId:"",controlRef:"",riskRef:"",reason:"",expiresAt:"",evidenceReference:"",evidenceSha256:""});
 const load=useCallback(async()=>{const[g,a]=await Promise.all([fetch(withBasePath("/api/continuous-assurance/governance"),{cache:"no-store"}),fetch(withBasePath("/api/auth"),{cache:"no-store"})]);if(g.ok){const d=await g.json();setSummary(d.summary||empty);setTrend(d.trend30d||emptyTrend);setRisks(d.risksRequiringReview||[]);setReviews(d.riskReviews||[]);setExceptions(d.exceptions||[])}if(a.ok){const d=await a.json();setRole(d?.user?.role||"Viewer")}},[]);
 useEffect(()=>{let live=true;(async()=>{try{if(live)await load()}catch{}})();return()=>{live=false}},[load]);
 async function post(body:Record<string,unknown>){setBusy(true);setMessage("");try{const r=await fetch(withBasePath("/api/continuous-assurance/governance"),{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)}),d=await r.json().catch(()=>({}));setMessage(r.ok?(d.message||(tr?"İşlem tamamlandı.":"Completed.")):(d.error||(tr?"İşlem başarısız.":"Operation failed.")));if(r.ok)await load();return r.ok}finally{setBusy(false)}}
 async function submitRisk(){if(!risk)return;const ok=await post({action:"submit-risk-review",riskId:risk.id,residualLikelihood:Number(riskForm.residualLikelihood),residualImpact:Number(riskForm.residualImpact),rationale:riskForm.rationale,evidenceReference:riskForm.evidenceReference,evidenceSha256:riskForm.evidenceSha256});if(ok){setRisk(null);setRiskForm({residualLikelihood:"",residualImpact:"",rationale:"",evidenceReference:"",evidenceSha256:""})}}
 async function submitException(){const ok=await post({action:"create-exception",...exceptionForm});if(ok){setExceptionOpen(false);setExceptionForm({findingId:"",ruleId:"",controlRef:"",riskRef:"",reason:"",expiresAt:"",evidenceReference:"",evidenceSha256:""})}}
 async function review(action:"review-risk"|"review-exception",id:string,decision:"approve"|"reject"){let note="";if(decision==="reject"){note=window.prompt(tr?"Ret gerekçesini yazın (en az 10 karakter):":"Enter rejection reason (minimum 10 characters):")||"";if(note.trim().length<10)return}await post(action==="review-risk"?{action,reviewId:id,decision,note}:{action,exceptionId:id,decision,note})}
 async function revoke(id:string){const note=window.prompt(tr?"Exception revoke gerekçesini yazın (en az 10 karakter):":"Enter exception revocation reason (minimum 10 characters):")||"";if(note.trim().length<10)return;await post({action:"revoke-exception",exceptionId:id,note})}
 const pendingReviews=reviews.filter(x=>x.status==="pending-review").slice(0,6),pendingExceptions=exceptions.filter(x=>x.status==="pending-review").slice(0,6),activeExceptions=exceptions.filter(x=>x.status==="active").slice(0,6),attentionExceptions=exceptions.filter(x=>x.retestRequired).slice(0,6);
 return <section className="assurance-governance">
  <header><div><small>EXECUTIVE ASSURANCE · GOVERNANCE</small><h4>{tr?"Risk kararları ve exception yönetimi":"Risk decisions & exception governance"}</h4><p>{tr?"Continuous Assurance sinyallerini insan onaylı residual risk kararlarına, süreli istisnalara ve zorunlu re-test akışına bağlayın.":"Turn Continuous Assurance signals into human-approved residual risk decisions, time-bounded exceptions and mandatory re-test workflows."}</p></div>{role!=="Viewer"&&<button onClick={()=>setExceptionOpen(true)}>{tr?"+ Exception Talebi":"+ Exception Request"}</button>}</header>
  {message&&<div className="ag-message" onClick={()=>setMessage("")}>{message}<b>×</b></div>}
  <div className="ag-metrics"><article className={summary.reviewRequired?"attention":"healthy"}><b>{summary.reviewRequired}</b><span>{tr?"Risk review gerekli":"Risk reviews required"}</span></article><article className={summary.riskReviewOverdue?"critical":"healthy"}><b>{summary.riskReviewOverdue}</b><span>{tr?"Gecikmiş risk review":"Overdue risk reviews"}</span></article><article className={summary.activeExceptions?"attention":"healthy"}><b>{summary.activeExceptions}</b><span>{tr?"Aktif exception":"Active exceptions"}</span></article><article className={summary.retestRequiredExceptions?"critical":"healthy"}><b>{summary.retestRequiredExceptions}</b><span>{tr?"Zorunlu re-test":"Mandatory re-tests"}</span></article><article className={summary.failedRetest?"critical":"healthy"}><b>{summary.failedRetest}</b><span>{tr?"Başarısız re-test":"Failed re-tests"}</span></article><article className={summary.openFindings?"attention":"healthy"}><b>{summary.openFindings}</b><span>{tr?"Açık assurance bulgusu":"Open assurance findings"}</span></article></div>
  <div className="ag-aging"><span className={summary.riskReviewCritical?"critical":""}><b>{summary.riskReviewCritical}</b>{tr?"14+ gün kritik risk review":"14+ day critical risk reviews"}</span><span><b>{summary.oldestRiskReviewDays}</b>{tr?"En eski review yaşı (gün)":"Oldest review age (days)"}</span><span><b>{summary.avgRiskReviewAgeDays}</b>{tr?"Ort. review yaşı":"Average review age"}</span><span className={summary.expiringExceptions?"attention":""}><b>{summary.expiringExceptions}</b>{tr?"14 gün içinde bitecek exception":"Exceptions expiring in 14d"}</span><span className={summary.expiredExceptions?"critical":""}><b>{summary.expiredExceptions}</b>{tr?"Süresi bitmiş exception":"Expired exceptions"}</span></div>
  <div className="ag-posture"><span className="effective">Effective <b>{summary.effective}</b></span><span className="degraded">Degraded <b>{summary.degraded}</b></span><span className="ineffective">Ineffective <b>{summary.ineffective}</b></span><span>{tr?"Aktif iş":"Active work"} <b>{summary.pendingWork}</b></span></div>
  <div className="ag-trend"><header><b>{tr?"30 Günlük Governance Trend":"30-Day Governance Trend"}</b><small>{tr?"İnsan kararı, exception lifecycle ve re-test sonuçları":"Human decisions, exception lifecycle and re-test outcomes"}</small></header><div><span><b>{trend.riskReviewsSubmitted}</b>{tr?"Risk review gönderildi":"Risk reviews submitted"}</span><span><b>{trend.riskReviewsApproved}</b>{tr?"Risk kararı onaylandı":"Risk decisions approved"}</span><span><b>{trend.exceptionsSubmitted}</b>{tr?"Exception açıldı":"Exceptions requested"}</span><span><b>{trend.exceptionsEnded}</b>{tr?"Exception sona erdi":"Exceptions ended"}</span><span><b>{trend.retestCompleted}</b>{tr?"Re-test başarılı":"Re-tests completed"}</span><span className={trend.retestFailed?"critical":""}><b>{trend.retestFailed}</b>{tr?"Re-test başarısız/hata":"Re-tests failed/error"}</span></div></div>
  <div className="ag-grid">
   <article><header><b>Residual Risk Review</b><small>{tr?"Otomatik güvence sonucu risk düşürmez; onaylı karar gerekir.":"Automation never lowers residual risk without an approved decision."}</small></header>{risks.length?risks.slice(0,8).map(x=><div className={`ag-row urgency-${x.reviewUrgency}`} key={x.id}><span><b>{x.title}</b><small>{x.owner||"—"} · {x.riskLevel||"—"} · {x.assuranceState} · {x.reviewAgeDays}d · {x.reviewUrgency}</small></span>{role!=="Viewer"&&<button onClick={()=>setRisk(x)}>{tr?"Değerlendir":"Assess"}</button>}</div>):<p className="ag-empty">{tr?"Risk owner review bekleyen kayıt yok.":"No risk owner review is pending."}</p>}</article>
   <article><header><b>Exception / Waiver</b><small>{tr?"Süreli istisna assurance durumunu effective yapmaz; bitiş/revoke sonrası re-test gerekir.":"A time-bounded exception never changes assurance to effective; expiry or revocation requires re-test."}</small></header>{[...pendingExceptions,...activeExceptions,...attentionExceptions].filter((x,i,a)=>a.findIndex(y=>y.id===x.id)===i).slice(0,8).map(x=><div className="ag-row" key={x.id}><span><b>{x.controlRef||x.ruleId||x.riskRef||x.findingId||x.id}</b><small>{x.status} · {tr?"bitiş":"expires"} {x.expiresAt}{x.retestRequired?` · ${tr?"RE-TEST GEREKLİ":"RE-TEST REQUIRED"}`:""}</small></span>{x.status==="pending-review"&&role==="Admin"?<div><button className="approve" disabled={busy} onClick={()=>review("review-exception",x.id,"approve")}>{tr?"Onay":"Approve"}</button><button className="reject" disabled={busy} onClick={()=>review("review-exception",x.id,"reject")}>{tr?"Ret":"Reject"}</button></div>:x.status==="active"&&role==="Admin"?<button className="reject" disabled={busy} onClick={()=>revoke(x.id)}>{tr?"Revoke":"Revoke"}</button>:null}</div>)}{!pendingExceptions.length&&!activeExceptions.length&&!attentionExceptions.length&&<p className="ag-empty">{tr?"Aktif, onay bekleyen veya re-test gerektiren exception yok.":"No active, pending or re-test-required exception."}</p>}</article>
  </div>
  {role==="Admin"&&pendingReviews.length>0&&<div className="ag-review-strip"><b>{tr?"Bağımsız risk onay kuyruğu":"Independent risk approval queue"}</b>{pendingReviews.map(x=><span key={x.id}><em>{x.riskId}</em><button className="approve" disabled={busy} onClick={()=>review("review-risk",x.id,"approve")}>{tr?"Onayla":"Approve"}</button><button className="reject" disabled={busy} onClick={()=>review("review-risk",x.id,"reject")}>{tr?"Reddet":"Reject"}</button></span>)}</div>}
  {risk&&<div className="ag-overlay"><section className="ag-dialog"><header><div><small>RISK OWNER REASSESSMENT</small><h4>{risk.title}</h4><p>{tr?`${risk.reviewAgeDays} gündür review bekliyor · ${risk.reviewUrgency}`:`Waiting ${risk.reviewAgeDays} days · ${risk.reviewUrgency}`}</p></div><button onClick={()=>setRisk(null)}>×</button></header><div className="ag-two"><label>Residual likelihood<input type="number" min="1" max="5" value={riskForm.residualLikelihood} onChange={e=>setRiskForm({...riskForm,residualLikelihood:e.target.value})}/></label><label>Residual impact<input type="number" min="1" max="5" value={riskForm.residualImpact} onChange={e=>setRiskForm({...riskForm,residualImpact:e.target.value})}/></label></div><label>{tr?"Gerekçe":"Rationale"}<textarea value={riskForm.rationale} onChange={e=>setRiskForm({...riskForm,rationale:e.target.value})}/></label><label>{tr?"Kanıt referansı":"Evidence reference"}<input value={riskForm.evidenceReference} onChange={e=>setRiskForm({...riskForm,evidenceReference:e.target.value})}/></label><label>SHA-256<input value={riskForm.evidenceSha256} onChange={e=>setRiskForm({...riskForm,evidenceSha256:e.target.value})}/></label><footer><button onClick={()=>setRisk(null)}>{tr?"Vazgeç":"Cancel"}</button><button className="primary" disabled={busy} onClick={submitRisk}>{tr?"Bağımsız Onaya Gönder":"Submit for Independent Review"}</button></footer></section></div>}
  {exceptionOpen&&<div className="ag-overlay"><section className="ag-dialog"><header><div><small>ASSURANCE EXCEPTION</small><h4>{tr?"Süreli exception talebi":"Time-bounded exception request"}</h4></div><button onClick={()=>setExceptionOpen(false)}>×</button></header><div className="ag-two"><label>Control ref<input value={exceptionForm.controlRef} onChange={e=>setExceptionForm({...exceptionForm,controlRef:e.target.value})}/></label><label>Risk ref<input value={exceptionForm.riskRef} onChange={e=>setExceptionForm({...exceptionForm,riskRef:e.target.value})}/></label><label>Rule ID<input value={exceptionForm.ruleId} onChange={e=>setExceptionForm({...exceptionForm,ruleId:e.target.value})}/></label><label>Finding ID<input value={exceptionForm.findingId} onChange={e=>setExceptionForm({...exceptionForm,findingId:e.target.value})}/></label></div><label>{tr?"Bitiş tarihi (maks. 180 gün)":"Expiry date (max 180 days)"}<input type="date" value={exceptionForm.expiresAt} onChange={e=>setExceptionForm({...exceptionForm,expiresAt:e.target.value})}/></label><label>{tr?"Gerekçe":"Reason"}<textarea value={exceptionForm.reason} onChange={e=>setExceptionForm({...exceptionForm,reason:e.target.value})}/></label><label>{tr?"Kanıt referansı":"Evidence reference"}<input value={exceptionForm.evidenceReference} onChange={e=>setExceptionForm({...exceptionForm,evidenceReference:e.target.value})}/></label><label>SHA-256<input value={exceptionForm.evidenceSha256} onChange={e=>setExceptionForm({...exceptionForm,evidenceSha256:e.target.value})}/></label><footer><button onClick={()=>setExceptionOpen(false)}>{tr?"Vazgeç":"Cancel"}</button><button className="primary" disabled={busy} onClick={submitException}>{tr?"Bağımsız Onaya Gönder":"Submit for Independent Review"}</button></footer></section></div>}
 </section>;
}
