"use client";
import {useCallback,useEffect,useMemo,useState} from "react";
import {withBasePath} from "./base-path";
import "./continuous-assurance-escalation-center.css";

type Lang="tr"|"en";
type Escalation={id:string;kind:string;severity:string;subjectRef:string;owner:string;title:string;detail:string;status:string;firstSeenAt:string;lastSeenAt:string;acknowledgedBy:string;acknowledgedAt:string;ackNote:string;resolvedAt:string};
type Summary={active:number;acknowledged:number;critical:number;high:number;medium:number;resolved30d:number};
type Policy={reminderDays:number;remindersEnabled:boolean;signals:number};
const empty:Summary={active:0,acknowledged:0,critical:0,high:0,medium:0,resolved30d:0};

export default function ContinuousAssuranceEscalationCenter({lang}:{lang:Lang}){
 const tr=lang==="tr",[records,setRecords]=useState<Escalation[]>([]),[summary,setSummary]=useState<Summary>(empty),[policy,setPolicy]=useState<Policy>({reminderDays:15,remindersEnabled:true,signals:0}),[role,setRole]=useState("Viewer"),[filter,setFilter]=useState("open"),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const load=useCallback(async()=>{const[e,a]=await Promise.all([fetch(withBasePath("/api/continuous-assurance/escalations"),{cache:"no-store"}),fetch(withBasePath("/api/auth"),{cache:"no-store"})]);if(e.ok){const d=await e.json();setRecords(d.records||[]);setSummary(d.summary||empty);setPolicy(d.policy||{reminderDays:15,remindersEnabled:true,signals:0})}if(a.ok){const d=await a.json();setRole(d?.user?.role||"Viewer")}},[]);
 useEffect(()=>{let live=true;(async()=>{try{if(live)await load()}catch{}})();return()=>{live=false}},[load]);
 async function acknowledge(item:Escalation){const note=window.prompt(tr?"Aksiyon / takip notunu yazın (en az 10 karakter):":"Enter action / follow-up note (minimum 10 characters):")||"";if(note.trim().length<10)return;setBusy(true);setMessage("");try{const r=await fetch(withBasePath("/api/continuous-assurance/escalations"),{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"acknowledge",id:item.id,note})}),d=await r.json().catch(()=>({}));setMessage(r.ok?(tr?"Escalation acknowledge edildi.":"Escalation acknowledged."):(d.error||(tr?"İşlem başarısız.":"Operation failed.")));if(r.ok)await load()}finally{setBusy(false)}}
 const visible=useMemo(()=>records.filter(item=>filter==="all"?true:filter==="open"?item.status!=="resolved":filter==="critical"?item.status!=="resolved"&&item.severity==="critical":filter==="ack"?item.status==="acknowledged":item.kind===filter).slice(0,40),[records,filter]);
 const filters=[{id:"open",tr:"Açık",en:"Open"},{id:"critical",tr:"Kritik",en:"Critical"},{id:"ack",tr:"Acknowledge",en:"Acknowledged"},{id:"risk-review",tr:"Risk Review",en:"Risk Review"},{id:"exception-expiry",tr:"Exception",en:"Exception"},{id:"mandatory-retest",tr:"Re-test",en:"Re-test"},{id:"all",tr:"Tümü",en:"All"}];
 return <section className="assurance-escalation-center">
  <header><div><small>ASSURANCE ESCALATION CENTER</small><h4>{tr?"Güvence uyarıları ve takip merkezi":"Assurance alerts & follow-up"}</h4><p>{tr?"Geciken risk kararları, exception süreleri ve re-test sonuçlarını tekilleştirilmiş, kalıcı ve aksiyonlanabilir sinyallere dönüştürür.":"Turn overdue risk decisions, exception deadlines and re-test outcomes into deduplicated, durable and actionable signals."}</p></div><button disabled={busy} onClick={()=>load()}>{tr?"Yenile":"Refresh"}</button></header>
  {message&&<div className="aec-message" onClick={()=>setMessage("")}>{message}<b>×</b></div>}
  <div className="aec-metrics"><article className={summary.critical?"critical":"healthy"}><b>{summary.critical}</b><span>{tr?"Kritik açık":"Critical open"}</span></article><article className={summary.high?"attention":"healthy"}><b>{summary.high}</b><span>{tr?"Yüksek açık":"High open"}</span></article><article><b>{summary.active}</b><span>{tr?"Aksiyon bekliyor":"Needs action"}</span></article><article><b>{summary.acknowledged}</b><span>{tr?"Takibe alındı":"Acknowledged"}</span></article><article><b>{summary.resolved30d}</b><span>{tr?"30 günde çözüldü":"Resolved in 30d"}</span></article><article><b>{policy.remindersEnabled?`${policy.reminderDays}d`:"OFF"}</b><span>{tr?"Reminder politikası":"Reminder policy"}</span></article></div>
  <div className="aec-toolbar"><div>{filters.map(item=><button key={item.id} className={filter===item.id?"active":""} onClick={()=>setFilter(item.id)}>{tr?item.tr:item.en}</button>)}</div><small>{policy.signals} {tr?"canlı koşul":"live conditions"}</small></div>
  <div className="aec-list">{visible.map(item=><article key={item.id} className={`${item.severity} ${item.status}`}><div className="aec-severity"><b>{item.severity.toUpperCase()}</b><small>{item.kind.replaceAll("-"," ")}</small></div><div className="aec-copy"><span><b>{item.title}</b><em>{item.status}</em></span><p>{item.detail}</p><small>{item.subjectRef} · {item.owner||"unassigned"} · {new Date(item.lastSeenAt).toLocaleString(tr?"tr-TR":"en-GB")}</small>{item.status==="acknowledged"&&<small>{tr?"Takip":"Follow-up"}: {item.acknowledgedBy} · {item.ackNote}</small>}</div>{item.status==="active"&&role!=="Viewer"&&<button disabled={busy} onClick={()=>acknowledge(item)}>{tr?"Acknowledge":"Acknowledge"}</button>}</article>)}{!visible.length&&<p className="aec-empty">{tr?"Bu filtrede aktif escalation bulunmuyor.":"No escalation matches this filter."}</p>}</div>
 </section>;
}
