"use client";
import {useCallback,useEffect,useRef,useState} from "react";
import {withBasePath} from "./base-path";
import {navigateToFornost} from "./navigation-focus";
import "./continuous-assurance-governance.css";
import RiskReviewDetails,{RiskRating,type RiskContext,type RiskReview} from "./risk-review-details";

type Lang="tr"|"en";
type Risk={context:RiskContext|null;id:string;riskRef:string;title:string;owner:string;riskLevel:string;assuranceState:string;lastAssuranceRunRef:string;reason:string;requestedAt:string;reviewAgeDays:number;reviewUrgency:string;reminderDue:boolean;escalationDue:boolean};
type Review=RiskReview;
type Exception={id:string;findingId:string;ruleId:string;controlRef:string;riskRef:string;reason:string;expiresAt:string;status:string;submittedBy:string;submittedAt:string;retestRequired:boolean;retestWorkItemId:string;retestCompletedAt:string;retestResultRef:string;lifecycleUpdatedAt:string};
type Summary={reviewRequired:number;pendingRiskReviews:number;riskReviewOverdue:number;riskReviewCritical:number;oldestRiskReviewDays:number;avgRiskReviewAgeDays:number;activeExceptions:number;expiringExceptions:number;expiredExceptions:number;retestRequiredExceptions:number;effective:number;degraded:number;ineffective:number;pendingWork:number;failedRetest:number;openFindings:number};
type Trend={riskReviewsSubmitted:number;riskReviewsApproved:number;exceptionsSubmitted:number;exceptionsEnded:number;retestCompleted:number;retestFailed:number};
const empty:Summary={reviewRequired:0,pendingRiskReviews:0,riskReviewOverdue:0,riskReviewCritical:0,oldestRiskReviewDays:0,avgRiskReviewAgeDays:0,activeExceptions:0,expiringExceptions:0,expiredExceptions:0,retestRequiredExceptions:0,effective:0,degraded:0,ineffective:0,pendingWork:0,failedRetest:0,openFindings:0};
const emptyTrend:Trend={riskReviewsSubmitted:0,riskReviewsApproved:0,exceptionsSubmitted:0,exceptionsEnded:0,retestCompleted:0,retestFailed:0};

function openRisk(ref:string){const value=String(ref||"").trim();if(!value)return false;return navigateToFornost({module:"Risk Assessment",ref:value,source:"assurance-governance",filter:{riskRef:value}})}
function openControl(ref:string){const value=String(ref||"").trim();if(!value)return false;return navigateToFornost({module:"Kontroller",ref:value,source:"assurance-governance",filter:{controlRef:value}})}
function openRule(ref:string){const value=String(ref||"").trim();if(!value)return false;return navigateToFornost({module:"Kanıt Otomasyonu",ref:value,source:"assurance-governance",filter:{ruleRef:value}})}
function openFinding(ref:string){const value=String(ref||"").trim();if(!value)return false;return navigateToFornost({module:"Kanıt Otomasyonu",ref:value,source:"assurance-governance",filter:{findingRef:value}})}

export default function ContinuousAssuranceGovernance({lang}:{lang:Lang}){
 const tr=lang==="tr",[summary,setSummary]=useState<Summary>(empty),[trend,setTrend]=useState<Trend>(emptyTrend),[risks,setRisks]=useState<Risk[]>([]),[reviews,setReviews]=useState<Review[]>([]),[exceptions,setExceptions]=useState<Exception[]>([]),[role,setRole]=useState("Viewer"),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[risk,setRisk]=useState<Risk|null>(null),[riskForm,setRiskForm]=useState({residualLikelihood:"",residualImpact:"",rationale:"",evidenceReference:"",evidenceSha256:""}),[exceptionOpen,setExceptionOpen]=useState(false),[exceptionForm,setExceptionForm]=useState({findingId:"",ruleId:"",controlRef:"",riskRef:"",reason:"",expiresAt:"",evidenceReference:"",evidenceSha256:""});
 const [loading,setLoading]=useState(true),[loadError,setLoadError]=useState(false),[complete,setComplete]=useState(false),[evaluatedAt,setEvaluatedAt]=useState(''),[email,setEmail]=useState('');
 const [riskPage,setRiskPage]=useState(0),[exceptionPage,setExceptionPage]=useState(0),[reviewPage,setReviewPage]=useState(0),[reviewFilter,setReviewFilter]=useState('pending'),[search,setSearch]=useState(''),[reviewId,setReviewId]=useState('');
 const request=useRef(0),controller=useRef<AbortController|null>(null);
 const load=useCallback(async()=>{
  controller.current?.abort();const pending=new AbortController(),id=++request.current;controller.current=pending;setLoading(true);setLoadError(false);
  const timeout=window.setTimeout(()=>pending.abort(),20000);
  try{
   const[g,a]=await Promise.all([fetch(withBasePath("/api/continuous-assurance/governance"),{cache:"no-store",signal:pending.signal}),fetch(withBasePath("/api/auth"),{cache:"no-store",signal:pending.signal})]);
   if(!g.ok||!a.ok)throw new Error('unavailable');const[d,actor]=await Promise.all([g.json(),a.json()]);
   if(!d.summary||!d.trend30d||!Array.isArray(d.risksRequiringReview)||!Array.isArray(d.riskReviews)||!Array.isArray(d.exceptions)||typeof d.dataQuality?.verified!=='boolean'||!Number.isFinite(Date.parse(d.generatedAt)))throw new Error('invalid');
   if(id!==request.current)return false;
   setSummary(d.summary);setTrend(d.trend30d);setRisks(d.risksRequiringReview);setReviews(d.riskReviews);setExceptions(d.exceptions);setComplete(d.dataQuality.verified);setEvaluatedAt(d.generatedAt);setRole(actor?.user?.role||'Viewer');setEmail(actor?.user?.email||'');return true;
  }catch{if(id===request.current)setLoadError(true);return false;}finally{window.clearTimeout(timeout);if(id===request.current)setLoading(false);}
 },[]);
 const cancel=useCallback(()=>{request.current++;controller.current?.abort();},[]);
 useEffect(()=>{const initial=window.setTimeout(()=>void load(),0),timer=window.setInterval(()=>void load(),300000);return()=>{window.clearTimeout(initial);window.clearInterval(timer);cancel();}},[load,cancel]);
 async function post(body:Record<string,unknown>){setBusy(true);setMessage('');try{const r=await fetch(withBasePath("/api/continuous-assurance/governance"),{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}),d=await r.json().catch(()=>({}));setMessage(r.ok?(tr?'İşlem tamamlandı.':'Completed.'):(d.error||(tr?'İşlem başarısız.':'Operation failed.')));if(r.ok||r.status===409)await load();return r.ok;}catch{setMessage(tr?'İşlem sonucu alınamadı. Tekrar denemeden önce listeyi yenileyin.':'The result could not be received. Refresh the list before retrying.');setLoadError(true);return false;}finally{setBusy(false);}}
 async function submitRisk(){if(!risk)return;const ok=await post({action:"submit-risk-review",riskId:risk.id,expectedRiskRevision:risk.context?.revision,residualLikelihood:Number(riskForm.residualLikelihood),residualImpact:Number(riskForm.residualImpact),rationale:riskForm.rationale,evidenceReference:riskForm.evidenceReference,evidenceSha256:riskForm.evidenceSha256});if(ok){setRisk(null);setRiskForm({residualLikelihood:"",residualImpact:"",rationale:"",evidenceReference:"",evidenceSha256:""})}}
 async function submitException(){const ok=await post({action:"create-exception",...exceptionForm});if(ok){setExceptionOpen(false);setExceptionForm({findingId:"",ruleId:"",controlRef:"",riskRef:"",reason:"",expiresAt:"",evidenceReference:"",evidenceSha256:""})}}
 async function review(action:"review-risk"|"review-exception",id:string,decision:"approve"|"reject"){let note="";if(decision==="reject"){note=window.prompt(tr?"Ret gerekçesini yazın (en az 10 karakter):":"Enter rejection reason (minimum 10 characters):")||"";if(note.trim().length<10)return}await post(action==="review-risk"?{action,reviewId:id,decision,note}:{action,exceptionId:id,decision,note})}
 async function revoke(id:string){const note=window.prompt(tr?"Exception revoke gerekçesini yazın (en az 10 karakter):":"Enter exception revocation reason (minimum 10 characters):")||"";if(note.trim().length<10)return;await post({action:"revoke-exception",exceptionId:id,note})}
 const reliable=complete&&!loading&&!loadError,metric=(n:number)=>reliable?n:'—';
 const match=(...values:unknown[])=>values.map(String).join(' ').toLocaleLowerCase(tr?'tr-TR':'en').includes(search.trim().toLocaleLowerCase(tr?'tr-TR':'en'));
 const riskItems=risks.filter(x=>match(x.riskRef,x.title,x.owner)),exceptionItems=exceptions.filter(x=>match(x.id,x.controlRef,x.riskRef,x.reason));
 const reviewItems=reviews.filter(x=>(reviewFilter==='all'||x.status==='pending-review')&&match(x.riskId,x.currentRisk?.reference||'',x.currentRisk?.title||'',x.submittedBy,x.proposal.rationale||''));
 const selectedReview=reviews.find(x=>x.id===reviewId);
 const slice=<T,>(items:T[],page:number)=>items.slice(Math.min(page,Math.max(0,Math.ceil(items.length/8)-1))*8,(Math.min(page,Math.max(0,Math.ceil(items.length/8)-1))+1)*8);
 const pager=(count:number,page:number,change:(value:number)=>void,label:string)=>{const current=Math.min(page,Math.max(0,Math.ceil(count/8)-1)),pages=Math.max(1,Math.ceil(count/8));return <nav className="ag-pagination" aria-label={label}><span>{count} · {current+1}/{pages}</span><button type="button" disabled={!current} onClick={()=>change(current-1)}>{tr?'Önceki':'Previous'}</button><button type="button" disabled={current+1>=pages} onClick={()=>change(current+1)}>{tr?'Sonraki':'Next'}</button></nav>};
 return <section className="assurance-governance" aria-busy={loading}>
  <header><div><small>EXECUTIVE ASSURANCE · GOVERNANCE</small><h4>{tr?"Risk kararları ve exception yönetimi":"Risk decisions & exception governance"}</h4><p>{tr?"Continuous Assurance sinyallerini insan onaylı residual risk kararlarına, süreli istisnalara ve zorunlu re-test akışına bağlayın.":"Turn Continuous Assurance signals into human-approved residual risk decisions, time-bounded exceptions and mandatory re-test workflows."}</p></div>{role!=="Viewer"&&<button disabled={!reliable||busy} onClick={()=>setExceptionOpen(true)}>{tr?"+ Exception Talebi":"+ Exception Request"}</button>}</header>
  <div className="ag-load-controls"><span>{loading?(tr?'Veriler yükleniyor…':'Loading…'):evaluatedAt?`${tr?'Değerlendirme':'Evaluated'}: ${new Date(evaluatedAt).toLocaleString(tr?'tr-TR':'en-GB')}`:''}</span><button type="button" disabled={loading||busy} onClick={()=>void load()}>{tr?'Yenile':'Refresh governance'}</button></div>
  {loadError&&<div className="ag-notice" role="alert">{tr?'Veriler yüklenemedi. Önceki sonuçlar güncel değildir; yeniden deneyin.':'Data could not be loaded. Previous results are not current; retry.'}</div>}
  {!loading&&!loadError&&evaluatedAt&&!complete&&<div className="ag-notice" role="alert">{tr?'Değerlendirme eksik: kaynak okunamadı, kayıt bozuk veya okuma sınırı aşıldı. Gösterilen liste kısmi olabilir; karar işlemleri kapalı.':'Evaluation incomplete: a source is unreadable, a record is invalid or a read limit was exceeded. Lists may be partial; decision actions are disabled.'}</div>}
  {message&&<div className="ag-message" role="status">{message}<button type="button" onClick={()=>setMessage('')} aria-label={tr?'Mesajı kapat':'Dismiss message'}>×</button></div>}
  <div className="ag-metrics"><article className={summary.reviewRequired?"attention":"healthy"}><b>{metric(summary.reviewRequired)}</b><span>{tr?"Risk review gerekli":"Risk reviews required"}</span></article><article className={summary.riskReviewOverdue?"critical":"healthy"}><b>{metric(summary.riskReviewOverdue)}</b><span>{tr?"Gecikmiş risk review":"Overdue risk reviews"}</span></article><article className={summary.activeExceptions?"attention":"healthy"}><b>{metric(summary.activeExceptions)}</b><span>{tr?"Aktif exception":"Active exceptions"}</span></article><article className={summary.retestRequiredExceptions?"critical":"healthy"}><b>{metric(summary.retestRequiredExceptions)}</b><span>{tr?"Zorunlu re-test":"Mandatory re-tests"}</span></article><article className={summary.failedRetest?"critical":"healthy"}><b>{metric(summary.failedRetest)}</b><span>{tr?"Başarısız re-test":"Failed re-tests"}</span></article><article className={summary.openFindings?"attention":"healthy"}><b>{metric(summary.openFindings)}</b><span>{tr?"Açık assurance bulgusu":"Open assurance findings"}</span></article></div>
  <div className="ag-aging"><span className={summary.riskReviewCritical?"critical":""}><b>{metric(summary.riskReviewCritical)}</b>{tr?"14+ gün kritik risk review":"14+ day critical risk reviews"}</span><span><b>{metric(summary.oldestRiskReviewDays)}</b>{tr?"En eski review yaşı (gün)":"Oldest review age (days)"}</span><span><b>{metric(summary.avgRiskReviewAgeDays)}</b>{tr?"Ort. review yaşı":"Average review age"}</span><span className={summary.expiringExceptions?"attention":""}><b>{metric(summary.expiringExceptions)}</b>{tr?"14 gün içinde bitecek exception":"Exceptions expiring in 14d"}</span><span className={summary.expiredExceptions?"critical":""}><b>{metric(summary.expiredExceptions)}</b>{tr?"Süresi bitmiş exception":"Expired exceptions"}</span></div>
  <div className="ag-posture"><span className="effective">Effective <b>{metric(summary.effective)}</b></span><span className="degraded">Degraded <b>{metric(summary.degraded)}</b></span><span className="ineffective">Ineffective <b>{metric(summary.ineffective)}</b></span><span>{tr?"Aktif iş":"Active work"} <b>{metric(summary.pendingWork)}</b></span></div>
  <div className="ag-trend"><header><b>{tr?"30 Günlük Governance Trend":"30-Day Governance Trend"}</b><small>{tr?"İnsan kararı, exception lifecycle ve re-test sonuçları":"Human decisions, exception lifecycle and re-test outcomes"}</small></header><div><span><b>{metric(trend.riskReviewsSubmitted)}</b>{tr?"Risk review gönderildi":"Risk reviews submitted"}</span><span><b>{metric(trend.riskReviewsApproved)}</b>{tr?"Risk kararı onaylandı":"Risk decisions approved"}</span><span><b>{metric(trend.exceptionsSubmitted)}</b>{tr?"Exception açıldı":"Exceptions requested"}</span><span><b>{metric(trend.exceptionsEnded)}</b>{tr?"Exception sona erdi":"Exceptions ended"}</span><span><b>{metric(trend.retestCompleted)}</b>{tr?"Re-test başarılı":"Re-tests completed"}</span><span className={trend.retestFailed?"critical":""}><b>{metric(trend.retestFailed)}</b>{tr?"Re-test başarısız/hata":"Re-tests failed/error"}</span></div></div>
  <label className="ag-search">{tr?'Risk, teklif veya istisna ara':'Search risks, proposals or exceptions'}<input value={search} onChange={event=>{setSearch(event.target.value);setRiskPage(0);setExceptionPage(0);setReviewPage(0);}}/></label>
  <div className="ag-grid">
   <article><header><b>Residual Risk Review</b><small>{tr?"Otomatik güvence sonucu risk düşürmez; onaylı karar gerekir.":"Automation never lowers residual risk without an approved decision."}</small></header>{riskItems.length?slice(riskItems,riskPage).map(x=><div className={`ag-row urgency-${x.reviewUrgency}`} key={x.id}><span><b>{x.riskRef||x.title} · {x.title}</b><small>{x.owner||"—"} · {x.riskLevel||"—"} · {x.assuranceState} · {x.reviewAgeDays}d · {x.reviewUrgency}</small></span><div><button onClick={()=>openRisk(x.id)}>{tr?"Riski Aç":"Open Risk"}</button>{role!=="Viewer"&&<button disabled={!reliable||busy||reviews.some(review=>review.riskId===x.id&&review.status==='pending-review')} onClick={()=>{setMessage('');setRisk(x);setRiskForm({residualLikelihood:String(x.context?.residualLikelihood||''),residualImpact:String(x.context?.residualImpact||''),rationale:'',evidenceReference:'',evidenceSha256:''});}}>{tr?"Değerlendir":"Assess"}</button>}</div></div>):<p className="ag-empty">{tr?"Eşleşen risk değerlendirmesi yok.":"No matching risk review is listed."}</p>}{pager(riskItems.length,riskPage,setRiskPage,tr?'Risk sayfaları':'Risk pages')}</article>
   <article><header><b>Exception / Waiver</b><small>{tr?"Süreli istisna assurance durumunu effective yapmaz; bitiş/revoke sonrası re-test gerekir.":"A time-bounded exception never changes assurance to effective; expiry or revocation requires re-test."}</small></header>{slice(exceptionItems,exceptionPage).map(x=><div className="ag-row" key={x.id}><span><b>{x.controlRef||x.ruleId||x.riskRef||x.findingId||x.id}</b><small>{x.status} · {tr?"bitiş":"expires"} {x.expiresAt}{x.retestRequired?` · ${tr?"RE-TEST GEREKLİ":"RE-TEST REQUIRED"}`:x.retestCompletedAt?` · ${tr?"RE-TEST TAMAMLANDI":"RE-TEST COMPLETED"}`:""}</small></span><div>{x.controlRef&&<button onClick={()=>openControl(x.controlRef)}>{tr?"Kontrol":"Control"}</button>}{x.ruleId&&<button onClick={()=>openRule(x.ruleId)}>{tr?"Kural":"Rule"}</button>}{x.findingId&&<button onClick={()=>openFinding(x.findingId)}>{tr?"Bulgu":"Finding"}</button>}{x.status==="pending-review"&&role==="Admin"&&<><button className="approve" disabled={busy||!reliable} onClick={()=>review("review-exception",x.id,"approve")}>{tr?"Onay":"Approve"}</button><button className="reject" disabled={busy||!reliable} onClick={()=>review("review-exception",x.id,"reject")}>{tr?"Ret":"Reject"}</button></>}{x.status==="active"&&role==="Admin"&&<button className="reject" disabled={busy||!reliable} onClick={()=>revoke(x.id)}>{tr?"Revoke":"Revoke"}</button>}</div></div>)}{!exceptionItems.length&&<p className="ag-empty">{tr?"Eşleşen istisna yok.":"No matching exception is listed."}</p>}{pager(exceptionItems.length,exceptionPage,setExceptionPage,tr?'İstisna sayfaları':'Exception pages')}</article>
  </div>
  <section className="ag-review-list" aria-label={tr?'Risk teklifleri':'Risk proposals'}><header><b>{tr?'Bağımsız risk onay kuyruğu':'Independent risk approval queue'}</b><label>{tr?'Görünüm':'View'}<select aria-label={tr?'Teklif görünümü':'Proposal view'} value={reviewFilter} onChange={event=>{setReviewFilter(event.target.value);setReviewPage(0);}}><option value="pending">{tr?'Bekleyen teklifler':'Pending proposals'}</option><option value="all">{tr?'Tüm teklifler / geçmiş':'All proposals / history'}</option></select></label></header>
  {slice(reviewItems,reviewPage).map(x=><div className="ag-row" key={x.id}><span><b>{x.currentRisk?.reference||x.riskId} · {x.currentRisk?.title||''}</b><small>{x.submittedBy} · {x.status==='pending-review'?(x.approvalBlocker?(tr?'Yeniden teklif gerekli':'New proposal required'):(tr?'Bağımsız onay bekliyor':'Awaiting independent approval')):x.status==='approved'?(tr?'Onaylandı':'Approved'):(tr?'Reddedildi':'Rejected')}</small></span><div><button type="button" onClick={()=>{setMessage('');setReviewId(x.id);}} aria-label={`${tr?'Teklifi incele':'Review proposal'} ${x.currentRisk?.reference||x.riskId}`}>{tr?'İncele':'Review'}</button></div></div>)}
  {!reviewItems.length&&<p className="ag-empty">{tr?'Eşleşen teklif yok.':'No matching proposals.'}</p>}{pager(reviewItems.length,reviewPage,setReviewPage,tr?'Teklif sayfaları':'Proposal pages')}</section>
  {selectedReview&&<RiskReviewDetails key={selectedReview.id} review={selectedReview} lang={lang} canDecide={role==='Admin'&&reliable} own={selectedReview.submittedBy.toLowerCase()===email.toLowerCase()} busy={busy} message={message} onClose={()=>setReviewId('')} onDecide={async(decision,note)=>{if(await post({action:'review-risk',reviewId:selectedReview.id,decision,note}))setReviewId('');}}/>}
  {risk&&<div className="ag-overlay"><section data-escape-layer className="ag-dialog" role="dialog" aria-modal="true" aria-label={tr?'Risk değerlendirmesi':'Risk assessment'}><header><div><small>RISK OWNER REASSESSMENT</small><h4>{risk.riskRef||risk.title} · {risk.title}</h4><p>{tr?`${risk.reviewAgeDays} gündür review bekliyor · ${risk.reviewUrgency}`:`Waiting ${risk.reviewAgeDays} days · ${risk.reviewUrgency}`}</p></div><button data-escape-close type="button" onClick={()=>setRisk(null)}>×</button></header><p className="ag-hint">{risk.reason}</p><RiskRating context={risk.context} label={tr?'Mevcut artık risk':'Current residual risk'}/><div className="ag-two"><label>{tr?'Artık risk olasılığı':'Residual likelihood'}<input type="number" min="1" max="5" value={riskForm.residualLikelihood} onChange={e=>setRiskForm({...riskForm,residualLikelihood:e.target.value})}/></label><label>{tr?'Artık risk etkisi':'Residual impact'}<input type="number" min="1" max="5" value={riskForm.residualImpact} onChange={e=>setRiskForm({...riskForm,residualImpact:e.target.value})}/></label></div><label>{tr?"Gerekçe":"Rationale"}<textarea value={riskForm.rationale} onChange={e=>setRiskForm({...riskForm,rationale:e.target.value})}/></label><label>{tr?"Kanıt referansı":"Evidence reference"}<input value={riskForm.evidenceReference} onChange={e=>setRiskForm({...riskForm,evidenceReference:e.target.value})}/></label><label>SHA-256<input value={riskForm.evidenceSha256} onChange={e=>setRiskForm({...riskForm,evidenceSha256:e.target.value})}/></label>{message&&<p className="ag-notice" role="alert">{message}</p>}<footer><button onClick={()=>setRisk(null)}>{tr?"Vazgeç":"Cancel"}</button><button className="primary" disabled={busy||!reliable||![riskForm.residualLikelihood,riskForm.residualImpact].every(v=>Number.isInteger(Number(v))&&Number(v)>=1&&Number(v)<=5)||riskForm.rationale.trim().length<20||!riskForm.evidenceReference.trim()||! /^[a-f0-9]{64}$/i.test(riskForm.evidenceSha256)} onClick={submitRisk}>{tr?"Bağımsız Onaya Gönder":"Submit for Independent Review"}</button></footer></section></div>}
  {exceptionOpen&&<div className="ag-overlay"><section data-escape-layer className="ag-dialog"><header><div><small>ASSURANCE EXCEPTION</small><h4>{tr?"Süreli exception talebi":"Time-bounded exception request"}</h4></div><button data-escape-close type="button" onClick={()=>setExceptionOpen(false)}>×</button></header><div className="ag-two"><label>Control ref<input value={exceptionForm.controlRef} onChange={e=>setExceptionForm({...exceptionForm,controlRef:e.target.value})}/></label><label>Risk ref<input value={exceptionForm.riskRef} onChange={e=>setExceptionForm({...exceptionForm,riskRef:e.target.value})}/></label><label>Rule ID<input value={exceptionForm.ruleId} onChange={e=>setExceptionForm({...exceptionForm,ruleId:e.target.value})}/></label><label>Finding ID<input value={exceptionForm.findingId} onChange={e=>setExceptionForm({...exceptionForm,findingId:e.target.value})}/></label></div><label>{tr?"Bitiş tarihi (maks. 180 gün)":"Expiry date (max 180 days)"}<input type="date" value={exceptionForm.expiresAt} onChange={e=>setExceptionForm({...exceptionForm,expiresAt:e.target.value})}/></label><label>{tr?"Gerekçe":"Reason"}<textarea value={exceptionForm.reason} onChange={e=>setExceptionForm({...exceptionForm,reason:e.target.value})}/></label><label>{tr?"Kanıt referansı":"Evidence reference"}<input value={exceptionForm.evidenceReference} onChange={e=>setExceptionForm({...exceptionForm,evidenceReference:e.target.value})}/></label><label>SHA-256<input value={exceptionForm.evidenceSha256} onChange={e=>setExceptionForm({...exceptionForm,evidenceSha256:e.target.value})}/></label><footer><button onClick={()=>setExceptionOpen(false)}>{tr?"Vazgeç":"Cancel"}</button><button className="primary" disabled={busy||!reliable} onClick={submitException}>{tr?"Bağımsız Onaya Gönder":"Submit for Independent Review"}</button></footer></section></div>}
 </section>;
}
