"use client";
import {useCallback,useEffect,useMemo,useState} from "react";
import {withBasePath} from "./base-path";
import "./continuous-assurance-alerts.css";

type Lang="tr"|"en";
type Alert={id:string;type:string;refType:string;refId:string;severity:"medium"|"high"|"critical";title:string;detail:string;status:string;firstSeenAt:string;lastSeenAt:string;acknowledgedBy:string;acknowledgedAt:string;acknowledgementNote:string;resolvedAt:string;occurrenceCount:number;escalation:"none"|"owner"|"management"|"executive"};
type Summary={active:number;unacknowledged:number;critical:number;high:number;escalated:number;resolved:number};
type Filter="active"|"critical"|"escalated"|"acknowledged"|"all";
const empty:Summary={active:0,unacknowledged:0,critical:0,high:0,escalated:0,resolved:0};

export default function ContinuousAssuranceAlerts({lang}:{lang:Lang}){
 const tr=lang==="tr",[alerts,setAlerts]=useState<Alert[]>([]),[summary,setSummary]=useState<Summary>(empty),[role,setRole]=useState("Viewer"),[loading,setLoading]=useState(true),[filter,setFilter]=useState<Filter>("active"),[ack,setAck]=useState<Alert|null>(null),[note,setNote]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const load=useCallback(async()=>{const[a,u]=await Promise.all([fetch(withBasePath("/api/continuous-assurance/alerts"),{cache:"no-store"}),fetch(withBasePath("/api/auth"),{cache:"no-store"})]);if(a.ok){const d=await a.json();setAlerts(Array.isArray(d.alerts)?d.alerts:[]);setSummary(d.summary||empty)}if(u.ok){const d=await u.json();setRole(d?.user?.role||"Viewer")}},[]);
 useEffect(()=>{let live=true;(async()=>{try{if(live)await load()}catch{}finally{if(live)setLoading(false)}})();return()=>{live=false}},[load]);
 const visible=useMemo(()=>alerts.filter(item=>{if(filter==="all")return true;if(filter==="active")return item.status!=="resolved";if(filter==="critical")return item.status!=="resolved"&&item.severity==="critical";if(filter==="escalated")return item.status!=="resolved"&&(item.escalation==="management"||item.escalation==="executive");return item.status==="acknowledged"}).slice(0,30),[alerts,filter]);
 const fmt=(value:string)=>{const date=new Date(value);return Number.isNaN(date.getTime())?value:new Intl.DateTimeFormat(tr?"tr-TR":"en-GB",{dateStyle:"short",timeStyle:"short"}).format(date)};
 const typeLabel=(value:string)=>tr?({"retest-failed":"Re-test başarısız","retest-error":"Re-test hatası","work-sla-breached":"SLA ihlali","exception-expired":"Exception süresi doldu","exception-expiring":"Exception süresi yaklaşıyor","exception-review-expired":"Onay bekleyen exception süresi doldu","risk-review-required":"Risk review gerekli","finding-overdue":"Bulgu gecikti"} as Record<string,string>)[value]||value:({"retest-failed":"Re-test failed","retest-error":"Re-test error","work-sla-breached":"SLA breached","exception-expired":"Exception expired","exception-expiring":"Exception expiring","exception-review-expired":"Pending exception expired","risk-review-required":"Risk review required","finding-overdue":"Finding overdue"} as Record<string,string>)[value]||value;
 const escalationLabel=(value:Alert["escalation"])=>tr?({none:"Normal",owner:"Owner",management:"Yönetim",executive:"Executive"} as Record<Alert["escalation"],string>)[value]:({none:"Normal",owner:"Owner",management:"Management",executive:"Executive"} as Record<Alert["escalation"],string>)[value];
 async function acknowledge(){if(!ack||note.trim().length<5)return;setBusy(true);setMessage("");try{const r=await fetch(withBasePath("/api/continuous-assurance/alerts"),{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"acknowledge-alert",alertId:ack.id,note})}),d=await r.json().catch(()=>({}));setMessage(r.ok?(d.message||(tr?"Alert acknowledge edildi.":"Alert acknowledged.")):(d.error||(tr?"İşlem başarısız.":"Operation failed.")));if(r.ok){setAck(null);setNote("");await load()}}finally{setBusy(false)}}
 return <section className="assurance-alerts">
  <header><div><small>ALERTS · ESCALATIONS</small><h4>{tr?"Continuous Assurance uyarı merkezi":"Continuous Assurance alert center"}</h4><p>{tr?"Kontrol, re-test, SLA, exception, bulgu ve risk sinyallerini tek operasyonel akışta yönetin.":"Manage control, re-test, SLA, exception, finding and risk signals in one operational flow."}</p></div><span className={summary.critical?"critical":"healthy"}>{summary.active} {tr?"aktif":"active"}</span></header>
  {message&&<div className="aa-message" onClick={()=>setMessage("")}>{message}<b>×</b></div>}
  <div className="aa-summary"><article className={summary.unacknowledged?"attention":"healthy"}><b>{loading?"…":summary.unacknowledged}</b><small>{tr?"Acknowledge edilmemiş":"Unacknowledged"}</small></article><article className={summary.critical?"critical":"healthy"}><b>{summary.critical}</b><small>Critical</small></article><article className={summary.high?"attention":"healthy"}><b>{summary.high}</b><small>High</small></article><article className={summary.escalated?"critical":"healthy"}><b>{summary.escalated}</b><small>{tr?"Yönetim+ escalation":"Management+ escalation"}</small></article><article><b>{summary.resolved}</b><small>{tr?"Otomatik çözülen":"Auto-resolved"}</small></article></div>
  <div className="aa-filters">{(["active","critical","escalated","acknowledged","all"] as Filter[]).map(value=><button key={value} className={filter===value?"active":""} onClick={()=>setFilter(value)}>{tr?({active:"Aktif",critical:"Critical",escalated:"Escalated",acknowledged:"Acknowledged",all:"Tümü"} as Record<Filter,string>)[value]:({active:"Active",critical:"Critical",escalated:"Escalated",acknowledged:"Acknowledged",all:"All"} as Record<Filter,string>)[value]}</button>)}</div>
  {visible.length?<div className="aa-list">{visible.map(item=><article key={item.id} className={`severity-${item.severity} status-${item.status}`}><div className="aa-severity"><span>{item.severity}</span><small>{typeLabel(item.type)}</small></div><div className="aa-main"><b>{item.title}</b><p>{item.detail}</p><footer><code>{item.refType}:{item.refId}</code><span>{tr?"İlk":"First"} {fmt(item.firstSeenAt)}</span>{item.occurrenceCount>1&&<em>×{item.occurrenceCount}</em>}</footer></div><div className="aa-state"><span className={`escalation ${item.escalation}`}>{escalationLabel(item.escalation)}</span><small>{item.status}</small>{item.status==="open"&&role!=="Viewer"&&<button onClick={()=>{setAck(item);setNote("")}}>{tr?"Acknowledge":"Acknowledge"}</button>}{item.status==="acknowledged"&&<em>{item.acknowledgedBy||"—"}</em>}</div></article>)}</div>:<div className="aa-empty">{loading?(tr?"Alert sinyalleri yükleniyor…":"Loading alert signals…"):(tr?"Bu filtrede aktif alert yok.":"No alerts in this filter.")}</div>}
  {ack&&<div className="aa-overlay" onMouseDown={event=>{if(event.target===event.currentTarget&&!busy)setAck(null)}}><section className="aa-dialog" role="dialog" aria-modal="true"><header><div><small>ACKNOWLEDGEMENT</small><h4>{ack.title}</h4></div><button disabled={busy} onClick={()=>setAck(null)}>×</button></header><p>{tr?"Acknowledge alerti kapatmaz. Underlying koşul düzelene kadar aktif kalır ve escalation süresi işlemeye devam eder.":"Acknowledgement does not close the alert. It remains active until the underlying condition clears and escalation aging continues."}</p><label>{tr?"Operasyon notu":"Operational note"}<textarea autoFocus value={note} onChange={e=>setNote(e.target.value)} placeholder={tr?"Yapılan aksiyonu veya takip planını yazın…":"Describe the action taken or follow-up plan…"}/></label><footer><button disabled={busy} onClick={()=>setAck(null)}>{tr?"Vazgeç":"Cancel"}</button><button className="primary" disabled={busy||note.trim().length<5} onClick={acknowledge}>{busy?(tr?"İşleniyor…":"Processing…"):(tr?"Acknowledge Et":"Acknowledge")}</button></footer></section></div>}
 </section>;
}
