"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
import {withBasePath} from "./base-path";
import "./continuity-center.css";
type Lang="tr"|"en";type User={role:string;email:string};
type Plan={id:string;code:string;name:string;process:string;biaRef:string;criticality:string;owner:string;reviewer:string;crisisLead:string;rtoHours:number;rpoHours:number;mtpdHours:number;dependencies:string;recoveryStrategy:string;communicationPlan:string;minimumStaff:number;reviewDate:string;status:string};
type Exercise={id:string;code:string;planId:string;type:string;scheduledDate:string;scenario:string;facilitator:string;status:string;outcome?:string;rtoBreached:boolean;rpoBreached:boolean};type Gap={id:string;planId:string;severity:string;title:string;owner:string;reviewer:string;dueDate:string;status:string};
type FormState=Record<string,string|number>;
type Summary={activePlans:number;overdueReviews:number;dueExercises:number;failedExercises:number;rtoBreaches:number;openGaps:number};const emptySummary={activePlans:0,overdueReviews:0,dueExercises:0,failedExercises:0,rtoBreaches:0,openGaps:0};
const future=(days:number)=>new Date(Date.now()+days*86400000).toISOString().slice(0,10);
const newPlan=(email:string)=>({name:"",process:"",biaRef:"",criticality:"high",owner:email,reviewer:"",crisisLead:"",rtoHours:4,rpoHours:1,mtpdHours:24,dependencies:"",recoveryStrategy:"",communicationPlan:"",alternateSite:"",supplierDependencies:"",minimumStaff:2,reviewDate:future(365)});
export default function ContinuityCenter({lang,currentUser}:{lang:Lang;currentUser:User}){const tr=lang==="tr",[plans,setPlans]=useState<Plan[]>([]),[exercises,setExercises]=useState<Exercise[]>([]),[gaps,setGaps]=useState<Gap[]>([]),[summary,setSummary]=useState<Summary>(emptySummary),[tab,setTab]=useState("plans"),[query,setQuery]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[planForm,setPlanForm]=useState<FormState|null>(null),[exerciseForm,setExerciseForm]=useState<FormState|null>(null),[dialog,setDialog]=useState<FormState|null>(null);
 const apply=(x:{plans?:Plan[];exercises?:Exercise[];gaps?:Gap[];summary?:Summary})=>{setPlans(x.plans||[]);setExercises(x.exercises||[]);setGaps(x.gaps||[]);setSummary(x.summary||emptySummary)};async function load(){const r=await fetch(withBasePath("/api/continuity"),{cache:"no-store"});if(r.ok)apply(await r.json())}useEffect(()=>{let live=true;fetch(withBasePath("/api/continuity"),{cache:"no-store"}).then(r=>r.ok?r.json():null).then(x=>{if(live&&x)apply(x)}).catch(()=>{});return()=>{live=false}},[]);
 async function api(body:Record<string,unknown>){setBusy(true);setNotice("");try{const r=await fetch(withBasePath("/api/continuity"),{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)}),x=await r.json().catch(()=>({}));setNotice(r.ok?(x.message||"OK"):(x.error||"Error"));if(r.ok)await load();return r.ok}catch{setNotice(tr?"Sunucuya ulaşılamadı.":"Server unavailable.");return false}finally{setBusy(false)}}
 async function createPlan(e:FormEvent){e.preventDefault();if(planForm&&await api({action:"create-plan",...planForm}))setPlanForm(null)}async function createExercise(e:FormEvent){e.preventDefault();if(exerciseForm&&await api({action:"schedule-exercise",...exerciseForm}))setExerciseForm(null)}
 const rows=useMemo(()=>{const q=query.toLocaleLowerCase("tr");return tab==="plans"?plans.filter(x=>`${x.code} ${x.name} ${x.process} ${x.biaRef}`.toLocaleLowerCase("tr").includes(q)):tab==="exercises"?exercises.filter(x=>`${x.code} ${x.type} ${x.scenario}`.toLocaleLowerCase("tr").includes(q)):gaps.filter(x=>`${x.title} ${x.owner} ${x.severity}`.toLocaleLowerCase("tr").includes(q))},[tab,query,plans,exercises,gaps]);
 const action=(kind:string,id:string)=>setDialog({kind,id,note:"",confirmation:"",evidenceReference:"",evidenceSha256:"",outcome:"passed",actualRecoveryHours:"",actualDataLossHours:"",observations:"",rootCause:""});async function submitDialog(){if(!dialog)return;const key=dialog.kind==="complete-exercise"?"exerciseId":dialog.kind==="close-gap"?"gapId":"planId";if(await api({action:dialog.kind,[key]:dialog.id,...dialog}))setDialog(null)}
 return <section className="continuity-page"><header className="continuity-hero"><div><small>BCM · BIA · RTO/RPO · EXERCISE · OPERATIONAL RESILIENCE</small><h2>{tr?"İş Sürekliliği ve Dayanıklılık":"Business Continuity & Resilience"}</h2><p>{tr?"Kritik süreçleri onaylı kurtarma planlarına, kanıtlı tatbikatlara ve bağımsız iyileştirme kapanışına bağlayın.":"Connect critical processes to approved recovery plans, evidenced exercises and independent remediation closure."}</p></div><div>{currentUser.role==="Admin"&&<a href={withBasePath("/api/continuity?format=csv")}>CSV</a>}{currentUser.role!=="Viewer"&&<button onClick={()=>setPlanForm(newPlan(currentUser.email))}>+ {tr?"Yeni Plan":"New Plan"}</button>}</div></header>
 {notice&&<button className="continuity-notice" onClick={()=>setNotice("")}>{notice}<b>×</b></button>}<div className="continuity-kpis">{[[summary.activePlans,tr?"Etkin plan":"Active plans"],[summary.overdueReviews,tr?"Gecikmiş review":"Overdue reviews"],[summary.dueExercises,tr?"Bekleyen tatbikat":"Exercises due"],[summary.failedExercises,tr?"Başarısız/kısmi":"Failed/partial"],[summary.rtoBreaches,"RTO breach"],[summary.openGaps,tr?"Açık aksiyon":"Open gaps"]].map(([v,l])=><article key={String(l)}><small>{l}</small><strong>{v}</strong></article>)}</div>
 <nav className="continuity-tabs">{[["plans",tr?"Planlar":"Plans"],["exercises",tr?"Tatbikatlar":"Exercises"],["gaps",tr?"İyileştirme açıkları":"Improvement gaps"]].map(([k,l])=><button className={tab===k?"active":""} key={k} onClick={()=>setTab(k)}>{l}</button>)}<input value={query} onChange={e=>setQuery(e.target.value)} placeholder={tr?"Ara…":"Search…"}/></nav>
 <div className="continuity-table"><table><thead><tr>{tab==="plans"?<><th>{tr?"Plan / Süreç":"Plan / Process"}</th><th>BIA</th><th>RTO / RPO / MTPD</th><th>{tr?"Yönetişim":"Governance"}</th><th>{tr?"Durum":"Status"}</th></>:tab==="exercises"?<><th>{tr?"Tatbikat":"Exercise"}</th><th>{tr?"Plan / Tarih":"Plan / Date"}</th><th>Facilitator</th><th>{tr?"Sonuç":"Outcome"}</th><th>{tr?"İşlem":"Action"}</th></>:<><th>{tr?"Açık":"Gap"}</th><th>{tr?"Sahip":"Owner"}</th><th>Reviewer</th><th>{tr?"Termin":"Due"}</th><th>{tr?"İşlem":"Action"}</th></>}</tr></thead><tbody>{tab==="plans"&&(rows as Plan[]).map(x=><tr key={x.id}><td><b>{x.name}</b><small>{x.code} · {x.process}</small></td><td><b>{x.biaRef}</b><small>{x.criticality}</small></td><td><b>{x.rtoHours}h / {x.rpoHours}h</b><small>MTPD {x.mtpdHours}h · staff {x.minimumStaff}</small></td><td><b>{x.owner}</b><small>{x.reviewer}</small></td><td><span>{x.status}</span><small>{x.reviewDate}</small><div className="continuity-actions">{x.status==="draft"&&<button onClick={()=>action("approve-plan",x.id)}>approve</button>}{x.status==="approved"&&<button onClick={()=>action("activate-plan",x.id)}>activate</button>}{x.status==="active"&&<><button onClick={()=>setExerciseForm({planId:x.id,type:"tabletop",scheduledDate:future(30),scenario:"",facilitator:currentUser.email})}>exercise</button><button onClick={()=>action("retire-plan",x.id)}>retire</button></>}</div></td></tr>)}{tab==="exercises"&&(rows as Exercise[]).map(x=><tr key={x.id}><td><b>{x.code}</b><small>{x.type}</small></td><td><b>{plans.find(p=>p.id===x.planId)?.name||x.planId}</b><small>{x.scheduledDate}</small></td><td>{x.facilitator}</td><td><span>{x.outcome||x.status}</span><small>{x.rtoBreached?"RTO breach ":""}{x.rpoBreached?"RPO breach":""}</small></td><td>{x.status==="planned"&&currentUser.role!=="Viewer"&&<button onClick={()=>action("complete-exercise",x.id)}>complete</button>}</td></tr>)}{tab==="gaps"&&(rows as Gap[]).map(x=><tr key={x.id}><td><b>{x.title}</b><small>{x.severity} · {x.status}</small></td><td>{x.owner}</td><td>{x.reviewer}</td><td>{x.dueDate}</td><td>{x.status==="open"&&currentUser.role!=="Viewer"&&<button onClick={()=>action("close-gap",x.id)}>close</button>}</td></tr>)}</tbody></table>{!rows.length&&<p className="continuity-empty">{tr?"Kayıt bulunamadı.":"No records found."}</p>}</div>
 {planForm&&<Overlay title={tr?"Yeni süreklilik planı":"New continuity plan"} close={()=>setPlanForm(null)}><form onSubmit={createPlan} className="continuity-form"><div className="form-grid">{[["name","Plan adı"],["process","Kritik süreç"],["biaRef","BIA referansı"],["owner","Plan sahibi"],["reviewer","Bağımsız reviewer"],["crisisLead","Kriz lideri"]].map(([k,l])=><Field key={k} label={l} name={k} form={planForm} set={setPlanForm}/>)}<label>Kritiklik<select value={planForm.criticality} onChange={e=>setPlanForm({...planForm,criticality:e.target.value})}>{["low","medium","high","critical"].map(x=><option key={x}>{x}</option>)}</select></label>{[["rtoHours","RTO (saat)"],["rpoHours","RPO (saat)"],["mtpdHours","MTPD (saat)"],["minimumStaff","Minimum personel"]].map(([k,l])=><Field key={k} type="number" label={l} name={k} form={planForm} set={setPlanForm}/>)}<Field type="date" label="Review" name="reviewDate" form={planForm} set={setPlanForm}/>{[["dependencies","Bağımlılıklar"],["recoveryStrategy","Kurtarma stratejisi"],["communicationPlan","İletişim planı"],["alternateSite","Alternatif lokasyon"],["supplierDependencies","Tedarikçi bağımlılıkları"]].map(([k,l])=><Field wide area key={k} label={l} name={k} form={planForm} set={setPlanForm}/>)}</div><footer><button disabled={busy}>{tr?"Planı oluştur":"Create plan"}</button></footer></form></Overlay>}
 {exerciseForm&&<Overlay title={tr?"Tatbikat zamanla":"Schedule exercise"} close={()=>setExerciseForm(null)}><form className="continuity-form" onSubmit={createExercise}><label>{tr?"Tür":"Type"}<select value={exerciseForm.type} onChange={e=>setExerciseForm({...exerciseForm,type:e.target.value})}>{["tabletop","technical","failover","full-scale"].map(x=><option key={x}>{x}</option>)}</select></label><Field type="date" label={tr?"Tarih":"Date"} name="scheduledDate" form={exerciseForm} set={setExerciseForm}/><Field label="Facilitator" name="facilitator" form={exerciseForm} set={setExerciseForm}/><Field area label={tr?"Senaryo":"Scenario"} name="scenario" form={exerciseForm} set={setExerciseForm}/><footer><button disabled={busy}>{tr?"Zamanla":"Schedule"}</button></footer></form></Overlay>}
 {dialog&&<Overlay title={dialog.kind} close={()=>setDialog(null)}><div className="continuity-form">{dialog.kind==="complete-exercise"&&<><label>Outcome<select value={dialog.outcome} onChange={e=>setDialog({...dialog,outcome:e.target.value})}>{["passed","partial","failed"].map(x=><option key={x}>{x}</option>)}</select></label><Field type="number" label="Actual recovery (h)" name="actualRecoveryHours" form={dialog} set={setDialog}/><Field type="number" label="Actual data loss (h)" name="actualDataLossHours" form={dialog} set={setDialog}/><Field area label="Observations" name="observations" form={dialog} set={setDialog}/><Field area label="Root cause (partial/failed)" name="rootCause" form={dialog} set={setDialog}/></>}<Field area label={tr?"Karar notu":"Decision note"} name="note" form={dialog} set={setDialog}/><Field label={tr?"Kanıt referansı":"Evidence reference"} name="evidenceReference" form={dialog} set={setDialog}/><Field label="SHA-256" name="evidenceSha256" form={dialog} set={setDialog}/>{dialog.kind!=="complete-exercise"&&<Field label={tr?"Onay ifadesi":"Confirmation phrase"} name="confirmation" form={dialog} set={setDialog}/>}<footer><button disabled={busy} onClick={()=>void submitDialog()}>{tr?"Uygula":"Apply"}</button></footer></div></Overlay>}</section>}
function Overlay({title,close,children}:{title:React.ReactNode;close:()=>void;children:React.ReactNode}){return <div className="continuity-overlay"><article role="dialog" aria-modal="true" aria-label={typeof title==="string"?title:"Continuity dialog"}><header><h3>{title}</h3><button type="button" aria-label="Close dialog" onClick={close}>×</button></header>{children}</article></div>}
function Field({label,name,form,set,type="text",area=false,wide=false}:{label:string;name:string;form:FormState;set:React.Dispatch<React.SetStateAction<FormState|null>>;type?:string;area?:boolean;wide?:boolean}){return <label className={wide?"wide":""}>{label}{area?<textarea value={String(form[name]??"")} onChange={e=>set({...form,[name]:e.target.value})}/>:<input type={type} step={type==="number"?"0.25":undefined} value={form[name]??""} onChange={e=>set({...form,[name]:type==="number"?Number(e.target.value):e.target.value})}/>}</label>}
