"use client";
import {useCallback,useEffect,useState} from "react";
import {withBasePath} from "./base-path";
import "./continuous-assurance-governance.css";

type Lang="tr"|"en";
type Risk={id:string;title:string;owner:string;riskLevel:string;assuranceState:string;lastAssuranceRunRef:string;reason:string};
type Review={id:string;riskId:string;status:string;proposal:Record<string,unknown>;submittedBy:string;submittedAt:string;reviewedBy:string};
type Exception={id:string;findingId:string;ruleId:string;controlRef:string;riskRef:string;reason:string;expiresAt:string;status:string;submittedBy:string;submittedAt:string};
type Summary={reviewRequired:number;pendingRiskReviews:number;activeExceptions:number;expiringExceptions:number;effective:number;degraded:number;ineffective:number;pendingWork:number;failedRetest:number;openFindings:number};
const empty:Summary={reviewRequired:0,pendingRiskReviews:0,activeExceptions:0,expiringExceptions:0,effective:0,degraded:0,ineffective:0,pendingWork:0,failedRetest:0,openFindings:0};

export default function ContinuousAssuranceGovernance({lang}:{lang:Lang}){
 const tr=lang==="tr",[summary,setSummary]=useState<Summary>(empty),[risks,setRisks]=useState<Risk[]>([]),[reviews,setReviews]=useState<Review[]>([]),[exceptions,setExceptions]=useState<Exception[]>([]),[role,setRole]=useState("Viewer"),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[risk,setRisk]=useState<Risk|null>(null),[riskForm,setRiskForm]=useState({residualLikelihood:"",residualImpact:"",rationale:"",evidenceReference:"",evidenceSha256:""}),[exceptionOpen,setExceptionOpen]=useState(false),[exceptionForm,setExceptionForm]=useState({findingId:"",ruleId:"",controlRef:"",riskRef:"",reason:"",expiresAt:"",evidenceReference:"",evidenceSha256:""});
 const load=useCallback(async()=>{const[g,a]=await Promise.all([fetch(withBasePath("/api/continuous-assurance/governance"),{cache:"no-store"}),fetch(withBasePath("/api/auth"),{cache:"no-store"})]);if(g.ok){const d=await g.json();setSummary(d.summary||empty);setRisks(d.risksRequiringReview||[]);setReviews(d.riskReviews||[]);setExceptions(d.exceptions||[])}if(a.ok){const d=await a.json();setRole(d?.user?.role||"Viewer")}},[]);
 useEffect(()=>{load().catch(()=>{})},[load]);
 async function post(body:Record<string,unknown>){setBusy(true);setMessage("");try{const r=await fetch(withBasePath("/api/continuous-assurance/governance"),{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)}),d=await r.json().catch(()=>({}));setMessage(r.ok?(d.message||(tr?"İşlem tamamlandı.":"Completed.")):(d.error||(tr?"İşlem başarısız.":"Operation failed.")));if(r.ok)await load();return r.ok}finally{setBusy(false)}}
 async function submitRisk(){if(!risk)return;const ok=await post({action:"submit-risk-review",riskId:risk.id,residualLikelihood:Number(riskForm.residualLikelihood),residualImpact:Number(riskForm.residualImpact),rationale:riskForm.rationale,evidenceReference:riskForm.evidenceReference,evidenceSha256:riskForm.evidenceSha256});if(ok){setRisk(null);setRiskForm({residualLikelihood:"",residualImpact:"",rationale:"",evidenceReference:"",evidenceSha256:""})}}
 async function submitException(){const ok=await post({action:"create-exception",...exceptionForm});if(ok){setExceptionOpen(false);setExceptionForm({findingId:"",ruleId:"",controlRef:"",riskRef:"",reason:"",expiresAt:"",evidenceReference:"",evidenceSha256:""})}}
 async function review(action:"review-risk"|"review-exception",id:string,decision:"approve"|"reject"){let note="";if(decision==="reject"){note=window.prompt(tr?"Ret gerekçesini yazın (en az 10 karakter):":"Enter rejection reason (minimum 10 characters):")||"";if(note.trim().length<10)return}await post(action==="review-risk"?{action,reviewId:id,decision,note}:{action,exceptionId:id,decision,note})}
 const pendingReviews=reviews.filter(x=>x.status==="pending-review").slice(0,6),pendingExceptions=exceptions.filter(x=>x.status==="pending-review").slice(0,6),activeExceptions=exceptions.filter(x=>x.status==="active").slice(0,6);
 return <section className="assurance-governance">
  <header><div><small>EXECUTIVE ASSURANCE · GOVERNANCE</small><h4>{tr?"Risk kararları ve exception yönetimi":"Risk decisions & exception governance"}</h4><p>{tr?"Continuous Assurance sinyallerini insan onaylı residual risk kararlarına ve süreli istisnalara bağlayın.":"Turn Continuous Assurance signals into human-approved residual risk decisions and time-bounded exceptions."}</p></div>{role!=="Viewer"&&<button onClick={()=>setExceptionOpen(true)}>{tr?"+ Exception Talebi":"+ Exception Request"}</button>}</header>
  {message&&<div className="ag-message" onClick={()=>setMessage("")}>{message}<b>×</b></div>}
  <div className="ag-metrics"><article className={summary.reviewRequired?"attention":"healthy"}><b>{summary.reviewRequired}</b><span>{tr?"Risk review gerekli":"Risk reviews required"}</span></article><article className={summary.pendingRiskReviews?"attention":"healthy"}><b>{summary.pendingRiskReviews}</b><span>{tr?"Onay bekleyen risk":"Pending risk approvals"}</span></article><article className={summary.activeExceptions?"attention":"healthy"}><b>{summary.activeExceptions}</b><span>{tr?"Aktif exception":"Active exceptions"}</span></article><article className={summary.expiringExceptions?"critical":"healthy"}><b>{summary.expiringExceptions}</b><span>{tr?"14 gün içinde biten":"Expiring in 14 days"}</span></article><article className={summary.failedRetest?"critical":"healthy"}><b>{summary.failedRetest}</b><span>{tr?"Başarısız re-test":"Failed re-tests"}</span></article><article className={summary.openFindings?"attention":"healthy"}><b>{summary.openFindings}</b><span>{tr?"Açık assurance bulgusu":"Open assurance findings"}</span></article></div>
  <div className="ag-posture"><span className="effective">{tr?"Effective":"Effective"} <b>{summary.effective}</b></span><span className="degraded">{tr?"Degraded":"Degraded"} <b>{summary.degraded}</b></span><span className="ineffective">{tr?"Ineffective":"Ineffective"} <b>{summary.ineffective}</b></span><span>{tr?"Aktif iş":"Active work"} <b>{summary.pendingWork}</b></span></div>
  <div className="ag-grid">
   <article><header><b>{tr?"Residual Risk Review":"Residual Risk Review"}</b><small>{tr?"Otomatik güvence sonucu risk düşürmez; onaylı karar gerekir.":"Automation never lowers residual risk without an approved decision."}</small></header>{risks.length?risks.slice(0,8).map(x=><div className="ag-row" key={x.id}><span><b>{x.title}</b><small>{x.owner||"—"} · {x.riskLevel||"—"} · {x.assuranceState}</small></span>{role!=="Viewer"&&<button onClick={()=>setRisk(x)}>{tr?"Değerlendir":"Assess"}</button>}</div>):<p className="ag-empty">{tr?"Risk owner review bekleyen kayıt yok.":"No risk owner review is pending."}</p>}</article>
   <article><header><b>{tr?"Exception / Waiver":"Exception / Waiver"}</b><small>{tr?"Süreli istisna assurance durumunu effective yapmaz.":"A time-bounded exception never changes assurance to effective."}</small></header>{[...pendingExceptions,...activeExceptions].slice(0,8).map(x=><div className="ag-row" key={x.id}><span><b>{x.controlRef||x.ruleId||x.riskRef||x.findingId||x.id}</b><small>{x.status} · {tr?"bitiş":"expires"} {x.expiresAt}</small></span>{x.status==="pending-review"&&role==="Admin"&&<div><button className="approve" disabled={busy} onClick={()=>review("review-exception",x.id,"approve")}>{tr?"Onay":"Approve"}</button><button className="reject" disabled={busy} onClick={()=>review("review-exception",x.id,"reject")}>{tr?"Ret":"Reject"}</button></div>}</div>)}{!pendingExceptions.length&&!activeExceptions.length&&<p className="ag-empty">{tr?"Aktif veya onay bekleyen exception yok.":"No active or pending exception."}</p>}</article>
  </div>
  {role==="Admin"&&pendingReviews.length>0&&<div className="ag-review-strip"><b>{tr?"Bağımsız risk onay kuyruğu":"Independent risk approval queue"}</b>{pendingReviews.map(x=><span key={x.id}><em>{x.riskId}</em><button className="approve" disabled={busy} onClick={()=>review("review-risk",x.id,"approve")}>{tr?"Onayla":"Approve"}</button><button className="reject" disabled={busy} onClick={()=>review("review-risk",x.id,"reject")}>{tr?"Reddet":"Reject"}</button></span>)}</div>}
  {risk&&<div className="ag-overlay"><section className="ag-dialog"><header><div><small>RISK OWNER REASSESSMENT</small><h4>{risk.title}</h4></div><button onClick={()=>setRisk(null)}>×</button></header><div className="ag-two"><label>Residual likelihood<input type="number" min="1" max="5" value={riskForm.residualLikelihood} onChange={e=>setRiskForm({...riskForm,residualLikelihood:e.target.value})}/></label><label>Residual impact<input type="number" min="1" max="5" value={riskForm.residualImpact} onChange={e=>setRiskForm({...riskForm,residualImpact:e.target.value})}/></label></div><label>{tr?"Gerekçe":"Rationale"}<textarea value={riskForm.rationale} onChange={e=>setRiskForm({...riskForm,rationale:e.target.value})}/></label><label>{tr?"Kanıt referansı":"Evidence reference"}<input value={riskForm.evidenceReference} onChange={e=>setRiskForm({...riskForm,evidenceReference:e.target.value})}/></label><label>SHA-256<input value={riskForm.evidenceSha256} onChange={e=>setRiskForm({...riskForm,evidenceSha256:e.target.value})}/></label><footer><button onClick={()=>setRisk(null)}>{tr?"Vazgeç":"Cancel"}</button><button className="primary" disabled={busy} onClick={submitRisk}>{tr?"Bağımsız Onaya Gönder":"Submit for Independent Review"}</button></footer></section></div>}
  {exceptionOpen&&<div className="ag-overlay"><section className="ag-dialog"><header><div><small>ASSURANCE EXCEPTION</small><h4>{tr?"Süreli exception talebi":"Time-bounded exception request"}</h4></div><button onClick={()=>setExceptionOpen(false)}>×</button></header><div className="ag-two"><label>Control ref<input value={exceptionForm.controlRef} onChange={e=>setExceptionForm({...exceptionForm,controlRef:e.target.value})}/></label><label>Risk ref<input value={exceptionForm.riskRef} onChange={e=>setExceptionForm({...exceptionForm,riskRef:e.target.value})}/></label><label>Rule ID<input value={exceptionForm.ruleId} onChange={e=>setExceptionForm({...exceptionForm,ruleId:e.target.value})}/></label><label>Finding ID<input value={exceptionForm.findingId} onChange={e=>setExceptionForm({...exceptionForm,findingId:e.target.value})}/></label></div><label>{tr?"Bitiş tarihi (maks. 180 gün)":"Expiry date (max 180 days)"}<input type="date" value={exceptionForm.expiresAt} onChange={e=>setExceptionForm({...exceptionForm,expiresAt:e.target.value})}/></label><label>{tr?"Gerekçe":"Reason"}<textarea value={exceptionForm.reason} onChange={e=>setExceptionForm({...exceptionForm,reason:e.target.value})}/></label><label>{tr?"Kanıt referansı":"Evidence reference"}<input value={exceptionForm.evidenceReference} onChange={e=>setExceptionForm({...exceptionForm,evidenceReference:e.target.value})}/></label><label>SHA-256<input value={exceptionForm.evidenceSha256} onChange={e=>setExceptionForm({...exceptionForm,evidenceSha256:e.target.value})}/></label><footer><button onClick={()=>setExceptionOpen(false)}>{tr?"Vazgeç":"Cancel"}</button><button className="primary" disabled={busy} onClick={submitException}>{tr?"Bağımsız Onaya Gönder":"Submit for Independent Review"}</button></footer></section></div>}
 </section>;
}
