"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { withBasePath } from "./base-path";
import "./evidence-automation.css";

type Lang = "tr" | "en";
type Source = { id:string; name:string; vendor:string; category:string; driver:string; enabled:boolean; config:Record<string,string>; hasSecret:boolean; lastTestStatus?:string; lastTestAt?:string };
type Rule = { id:string; name:string; sourceId:string; controlRefs:string; jsonPath:string; operator:string; expected:string; schedule:string; enabled:boolean; lastStatus?:string; lastRunAt?:string };
type Run = { id:string; ruleName:string; sourceName:string; status:string; score:number; detail:string; evidenceId?:string; createdAt:string };

const catalog = [
  ["Cloud & SaaS","Microsoft 365 / Graph","microsoft-graph"],["Cloud & SaaS","Azure","azure-rest"],["Cloud & SaaS","AWS","aws-api"],["Cloud & SaaS","Google Cloud","gcp-api"],["Cloud & SaaS","Cloudflare","cloudflare-api"],["Cloud & SaaS","GitHub / GitLab","devops-api"],
  ["Firewall & Network","Fortinet FortiGate / FortiAnalyzer","rest-json"],["Firewall & Network","Palo Alto / Panorama","rest-json"],["Firewall & Network","Cisco Secure Firewall","rest-json"],["Firewall & Network","Check Point","rest-json"],["Firewall & Network","Juniper / Aruba / F5","rest-json"],
  ["XDR, EDR & SIEM","Microsoft Defender XDR / Sentinel","rest-json"],["XDR, EDR & SIEM","CrowdStrike Falcon","rest-json"],["XDR, EDR & SIEM","Palo Alto Cortex XDR","rest-json"],["XDR, EDR & SIEM","SentinelOne","rest-json"],["XDR, EDR & SIEM","Splunk / QRadar / Elastic / Wazuh","rest-json"],
  ["IAM, PAM & IGA","Microsoft Entra ID","microsoft-graph"],["IAM, PAM & IGA","Okta","rest-json"],["IAM, PAM & IGA","CyberArk / Segura / BeyondTrust","rest-json"],["IAM, PAM & IGA","SailPoint / Saviynt / One Identity","rest-json"],["IAM, PAM & IGA","LDAP / Active Directory Bridge","https-bridge"],
  ["Data, DB & Application","Purview DLP / EDM","microsoft-graph"],["Data, DB & Application","Imperva / IBM Guardium DAM","rest-json"],["Data, DB & Application","Oracle / SQL Server / PostgreSQL","https-bridge"],["Data, DB & Application","Tenable / Qualys / Rapid7","rest-json"],["Data, DB & Application","Checkmarx / SonarQube / Snyk","rest-json"],
  ["Work & Custom","Jira / ServiceNow / Azure DevOps","rest-json"],["Work & Custom","Generic REST / JSON API","rest-json"],["Work & Custom","Webhook Receiver","webhook"],["Work & Custom","On-prem HTTPS Collector Bridge","https-bridge"],
] as const;

export default function EvidenceAutomation({lang,currentUser}:{lang:Lang;currentUser:{role:string}}){
  const tr=lang==="tr", [tab,setTab]=useState<"overview"|"sources"|"rules"|"runs">("overview"), [sources,setSources]=useState<Source[]>([]), [rules,setRules]=useState<Rule[]>([]), [runs,setRuns]=useState<Run[]>([]), [busy,setBusy]=useState(""), [message,setMessage]=useState(""), [sourceOpen,setSourceOpen]=useState(false), [ruleOpen,setRuleOpen]=useState(false);
  const [source,setSource]=useState({name:"",vendor:"Generic REST / JSON API",category:"Work & Custom",driver:"rest-json",baseUrl:"",authType:"bearer",headerName:"x-api-key",secret:""});
  const [rule,setRule]=useState({name:"",sourceId:"",controlRefs:"",jsonPath:"",operator:"exists",expected:"",schedule:"daily"});
  async function load(){const r=await fetch(withBasePath("/api/evidence-automation"),{cache:"no-store"});if(r.ok){const j=await r.json();setSources(j.sources||[]);setRules(j.rules||[]);setRuns(j.runs||[])}}
  useEffect(()=>{let live=true;fetch(withBasePath("/api/evidence-automation"),{cache:"no-store"}).then(r=>r.ok?r.json():null).then(j=>{if(live&&j){setSources(j.sources||[]);setRules(j.rules||[]);setRuns(j.runs||[])}}).catch(()=>{});return()=>{live=false}},[]);
  const stats=useMemo(()=>({healthy:sources.filter(x=>x.lastTestStatus==="success").length,active:rules.filter(x=>x.enabled).length,pass:runs.filter(x=>x.status==="pass").length,review:runs.filter(x=>x.status!=="pass").length}),[sources,rules,runs]);
  async function api(body:Record<string,unknown>){setBusy(String(body.action||"save"));setMessage("");const r=await fetch(withBasePath("/api/evidence-automation"),{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)}),j=await r.json().catch(()=>({}));setBusy("");setMessage(r.ok?(j.message||(tr?"İşlem tamamlandı.":"Completed.")):(j.error||(tr?"İşlem başarısız.":"Operation failed.")));if(r.ok)await load();return r.ok}
  async function saveSource(e:FormEvent){e.preventDefault();if(await api({action:"save-source",...source})){setSourceOpen(false);setSource({...source,name:"",baseUrl:"",secret:""})}}
  async function saveRule(e:FormEvent){e.preventDefault();if(await api({action:"save-rule",...rule})){setRuleOpen(false);setRule({...rule,name:"",controlRefs:"",jsonPath:"",expected:""})}}
  function pick(entry:typeof catalog[number]){setSource({name:entry[1],vendor:entry[1],category:entry[0],driver:entry[2],baseUrl:"",authType:"bearer",headerName:"x-api-key",secret:""});setSourceOpen(true)}
  return <section className="ea-page">
    <div className="ea-hero"><div><small>{tr?"SÜREKLİ GÜVENCE":"CONTINUOUS ASSURANCE"}</small><h2>{tr?"Kanıt Otomasyonu":"Evidence Automation"}</h2><p>{tr?"Her üreticiden API kanıtı topla, kuralla doğrula ve kontrol maddelerine otomatik bağla.":"Collect API evidence from any vendor, validate it with rules and map it to controls automatically."}</p></div><div className="ea-hero-actions"><span className="ea-live"><i/>{tr?"Collector hazır":"Collector ready"}</span>{currentUser.role==="Admin"&&<button className="primary" onClick={()=>setSourceOpen(true)}>+ {tr?"Kaynak Ekle":"Add Source"}</button>}</div></div>
    {message&&<div className="ea-message" onClick={()=>setMessage("")}>{message}<b>×</b></div>}
    <div className="ea-stats"><Metric value={sources.length} label={tr?"Bağlı kaynak":"Connected sources"}/><Metric value={stats.active} label={tr?"Aktif kural":"Active rules"}/><Metric value={stats.pass} label={tr?"Başarılı doğrulama":"Passed validations"}/><Metric value={stats.review} label={tr?"İnceleme gerekli":"Needs review"}/></div>
    <div className="ea-tabs">{(["overview","sources","rules","runs"] as const).map(x=><button key={x} className={tab===x?"active":""} onClick={()=>setTab(x)}>{x==="overview"?(tr?"Connector Kataloğu":"Connector Catalog"):x==="sources"?(tr?"Kanıt Kaynakları":"Evidence Sources"):x==="rules"?(tr?"Toplama Kuralları":"Collection Rules"):(tr?"Çalıştırma Geçmişi":"Run History")}</button>)}</div>
    {tab==="overview"&&<div className="ea-catalog">{Array.from(new Set(catalog.map(x=>x[0]))).map(group=><article key={group}><header><h3>{group}</h3><span>{catalog.filter(x=>x[0]===group).length}</span></header><div>{catalog.filter(x=>x[0]===group).map(entry=><button key={entry[1]} onClick={()=>pick(entry)}><b>{entry[1]}</b><small>{entry[2]==="https-bridge"?(tr?"Şirket içi köprü":"On-prem bridge"):(tr?"API şablonu":"API template")}</small><i>+</i></button>)}</div></article>)}</div>}
    {tab==="sources"&&<DataTable empty={tr?"Henüz kanıt kaynağı eklenmedi.":"No evidence source yet."} heads={[tr?"Kaynak":"Source",tr?"Kategori":"Category",tr?"Sürücü":"Driver",tr?"Son test":"Last test",tr?"Durum":"Status",""]} rows={sources.map(x=>[<span key="source"><b>{x.name}</b><small>{x.vendor}</small></span>,x.category,x.driver,x.lastTestAt?new Date(x.lastTestAt).toLocaleString():"—",<Status key="status" value={x.lastTestStatus||"not-tested"}/>,<button key="test" className="ghost" disabled={!!busy} onClick={()=>api({action:"test-source",sourceId:x.id})}>{tr?"Bağlantıyı Test Et":"Test Connection"}</button>])}/>} 
    {tab==="rules"&&<><div className="ea-section-action"><p>{tr?"API yanıtındaki alanı bir eşik ile değerlendir ve sonucu birden fazla ISO, SOC 2, PCI DSS veya özel kontrol maddesine bağla.":"Evaluate an API response field against a threshold and map it to multiple controls."}</p>{currentUser.role!=="Viewer"&&<button className="primary" onClick={()=>setRuleOpen(true)}>+ {tr?"Kural Ekle":"Add Rule"}</button>}</div><DataTable empty={tr?"Henüz toplama kuralı yok.":"No collection rule yet."} heads={[tr?"Kural":"Rule",tr?"Kaynak":"Source",tr?"Kontroller":"Controls",tr?"Doğrulama":"Validation",tr?"Zamanlama":"Schedule",""]} rows={rules.map(x=>[<span key="rule"><b>{x.name}</b><small>{x.lastRunAt?new Date(x.lastRunAt).toLocaleString():tr?"Henüz çalışmadı":"Never run"}</small></span>,sources.find(s=>s.id===x.sourceId)?.name||"—",x.controlRefs||"—",`${x.jsonPath||"$"} ${x.operator} ${x.expected}`,x.schedule,<button key="run" className="primary" disabled={!!busy} onClick={()=>api({action:"run-rule",ruleId:x.id})}>{tr?"Şimdi Topla":"Collect Now"}</button>])}/></>}
    {tab==="runs"&&<DataTable empty={tr?"Henüz çalıştırma kaydı yok.":"No collection runs yet."} heads={[tr?"Kural":"Rule",tr?"Kaynak":"Source",tr?"Sonuç":"Result",tr?"Puan":"Score",tr?"Açıklama":"Detail",tr?"Zaman":"Time"]} rows={runs.map(x=>[x.ruleName,x.sourceName,<Status key="status" value={x.status}/>,`${x.score}/100`,x.detail,new Date(x.createdAt).toLocaleString()])}/>} 
    {sourceOpen&&<Modal title={tr?"Kanıt kaynağı ekle":"Add evidence source"} onClose={()=>setSourceOpen(false)}><form className="ea-form" onSubmit={saveSource}><label>{tr?"Kaynak adı":"Source name"}<input required value={source.name} onChange={e=>setSource({...source,name:e.target.value})}/></label><label>{tr?"Kategori":"Category"}<select value={source.category} onChange={e=>setSource({...source,category:e.target.value})}>{Array.from(new Set(catalog.map(x=>x[0]))).map(x=><option key={x}>{x}</option>)}</select></label><label className="wide">API Base URL<input required type="url" placeholder="https://api.vendor.com/v1" value={source.baseUrl} onChange={e=>setSource({...source,baseUrl:e.target.value})}/></label><label>{tr?"Kimlik doğrulama":"Authentication"}<select value={source.authType} onChange={e=>setSource({...source,authType:e.target.value})}><option value="bearer">Bearer token</option><option value="api-key">API key header</option><option value="basic">Basic auth</option><option value="none">None</option></select></label><label>{tr?"Token / API anahtarı":"Token / API key"}<input type="password" value={source.secret} onChange={e=>setSource({...source,secret:e.target.value})} placeholder={tr?"Şifreli saklanır":"Stored encrypted"}/></label><footer><button type="button" className="ghost" onClick={()=>setSourceOpen(false)}>{tr?"Vazgeç":"Cancel"}</button><button className="primary" disabled={!!busy}>{tr?"Kaynağı Kaydet":"Save Source"}</button></footer></form></Modal>}
    {ruleOpen&&<Modal title={tr?"Toplama ve doğrulama kuralı":"Collection and validation rule"} onClose={()=>setRuleOpen(false)}><form className="ea-form" onSubmit={saveRule}><label className="wide">{tr?"Kural adı":"Rule name"}<input required value={rule.name} onChange={e=>setRule({...rule,name:e.target.value})}/></label><label>{tr?"Kanıt kaynağı":"Evidence source"}<select required value={rule.sourceId} onChange={e=>setRule({...rule,sourceId:e.target.value})}><option value="">—</option>{sources.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>{tr?"Zamanlama":"Schedule"}<select value={rule.schedule} onChange={e=>setRule({...rule,schedule:e.target.value})}><option value="hourly">Hourly</option><option value="daily">Daily</option><option value="weekly">Weekly</option><option value="monthly">Monthly</option></select></label><label className="wide">{tr?"Bağlı kontrol/maddeler":"Mapped controls"}<input required placeholder="CC6.1, A.5.15, PCI 8.4.2" value={rule.controlRefs} onChange={e=>setRule({...rule,controlRefs:e.target.value})}/></label><label>JSON path<input placeholder="data.compliantPercentage" value={rule.jsonPath} onChange={e=>setRule({...rule,jsonPath:e.target.value})}/></label><label>{tr?"Operatör":"Operator"}<select value={rule.operator} onChange={e=>setRule({...rule,operator:e.target.value})}><option value="exists">exists</option><option value="eq">equals</option><option value="gte">≥</option><option value="lte">≤</option><option value="contains">contains</option></select></label><label className="wide">{tr?"Beklenen değer":"Expected value"}<input value={rule.expected} onChange={e=>setRule({...rule,expected:e.target.value})}/></label><footer><button type="button" className="ghost" onClick={()=>setRuleOpen(false)}>{tr?"Vazgeç":"Cancel"}</button><button className="primary" disabled={!!busy}>{tr?"Kuralı Kaydet":"Save Rule"}</button></footer></form></Modal>}
  </section>
}

function Metric({value,label}:{value:number;label:string}){return <div><b>{value}</b><span>{label}</span></div>}
function Status({value}:{value:string}){const label=value==="pass"?"Uygun":value==="fail"?"Başarısız":value==="success"?"Bağlı":value==="error"?"Hata":"Test edilmedi";return <span className={`ea-status ${value}`}>{label}</span>}
function DataTable({heads,rows,empty}:{heads:string[];rows:React.ReactNode[][];empty:string}){return <div className="ea-table"><div className="table-wrap"><table><thead><tr>{heads.map((x,i)=><th key={`${x}-${i}`}>{x}</th>)}</tr></thead><tbody>{rows.length?rows.map((row,i)=><tr key={i}>{row.map((cell,j)=><td key={j}>{cell}</td>)}</tr>):<tr><td colSpan={heads.length} className="empty">{empty}</td></tr>}</tbody></table></div></div>}
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){return <div className="overlay" onMouseDown={onClose}><div className="modal ea-modal" onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><div><small>FORNOST COLLECTOR</small><h2>{title}</h2></div><button onClick={onClose}>×</button></div>{children}</div></div>}
