"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
import {withBasePath} from "./base-path";
import {addDays,findingSlaDays} from "./findings/domain";
import "./findings-center.css";
type Lang="tr"|"en";
type Finding={id:string;code:string;sourceType:string;sourceRef:string;sourceTitle:string;findingType:string;title:string;description:string;severity:string;owner:string;reviewer:string;rootCause:string;correctiveAction:string;preventiveAction:string;dueDate:string;status:string;riskRef?:string;controlRef?:string;acceptUntil?:string;acceptanceRationale?:string;recurrenceCount:number;attention:string;updatedAt:string};
type Summary={total:number;open:number;critical:number;overdue:number;verification:number;accepted:number;closed:number;recurring:number};
type FindingsPayload={findings?:Finding[];events?:Array<Record<string,string>>;sourceSignals?:Array<{source:string;count:number}>;summary?:Summary};
const emptySummary:Summary={total:0,open:0,critical:0,overdue:0,verification:0,accepted:0,closed:0,recurring:0};
const today=()=>new Date().toISOString().slice(0,10),emptyForm=(email:string)=>({sourceType:"audit",sourceRef:"",sourceTitle:"",findingType:"nonconformity",title:"",description:"",severity:"high",owner:email,reviewer:"",rootCause:"",correctiveAction:"",preventiveAction:"",dueDate:addDays(today(),30),riskRef:"",controlRef:""});
const phrases:Record<string,string>={start:"CAPA AKSİYONUNU BAŞLAT",submit:"CAPA DOĞRULAMAYA GÖNDER",verify:"BULGUYU KAPAT",reopen:"BULGUYU YENİDEN AÇ","accept-risk":"BULGU RİSKİNİ KABUL ET"};
export default function FindingsCenter({lang,currentUser}:{lang:Lang;currentUser:{role:string;email:string}}){
 const tr=lang==="tr",[findings,setFindings]=useState<Finding[]>([]),[events,setEvents]=useState<Array<Record<string,string>>>([]),[signals,setSignals]=useState<Array<{source:string;count:number}>>([]),[summary,setSummary]=useState<Summary>(emptySummary),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[query,setQuery]=useState(""),[filter,setFilter]=useState("all"),[form,setForm]=useState<Record<string,string>|null>(null),[selected,setSelected]=useState<Finding|null>(null),[action,setAction]=useState<{finding:Finding;operation:string;note:string;evidenceReference:string;evidenceSha256:string;confirmation:string;acceptUntil:string;acceptanceRationale:string}|null>(null);
 const apply=(body:FindingsPayload)=>{setFindings(body.findings||[]);setEvents(body.events||[]);setSignals(body.sourceSignals||[]);setSummary(body.summary||emptySummary)};
 async function load(){const response=await fetch(withBasePath("/api/findings"),{cache:"no-store"});if(response.ok)apply(await response.json())}
 useEffect(()=>{let active=true;fetch(withBasePath("/api/findings"),{cache:"no-store"}).then(x=>x.ok?x.json():null).then(body=>{if(active&&body)apply(body)}).catch(()=>{});return()=>{active=false}},[]);
 async function api(body:Record<string,unknown>){setBusy(true);setNotice("");try{const response=await fetch(withBasePath("/api/findings"),{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)}),result=await response.json().catch(()=>({}));setNotice(response.ok?(result.message||(tr?"İşlem tamamlandı.":"Completed.")):(result.error||(tr?"İşlem başarısız.":"Operation failed.")));if(response.ok)await load();return response.ok}catch{setNotice(tr?"Sunucuya ulaşılamadı.":"Server unavailable.");return false}finally{setBusy(false)}}
 async function create(event:FormEvent){event.preventDefault();if(form&&await api({action:"create",...form}))setForm(null)}
 const startAction=(finding:Finding,operation:string)=>setAction({finding,operation,note:"",evidenceReference:"",evidenceSha256:"",confirmation:"",acceptUntil:addDays(today(),90),acceptanceRationale:""});
 async function transition(){if(!action)return;if(await api({action:"transition",findingId:action.finding.id,...action})){setAction(null);setSelected(null)}}
 const filtered=useMemo(()=>findings.filter(x=>(filter==="all"||x.attention===filter||x.status===filter)&&`${x.code} ${x.title} ${x.sourceRef} ${x.owner}`.toLocaleLowerCase("tr").includes(query.toLocaleLowerCase("tr"))),[findings,filter,query]),format=(value?:string)=>value?new Intl.DateTimeFormat(tr?"tr-TR":"en-GB",{dateStyle:"medium"}).format(new Date(`${value.slice(0,10)}T12:00:00Z`)):"—";
 return <section className="finding-page">
  <div className="finding-hero"><div><small>ENTERPRISE FINDINGS · ROOT CAUSE · CAPA · ASSURANCE</small><h2>{tr?"Bulgular ve CAPA Merkezi":"Findings & CAPA Center"}</h2><p>{tr?"Denetim, kontrol, tedarikçi, regülasyon, risk ve güvenlik bulgularını tek sahiplik, SLA, kök neden ve bağımsız kanıt doğrulama zincirinde yönetin.":"Govern audit, control, vendor, regulatory, risk and security findings through one ownership, SLA, root-cause and independent evidence chain."}</p></div><div>{currentUser.role==="Admin"&&<a href={withBasePath("/api/findings?format=csv")}>CAPA CSV</a>}{currentUser.role!=="Viewer"&&<button onClick={()=>setForm(emptyForm(currentUser.email))}>+ {tr?"Yeni Bulgu":"New Finding"}</button>}</div></div>
  {notice&&<button className="finding-notice" onClick={()=>setNotice("")}>{notice}<b>×</b></button>}
  <div className="finding-kpis">{[[summary.open,tr?"Açık CAPA":"Open CAPA"],[summary.critical,tr?"Kritik":"Critical"],[summary.overdue,tr?"Gecikmiş":"Overdue"],[summary.verification,tr?"Doğrulamada":"Verification"],[summary.accepted,tr?"Risk kabulü":"Accepted risk"],[summary.recurring,tr?"Tekrarlayan":"Recurring"]].map(([value,label])=><article key={String(label)}><small>{label}</small><strong>{value}</strong></article>)}</div>
  <div className="finding-source-strip"><div><small>{tr?"BAĞLI KAYNAK KUYRUĞU":"CONNECTED SOURCE QUEUE"}</small><b>{tr?"Dağınık bulguları kurumsal CAPA kaydına dönüştürün":"Convert distributed findings into governed CAPA records"}</b></div>{signals.map(x=><span key={x.source}><b>{x.count}</b><small>{x.source}</small></span>)}</div>
  <div className="finding-toolbar"><input aria-label={tr?"Bulgu ara":"Search findings"} placeholder={tr?"Kod, başlık, kaynak veya sahip ara…":"Search code, title, source or owner…"} value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label={tr?"Durum filtresi":"Status filter"} value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">{tr?"Tüm kayıtlar":"All records"}</option><option value="priority">{tr?"Öncelikli":"Priority"}</option><option value="overdue">{tr?"Gecikmiş":"Overdue"}</option><option value="verification">{tr?"Doğrulamada":"Verification"}</option><option value="accepted">{tr?"Risk kabulü":"Accepted risk"}</option><option value="closed">{tr?"Kapalı":"Closed"}</option></select><span>{filtered.length} / {summary.total}</span></div>
  <div className="finding-table-wrap"><table className="finding-table"><thead><tr><th>{tr?"Bulgu":"Finding"}</th><th>{tr?"Kaynak":"Source"}</th><th>{tr?"Önem":"Severity"}</th><th>{tr?"Sahip":"Owner"}</th><th>{tr?"Termin":"Due"}</th><th>{tr?"Durum":"Status"}</th></tr></thead><tbody>{filtered.map(x=><tr key={x.id} onClick={()=>setSelected(x)}><td><b>{x.title}</b><small>{x.code} · {x.findingType}{x.recurrenceCount?` · ↻ ${x.recurrenceCount}`:""}</small></td><td><b>{x.sourceType}</b><small>{x.sourceRef} · {x.sourceTitle}</small></td><td><span className={`finding-badge ${x.severity}`}>{x.severity}</span></td><td><b>{x.owner}</b><small>{tr?"Reviewer":"Reviewer"}: {x.reviewer}</small></td><td><b>{format(x.dueDate)}</b><small className={x.attention==="overdue"||x.attention==="acceptance-expired"?"danger":""}>{x.attention}</small></td><td><span className={`finding-state ${x.status}`}>{x.status}</span></td></tr>)}</tbody></table>{!filtered.length&&<div className="finding-empty">{tr?"Filtreyle eşleşen bulgu yok.":"No findings match the filter."}</div>}</div>
  {selected&&<div className="finding-overlay" onMouseDown={()=>setSelected(null)}><article className="finding-detail" onMouseDown={e=>e.stopPropagation()}><header><div><small>{selected.code} · {selected.sourceType}/{selected.sourceRef}</small><h3>{selected.title}</h3></div><button onClick={()=>setSelected(null)}>×</button></header><div className="finding-detail-grid"><section><small>{tr?"BULGU":"FINDING"}</small><p>{selected.description}</p><dl><div><dt>{tr?"Kök neden":"Root cause"}</dt><dd>{selected.rootCause}</dd></div><div><dt>{tr?"Düzeltici aksiyon":"Corrective action"}</dt><dd>{selected.correctiveAction}</dd></div><div><dt>{tr?"Önleyici aksiyon":"Preventive action"}</dt><dd>{selected.preventiveAction}</dd></div></dl></section><aside><small>{tr?"YÖNETİŞİM":"GOVERNANCE"}</small><b>{selected.severity} · {selected.status}</b><span>{tr?"Termin":"Due"}: {format(selected.dueDate)}</span><span>{tr?"Risk":"Risk"}: {selected.riskRef||"—"}</span><span>{tr?"Kontrol":"Control"}: {selected.controlRef||"—"}</span>{selected.acceptUntil&&<span>{tr?"Kabul bitişi":"Acceptance expiry"}: {format(selected.acceptUntil)}</span>}</aside></div><footer>{selected.status==="open"&&<button onClick={()=>startAction(selected,"start")}>{tr?"CAPA'yı başlat":"Start CAPA"}</button>}{["open","in-progress"].includes(selected.status)&&currentUser.role==="Admin"&&<button className="secondary" onClick={()=>startAction(selected,"accept-risk")}>{tr?"Riski kabul et":"Accept risk"}</button>}{selected.status==="in-progress"&&<button onClick={()=>startAction(selected,"submit")}>{tr?"Doğrulamaya gönder":"Submit for verification"}</button>}{selected.status==="verification"&&currentUser.role==="Admin"&&<button onClick={()=>startAction(selected,"verify")}>{tr?"Doğrula ve kapat":"Verify & close"}</button>}{["verification","closed","accepted"].includes(selected.status)&&currentUser.role==="Admin"&&<button className="secondary" onClick={()=>startAction(selected,"reopen")}>{tr?"Yeniden aç":"Reopen"}</button>}</footer></article></div>}
  {form&&<div className="finding-overlay"><form className="finding-form" onSubmit={create}><header><div><small>CONTROLLED CAPA RECORD</small><h3>{tr?"Yeni kurumsal bulgu":"New enterprise finding"}</h3></div><button type="button" onClick={()=>setForm(null)}>×</button></header><div className="finding-form-grid"><label>{tr?"Kaynak türü":"Source type"}<select value={form.sourceType} onChange={e=>setForm({...form,sourceType:e.target.value})}>{["audit","control","vendor","regulatory","risk","policy","incident","vulnerability","ai","manual"].map(x=><option key={x}>{x}</option>)}</select></label><label>{tr?"Bulgu türü":"Finding type"}<select value={form.findingType} onChange={e=>setForm({...form,findingType:e.target.value})}>{["nonconformity","control-deficiency","observation","vulnerability","incident-action","improvement"].map(x=><option key={x}>{x}</option>)}</select></label><Field label={tr?"Kaynak referansı":"Source reference"} name="sourceRef" form={form} setForm={setForm}/><Field label={tr?"Kaynak başlığı":"Source title"} name="sourceTitle" form={form} setForm={setForm}/><Field wide label={tr?"Bulgu başlığı":"Finding title"} name="title" form={form} setForm={setForm}/><Field wide area label={tr?"Açıklama":"Description"} name="description" form={form} setForm={setForm}/><label>{tr?"Önem":"Severity"}<select value={form.severity} onChange={e=>{const severity=e.target.value;setForm({...form,severity,dueDate:addDays(today(),findingSlaDays(severity))})}}>{["low","medium","high","critical"].map(x=><option key={x}>{x}</option>)}</select></label><Field type="date" label={tr?"SLA termini":"SLA due date"} name="dueDate" form={form} setForm={setForm}/><Field label={tr?"Aksiyon sahibi e-posta":"Action owner email"} name="owner" form={form} setForm={setForm}/><Field label={tr?"Bağımsız reviewer e-posta":"Independent reviewer email"} name="reviewer" form={form} setForm={setForm}/><Field wide area label={tr?"Kök neden":"Root cause"} name="rootCause" form={form} setForm={setForm}/><Field wide area label={tr?"Düzeltici aksiyon":"Corrective action"} name="correctiveAction" form={form} setForm={setForm}/><Field wide area label={tr?"Önleyici aksiyon":"Preventive action"} name="preventiveAction" form={form} setForm={setForm}/><Field label={tr?"Risk referansı":"Risk reference"} name="riskRef" form={form} setForm={setForm}/><Field label={tr?"Kontrol referansı":"Control reference"} name="controlRef" form={form} setForm={setForm}/></div><footer><button type="button" className="secondary" onClick={()=>setForm(null)}>{tr?"İptal":"Cancel"}</button><button disabled={busy}>{tr?"Bulgu ve CAPA oluştur":"Create finding & CAPA"}</button></footer></form></div>}
  {action&&<div className="finding-overlay"><article className="finding-action"><header><div><small>{action.finding.code}</small><h3>{action.finding.title}</h3></div><button onClick={()=>setAction(null)}>×</button></header><p>{tr?"İşlem, değişmez denetim izine aktör ve kanıt bilgisiyle yazılır.":"The action is written to the immutable audit trail with actor and evidence."}</p><label>{tr?"Açıklama":"Note"}<textarea value={action.note} onChange={e=>setAction({...action,note:e.target.value})}/></label>{["submit","verify","accept-risk"].includes(action.operation)&&<><label>{tr?"Kanıt referansı":"Evidence reference"}<input value={action.evidenceReference} onChange={e=>setAction({...action,evidenceReference:e.target.value})}/></label><label>SHA-256<input value={action.evidenceSha256} maxLength={64} onChange={e=>setAction({...action,evidenceSha256:e.target.value})}/></label></>}{action.operation==="accept-risk"&&<><label>{tr?"Kabul bitişi":"Acceptance expiry"}<input type="date" value={action.acceptUntil} onChange={e=>setAction({...action,acceptUntil:e.target.value})}/></label><label>{tr?"Risk kabul gerekçesi":"Risk acceptance rationale"}<textarea value={action.acceptanceRationale} onChange={e=>setAction({...action,acceptanceRationale:e.target.value})}/></label></>}<label>{tr?"Onay ifadesi":"Confirmation phrase"}<input value={action.confirmation} onChange={e=>setAction({...action,confirmation:e.target.value})}/><small>{phrases[action.operation]}</small></label><footer><button className="secondary" onClick={()=>setAction(null)}>{tr?"İptal":"Cancel"}</button><button disabled={busy} onClick={()=>void transition()}>{tr?"İşlemi uygula":"Apply action"}</button></footer></article></div>}
  {events.length>0&&<details className="finding-history"><summary>{tr?"Son denetim izi olayları":"Recent audit trail events"}</summary>{events.slice(0,20).map(x=><div key={x.id}><b>{x.action}</b><span>{x.findingId} · {x.actor}</span><small>{x.detail}</small></div>)}</details>}
 </section>
}
function Field({label,name,form,setForm,wide=false,area=false,type="text"}:{label:string;name:string;form:Record<string,string>;setForm:(x:Record<string,string>)=>void;wide?:boolean;area?:boolean;type?:string}){return <label className={wide?"wide":""}>{label}{area?<textarea value={form[name]} onChange={e=>setForm({...form,[name]:e.target.value})}/>:<input type={type} value={form[name]} onChange={e=>setForm({...form,[name]:e.target.value})}/>}</label>}
