"use client";
import {FormEvent,useCallback,useEffect,useRef,useState} from "react";
import {withBasePath} from "./base-path";
import {FINDING_SOURCES,addDays,findingSlaDays} from "./findings/domain";
import "./findings-center.css";
import {findingsRequest,validFindingsPayload,validFindingPagination,type FindingPagination} from "./findings/workspace";
import FindingControlContextPanel from "./findings/control-context-panel";
import FindingHistoryPanel from "./findings/history-panel";
import {loadCapaReport,capaReportFailure,capaReportFailureMessage,CAPA_REPORT_MODULE} from "./findings/reporting";
import {buildReportCsv,downloadBlob,reportMetrics} from "./report-export";
import {FORNOST_FOCUS_EVENT,peekPendingFornostFocus,consumePendingFornostFocus,type FornostNavigationRequest} from "./navigation-focus";
import {sameDomainModule} from "./domain-identity";
type Lang="tr"|"en";
type Finding={id:string;code:string;sourceType:string;sourceRef:string;sourceTitle:string;findingType:string;title:string;description:string;severity:string;owner:string;reviewer:string;rootCause:string;correctiveAction:string;preventiveAction:string;dueDate:string;status:string;riskRef?:string;controlRef?:string;acceptUntil?:string;acceptanceRationale?:string;recurrenceCount:number;attention:string;updatedAt:string};
type Summary={total:number;open:number;critical:number;overdue:number;verification:number;accepted:number;closed:number;recurring:number};
type FindingsPayload={pagination?:FindingPagination;findings?:Finding[];events?:Array<Record<string,string>>;sourceSignals?:Array<{source:string;count:number;available?:boolean}>;summary?:Summary};
const emptySummary:Summary={total:0,open:0,critical:0,overdue:0,verification:0,accepted:0,closed:0,recurring:0};
const manualFindingSources=FINDING_SOURCES.filter(source=>source!=="continuous-control");
const today=()=>new Date().toISOString().slice(0,10),emptyForm=(email:string)=>({sourceType:"audit",sourceRef:"",sourceTitle:"",findingType:"nonconformity",title:"",description:"",severity:"high",owner:email,reviewer:"",rootCause:"",correctiveAction:"",preventiveAction:"",dueDate:addDays(today(),30),riskRef:"",controlRef:""});
const phrases:Record<string,string>={start:"CAPA AKSİYONUNU BAŞLAT",submit:"CAPA DOĞRULAMAYA GÖNDER",verify:"BULGUYU KAPAT",reopen:"BULGUYU YENİDEN AÇ","accept-risk":"BULGU RİSKİNİ KABUL ET"};
export default function FindingsCenter({lang,currentUser}:{lang:Lang;currentUser:{role:string;email:string}}){
 const tr=lang==="tr",[findings,setFindings]=useState<Finding[]>([]),[events,setEvents]=useState<Array<Record<string,string>>>([]),[signals,setSignals]=useState<Array<{source:string;count:number;available?:boolean}>>([]),[summary,setSummary]=useState<Summary>(emptySummary),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[query,setQuery]=useState(""),[filter,setFilter]=useState("all"),[form,setForm]=useState<Record<string,string>|null>(null),[selected,setSelected]=useState<Finding|null>(null),[action,setAction]=useState<{finding:Finding;operation:string;note:string;evidenceReference:string;evidenceSha256:string;confirmation:string;acceptUntil:string;acceptanceRationale:string}|null>(null);
 const [focusRef,setFocusRef]=useState(""),[focusNonce,setFocusNonce]=useState(0);
 const [pagination,setPagination]=useState<FindingPagination>({page:1,pages:1,total:0,start:0,end:0});
 const [loading,setLoading]=useState(true),[loadError,setLoadError]=useState(false),[page,setPage]=useState(1);
 const [exporting,setExporting]=useState(false),[exportLoaded,setExportLoaded]=useState(0);
 const exportController=useRef<AbortController|null>(null);
 useEffect(()=>()=>exportController.current?.abort(),[]);
 const autoOpenRef=useRef<string|null>(null);
 const loadController=useRef<AbortController|null>(null),writeController=useRef<AbortController|null>(null),sending=useRef(false);
 const load=useCallback(async()=>{
  loadController.current?.abort();const controller=new AbortController();loadController.current=controller;
  setLoading(true);setLoadError(false);
  try {
   const {response,body}=await findingsRequest(withBasePath("/api/findings?"+new URLSearchParams({view:"register",q:query,filter,page:String(page),lang,...(focusRef?{ref:focusRef}:{})})),{cache:"no-store",signal:controller.signal});
   if(!response.ok||!validFindingsPayload(body)||!validFindingPagination(body.pagination,Array.isArray(body.findings)?body.findings.length:0))throw new Error("Findings unavailable");
   if(controller.signal.aborted)return;
   const data=body as FindingsPayload;
   setPagination(data.pagination!);setFindings(data.findings||[]);setEvents(data.events||[]);setSignals(data.sourceSignals||[]);setSummary(data.summary||emptySummary);
   const openFocused=!!focusRef&&autoOpenRef.current===focusRef;if(openFocused)autoOpenRef.current=null;
   setSelected(previous=>openFocused?(data.findings||[])[0]||null:previous?(data.findings||[]).find(item=>item.id===previous.id)||null:null);
  }catch{if(!controller.signal.aborted)setLoadError(true);}
  finally{if(!controller.signal.aborted)setLoading(false);}
 },[query,filter,page,lang,focusRef]);
 useEffect(()=>{const timer=setTimeout(()=>void load(),200);return()=>{clearTimeout(timer);loadController.current?.abort();};},[load,focusNonce]);
 useEffect(()=>{const writes=writeController;return()=>writes.current?.abort();},[]);
 useEffect(()=>{
  const accept=(request:FornostNavigationRequest|null)=>{
   if(!request||!sameDomainModule(request.module,"Bulgular ve CAPA")||sending.current)return;
   const ref=request.filter?.findingRef||request.filter?.recordRef||request.ref||"";
   if(!ref||ref.length>200||/\p{Cc}/u.test(ref))return;
   autoOpenRef.current=ref;consumePendingFornostFocus("Bulgular ve CAPA");loadController.current?.abort();setSelected(null);setAction(null);setForm(null);setLoading(true);setLoadError(false);setFocusRef(ref);setFocusNonce(value=>value+1);setQuery("");setFilter("all");setPage(1);
  };
  accept(peekPendingFornostFocus());
  const listener=(event:Event)=>accept((event as CustomEvent<FornostNavigationRequest>).detail);
  window.addEventListener(FORNOST_FOCUS_EVENT,listener);return()=>window.removeEventListener(FORNOST_FOCUS_EVENT,listener);
 },[]);

 async function api(body:Record<string,unknown>){
  if(sending.current||loading||loadError||!["Admin","Editor"].includes(currentUser.role))return false;
  sending.current=true;setBusy(true);setNotice("");
  const controller=new AbortController();writeController.current=controller;
  const uncertain=()=>{setNotice(tr?"İşlem sonucu doğrulanamadı. Tekrar göndermeden önce yenilenen listeyi kontrol edin.":"The result could not be confirmed. Check the refreshed list before submitting again.");setForm(null);setAction(null);setSelected(null);};
  try{
   const {response,body:result}=await findingsRequest(withBasePath("/api/findings"),{method:"POST",headers:{"content-type":"application/json"},signal:controller.signal,body:JSON.stringify(body)});
   if(controller.signal.aborted)return false;
   if(response.status>=500){uncertain();await load();return false;}
   setNotice(response.ok?(typeof result.message==="string"?result.message:(tr?"İşlem tamamlandı.":"Completed.")):(typeof result.error==="string"?result.error:(tr?"İşlem başarısız.":"Operation failed.")));
   if(response.ok||response.status===409){setAction(null);setSelected(null);await load();}
   return response.ok;
  }catch{if(!controller.signal.aborted){uncertain();await load();}return false;}
  finally{sending.current=false;if(!controller.signal.aborted)setBusy(false);}
 }
 async function exportCsv(){
  if(exportController.current||loading||loadError)return;
  const controller=new AbortController();exportController.current=controller;setExporting(true);setExportLoaded(0);setNotice("");
  try{
   const rows=await loadCapaReport(withBasePath("/api/findings?format=report"),controller.signal,fetch,count=>{if(!controller.signal.aborted)setExportLoaded(count);});
   if(controller.signal.aborted)return;
   const csv=buildReportCsv(tr?"Tüm Bulgular ve CAPA":"All Findings & CAPA",rows,reportMetrics(CAPA_REPORT_MODULE,rows,tr),tr,{template:"detailed",preparedBy:currentUser.email,scope:tr?"Tüm merkezi CAPA kayıtları; ekran araması ve durum filtresi uygulanmaz.":"All canonical CAPA records; screen search and status filters are not applied."});
   downloadBlob("fornost-findings-capa.csv",new Blob([csv],{type:"text/csv;charset=utf-8"}));
  }catch(error){if(!controller.signal.aborted)setNotice(capaReportFailureMessage(capaReportFailure(error),tr));}
  finally{exportController.current=null;if(!controller.signal.aborted)setExporting(false);}
 }
 async function create(event:FormEvent){event.preventDefault();if(form&&await api({action:"create",...form}))setForm(null)}
 const startAction=(finding:Finding,operation:string)=>{if(loading||loadError||sending.current)return;setAction({finding,operation,note:"",evidenceReference:"",evidenceSha256:"",confirmation:"",acceptUntil:addDays(today(),90),acceptanceRationale:""});};
 async function transition(){if(!action)return;const {finding,...decision}=action;if(await api({action:"transition",findingId:finding.id,expectedUpdatedAt:finding.updatedAt,...decision})){setAction(null);setSelected(null)}}
 const listing={...pagination,rows:findings};
 const changeScope=()=>{autoOpenRef.current=null;loadController.current?.abort();setFocusRef("");setLoading(true);setSelected(null);};
 const format=(value?:string)=>{if(!value)return "—";const date=new Date(`${value.slice(0,10)}T12:00:00Z`);return Number.isFinite(date.getTime())?new Intl.DateTimeFormat(tr?"tr-TR":"en-GB",{dateStyle:"medium"}).format(date):"—";};
 return <section className="finding-page" data-native-focus="true" aria-busy={loading||busy}>
  <div className="finding-hero"><div><small>ENTERPRISE FINDINGS · ROOT CAUSE · CAPA · ASSURANCE</small><h2>{tr?"Bulgular ve CAPA Merkezi":"Findings & CAPA Center"}</h2><p>{tr?"Denetim, kontrol, sürekli kontrol, tedarikçi, regülasyon, risk ve güvenlik bulgularını tek sahiplik, SLA, kök neden ve bağımsız kanıt doğrulama zincirinde yönetin.":"Govern audit, control, continuous-control, vendor, regulatory, risk and security findings through one ownership, SLA, root-cause and independent evidence chain."}</p></div><div>{currentUser.role==="Admin"&&<button type="button" disabled={exporting||loading||loadError} onClick={()=>void exportCsv()}>{exporting?`${tr?"Yükleniyor":"Loading"}… ${exportLoaded}`:(tr?"Tüm CAPA · CSV":"All CAPA · CSV")}</button>}{["Admin","Editor"].includes(currentUser.role)&&<button disabled={loading||loadError||busy} onClick={()=>setForm(emptyForm(currentUser.email))}>+ {tr?"Yeni Bulgu":"New Finding"}</button>}</div></div>
  <div className="finding-load-status" role={loadError?"alert":"status"}><span>{loading?(tr?"Bulgular yükleniyor…":"Loading findings…"):loadError?(tr?"Bulgular alınamadı. Gösterilen kayıtlar güncel olmayabilir; işlem yapmadan önce yeniden deneyin.":"Findings could not be loaded. Displayed records may be stale; retry before making changes."):(tr?"Kayıtlar güncel":"Records are up to date")}</span><button type="button" disabled={loading||busy} onClick={()=>void load()}>{loadError?(tr?"Yeniden dene":"Retry"):(tr?"Yenile":"Refresh")}</button></div>
  {focusRef&&<div className="finding-load-status" role="status"><span>{tr?"Seçilen bulgu":"Selected finding"}: {focusRef}{!loading&&(loadError||!findings.length)?(tr?" · Kayıt bulunamadı, belirsiz veya erişilemiyor.":" · Record missing, ambiguous or unavailable."):""}</span><button type="button" disabled={busy} onClick={()=>{changeScope();setQuery("");setFilter("all");setPage(1)}}>{tr?"Tüm kayıtları göster":"Show all records"}</button></div>}
  {notice&&<button className="finding-notice" onClick={()=>setNotice("")}>{notice}<b>×</b></button>}
  <div className="finding-kpis">{[[summary.open,tr?"Açık CAPA":"Open CAPA"],[summary.critical,tr?"Kritik":"Critical"],[summary.overdue,tr?"Gecikmiş":"Overdue"],[summary.verification,tr?"Doğrulamada":"Verification"],[summary.accepted,tr?"Risk kabulü":"Accepted risk"],[summary.recurring,tr?"Tekrarlayan":"Recurring"]].map(([value,label])=><article key={String(label)}><small>{label}</small><strong>{loading||loadError?"—":value}</strong></article>)}</div>
  <div className="finding-source-strip"><div><small>{tr?"BAĞLI KAYNAK KUYRUĞU":"CONNECTED SOURCE QUEUE"}</small><b>{tr?"Dağınık bulguları kurumsal CAPA kaydına dönüştürün":"Convert distributed findings into governed CAPA records"}</b></div>{signals.map(x=><span key={x.source}><b>{loading||loadError||x.available===false?"—":x.count}</b><small>{x.source}{x.available===false?(tr?" · Alınamadı":" · Unavailable"):""}</small></span>)}</div>
  <div className="finding-toolbar"><input aria-label={tr?"Bulgu ara":"Search findings"} placeholder={tr?"Kod, başlık, kaynak veya sahip ara…":"Search code, title, source or owner…"} value={query} maxLength={200} disabled={busy} onChange={e=>{changeScope();setQuery(e.target.value);setPage(1)}}/><select aria-label={tr?"Durum filtresi":"Status filter"} value={filter} disabled={busy} onChange={e=>{changeScope();setFilter(e.target.value);setPage(1)}}><option value="all">{tr?"Tüm kayıtlar":"All records"}</option><option value="priority">{tr?"Öncelikli":"Priority"}</option><option value="overdue">{tr?"Gecikmiş":"Overdue"}</option><option value="verification">{tr?"Doğrulamada":"Verification"}</option><option value="accepted">{tr?"Risk kabulü":"Accepted risk"}</option><option value="closed">{tr?"Kapalı":"Closed"}</option></select><span>{listing.total} / {summary.total}</span></div>
  <div className="finding-table-wrap"><table className="finding-table"><thead><tr><th>{tr?"Bulgu":"Finding"}</th><th>{tr?"Kaynak":"Source"}</th><th>{tr?"Önem":"Severity"}</th><th>{tr?"Sahip":"Owner"}</th><th>{tr?"Termin":"Due"}</th><th>{tr?"Durum":"Status"}</th></tr></thead><tbody>{listing.rows.map(x=><tr key={x.id} onClick={()=>{if(!loading&&!loadError)setSelected(x)}}><td><button className="finding-row-open" disabled={loading||loadError} type="button" onClick={()=>{if(!loading&&!loadError)setSelected(x)}}>{x.title}</button><small>{x.code} · {x.findingType}{x.recurrenceCount?` · ↻ ${x.recurrenceCount}`:""}</small></td><td><b>{x.sourceType}</b><small>{x.sourceRef} · {x.sourceTitle}</small></td><td><span className={`finding-badge ${x.severity}`}>{x.severity}</span></td><td><b>{x.owner}</b><small>{tr?"Reviewer":"Reviewer"}: {x.reviewer}</small></td><td><b>{format(x.dueDate)}</b><small className={x.attention==="overdue"||x.attention==="acceptance-expired"?"danger":""}>{x.attention}</small></td><td><span className={`finding-state ${x.status}`}>{x.status}</span></td></tr>)}</tbody></table>{!loading&&!loadError&&!listing.total&&<div className="finding-empty">{tr?"Filtreyle eşleşen bulgu yok.":"No findings match the filter."}</div>}</div>
  <nav className="finding-pagination" aria-label={tr?"Bulgu sayfaları":"Finding pages"}><span>{listing.start}–{listing.end} / {listing.total} · {tr?"Sayfa":"Page"} {listing.page}/{listing.pages}</span><button type="button" disabled={listing.page<=1||loading||busy} onClick={()=>{changeScope();setPage(listing.page-1)}}>{tr?"Önceki":"Previous"}</button><button type="button" disabled={listing.page>=listing.pages||loading||busy} onClick={()=>{changeScope();setPage(listing.page+1)}}>{tr?"Sonraki":"Next"}</button></nav>
  <p role="note">{tr?"Arama ve filtreler tüm merkezi CAPA kayıtlarını kapsar. Üst sayımlar ve Tüm CAPA CSV filtrelerden bağımsızdır.":"Search and filters cover all canonical CAPA records. Top counts and All CAPA CSV are independent of these filters."}</p>
  {selected&&<div className="finding-overlay" onMouseDown={()=>setSelected(null)}><article className="finding-detail" role="dialog" aria-modal="true" aria-label={selected.title} onMouseDown={e=>e.stopPropagation()}><header><div><small>{selected.code} · {selected.sourceType}/{selected.sourceRef}</small><h3>{selected.title}</h3></div><button aria-label={tr?"Kapat":"Close"} onClick={()=>setSelected(null)}>×</button></header><div className="finding-detail-grid"><section><small>{tr?"BULGU":"FINDING"}</small><p>{selected.description}</p><dl><div><dt>{tr?"Kök neden":"Root cause"}</dt><dd>{selected.rootCause}</dd></div><div><dt>{tr?"Düzeltici aksiyon":"Corrective action"}</dt><dd>{selected.correctiveAction}</dd></div><div><dt>{tr?"Önleyici aksiyon":"Preventive action"}</dt><dd>{selected.preventiveAction}</dd></div></dl></section><aside><small>{tr?"YÖNETİŞİM":"GOVERNANCE"}</small><b>{selected.severity} · {selected.status}</b><span>{tr?"Termin":"Due"}: {format(selected.dueDate)}</span><span>{tr?"Risk":"Risk"}: {selected.riskRef||"—"}</span><span>{tr?"Kontrol":"Control"}: {selected.controlRef||"—"}</span>{selected.acceptUntil&&<span>{tr?"Kabul bitişi":"Acceptance expiry"}: {format(selected.acceptUntil)}</span>}</aside></div>{selected.sourceType==="continuous-control"&&<FindingControlContextPanel key={selected.id} findingId={selected.id} lang={lang} close={()=>setSelected(null)}/>}<FindingHistoryPanel key={selected.id} findingId={selected.id} lang={lang}/><footer>{selected.status==="open"&&canActOnFinding(selected,currentUser)&&<button onClick={()=>startAction(selected,"start")}>{tr?"CAPA'yı başlat":"Start CAPA"}</button>}{["open","in-progress"].includes(selected.status)&&currentUser.role==="Admin"&&<button className="secondary" onClick={()=>startAction(selected,"accept-risk")}>{tr?"Riski kabul et":"Accept risk"}</button>}{selected.status==="in-progress"&&canActOnFinding(selected,currentUser)&&<button onClick={()=>startAction(selected,"submit")}>{tr?"Doğrulamaya gönder":"Submit for verification"}</button>}{selected.status==="verification"&&currentUser.role==="Admin"&&<button onClick={()=>startAction(selected,"verify")}>{tr?"Doğrula ve kapat":"Verify & close"}</button>}{["verification","closed","accepted"].includes(selected.status)&&currentUser.role==="Admin"&&<button className="secondary" onClick={()=>startAction(selected,"reopen")}>{tr?"Yeniden aç":"Reopen"}</button>}</footer></article></div>}
  {form&&<div className="finding-overlay"><form className="finding-form" onSubmit={create}><header><div><small>CONTROLLED CAPA RECORD</small><h3>{tr?"Yeni kurumsal bulgu":"New enterprise finding"}</h3></div><button type="button" onClick={()=>setForm(null)}>×</button></header><div className="finding-form-grid"><label>{tr?"Kaynak türü":"Source type"}<select value={form.sourceType} onChange={e=>setForm({...form,sourceType:e.target.value})}>{manualFindingSources.map(x=><option key={x}>{x}</option>)}</select></label><label>{tr?"Bulgu türü":"Finding type"}<select value={form.findingType} onChange={e=>setForm({...form,findingType:e.target.value})}>{["nonconformity","control-deficiency","observation","vulnerability","incident-action","improvement"].map(x=><option key={x}>{x}</option>)}</select></label><Field label={tr?"Kaynak referansı":"Source reference"} name="sourceRef" form={form} setForm={setForm}/><Field label={tr?"Kaynak başlığı":"Source title"} name="sourceTitle" form={form} setForm={setForm}/><Field wide label={tr?"Bulgu başlığı":"Finding title"} name="title" form={form} setForm={setForm}/><Field wide area label={tr?"Açıklama":"Description"} name="description" form={form} setForm={setForm}/><label>{tr?"Önem":"Severity"}<select value={form.severity} onChange={e=>{const severity=e.target.value;setForm({...form,severity,dueDate:addDays(today(),findingSlaDays(severity))})}}>{["low","medium","high","critical"].map(x=><option key={x}>{x}</option>)}</select></label><Field type="date" label={tr?"SLA termini":"SLA due date"} name="dueDate" form={form} setForm={setForm}/><Field label={tr?"Aksiyon sahibi e-posta":"Action owner email"} name="owner" form={form} setForm={setForm}/><Field label={tr?"Bağımsız reviewer e-posta":"Independent reviewer email"} name="reviewer" form={form} setForm={setForm}/><Field wide area label={tr?"Kök neden":"Root cause"} name="rootCause" form={form} setForm={setForm}/><Field wide area label={tr?"Düzeltici aksiyon":"Corrective action"} name="correctiveAction" form={form} setForm={setForm}/><Field wide area label={tr?"Önleyici aksiyon":"Preventive action"} name="preventiveAction" form={form} setForm={setForm}/><Field label={tr?"Risk referansı":"Risk reference"} name="riskRef" form={form} setForm={setForm}/><Field label={tr?"Kontrol referansı":"Control reference"} name="controlRef" form={form} setForm={setForm}/></div><footer><button type="button" className="secondary" onClick={()=>setForm(null)}>{tr?"İptal":"Cancel"}</button><button disabled={busy||loading||loadError}>{tr?"Bulgu ve CAPA oluştur":"Create finding & CAPA"}</button></footer></form></div>}
  {action&&<div className="finding-overlay"><article className="finding-action"><header><div><small>{action.finding.code}</small><h3>{action.finding.title}</h3></div><button onClick={()=>setAction(null)}>×</button></header><p>{tr?"İşlem, değişmez denetim izine aktör ve kanıt bilgisiyle yazılır.":"The action is written to the immutable audit trail with actor and evidence."}</p><label>{tr?"Açıklama":"Note"}<textarea value={action.note} onChange={e=>setAction({...action,note:e.target.value})}/></label>{["submit","verify","accept-risk"].includes(action.operation)&&<><label>{tr?"Kanıt referansı":"Evidence reference"}<input value={action.evidenceReference} onChange={e=>setAction({...action,evidenceReference:e.target.value})}/></label><label>SHA-256<input value={action.evidenceSha256} maxLength={64} onChange={e=>setAction({...action,evidenceSha256:e.target.value})}/></label></>}{action.operation==="accept-risk"&&<><label>{tr?"Kabul bitişi":"Acceptance expiry"}<input type="date" value={action.acceptUntil} onChange={e=>setAction({...action,acceptUntil:e.target.value})}/></label><label>{tr?"Risk kabul gerekçesi":"Risk acceptance rationale"}<textarea value={action.acceptanceRationale} onChange={e=>setAction({...action,acceptanceRationale:e.target.value})}/></label></>}<label>{tr?"Onay ifadesi":"Confirmation phrase"}<input value={action.confirmation} onChange={e=>setAction({...action,confirmation:e.target.value})}/><small>{phrases[action.operation]}</small></label><footer><button className="secondary" onClick={()=>setAction(null)}>{tr?"İptal":"Cancel"}</button><button disabled={busy||loading||loadError} onClick={()=>void transition()}>{tr?"İşlemi uygula":"Apply action"}</button></footer></article></div>}
  {events.length>0&&<details className="finding-history"><summary>{tr?"Son denetim izi olayları":"Recent audit trail events"}</summary>{events.slice(0,20).map(x=><div key={x.id}><b>{x.action}</b><span>{x.findingId} · {x.actor}</span><small>{x.detail}</small></div>)}</details>}
 </section>
}
function Field({label,name,form,setForm,wide=false,area=false,type="text"}:{label:string;name:string;form:Record<string,string>;setForm:(x:Record<string,string>)=>void;wide?:boolean;area?:boolean;type?:string}){return <label className={wide?"wide":""}>{label}{area?<textarea value={form[name]} onChange={e=>setForm({...form,[name]:e.target.value})}/>:<input type={type} value={form[name]} onChange={e=>setForm({...form,[name]:e.target.value})}/>}</label>}

function canActOnFinding(finding:Finding,user:{role:string;email:string}){return user.role==="Admin"||(user.role==="Editor"&&finding.owner.toLowerCase()===user.email.toLowerCase())}
