"use client";
import { FormEvent,useCallback,useEffect,useRef,useState } from "react";
import { withBasePath } from "./base-path";
import { AiRecordFocusBanner, type AiRecordFocusProps } from "./ai-record-focus";
import { validAiCollection } from "./ai-record-navigation";
import { useAiActionList, AiActionListFilters, AiActionListPages, aiStatusLabels, aiSeverityLabels } from "./ai-action-list";
type Model={id:string;updatedAt:string;systemName:string;modelName:string;vendor:string;purpose:string;owner:string;deployment:string;region:string;dataClassification:string;autonomy:string;affectedUsers:number;impact:number;likelihood:number;dataSensitivity:number;autonomyRisk:number;controlMaturity:number;inherentScore:number;residualScore:number;riskTier:string;controls:string;status:string;reviewDate:string;overdue:boolean;decisionNote:string|null};
type Form={systemName:string;modelName:string;vendor:string;purpose:string;owner:string;deployment:string;region:string;dataClassification:string;autonomy:string;affectedUsers:number;impact:number;likelihood:number;dataSensitivity:number;autonomyRisk:number;controlMaturity:number;controls:string;reviewDate:string};
const initial:Form={systemName:"",modelName:"",vendor:"",purpose:"",owner:"",deployment:"External SaaS",region:"EU",dataClassification:"Internal",autonomy:"Advisory",affectedUsers:0,impact:3,likelihood:3,dataSensitivity:3,autonomyRisk:2,controlMaturity:3,controls:"RBAC, insan onayı, audit log, veri minimizasyonu",reviewDate:""};
export default function FornostAiModelInventory({focusRef,clearFocus,lang="tr"}:AiRecordFocusProps){const [models,setModels]=useState<Model[]>([]),[summary,setSummary]=useState({total:0,approved:0,highRisk:0,overdue:0}),[provider,setProvider]=useState<{provider:string;model:string;enabled:boolean}|null>(null),[form,setForm]=useState<Form>(initial),[editId,setEditId]=useState<string|null>(null),[decision,setDecision]=useState<{id:string;status:"approved"|"suspended";expectedUpdatedAt:string;note:string;confirmation:string}|null>(null),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false);
 const[showCreate,setShowCreate]=useState(false);
 const list=useAiActionList(models.map(m=>({...m,title:[m.systemName,m.modelName,m.vendor].join(" "),modelId:m.id,severity:m.riskTier,state:m.overdue?"overdue":m.status})),focusRef,()=>setDecision(null));
 const [loading,setLoading]=useState(true),[loadError,setLoadError]=useState(false);
 const[editVersion,setEditVersion]=useState("");const loadId=useRef(0);
 const load=useCallback(async()=>{
  const ticket=++loadId.current;setLoading(true);setLoadError(false);setDecision(null);
  try{const response=await fetch(withBasePath("/api/ai/models"),{cache:"no-store"});const body=await response.json();
   if(!response.ok||!validAiCollection(body.models))throw new Error("Invalid model source");
   if(ticket!==loadId.current)return;setModels(body.models);setSummary(body.summary||{total:0,approved:0,highRisk:0,overdue:0});setProvider(body.configuredProvider||null);
  }catch{if(ticket===loadId.current){setModels([]);setSummary({total:0,approved:0,highRisk:0,overdue:0});setProvider(null);setLoadError(true);}}finally{if(ticket===loadId.current)setLoading(false);}
 },[]);useEffect(()=>{const requests=loadId;const timer=window.setTimeout(()=>void load(),0);return()=>{window.clearTimeout(timer);requests.current++;};},[load]);
 const set=(key:keyof Form,value:string|number)=>setForm(current=>({...current,[key]:value}));
 async function submit(e:FormEvent){e.preventDefault();if(busy||loading||loadError||editId&&!editVersion)return;setBusy(true);try{const response=await fetch(withBasePath("/api/ai/models"),{method:editId?"PUT":"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...form,id:editId,expectedUpdatedAt:editVersion})});const body=await response.json().catch(()=>({}));setNotice(response.ok?(editId?"Model kaydı güncellendi.":`Model taslağı eklendi · ${body.riskTier} risk (${body.residualScore})`):String(body.error||"Model kaydedilemedi."));if(response.ok){setForm(initial);setEditId(null);setEditVersion("");setShowCreate(false);list.reset();await load();}else if(response.status===409||response.status>=500){setEditVersion("");await load();}}catch{setNotice("Kayıt sonucu doğrulanamadı. Güncel listeyi kontrol edin; düzenleme için kaydı yeniden açın.");setEditVersion("");await load();}finally{setBusy(false);}}
 function edit(m:Model){setShowCreate(false);setDecision(null);setEditId(m.id);setEditVersion(m.updatedAt);setForm({systemName:m.systemName,modelName:m.modelName,vendor:m.vendor,purpose:m.purpose,owner:m.owner,deployment:m.deployment,region:m.region,dataClassification:m.dataClassification,autonomy:m.autonomy,affectedUsers:m.affectedUsers,impact:m.impact,likelihood:m.likelihood,dataSensitivity:m.dataSensitivity,autonomyRisk:m.autonomyRisk,controlMaturity:m.controlMaturity,controls:m.controls,reviewDate:m.reviewDate});}
 async function decide(){
  if(!decision||busy||loading||loadError)return;setBusy(true);
  try{
   const response=await fetch(withBasePath("/api/ai/models"),{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(decision)});
   const body=await response.json().catch(()=>({}));setNotice(response.ok?"Model yaşam döngüsü güncellendi.":String(body.error||"Karar kaydedilemedi."));
   if(response.ok||response.status===409||response.status>=500){setDecision(null);await load();}
  }catch{setNotice("Karar sonucu doğrulanamadı. Güncel kaydı yükleyip kontrol edin.");setDecision(null);await load();}finally{setBusy(false);}
 }
 async function remove(m:Model){if(busy||loading||loadError||!window.confirm("Taslak model kaydı silinsin mi?"))return;setBusy(true);try{const response=await fetch(withBasePath("/api/ai/models"),{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({id:m.id,expectedUpdatedAt:m.updatedAt,confirmation:"SİL"})}),body=await response.json().catch(()=>({}));setNotice(response.ok?"Taslak model silindi.":String(body.error||"Model silinemedi."));if(response.ok&&editId===m.id){setEditId(null);setEditVersion("");setForm(initial);}if(response.ok||response.status===409||response.status>=500){if(editId===m.id)setEditVersion("");await load();}}catch{setNotice("Silme sonucu doğrulanamadı. Güncel listeyi kontrol edin.");if(editId===m.id)setEditVersion("");await load();}finally{setBusy(false);}}
 const factor=(key:keyof Form,label:string)=><label><span>{label}</span><select value={String(form[key])} onChange={e=>set(key,Number(e.target.value))}>{[1,2,3,4,5].map(n=><option key={n}>{n}</option>)}</select></label>;
 return <div className="ai-model-inventory"><AiRecordFocusBanner focusRef={focusRef} clearFocus={clearFocus} lang={lang} loading={loading} error={loadError} found={models.some(m=>m.id===focusRef)} retry={()=>void load()}/><section className="ai-inventory-hero"><div><small>AI GOVERNANCE · MODEL REGISTRY</small><h3>AI Sistem ve Model Envanteri</h3><p>Her AI sistemi sahiplik, veri kullanımı, lokasyon, otonomi ve artık risk üzerinden izlenir.</p></div><a href={withBasePath("/api/ai/models?format=csv")}>Kanıt CSV</a></section><div className="ai-inventory-stats"><article><b>{loading||loadError?"—":summary.total}</b><span>Toplam</span></article><article><b>{loading||loadError?"—":summary.approved}</b><span>Onaylı</span></article><article><b>{loading||loadError?"—":summary.highRisk}</b><span>Yüksek/Kritik</span></article><article><b>{loading||loadError?"—":summary.overdue}</b><span>İncelemesi geciken</span></article></div>{provider&&<div className="ai-provider-link"><b>Fornost çalışma modeli</b><span>{provider.provider} · {provider.model} · {provider.enabled?"etkin":"kapalı"}</span></div>}
 {!focusRef&&<AiActionListFilters list={list} statuses={["draft","approved","suspended","retired","overdue"]} severityLabel="Risk düzeyi" disabled={busy||loading||loadError}/>}
 {!loading&&!loadError&&<p className="ai-action-list-count">{list.filtered.length} / {models.length} model · Sayaçlar ve CSV liste filtresinden bağımsızdır.</p>}
 {models.length>=500&&<p role="status">Görüntüleme sınırına ulaşıldı; liste tüm modelleri içermeyebilir.</p>}
 {!focusRef&&!editId&&<button disabled={busy||loading||loadError} aria-expanded={showCreate} aria-controls="ai-model-create" onClick={()=>setShowCreate(!showCreate)}>{showCreate?"Formu kapat":"Yeni model"}</button>}
 {((!focusRef&&showCreate)||editId)&&<form id="ai-model-create" className="ai-inventory-form" onSubmit={submit}><b>{editId?"Taslak modeli düzenle":"Yeni AI sistemi kaydet"}</b><div><label><span>Sistem adı</span><input required value={form.systemName} onChange={e=>set("systemName",e.target.value)}/></label><label><span>Model</span><input required value={form.modelName} onChange={e=>set("modelName",e.target.value)}/></label><label><span>Sağlayıcı</span><input required value={form.vendor} onChange={e=>set("vendor",e.target.value)}/></label><label><span>Sorumlu</span><input required value={form.owner} onChange={e=>set("owner",e.target.value)}/></label><label><span>Dağıtım</span><select value={form.deployment} onChange={e=>set("deployment",e.target.value)}>{["External SaaS","Private Cloud","On-Prem","Local"].map(v=><option key={v}>{v}</option>)}</select></label><label><span>Veri lokasyonu</span><input value={form.region} onChange={e=>set("region",e.target.value)}/></label><label><span>Veri sınıfı</span><select value={form.dataClassification} onChange={e=>set("dataClassification",e.target.value)}>{["Public","Internal","Confidential","Restricted"].map(v=><option key={v}>{v}</option>)}</select></label><label><span>Karar rolü</span><select value={form.autonomy} onChange={e=>set("autonomy",e.target.value)}>{["Advisory","Human-reviewed","Human-approved","Autonomous"].map(v=><option key={v}>{v}</option>)}</select></label><label><span>Etkilenen kullanıcı</span><input type="number" min="0" value={form.affectedUsers} onChange={e=>set("affectedUsers",Number(e.target.value))}/></label><label><span>İnceleme tarihi</span><input required type="date" value={form.reviewDate} onChange={e=>set("reviewDate",e.target.value)}/></label></div><label><span>Kullanım amacı</span><textarea required rows={2} value={form.purpose} onChange={e=>set("purpose",e.target.value)}/></label><div className="ai-risk-factors">{factor("impact","Etki")}{factor("likelihood","Olasılık")}{factor("dataSensitivity","Veri hassasiyeti")}{factor("autonomyRisk","Otonomi riski")}{factor("controlMaturity","Kontrol olgunluğu")}</div><label><span>Uygulanan kontroller</span><textarea required rows={2} value={form.controls} onChange={e=>set("controls",e.target.value)}/></label>{editId&&!editVersion&&<p role="alert">Taslak alanlarınız korunuyor. Kaydetmeden önce güncel kaydı Düzenle ile yeniden açın.</p>}<footer>{editId&&<button type="button" disabled={busy} onClick={()=>{setEditId(null);setEditVersion("");setForm(initial);}}>Vazgeç</button>}<button disabled={busy||loading||loadError||!!editId&&!editVersion}>{busy?"Kaydediliyor…":editId?"Güncelle":"Taslak oluştur"}</button></footer></form>}{notice&&<p className="ai-inventory-notice">{notice}</p>}
 <div className="ai-inventory-list">{list.visible.map(m=><article data-record-id={m.id} key={m.id}><header><div><small>{m.id.slice(0,12)}</small><b>{m.systemName}</b><span>{m.vendor} · {m.modelName}</span></div><div><em className={String(m.riskTier).toLowerCase()}>{aiSeverityLabels[m.riskTier]||m.riskTier} · {m.residualScore}</em><strong className={m.status}>{aiStatusLabels[m.status]||m.status}</strong></div></header><p>{m.purpose}</p><dl><div><dt>Sorumlu</dt><dd>{m.owner}</dd></div><div><dt>Çalışma</dt><dd>{m.deployment} · {m.region}</dd></div><div><dt>Veri / karar</dt><dd>{m.dataClassification} · {m.autonomy}</dd></div><div><dt>İnceleme</dt><dd className={m.overdue?"overdue":""}>{m.reviewDate}</dd></div></dl><small>{m.controls}</small>{m.decisionNote&&<aside>{m.decisionNote}</aside>}<footer>{m.status==="draft"&&<><button disabled={busy||loading||loadError} onClick={()=>edit(m)}>Düzenle</button><button className="danger" disabled={busy||loading||loadError} onClick={()=>void remove(m)}>Sil</button></>} {m.status!=="retired"&&<><button disabled={busy||loading||loadError||m.status==="approved"} onClick={()=>setDecision({id:m.id,expectedUpdatedAt:m.updatedAt,status:"approved",note:"",confirmation:""})}>Onayla</button><button className="warn" disabled={busy||loading||loadError||m.status==="suspended"} onClick={()=>setDecision({id:m.id,expectedUpdatedAt:m.updatedAt,status:"suspended",note:"",confirmation:""})}>Askıya al</button></>}</footer>{m.status!=="retired"&&<small>Emeklilik işlemi AI Emeklilik merkezindeki doğrulanmış plan üzerinden tamamlanır.</small>}{decision?.id===m.id&&<div className="ai-inventory-decision"><textarea rows={2} value={decision.note} onChange={e=>setDecision({...decision,note:e.target.value})} placeholder="Zorunlu karar notu"/><input value={decision.confirmation} onChange={e=>setDecision({...decision,confirmation:e.target.value})} placeholder={decision.status==="approved"?"ONAYLA":"ASKIYA AL"}/><div><button onClick={()=>setDecision(null)}>Vazgeç</button><button disabled={busy||loading||loadError||decision.note.trim().length<5} onClick={()=>void decide()}>Kararı uygula</button></div></div>}</article>)}</div>{!loading&&!loadError&&!focusRef&&list.filtered.length===0&&<p className="ai-action-list-empty">{models.length?"Filtrelere uygun model bulunamadı. Filtreleri temizleyerek tekrar deneyin.":"Henüz model yok. Yeni model ile başlayın."}</p>}{!loading&&!loadError&&!focusRef&&<AiActionListPages list={list} disabled={busy}/>}</div>}
