"use client";
import {useEffect,useState} from "react";
import {withBasePath} from "./base-path";
type Alert={id:string;modelId:string;metric:string;title:string;severity:string;observedValue:number|null;thresholdValue:number|null;occurrenceCount:number;status:string;owner?:string;findingId?:string;lastSeenAt:string};
const confirmations:Record<string,string>={acknowledge:"ALARMI KABUL ET",escalate:"CAPA OLUŞTUR",resolve:"ALARMI ÇÖZ",reopen:"ALARMI YENİDEN AÇ"};
export default function FornostAiAssuranceAlerts(){
 const[data,setData]=useState<{alerts:Alert[];summary:Record<string,number>}>({alerts:[],summary:{}}),[busy,setBusy]=useState(false),[notice,setNotice]=useState(""),[dialog,setDialog]=useState<{alert:Alert;action:string;owner:string;note:string;confirmation:string}|null>(null);
 async function load(){const response=await fetch(withBasePath("/api/ai/assurance-alerts"),{cache:"no-store"}),body=await response.json().catch(()=>({}));if(response.ok)setData(body);}
 useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer);},[]);
 async function sync(){setBusy(true);const response=await fetch(withBasePath("/api/ai/assurance-alerts"),{method:"POST"}),body=await response.json().catch(()=>({}));setNotice(response.ok?`${body.created} yeni alarm, ${body.updated} tekilleştirilmiş tekrar işlendi.`:String(body.error||"Alarm taraması başarısız."));if(response.ok)await load();setBusy(false);}
 async function act(){if(!dialog)return;setBusy(true);const response=await fetch(withBasePath("/api/ai/assurance-alerts"),{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:dialog.alert.id,action:dialog.action,owner:dialog.owner,note:dialog.note,confirmation:dialog.confirmation})}),body=await response.json().catch(()=>({}));setNotice(response.ok?body.findingId?`Alarm CAPA'ya bağlandı: ${body.findingId}`:"Alarm durumu güncellendi.":String(body.error||"İşlem başarısız."));if(response.ok){setDialog(null);await load();}setBusy(false);}
 const open=(alert:Alert,action:string)=>setDialog({alert,action,owner:alert.owner||"",note:"",confirmation:""});
 return <section className="ai-alerts"><header><div><small>DETERMINISTIC · DEDUPLICATED · CAPA-LINKED</small><h3>AI Güvence Alarmları</h3><p>Onaylı baseline ihlallerini kalıcı, sahipli ve denetlenebilir aksiyona dönüştürür.</p></div><div className="actions"><a href={withBasePath("/api/ai/assurance-alerts?format=csv")}>Alarm Kanıt CSV</a><button disabled={busy} onClick={()=>void sync()}>Ölçümleri Tara</button></div></header>
 <div className="stats">{[["open","Açık"],["critical","Kritik"],["high","Yüksek"],["escalated","CAPA"],["resolved","Çözüldü"]].map(([key,label])=><article key={key}><b>{data.summary[key]||0}</b><span>{label}</span></article>)}</div>{notice&&<div className="notice">{notice}</div>}
 <div className="list">{data.alerts.map(alert=><article key={alert.id} className={alert.severity.toLowerCase()}><header><div><b>{alert.title}</b><small>{alert.modelId} · {alert.metric} · {alert.id}</small></div><span>{alert.severity} · {alert.status}</span></header><p>Gözlenen: <strong>{alert.observedValue??"ölçüm yok"}</strong> · Eşik: <strong>{alert.thresholdValue??"—"}</strong> · Tekrar: <strong>{alert.occurrenceCount}</strong></p><footer><small>{new Date(alert.lastSeenAt).toLocaleString("tr-TR")} {alert.owner?`· ${alert.owner}`:""} {alert.findingId?`· CAPA ${alert.findingId}`:""}</small><div>{alert.status==="open"&&<button onClick={()=>open(alert,"acknowledge")}>Kabul et</button>}{alert.status!=="resolved"&&["High","Critical"].includes(alert.severity)&&!alert.findingId&&<button onClick={()=>open(alert,"escalate")}>CAPA oluştur</button>}{["acknowledged","escalated"].includes(alert.status)&&<button onClick={()=>open(alert,"resolve")}>Çöz</button>}{alert.status==="resolved"&&<button onClick={()=>open(alert,"reopen")}>Yeniden aç</button>}</div></footer></article>)}</div>
 {dialog&&<div className="dialog"><div><h4>{dialog.alert.title}</h4><label>Sorumlu<input value={dialog.owner} onChange={e=>setDialog({...dialog,owner:e.target.value})}/></label><label>Açıklama<textarea rows={4} value={dialog.note} onChange={e=>setDialog({...dialog,note:e.target.value})}/></label><label>Onay metni: <b>{confirmations[dialog.action]}</b><input value={dialog.confirmation} onChange={e=>setDialog({...dialog,confirmation:e.target.value})}/></label><div><button onClick={()=>setDialog(null)}>Vazgeç</button><button disabled={busy} onClick={()=>void act()}>Kaydet</button></div></div></div>}
 </section>;
}
