"use client";
import {useCallback,useEffect,useState} from "react";
import {withBasePath} from "./base-path";

type Policy={emergencyStop:boolean;chatEnabled:boolean;draftsEnabled:boolean;agentsEnabled:boolean;retrievalEnabled:boolean;evaluationsEnabled:boolean;viewerChat:boolean;editorChat:boolean;maintenanceMessage:string;updatedBy:string|null;updatedAt:string|null};
const defaults:Policy={emergencyStop:false,chatEnabled:true,draftsEnabled:true,agentsEnabled:true,retrievalEnabled:true,evaluationsEnabled:true,viewerChat:true,editorChat:true,maintenanceMessage:"",updatedBy:null,updatedAt:null};
const controls:Array<{key:keyof Policy;label:string;detail:string}>=[
  {key:"chatEnabled",label:"Copilot sohbet",detail:"Soru-cevap ve kaynaklı GRC analizi"},{key:"draftsEnabled",label:"AI taslak üretimi",detail:"Risk, bulgu ve iyileştirme taslakları"},{key:"agentsEnabled",label:"Assurance agentları",detail:"Risk, audit, compliance ve evidence analizleri"},{key:"retrievalEnabled",label:"Retrieval laboratuvarı",detail:"Bilgi tabanı arama ve citation testi"},{key:"evaluationsEnabled",label:"Model değerlendirmeleri",detail:"Kalite ve güvenlik test koşumları"},
];
export default function FornostAiPolicy({onChanged}:{onChanged:()=>Promise<void>}){const[policy,setPolicy]=useState(defaults),[busy,setBusy]=useState(false),[notice,setNotice]=useState(""),[confirmation,setConfirmation]=useState("");
  const load=useCallback(async()=>{setBusy(true);const response=await fetch(withBasePath("/api/ai/policy"),{cache:"no-store"}).catch(()=>null),body=await response?.json().catch(()=>({}))||{};if(response?.ok)setPolicy({...defaults,...body.policy});else setNotice(String(body.error||"AI operasyon politikası okunamadı."));setBusy(false);},[]);
  useEffect(()=>{const timer=window.setTimeout(()=>{void load();},0);return()=>window.clearTimeout(timer);},[load]);
  async function save(){if(confirmation!=="POLİTİKAYI UYGULA"||busy)return;setBusy(true);setNotice("");const response=await fetch(withBasePath("/api/ai/policy"),{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({...policy,confirmation})}).catch(()=>null),body=await response?.json().catch(()=>({}))||{};if(response?.ok){setPolicy({...defaults,...body.policy});setConfirmation("");setNotice("AI operasyon politikası etkinleştirildi ve audit kaydına yazıldı.");await onChanged();}else setNotice(String(body.error||"Politika kaydedilemedi."));setBusy(false);}
  const set=(key:keyof Policy,value:boolean|string)=>setPolicy(current=>({...current,[key]:value}));
  return <div className="fornost-ai-policy"><div className={`fornost-ai-policy-emergency ${policy.emergencyStop?"stopped":"running"}`}><div><b>{policy.emergencyStop?"AI ACİL DURDURMA ETKİN":"AI operasyonları çalışabilir"}</b><p>Emergency stop tüm model çağrılarını ve retrieval testlerini backend seviyesinde engeller. Sağlayıcı ayarları ve mevcut kayıtlar korunur.</p></div><label className="fornost-ai-check"><input type="checkbox" checked={policy.emergencyStop} onChange={e=>set("emergencyStop",e.target.checked)}/><span>Acil durdurma</span></label></div>
    {notice&&<div className="fornost-ai-notice">{notice}</div>}
    <div className="fornost-ai-policy-grid">{controls.map(item=><article key={item.key}><div><b>{item.label}</b><small>{item.detail}</small></div><label className="fornost-ai-check"><input type="checkbox" checked={Boolean(policy[item.key])} onChange={e=>set(item.key,e.target.checked)}/><span>{policy[item.key]?"İzinli":"Kapalı"}</span></label></article>)}</div>
    <section className="fornost-ai-policy-roles"><b>Rol bazlı Copilot erişimi</b><label className="fornost-ai-check"><input type="checkbox" checked={policy.editorChat} onChange={e=>set("editorChat",e.target.checked)}/><span>Editor sohbet kullanabilir</span></label><label className="fornost-ai-check"><input type="checkbox" checked={policy.viewerChat} onChange={e=>set("viewerChat",e.target.checked)}/><span>Viewer sohbet kullanabilir</span></label><small>Admin erişimi kilitlenemez; acil durdurma Admin dahil herkese uygulanır.</small></section>
    <label className="fornost-ai-policy-message"><span>Bakım / durdurma mesajı</span><textarea rows={2} maxLength={300} value={policy.maintenanceMessage} onChange={e=>set("maintenanceMessage",e.target.value)} placeholder="Örn. Güvenlik incelemesi nedeniyle AI geçici olarak durduruldu."/></label>
    <div className="fornost-ai-policy-save"><div>{policy.updatedAt&&<small>Son değişiklik: {policy.updatedBy} · {new Date(policy.updatedAt).toLocaleString("tr-TR")}</small>}<input value={confirmation} onChange={e=>setConfirmation(e.target.value)} placeholder="POLİTİKAYI UYGULA"/></div><button disabled={busy||confirmation!=="POLİTİKAYI UYGULA"} onClick={()=>void save()}>{busy?"Uygulanıyor…":"Politikayı Uygula"}</button></div>
  </div>;
}
