"use client";
import {useCallback,useEffect,useRef,useState} from "react";
import {withBasePath} from "./base-path";
import { AiRecordFocusBanner, type AiRecordFocusProps } from "./ai-record-focus";
import { AiRelatedRecordLink } from "./ai-related-record-link";
import { validAiCollection } from "./ai-record-navigation";
import { useAiActionList, AiActionListFilters, AiActionListPages, aiStatusLabels, aiSeverityLabels } from "./ai-action-list";
type Alert={id:string;modelId:string;metric:string;title:string;severity:string;observedValue:number|null;thresholdValue:number|null;occurrenceCount:number;status:string;owner?:string;findingId?:string;lastSeenAt:string};
const confirmations:Record<string,string>={acknowledge:"ALARMI KABUL ET",escalate:"CAPA OLUŞTUR",resolve:"ALARMI ÇÖZ",reopen:"ALARMI YENİDEN AÇ"};
export default function FornostAiAssuranceAlerts({focusRef,clearFocus,lang="tr"}:AiRecordFocusProps){
 const[data,setData]=useState<{alerts:Alert[];summary:Record<string,number>}>({alerts:[],summary:{}}),[busy,setBusy]=useState(false),[notice,setNotice]=useState(""),[dialog,setDialog]=useState<{alert:Alert;action:string;owner:string;note:string;confirmation:string}|null>(null);
 const[loading,setLoading]=useState(true),[loadError,setLoadError]=useState(false);
 const list=useAiActionList(data.alerts,focusRef,()=>setDialog(null));
 const loadId=useRef(0);
 const load=useCallback(async()=>{
  const ticket=++loadId.current;setLoading(true);setLoadError(false);setDialog(null);
  try{const response=await fetch(withBasePath("/api/ai/assurance-alerts"),{cache:"no-store"}),body=await response.json();
   if(!response.ok||!validAiCollection(body.alerts))throw new Error("Invalid alert source");
   if(ticket===loadId.current)setData({alerts:body.alerts,summary:body.summary||{}});
  }catch{if(ticket===loadId.current){setData({alerts:[],summary:{}});setLoadError(true);}}finally{if(ticket===loadId.current)setLoading(false);}
 },[]);
 useEffect(()=>{const requests=loadId;const timer=setTimeout(()=>void load(),0);return()=>{clearTimeout(timer);requests.current++;};},[load]);
 async function sync(){if(busy||loading||loadError)return;setBusy(true);try{const response=await fetch(withBasePath("/api/ai/assurance-alerts"),{method:"POST"}),body=await response.json().catch(()=>({}));setNotice(response.ok?`${body.created} yeni alarm, ${body.updated} tekilleştirilmiş tekrar işlendi.`:String(body.error||"Alarm taraması başarısız."));if(response.ok||response.status===409||response.status>=500)await load();}catch{setNotice("Tarama sonucu doğrulanamadı. Güncel alarm listesini kontrol edin.");await load();}finally{setBusy(false);}}
 async function act(){if(!dialog||busy||loading||loadError)return;setBusy(true);try{const response=await fetch(withBasePath("/api/ai/assurance-alerts"),{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:dialog.alert.id,action:dialog.action,owner:dialog.owner,note:dialog.note,confirmation:dialog.confirmation})}),body=await response.json().catch(()=>({}));setNotice(response.ok?body.findingId?`Alarm CAPA'ya bağlandı: ${body.findingId}`:"Alarm durumu güncellendi.":String(body.error||"İşlem başarısız."));if(response.ok||response.status===409||response.status>=500){setDialog(null);await load();}}catch{setNotice("İşlem sonucu doğrulanamadı. Güncel listeyi kontrol edip işlemi yeniden açın.");setDialog(null);await load();}finally{setBusy(false);}}
 const open=(alert:Alert,action:string)=>setDialog({alert,action,owner:alert.owner||"",note:"",confirmation:""});
 return <section className="ai-alerts"><AiRecordFocusBanner focusRef={focusRef} clearFocus={clearFocus} lang={lang} loading={loading} error={loadError} found={data.alerts.some(a=>a.id===focusRef)} retry={()=>void load()}/><header><div><small>DETERMINISTIC · DEDUPLICATED · CAPA-LINKED</small><h3>AI Güvence Alarmları</h3><p>Onaylı baseline ihlallerini kalıcı, sahipli ve denetlenebilir aksiyona dönüştürür.</p></div><div className="actions"><a href={withBasePath("/api/ai/assurance-alerts?format=csv")}>Alarm Kanıt CSV</a><button disabled={busy||loading||loadError} onClick={()=>void sync()}>Ölçümleri Tara</button></div></header>
 <div className="stats">{[["open","Açık"],["critical","Kritik"],["high","Yüksek"],["escalated","CAPA"],["resolved","Çözüldü"]].map(([key,label])=><article key={key}><b>{loading||loadError?"—":data.summary[key]||0}</b><span>{label}</span></article>)}</div>{notice&&<div className="notice">{notice}</div>}

 {!focusRef&&<AiActionListFilters list={list} statuses={["open","acknowledged","escalated","resolved"]} disabled={busy||loading||loadError}/>}
 {!loading&&!loadError&&<p className="ai-action-list-count">{list.filtered.length} / {data.alerts.length} kayıt · Sayaçlar ve CSV liste filtresinden bağımsızdır.</p>}
 {data.alerts.length>=500&&<p role="status">Görüntüleme sınırına ulaşıldı; liste tüm kayıtları içermeyebilir.</p>}
 <div className="list">{list.visible.map(alert=><article data-record-id={alert.id} key={alert.id} className={alert.severity.toLowerCase()}><header><div><b>{alert.title}</b><small>{alert.modelId} · {alert.metric} · {alert.id}</small></div><span>{aiSeverityLabels[alert.severity]||alert.severity} · {aiStatusLabels[alert.status]||alert.status}</span></header><p>Gözlenen: <strong>{alert.observedValue??"ölçüm yok"}</strong> · Eşik: <strong>{alert.thresholdValue??"—"}</strong> · Tekrar: <strong>{alert.occurrenceCount}</strong></p><footer><small>{new Date(alert.lastSeenAt).toLocaleString("tr-TR")} {alert.owner?`· ${alert.owner}`:""} {alert.findingId?`· CAPA ${alert.findingId}`:""}</small><div><AiRelatedRecordLink kind="ai-model" recordRef={alert.modelId} label="Bağlı modeli aç" disabled={busy||loading||loadError}/><AiRelatedRecordLink kind="ai-finding" recordRef={alert.findingId} label="Bağlı bulguyu aç" disabled={busy||loading||loadError}/>{alert.status==="open"&&<button disabled={busy||loading||loadError} onClick={()=>open(alert,"acknowledge")}>Kabul et</button>}{alert.status!=="resolved"&&["High","Critical"].includes(alert.severity)&&!alert.findingId&&<button disabled={busy||loading||loadError} onClick={()=>open(alert,"escalate")}>CAPA oluştur</button>}{["acknowledged","escalated"].includes(alert.status)&&<button disabled={busy||loading||loadError} onClick={()=>open(alert,"resolve")}>Çöz</button>}{alert.status==="resolved"&&<button disabled={busy||loading||loadError} onClick={()=>open(alert,"reopen")}>Yeniden aç</button>}</div></footer></article>)}</div>
 {!loading&&!loadError&&!focusRef&&list.filtered.length===0&&<p className="ai-action-list-empty">{data.alerts.length?"Filtrelere uygun alarm bulunamadı. Filtreleri temizleyerek tekrar deneyin.":"Henüz alarm yok."}</p>}{!loading&&!loadError&&!focusRef&&<AiActionListPages list={list} disabled={busy}/>}
 {dialog&&<div className="dialog"><div><h4>{dialog.alert.title}</h4><label>Sorumlu<input value={dialog.owner} onChange={e=>setDialog({...dialog,owner:e.target.value})}/></label><label>Açıklama<textarea rows={4} value={dialog.note} onChange={e=>setDialog({...dialog,note:e.target.value})}/></label><label>Onay metni: <b>{confirmations[dialog.action]}</b><input value={dialog.confirmation} onChange={e=>setDialog({...dialog,confirmation:e.target.value})}/></label><div><button disabled={busy} onClick={()=>setDialog(null)}>Vazgeç</button><button disabled={busy||loading||loadError} onClick={()=>void act()}>Kaydet</button></div></div></div>}
 </section>;
}
