"use client";
import { FormEvent,useCallback,useEffect,useState } from "react";
import { withBasePath } from "./base-path";
import { AiRecordFocusBanner, type AiRecordFocusProps } from "./ai-record-focus";
import { validAiCollection } from "./ai-record-navigation";
type Model={id:string;updatedAt:string;systemName:string;modelName:string;vendor:string;purpose:string;owner:string;deployment:string;region:string;dataClassification:string;autonomy:string;affectedUsers:number;impact:number;likelihood:number;dataSensitivity:number;autonomyRisk:number;controlMaturity:number;inherentScore:number;residualScore:number;riskTier:string;controls:string;status:string;reviewDate:string;overdue:boolean;decisionNote:string|null};
type Form={systemName:string;modelName:string;vendor:string;purpose:string;owner:string;deployment:string;region:string;dataClassification:string;autonomy:string;affectedUsers:number;impact:number;likelihood:number;dataSensitivity:number;autonomyRisk:number;controlMaturity:number;controls:string;reviewDate:string};
const initial:Form={systemName:"",modelName:"",vendor:"",purpose:"",owner:"",deployment:"External SaaS",region:"EU",dataClassification:"Internal",autonomy:"Advisory",affectedUsers:0,impact:3,likelihood:3,dataSensitivity:3,autonomyRisk:2,controlMaturity:3,controls:"RBAC, insan onayı, audit log, veri minimizasyonu",reviewDate:""};
export default function FornostAiModelInventory({focusRef,clearFocus,lang="tr"}:AiRecordFocusProps){const [models,setModels]=useState<Model[]>([]),[summary,setSummary]=useState({total:0,approved:0,highRisk:0,overdue:0}),[provider,setProvider]=useState<{provider:string;model:string;enabled:boolean}|null>(null),[form,setForm]=useState<Form>(initial),[editId,setEditId]=useState<string|null>(null),[decision,setDecision]=useState<{id:string;status:"approved"|"suspended";expectedUpdatedAt:string;note:string;confirmation:string}|null>(null),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false);
 const [loading,setLoading]=useState(true),[loadError,setLoadError]=useState(false);
 const load=useCallback(async()=>{
  setLoading(true);setLoadError(false);
  try{const response=await fetch(withBasePath("/api/ai/models"),{cache:"no-store"});const body=await response.json();
   if(!response.ok||!validAiCollection(body.models))throw new Error("Invalid model source");
   setModels(body.models);setSummary(body.summary||{total:0,approved:0,highRisk:0,overdue:0});setProvider(body.configuredProvider||null);
  }catch{setModels([]);setSummary({total:0,approved:0,highRisk:0,overdue:0});setProvider(null);setLoadError(true);}finally{setLoading(false);}
 },[]);useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer);},[load]);
 const set=(key:keyof Form,value:string|number)=>setForm(current=>({...current,[key]:value}));
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);const response=await fetch(withBasePath("/api/ai/models"),{method:editId?"PUT":"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...form,id:editId})});const body=await response.json().catch(()=>({}));setNotice(response.ok?(editId?"Model kaydı güncellendi.":`Model taslağı eklendi · ${body.riskTier} risk (${body.residualScore})`):String(body.error||"Model kaydedilemedi."));if(response.ok){setForm(initial);setEditId(null);await load();}setBusy(false);}
 function edit(m:Model){setEditId(m.id);setForm({systemName:m.systemName,modelName:m.modelName,vendor:m.vendor,purpose:m.purpose,owner:m.owner,deployment:m.deployment,region:m.region,dataClassification:m.dataClassification,autonomy:m.autonomy,affectedUsers:m.affectedUsers,impact:m.impact,likelihood:m.likelihood,dataSensitivity:m.dataSensitivity,autonomyRisk:m.autonomyRisk,controlMaturity:m.controlMaturity,controls:m.controls,reviewDate:m.reviewDate});}
 async function decide(){
  if(!decision)return;setBusy(true);
  try{
   const response=await fetch(withBasePath("/api/ai/models"),{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(decision)});
   const body=await response.json().catch(()=>({}));setNotice(response.ok?"Model yaşam döngüsü güncellendi.":String(body.error||"Karar kaydedilemedi."));
   if(response.ok||response.status===409){setDecision(null);await load();}
  }catch{setNotice("Karar sonucu doğrulanamadı. Güncel kaydı yükleyip kontrol edin.");setDecision(null);await load();}finally{setBusy(false);}
 }
 async function remove(id:string){if(!window.confirm("Taslak model kaydı silinsin mi?"))return;await fetch(withBasePath("/api/ai/models"),{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({id,confirmation:"SİL"})});await load();}
 const factor=(key:keyof Form,label:string)=><label><span>{label}</span><select value={String(form[key])} onChange={e=>set(key,Number(e.target.value))}>{[1,2,3,4,5].map(n=><option key={n}>{n}</option>)}</select></label>;
 return <div className="ai-model-inventory"><AiRecordFocusBanner focusRef={focusRef} clearFocus={clearFocus} lang={lang} loading={loading} error={loadError} found={models.some(m=>m.id===focusRef)} retry={()=>void load()}/><section className="ai-inventory-hero"><div><small>AI GOVERNANCE · MODEL REGISTRY</small><h3>AI Sistem ve Model Envanteri</h3><p>Her AI sistemi sahiplik, veri kullanımı, lokasyon, otonomi ve artık risk üzerinden izlenir.</p></div><a href={withBasePath("/api/ai/models?format=csv")}>Kanıt CSV</a></section><div className="ai-inventory-stats"><article><b>{summary.total}</b><span>Toplam</span></article><article><b>{summary.approved}</b><span>Onaylı</span></article><article><b>{summary.highRisk}</b><span>Yüksek/Kritik</span></article><article><b>{summary.overdue}</b><span>İncelemesi geciken</span></article></div>{provider&&<div className="ai-provider-link"><b>Fornost çalışma modeli</b><span>{provider.provider} · {provider.model} · {provider.enabled?"etkin":"kapalı"}</span></div>}
 {(!focusRef||editId)&&<form className="ai-inventory-form" onSubmit={submit}><b>{editId?"Taslak modeli düzenle":"Yeni AI sistemi kaydet"}</b><div><label><span>Sistem adı</span><input required value={form.systemName} onChange={e=>set("systemName",e.target.value)}/></label><label><span>Model</span><input required value={form.modelName} onChange={e=>set("modelName",e.target.value)}/></label><label><span>Sağlayıcı</span><input required value={form.vendor} onChange={e=>set("vendor",e.target.value)}/></label><label><span>Sorumlu</span><input required value={form.owner} onChange={e=>set("owner",e.target.value)}/></label><label><span>Dağıtım</span><select value={form.deployment} onChange={e=>set("deployment",e.target.value)}>{["External SaaS","Private Cloud","On-Prem","Local"].map(v=><option key={v}>{v}</option>)}</select></label><label><span>Veri lokasyonu</span><input value={form.region} onChange={e=>set("region",e.target.value)}/></label><label><span>Veri sınıfı</span><select value={form.dataClassification} onChange={e=>set("dataClassification",e.target.value)}>{["Public","Internal","Confidential","Restricted"].map(v=><option key={v}>{v}</option>)}</select></label><label><span>Karar rolü</span><select value={form.autonomy} onChange={e=>set("autonomy",e.target.value)}>{["Advisory","Human-reviewed","Human-approved","Autonomous"].map(v=><option key={v}>{v}</option>)}</select></label><label><span>Etkilenen kullanıcı</span><input type="number" min="0" value={form.affectedUsers} onChange={e=>set("affectedUsers",Number(e.target.value))}/></label><label><span>İnceleme tarihi</span><input required type="date" value={form.reviewDate} onChange={e=>set("reviewDate",e.target.value)}/></label></div><label><span>Kullanım amacı</span><textarea required rows={2} value={form.purpose} onChange={e=>set("purpose",e.target.value)}/></label><div className="ai-risk-factors">{factor("impact","Etki")}{factor("likelihood","Olasılık")}{factor("dataSensitivity","Veri hassasiyeti")}{factor("autonomyRisk","Otonomi riski")}{factor("controlMaturity","Kontrol olgunluğu")}</div><label><span>Uygulanan kontroller</span><textarea required rows={2} value={form.controls} onChange={e=>set("controls",e.target.value)}/></label><footer>{editId&&<button type="button" onClick={()=>{setEditId(null);setForm(initial);}}>Vazgeç</button>}<button disabled={busy}>{busy?"Kaydediliyor…":editId?"Güncelle":"Taslak oluştur"}</button></footer></form>}{notice&&<p className="ai-inventory-notice">{notice}</p>}
 <div className="ai-inventory-list">{models.filter(m=>!focusRef||m.id===focusRef).map(m=><article data-record-id={m.id} key={m.id}><header><div><small>{m.id.slice(0,12)}</small><b>{m.systemName}</b><span>{m.vendor} · {m.modelName}</span></div><div><em className={String(m.riskTier).toLowerCase()}>{m.riskTier} · {m.residualScore}</em><strong className={m.status}>{m.status}</strong></div></header><p>{m.purpose}</p><dl><div><dt>Sorumlu</dt><dd>{m.owner}</dd></div><div><dt>Çalışma</dt><dd>{m.deployment} · {m.region}</dd></div><div><dt>Veri / karar</dt><dd>{m.dataClassification} · {m.autonomy}</dd></div><div><dt>İnceleme</dt><dd className={m.overdue?"overdue":""}>{m.reviewDate}</dd></div></dl><small>{m.controls}</small>{m.decisionNote&&<aside>{m.decisionNote}</aside>}<footer>{m.status==="draft"&&<><button onClick={()=>edit(m)}>Düzenle</button><button className="danger" onClick={()=>void remove(m.id)}>Sil</button></>} {m.status!=="retired"&&<><button disabled={busy||loading||loadError||m.status==="approved"} onClick={()=>setDecision({id:m.id,expectedUpdatedAt:m.updatedAt,status:"approved",note:"",confirmation:""})}>Onayla</button><button className="warn" disabled={busy||loading||loadError||m.status==="suspended"} onClick={()=>setDecision({id:m.id,expectedUpdatedAt:m.updatedAt,status:"suspended",note:"",confirmation:""})}>Askıya al</button></>}</footer>{m.status!=="retired"&&<small>Emeklilik işlemi AI Emeklilik merkezindeki doğrulanmış plan üzerinden tamamlanır.</small>}{decision?.id===m.id&&<div className="ai-inventory-decision"><textarea rows={2} value={decision.note} onChange={e=>setDecision({...decision,note:e.target.value})} placeholder="Zorunlu karar notu"/><input value={decision.confirmation} onChange={e=>setDecision({...decision,confirmation:e.target.value})} placeholder={decision.status==="approved"?"ONAYLA":"ASKIYA AL"}/><div><button onClick={()=>setDecision(null)}>Vazgeç</button><button disabled={busy||decision.note.trim().length<5} onClick={()=>void decide()}>Kararı uygula</button></div></div>}</article>)}</div></div>}
