"use client";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { withBasePath } from "./base-path";

type Role = "Admin" | "Editor" | "Viewer";
type Item = { id:string;modelId:string;parentId:string|null;type:string;reference:string;title:string;justification:string;scope:string;compensatingControls:string;owner:string;riskTier:string;expiresAt:string;reviewAt:string;status:string;state:string;decisionNote:string|null;createdBy:string;createdAt:string;decidedBy:string|null };
const initial = { modelId:"",parentId:"",type:"policy",reference:"",title:"",justification:"",scope:"",compensatingControls:"",owner:"",riskTier:"Medium",expiresAt:"",reviewAt:"" };

export default function FornostAiExceptions({ role }: { role: Role }) {
  const [data,setData]=useState<{models:{id:string;systemName:string;modelName:string}[];exceptions:Item[];summary:Record<string,number>}>({models:[],exceptions:[],summary:{}}),
    [form,setForm]=useState(initial),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),
    [decision,setDecision]=useState<{id:string;status:"approved"|"rejected"|"revoked";note:string;confirmation:string}|null>(null);
  const load=useCallback(async()=>{const response=await fetch(withBasePath("/api/ai/exceptions"),{cache:"no-store"}),body=await response.json().catch(()=>({}));if(response.ok)setData(body);},[]);
  useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer);},[load]);
  async function create(event:FormEvent){event.preventDefault();setBusy(true);const response=await fetch(withBasePath("/api/ai/exceptions"),{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(form)}),body=await response.json().catch(()=>({}));setNotice(response.ok?"İstisna talebi maker-checker incelemesine gönderildi.":String(body.error||"İstisna kaydedilemedi."));if(response.ok){setForm(initial);await load();}setBusy(false);}
  const phrase=(status:string)=>status==="approved"?"İSTİSNAYI ONAYLA":status==="rejected"?"İSTİSNAYI REDDET":"İSTİSNAYI GERİ ÇEK";
  async function decide(){if(!decision)return;setBusy(true);const response=await fetch(withBasePath("/api/ai/exceptions"),{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(decision)}),body=await response.json().catch(()=>({}));setNotice(response.ok?"İstisna kararı audit izine kaydedildi.":String(body.error||"Karar uygulanamadı."));if(response.ok){setDecision(null);await load();}setBusy(false);}
  return <div className="ai-exceptions">
    <header><div><small>TIME-BOUND WAIVER · COMPENSATING CONTROL · MAKER-CHECKER</small><h3>AI İstisna ve Waiver Merkezi</h3><p>Politika, kontrol, risk ve release sapmalarını süreli, gerekçeli ve geri alınabilir kararlarla yönetin.</p></div>{role==="Admin"&&<a href={withBasePath("/api/ai/exceptions?format=csv")}>İstisna Kanıt CSV</a>}</header>
    <div className="stats">{[["total","Toplam"],["pending","Onay bekleyen"],["active","Etkin"],["overdue","Geciken/süresi dolan"],["highRisk","Yüksek/kritik"]].map(([key,label])=><article key={key}><b>{data.summary[key]||0}</b><span>{label}</span></article>)}</div>
    {notice&&<div className="notice">{notice}</div>}
    {role!=="Viewer"&&<form onSubmit={create}><b>Yeni kontrollü istisna talebi</b><div className="grid">
      <label><span>AI sistemi</span><select required value={form.modelId} onChange={event=>setForm({...form,modelId:event.target.value,parentId:""})}><option value="">Seçin</option>{data.models.map(model=><option key={model.id} value={model.id}>{model.systemName} · {model.modelName}</option>)}</select></label>
      <label><span>Tür</span><select value={form.type} onChange={event=>setForm({...form,type:event.target.value})}><option value="policy">Politika</option><option value="control">Kontrol</option><option value="risk">Risk</option><option value="release">Release</option></select></label>
      <label><span>Risk seviyesi</span><select value={form.riskTier} onChange={event=>setForm({...form,riskTier:event.target.value})}><option>Low</option><option>Medium</option><option>High</option><option>Critical</option></select></label>
      <label><span>Kontrol/politika referansı</span><input required maxLength={160} value={form.reference} onChange={event=>setForm({...form,reference:event.target.value})}/></label>
      <label><span>İnceleme tarihi</span><input required type="date" value={form.reviewAt} onChange={event=>setForm({...form,reviewAt:event.target.value})}/></label>
      <label><span>Süre sonu (en fazla 180 gün)</span><input required type="date" value={form.expiresAt} onChange={event=>setForm({...form,expiresAt:event.target.value})}/></label>
    </div><label><span>Başlık</span><input required maxLength={200} value={form.title} onChange={event=>setForm({...form,title:event.target.value})}/></label><label><span>İş gerekçesi</span><textarea required minLength={20} maxLength={2000} rows={3} value={form.justification} onChange={event=>setForm({...form,justification:event.target.value})}/></label><label><span>Sınırlandırılmış kapsam</span><textarea required minLength={10} maxLength={1200} rows={2} value={form.scope} onChange={event=>setForm({...form,scope:event.target.value})}/></label><label><span>Telafi edici kontroller ve izleme</span><textarea required minLength={20} maxLength={2000} rows={3} value={form.compensatingControls} onChange={event=>setForm({...form,compensatingControls:event.target.value})}/></label><label><span>İstisna sorumlusu</span><input required maxLength={320} value={form.owner} onChange={event=>setForm({...form,owner:event.target.value})}/></label><button disabled={busy}>İncelemeye Gönder</button><small>Kritik riskli istisnalar onaylanamaz. Talebi oluşturan kişi aynı kaydı onaylayamaz.</small></form>}
    <div className="list">{data.exceptions.map(item=><article key={item.id} className={item.state}><header><div><b>{item.title}</b><small>{item.reference} · {item.type} · {item.id}</small></div><span>{item.state}</span></header><p>{item.justification}</p><div className="controls"><span>{item.riskTier}</span><span>Sahip: {item.owner}</span><span>Review: {item.reviewAt}</span><span>Bitiş: {item.expiresAt}</span></div><details><summary>Kapsam ve telafi edici kontroller</summary><p>{item.scope}</p><p>{item.compensatingControls}</p></details>{item.decisionNote&&<em>{item.decidedBy} · {item.decisionNote}</em>}{role==="Admin"&&<footer>{item.status==="draft"&&<><button onClick={()=>setDecision({id:item.id,status:"approved",note:"",confirmation:""})}>Onayla</button><button className="danger" onClick={()=>setDecision({id:item.id,status:"rejected",note:"",confirmation:""})}>Reddet</button></>}{item.status==="approved"&&<button className="warn" onClick={()=>setDecision({id:item.id,status:"revoked",note:"",confirmation:""})}>Geri Çek</button>}</footer>}{decision?.id===item.id&&<div className="decision"><textarea rows={2} minLength={10} maxLength={1200} placeholder="Karar gerekçesi" value={decision.note} onChange={event=>setDecision({...decision,note:event.target.value})}/><input placeholder={phrase(decision.status)} value={decision.confirmation} onChange={event=>setDecision({...decision,confirmation:event.target.value})}/><div><button onClick={()=>setDecision(null)}>Vazgeç</button><button disabled={busy||decision.note.trim().length<10||decision.confirmation!==phrase(decision.status)} onClick={()=>void decide()}>Kararı Kaydet</button></div></div>}</article>)}</div>
  </div>;
}
