"use client";

import { useCallback,useEffect,useState } from "react";
import { withBasePath } from "./base-path";

type Profile="primary"|"fallback";
type BudgetProfile={profile:Profile;monthlyTokenLimit:number;warnPercent:number;hardLimit:boolean;promptCostPerMillion:number;completionCostPerMillion:number;currency:string;updatedBy:string;updatedAt:string;calls:number;promptTokens:number;completionTokens:number;tokens:number;estimatedCost:number;unmeteredCalls:number;usagePercent:number;state:"ready"|"warning"|"exceeded"};
type UsageRow={actor:string;operation:string;profile:Profile;provider:string;model:string;promptTokens:number;completionTokens:number;estimatedCost:number;currency:string;metered:boolean;createdAt:string};
type BudgetData={month:string;profiles:BudgetProfile[];actors:Array<{actor:string;tokens:number;calls:number}>;operations:Array<{operation:string;tokens:number;calls:number}>;recent:UsageRow[]};
const csvCell=(value:unknown)=>{const text=String(value??""),safe=/^[=+\-@]/.test(text)?`'${text}`:text;return `"${safe.replace(/"/g,'""')}"`;};
const profileLabel=(value:Profile)=>value==="primary"?"Birincil provider":"Yedek provider";
const tokens=(value:number)=>new Intl.NumberFormat("tr-TR").format(value);

export default function FornostAiBudget(){
  const [data,setData]=useState<BudgetData|null>(null),[editing,setEditing]=useState<BudgetProfile|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[notice,setNotice]=useState("");
  const load=useCallback(async()=>{setLoading(true);const response=await fetch(withBasePath("/api/ai/budget"),{cache:"no-store"}).catch(()=>null),body=await response?.json().catch(()=>({}))||{};if(response?.ok)setData(body as BudgetData);else setNotice(String(body.error||"AI kullanım bütçesi yüklenemedi."));setLoading(false);},[]);
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer);},[load]);
  async function save(){if(!editing||busy)return;setBusy(true);setNotice("");const response=await fetch(withBasePath("/api/ai/budget"),{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify(editing)}).catch(()=>null),body=await response?.json().catch(()=>({}))||{};if(response?.ok){setEditing(null);setNotice("AI bütçe politikası denetim izine kaydedildi.");await load();}else setNotice(String(body.error||"AI bütçe politikası kaydedilemedi."));setBusy(false);}
  function exportEvidence(){if(!data)return;const rows:Array<Array<unknown>>=[["Dönem","Aktör","İşlem","Profil","Provider","Model","Girdi token","Çıktı token","Tahmini maliyet","Para birimi","Ölçüm","Tarih"],...data.recent.map(row=>[data.month,row.actor,row.operation,row.profile,row.provider,row.model,row.promptTokens,row.completionTokens,row.estimatedCost.toFixed(6),row.currency,row.metered?"Provider ölçümü":"Kullanım bilgisi yok",row.createdAt])];const csv="\uFEFF"+rows.map(row=>row.map(csvCell).join(";")).join("\n"),url=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"})),link=document.createElement("a");link.href=url;link.download=`fornost-ai-kullanim-${data.month}.csv`;link.click();URL.revokeObjectURL(url);}
  if(loading&&!data)return <div className="fornost-ai-audit-empty">AI kullanım verileri yükleniyor…</div>;
  return <div className="fornost-ai-budget">
    <div className="fornost-ai-security-note"><b>AI kullanım ve maliyet yönetişimi</b><p>Token metadatası provider yanıtından alınır. Prompt ve model cevabı bütçe defterinde tutulmaz; sert limit dolduğunda ilgili provider profili güvenli biçimde durdurulur.</p></div>
    <div className="fornost-ai-budget-head"><div><b>{data?.month||"Bu ay"}</b><span>Aylık kullanım dönemi</span></div><div><button onClick={()=>void load()} disabled={loading||busy}>Yenile</button><button onClick={exportEvidence} disabled={!data?.recent.length}>Kanıt CSV</button></div></div>
    {notice&&<div className="fornost-ai-notice">{notice}</div>}
    <div className="fornost-ai-budget-profiles">{data?.profiles.map(item=><article key={item.profile} className={item.state}><header><div><b>{profileLabel(item.profile)}</b><small>{item.calls} çağrı · {item.unmeteredCalls} ölçümsüz</small></div><span>{item.monthlyTokenLimit?`%${item.usagePercent}`:"Limitsiz"}</span></header><div className="fornost-ai-budget-meter"><i style={{width:`${Math.min(100,item.monthlyTokenLimit?item.usagePercent:0)}%`}}/></div><dl><div><dt>Toplam token</dt><dd>{tokens(item.tokens)}</dd></div><div><dt>Girdi / çıktı</dt><dd>{tokens(item.promptTokens)} / {tokens(item.completionTokens)}</dd></div><div><dt>Tahmini maliyet</dt><dd>{item.estimatedCost.toFixed(4)} {item.currency}</dd></div><div><dt>Sert limit</dt><dd>{item.hardLimit?"Etkin":"Kapalı"}</dd></div></dl><button onClick={()=>setEditing({...item})}>Politikayı Düzenle</button>{editing?.profile===item.profile&&<div className="fornost-ai-budget-editor"><div><label><span>Aylık token limiti (0 = limitsiz)</span><input type="number" min="0" max="1000000000" step="1000" value={editing.monthlyTokenLimit} onChange={event=>setEditing(value=>value?{...value,monthlyTokenLimit:Number(event.target.value)}:value)}/></label><label><span>Uyarı eşiği (%)</span><input type="number" min="50" max="100" value={editing.warnPercent} onChange={event=>setEditing(value=>value?{...value,warnPercent:Number(event.target.value)}:value)}/></label></div><div><label><span>Girdi fiyatı / 1M token</span><input type="number" min="0" max="100000" step="0.01" value={editing.promptCostPerMillion} onChange={event=>setEditing(value=>value?{...value,promptCostPerMillion:Number(event.target.value)}:value)}/></label><label><span>Çıktı fiyatı / 1M token</span><input type="number" min="0" max="100000" step="0.01" value={editing.completionCostPerMillion} onChange={event=>setEditing(value=>value?{...value,completionCostPerMillion:Number(event.target.value)}:value)}/></label></div><div><label><span>Para birimi</span><input maxLength={3} value={editing.currency} onChange={event=>setEditing(value=>value?{...value,currency:event.target.value.toUpperCase()}:value)}/></label><label className="fornost-ai-check"><input type="checkbox" checked={editing.hardLimit} onChange={event=>setEditing(value=>value?{...value,hardLimit:event.target.checked}:value)}/><span>Limit dolunca çağrıları durdur</span></label></div><footer><button onClick={()=>setEditing(null)}>Vazgeç</button><button disabled={busy} onClick={()=>void save()}>Politikayı Kaydet</button></footer></div>}</article>)}</div>
    <div className="fornost-ai-budget-breakdown"><section><b>En yüksek kullanıcı tüketimi</b>{data?.actors.length?data.actors.map(row=><p key={row.actor}><span>{row.actor}<small>{row.calls} çağrı</small></span><strong>{tokens(row.tokens)} token</strong></p>):<p>Bu ay kullanım yok.</p>}</section><section><b>İşlem dağılımı</b>{data?.operations.length?data.operations.map(row=><p key={row.operation}><span>{row.operation}<small>{row.calls} çağrı</small></span><strong>{tokens(row.tokens)} token</strong></p>):<p>Bu ay kullanım yok.</p>}</section></div>
  </div>;
}
