"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { withBasePath } from "./base-path";

type Role="Admin"|"Editor"|"Viewer";
type KnowledgeSource={id:string;name:string;sourceType:string;classification:string;status:"draft"|"approved"|"archived";currentVersion:number;contentHash:string;characterCount:number;chunkCount:number;createdBy:string;createdAt:string;updatedBy:string;updatedAt:string;approvedBy:string|null;approvedAt:string|null;decisionNote:string|null};
type Action={id:string;kind:"approve"|"archive"|"version"|"delete";note:string;content:string;confirmation:string}|null;

export default function FornostAiKnowledge({role}:{role:Role}){
  const [sources,setSources]=useState<KnowledgeSource[]>([]),[busy,setBusy]=useState(false),[notice,setNotice]=useState(""),[action,setAction]=useState<Action>(null);
  const [form,setForm]=useState({name:"",sourceType:"markdown",classification:"Internal",content:""});
  const load=useCallback(async()=>{const response=await fetch(withBasePath("/api/ai/knowledge"),{cache:"no-store"}).catch(()=>null);if(response?.ok){const body=await response.json().catch(()=>({}));setSources(Array.isArray(body.sources)?body.sources:[]);}},[]);
  useEffect(()=>{const timer=window.setTimeout(()=>{void load();},0);return()=>window.clearTimeout(timer);},[load]);

  async function create(event:FormEvent){event.preventDefault();if(role!=="Admin"||busy)return;setBusy(true);setNotice("");const response=await fetch(withBasePath("/api/ai/knowledge"),{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(form)}).catch(()=>null),body=await response?.json().catch(()=>({}))||{};if(response?.ok){setForm({name:"",sourceType:"markdown",classification:"Internal",content:""});setNotice("Kaynak taslak olarak oluşturuldu; AI bağlamına girmesi için onaylayın.");await load();}else setNotice(String(body.error||"Kaynak oluşturulamadı."));setBusy(false);}

  async function submitAction(){if(!action||role!=="Admin"||busy)return;setBusy(true);setNotice("");let method="PATCH";const payload:Record<string,string>={id:action.id,note:action.note,confirmation:action.confirmation};if(action.kind==="approve")payload.decision="approved";if(action.kind==="archive")payload.decision="archived";if(action.kind==="version"){method="PUT";payload.content=action.content;}if(action.kind==="delete")method="DELETE";const response=await fetch(withBasePath("/api/ai/knowledge"),{method,headers:{"content-type":"application/json"},body:JSON.stringify(payload)}).catch(()=>null),body=await response?.json().catch(()=>({}))||{};if(response?.ok){setAction(null);setNotice(action.kind==="version"?"Yeni sürüm taslak olarak oluşturuldu; yeniden onay gerekli.":"İşlem tamamlandı.");await load();}else setNotice(String(body.error||"İşlem tamamlanamadı."));setBusy(false);}

  const confirmation=action?.kind==="approve"?"ONAYLA":action?.kind==="archive"?"ARŞİVLE":action?.kind==="version"?"YENİ SÜRÜM":"SİL";
  return <div className="fornost-ai-knowledge">
    <div className="fornost-ai-security-note"><b>Yönetişimli AI Bilgi Tabanı</b><p>Yalnız onaylı güncel sürümler kaynak gösterilerek kullanılır. Restricted içerik saklanabilir ancak model bağlamına hiçbir zaman gönderilmez.</p></div>
    {role==="Admin"&&<form className="fornost-ai-knowledge-form" onSubmit={create}><b>Yeni bilgi kaynağı</b><label><span>Kaynak adı</span><input required minLength={3} maxLength={160} value={form.name} onChange={e=>setForm(value=>({...value,name:e.target.value}))} placeholder="Örn. Bilgi Güvenliği Politikası"/></label><div><label><span>İçerik türü</span><select value={form.sourceType} onChange={e=>setForm(value=>({...value,sourceType:e.target.value}))}><option value="text">Metin</option><option value="markdown">Markdown</option><option value="html">HTML</option><option value="csv">CSV</option><option value="json">JSON</option></select></label><label><span>Veri sınıfı</span><select value={form.classification} onChange={e=>setForm(value=>({...value,classification:e.target.value}))}><option>Public</option><option>Internal</option><option>Confidential</option><option>Restricted</option></select></label></div><label><span>İçerik · en fazla 160.000 karakter</span><textarea required minLength={40} maxLength={160000} rows={6} value={form.content} onChange={e=>setForm(value=>({...value,content:e.target.value}))} placeholder="Politika veya referans içeriğini buraya yapıştırın…"/></label><button disabled={busy||form.content.trim().length<40}>Taslak Kaynak Oluştur</button></form>}
    {notice&&<div className="fornost-ai-notice">{notice}</div>}
    <div className="fornost-ai-knowledge-head"><b>{sources.length} bilgi kaynağı</b><button disabled={busy} onClick={()=>void load()}>Yenile</button></div>
    {!sources.length&&<div className="fornost-ai-audit-empty">Henüz bilgi kaynağı yok.</div>}
    <div className="fornost-ai-knowledge-list">{sources.map(source=><article key={source.id}><header><div><b>{source.name}</b><small>{source.id}</small></div><span className={source.status}>{source.status}</span></header><dl><div><dt>Sürüm</dt><dd>v{source.currentVersion}</dd></div><div><dt>Sınıf</dt><dd>{source.classification}</dd></div><div><dt>Boyut</dt><dd>{source.characterCount.toLocaleString("tr-TR")} karakter</dd></div><div><dt>Parça</dt><dd>{source.chunkCount}</dd></div></dl><p>{source.sourceType.toUpperCase()} · hash:{source.contentHash.slice(0,12)}…</p><small>{source.updatedBy} · {new Date(source.updatedAt).toLocaleString("tr-TR")}</small>{source.decisionNote&&<em>{source.approvedBy||source.updatedBy} · {source.decisionNote}</em>}
      {role==="Admin"&&<div className="fornost-ai-knowledge-actions">{source.status==="draft"&&<button onClick={()=>setAction({id:source.id,kind:"approve",note:"",content:"",confirmation:""})}>Onayla</button>}{source.status!=="archived"&&<button className="secondary" onClick={()=>setAction({id:source.id,kind:"version",note:"",content:"",confirmation:""})}>Yeni Sürüm</button>}{source.status!=="archived"&&<button className="warn" onClick={()=>setAction({id:source.id,kind:"archive",note:"",content:"",confirmation:""})}>Arşivle</button>}{source.status!=="approved"&&<button className="danger" onClick={()=>setAction({id:source.id,kind:"delete",note:"",content:"",confirmation:""})}>Sil</button>}</div>}
      {action?.id===source.id&&<div className="fornost-ai-knowledge-decision"><b>{action.kind==="approve"?"Kaynağı onayla":action.kind==="archive"?"Kaynağı arşivle":action.kind==="version"?"Yeni içerik sürümü":"Kaynağı kalıcı sil"}</b>{action.kind==="version"?<textarea rows={6} maxLength={160000} value={action.content} onChange={e=>setAction(value=>value?{...value,content:e.target.value}:value)} placeholder="Yeni sürümün tam içeriği…"/>:action.kind!=="delete"&&<textarea rows={2} maxLength={800} value={action.note} onChange={e=>setAction(value=>value?{...value,note:e.target.value}:value)} placeholder="Zorunlu karar notu…"/>}<input value={action.confirmation} onChange={e=>setAction(value=>value?{...value,confirmation:e.target.value}:value)} placeholder={confirmation}/><small>{action.kind==="version"?"Yeni sürüm önceki sürümü korur ve onayı sıfırlar.":action.kind==="delete"?"Tüm sürümler ve parçalar kalıcı olarak silinir.":`İşlemi doğrulamak için ${confirmation} yazın.`}</small><div><button className="secondary" onClick={()=>setAction(null)}>Vazgeç</button><button disabled={busy||action.confirmation!==confirmation||(action.kind==="version"&&action.content.trim().length<40)||(action.kind!=="version"&&action.kind!=="delete"&&action.note.trim().length<5)} onClick={()=>void submitAction()}>İşlemi Uygula</button></div></div>}
    </article>)}</div>
  </div>;
}
