"use client";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { withBasePath } from "./base-path";

type Model={id:string;systemName:string;modelName:string;status:string};
type Profile={id:string;modelId:string;classification:string;status:string};
type Obligation={id:string;modelId:string;profileId:string|null;renewalOfId:string|null;cycleNumber:number;framework:string;obligationCode:string;title:string;description:string;owner:string;reviewer:string;dueDate:string;priority:string;evidencePlan:string;recurringDays:number;status:string;state:string;daysRemaining:number;reminderLevel:string;evidenceReference:string|null;evidenceSha256:string|null;verifiedBy:string|null};
const initial={modelId:"",profileId:"",framework:"EU AI Act",obligationCode:"",title:"",description:"",owner:"",reviewer:"",dueDate:"",priority:"High",evidencePlan:"",recurringDays:0};
const phrase=(action:string)=>action==="start"?"YÜKÜMLÜLÜĞÜ BAŞLAT":action==="submit"?"DOĞRULAMAYA GÖNDER":action==="verify"?"YÜKÜMLÜLÜĞÜ DOĞRULA":"YÜKÜMLÜLÜĞÜ YENİDEN AÇ";

export default function FornostAiObligations(){
  const[data,setData]=useState<{frameworks:string[];priorities:string[];models:Model[];profiles:Profile[];obligations:Obligation[];reminders:Obligation[];summary:Record<string,number>}>({frameworks:[],priorities:[],models:[],profiles:[],obligations:[],reminders:[],summary:{}}),[form,setForm]=useState(initial),[action,setAction]=useState<{id:string;action:string;note:string;evidenceReference:string;evidenceSha256:string;confirmation:string}|null>(null),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false);
  const load=useCallback(async()=>{const response=await fetch(withBasePath("/api/ai/obligations"),{cache:"no-store"}),body=await response.json().catch(()=>({}));if(response.ok)setData(body);},[]);
  useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer);},[load]);
  async function send(method:string,body:unknown){setBusy(true);const response=await fetch(withBasePath("/api/ai/obligations"),{method,headers:{"content-type":"application/json"},body:JSON.stringify(body)}),result=await response.json().catch(()=>({}));setNotice(response.ok?(method==="POST"?"Yükümlülük kaydı oluşturuldu.":"Yükümlülük akışı güncellendi."):String(result.error||"İşlem başarısız."));if(response.ok){setAction(null);if(method==="POST")setForm(initial);await load();}setBusy(false);}
  async function create(event:FormEvent){event.preventDefault();await send("POST",form);}
  const begin=(item:Obligation,next:string)=>setAction({id:item.id,action:next,note:"",evidenceReference:"",evidenceSha256:"",confirmation:""});
  return <section className="ai-obligations">
    <header><div><small>ACCOUNTABILITY · DEADLINE · EVIDENCE</small><h3>AI Yükümlülük Takibi</h3><p>Regülasyon gereksinimlerini sorumlu, son tarih, periyodik yenileme, kanıt ve bağımsız doğrulama akışıyla kapatın.</p></div><div className="exports"><a href={withBasePath("/api/ai/obligations?format=reminders")}>Uyarı Kuyruğu CSV</a><a href={withBasePath("/api/ai/obligations?format=csv")}>Kanıt CSV</a></div></header>
    <div className="stats">{[["total","Toplam"],["open","Açık"],["due30","30 gün"],["due15","15 gün"],["due7","7 gün"],["overdue","Geciken"],["blocking","Bloke eden"],["completed","Tamamlanan"]].map(([key,label])=><article key={key}><b>{data.summary[key]||0}</b><span>{label}</span></article>)}</div>
    <form onSubmit={create}><b>Yeni operasyonel yükümlülük</b><div className="grid">
      <label>AI sistemi<select required value={form.modelId} onChange={event=>setForm({...form,modelId:event.target.value,profileId:""})}><option value="">Seçin</option>{data.models.map(model=><option key={model.id} value={model.id}>{model.systemName} · {model.modelName}</option>)}</select></label>
      <label>Regülasyon profili<select value={form.profileId} onChange={event=>setForm({...form,profileId:event.target.value})}><option value="">Bağımsız kayıt</option>{data.profiles.filter(profile=>profile.modelId===form.modelId).map(profile=><option key={profile.id} value={profile.id}>{profile.classification} · {profile.status}</option>)}</select></label>
      <label>Çerçeve<select value={form.framework} onChange={event=>setForm({...form,framework:event.target.value})}>{data.frameworks.map(value=><option key={value}>{value}</option>)}</select></label>
      <label>Yükümlülük kodu<input required value={form.obligationCode} onChange={event=>setForm({...form,obligationCode:event.target.value})} placeholder="EU-AIA-26.2 / A.6.2.6"/></label>
      <label>Başlık<input required value={form.title} onChange={event=>setForm({...form,title:event.target.value})}/></label>
      <label>Öncelik<select value={form.priority} onChange={event=>setForm({...form,priority:event.target.value})}>{data.priorities.map(value=><option key={value}>{value}</option>)}</select></label>
      <label>Sahip<input required value={form.owner} onChange={event=>setForm({...form,owner:event.target.value})}/></label>
      <label>Bağımsız doğrulayıcı<input required value={form.reviewer} onChange={event=>setForm({...form,reviewer:event.target.value})}/></label>
      <label>Son tarih<input required type="date" value={form.dueDate} onChange={event=>setForm({...form,dueDate:event.target.value})}/></label>
      <label>Tekrar (gün)<input type="number" min="0" max="3650" value={form.recurringDays} onChange={event=>setForm({...form,recurringDays:Number(event.target.value)})}/></label>
    </div><label>Açıklama<textarea required rows={2} value={form.description} onChange={event=>setForm({...form,description:event.target.value})}/></label><label>Kanıt ve doğrulama planı<textarea required rows={2} value={form.evidencePlan} onChange={event=>setForm({...form,evidencePlan:event.target.value})}/></label><button disabled={busy}>Yükümlülüğü kaydet</button></form>
    {notice&&<p className="notice">{notice}</p>}
    {!!data.reminders.length&&<div className="reminder-queue"><header><div><small>DEADLINE ESCALATION</small><b>Yaklaşan ve geciken yükümlülükler</b></div><span>{data.reminders.length} aksiyon</span></header>{data.reminders.slice(0,8).map(item=><article key={`reminder-${item.id}`}><div><b>{item.title}</b><small>{item.owner} · {item.framework} · dönem {item.cycleNumber}</small></div><strong className={item.reminderLevel}>{item.daysRemaining<0?`${Math.abs(item.daysRemaining)} gün gecikti`:item.daysRemaining===0?"Bugün":`${item.daysRemaining} gün kaldı`}</strong></article>)}</div>}
    <div className="list">{data.obligations.map(item=><article key={item.id} className={`${item.state} ${item.priority.toLowerCase()}`}><header><div><small>{item.framework} · {item.obligationCode} · dönem {item.cycleNumber}</small><b>{item.title}</b></div><div><em>{item.priority}</em><span>{item.state}</span></div></header><p>{item.description}</p><dl><div><dt>Sahip</dt><dd>{item.owner}</dd></div><div><dt>Doğrulayıcı</dt><dd>{item.reviewer}</dd></div><div><dt>Son tarih</dt><dd>{item.dueDate}{item.status!=="completed"&&` · ${item.daysRemaining<0?`${Math.abs(item.daysRemaining)} gün gecikti`:`${item.daysRemaining} gün`}`}</dd></div><div><dt>Tekrar</dt><dd>{item.recurringDays?`${item.recurringDays} gün`:"Tek sefer"}</dd></div></dl>{item.renewalOfId&&<aside><b>Yenileme zinciri</b>Önceki dönem: {item.renewalOfId}</aside>}<aside><b>Kanıt planı</b>{item.evidencePlan}</aside>{item.evidenceReference&&<aside><b>Uygulama kanıtı</b>{item.evidenceReference}<code>{item.evidenceSha256}</code></aside>}<footer>{item.status==="open"&&<button onClick={()=>begin(item,"start")}>Başlat</button>}{item.status==="in-progress"&&<button onClick={()=>begin(item,"submit")}>Doğrulamaya gönder</button>}{item.status==="verification"&&<><button onClick={()=>begin(item,"verify")}>Doğrula ve dönemi yenile</button><button className="warn" onClick={()=>begin(item,"reopen")}>İade et</button></>}{item.status==="completed"&&<button className="warn" onClick={()=>begin(item,"reopen")}>Yeniden aç</button>}</footer>{action?.id===item.id&&<div className="action"><textarea rows={2} placeholder="İşlem ve karar notu" value={action.note} onChange={event=>setAction({...action,note:event.target.value})}/>{["submit","verify"].includes(action.action)&&<><input placeholder="Kanıt referansı" value={action.evidenceReference} onChange={event=>setAction({...action,evidenceReference:event.target.value})}/><input placeholder="SHA-256 (64 hex)" value={action.evidenceSha256} onChange={event=>setAction({...action,evidenceSha256:event.target.value})}/></>}<input placeholder={phrase(action.action)} value={action.confirmation} onChange={event=>setAction({...action,confirmation:event.target.value})}/><div><button onClick={()=>setAction(null)}>Vazgeç</button><button disabled={busy} onClick={()=>void send("PATCH",action)}>Uygula</button></div></div>}</article>)}</div>
  </section>;
}
