"use client";

import { useCallback,useEffect,useState } from "react";
import { withBasePath } from "./base-path";

type FeedbackStatus="open"|"in_review"|"resolved"|"dismissed";
type FeedbackKind="helpful"|"incorrect"|"incomplete"|"unsafe";
type FeedbackSeverity="low"|"medium"|"high"|"critical";
type FeedbackItem={id:string;activityId:string;kind:FeedbackKind;severity:FeedbackSeverity;comment:string;status:FeedbackStatus;assignedTo:string|null;resolutionNote:string|null;createdBy:string;createdAt:string;updatedBy:string;updatedAt:string;resolvedBy:string|null;resolvedAt:string|null;provider:string|null;model:string|null};
type Summary={total:number;unresolved:number;highRisk:number;resolved:number;helpful:number};
type Decision={id:string;status:"resolved"|"dismissed";assignedTo:string;resolutionNote:string};

const statusLabels:Record<FeedbackStatus,string>={open:"Açık",in_review:"İncelemede",resolved:"Çözüldü",dismissed:"Geçersiz"};
const kindLabels:Record<FeedbackKind,string>={helpful:"Yararlı",incorrect:"Yanlış",incomplete:"Eksik",unsafe:"Güvenlik olayı"};
const severityLabels:Record<FeedbackSeverity,string>={low:"Düşük",medium:"Orta",high:"Yüksek",critical:"Kritik"};
const csvCell=(value:unknown)=>{const text=String(value??""),safe=/^[=+\-@]/.test(text)?`'${text}`:text;return `"${safe.replace(/"/g,'""')}"`;};

export default function FornostAiFeedback({actor}:{actor:string}){
  const [items,setItems]=useState<FeedbackItem[]>([]),[summary,setSummary]=useState<Summary>({total:0,unresolved:0,highRisk:0,resolved:0,helpful:0});
  const [status,setStatus]=useState(""),[kind,setKind]=useState(""),[severity,setSeverity]=useState(""),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[notice,setNotice]=useState(""),[decision,setDecision]=useState<Decision|null>(null);

  const load=useCallback(async()=>{setLoading(true);const query=new URLSearchParams({limit:"100"});if(status)query.set("status",status);if(kind)query.set("kind",kind);if(severity)query.set("severity",severity);const response=await fetch(withBasePath(`/api/ai/feedback?${query}`),{cache:"no-store"}).catch(()=>null);const body=await response?.json().catch(()=>({}))||{};if(response?.ok){setItems(Array.isArray(body.items)?body.items:[]);setSummary(body.summary||{total:0,unresolved:0,highRisk:0,resolved:0,helpful:0});}else setNotice(String(body.error||"AI geri bildirim kayıtları yüklenemedi."));setLoading(false);},[status,kind,severity]);
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer);},[load]);

  async function transition(id:string,nextStatus:FeedbackStatus,assignedTo=actor,resolutionNote=""){if(busy)return;setBusy(true);setNotice("");const response=await fetch(withBasePath("/api/ai/feedback"),{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,status:nextStatus,assignedTo,resolutionNote})}).catch(()=>null);const body=await response?.json().catch(()=>({}))||{};if(response?.ok){setDecision(null);setNotice(nextStatus==="in_review"?"Kayıt incelemeye alındı.":nextStatus==="open"?"Kayıt yeniden açıldı.":"Triage kararı denetim izine kaydedildi.");await load();}else setNotice(String(body.error||"Kayıt güncellenemedi."));setBusy(false);}
  function exportEvidence(){const rows:Array<Array<unknown>>=[["Kayıt ID","AI aktivite ID","Tür","Önem","Durum","Bildiren","Bildirim tarihi","Sorumlu","Provider","Model","Açıklama","Çözüm notu","Çözen","Çözüm tarihi"],...items.map(item=>[item.id,item.activityId,kindLabels[item.kind],severityLabels[item.severity],statusLabels[item.status],item.createdBy,item.createdAt,item.assignedTo||"",item.provider||"",item.model||"",item.comment,item.resolutionNote||"",item.resolvedBy||"",item.resolvedAt||""])];const csv="\uFEFF"+rows.map(row=>row.map(csvCell).join(";")).join("\n"),url=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"})),link=document.createElement("a");link.href=url;link.download="fornost-ai-geri-bildirim-kaniti.csv";link.click();URL.revokeObjectURL(url);}

  return <div className="fornost-ai-feedback">
    <div className="fornost-ai-security-note"><b>AI geri bildirim ve olay yönetimi</b><p>Kullanıcı bildirimleri ilgili AI aktivitesine bağlanır. Ham soru ve model yanıtı saklanmaz; kritik açık kayıtlar kalite hazırlığını etkiler.</p></div>
    <div className="fornost-ai-feedback-summary"><article><b>{summary.unresolved}</b><span>Açık / incelemede</span></article><article className={summary.highRisk?"attention":"ready"}><b>{summary.highRisk}</b><span>Yüksek / kritik açık</span></article><article><b>{summary.resolved}</b><span>Çözüldü</span></article><article><b>{summary.helpful}</b><span>Yararlı bildirim</span></article></div>
    <div className="fornost-ai-feedback-toolbar"><div><select aria-label="Durum filtresi" value={status} onChange={event=>setStatus(event.target.value)}><option value="">Tüm durumlar</option><option value="open">Açık</option><option value="in_review">İncelemede</option><option value="resolved">Çözüldü</option><option value="dismissed">Geçersiz</option></select><select aria-label="Tür filtresi" value={kind} onChange={event=>setKind(event.target.value)}><option value="">Tüm türler</option><option value="helpful">Yararlı</option><option value="incorrect">Yanlış</option><option value="incomplete">Eksik</option><option value="unsafe">Güvenlik olayı</option></select><select aria-label="Önem filtresi" value={severity} onChange={event=>setSeverity(event.target.value)}><option value="">Tüm önemler</option><option value="low">Düşük</option><option value="medium">Orta</option><option value="high">Yüksek</option><option value="critical">Kritik</option></select></div><div><button onClick={()=>void load()} disabled={loading||busy}>Yenile</button><button onClick={exportEvidence} disabled={!items.length}>Kanıt CSV</button></div></div>
    {notice&&<div className="fornost-ai-notice">{notice}</div>}
    {loading?<div className="fornost-ai-audit-empty">Kayıtlar yükleniyor…</div>:!items.length?<div className="fornost-ai-audit-empty">Seçili filtrelerde geri bildirim kaydı yok.</div>:<div className="fornost-ai-feedback-list">{items.map(item=><article key={item.id} className={`${item.status} ${item.severity}`}><header><div><b>{kindLabels[item.kind]}</b><small>{item.id}</small></div><div><span className={item.severity}>{severityLabels[item.severity]}</span><span className={item.status}>{statusLabels[item.status]}</span></div></header><p>{item.comment||"Kullanıcı bu yanıtı yararlı olarak işaretledi."}</p><dl><div><dt>Bildiren</dt><dd>{item.createdBy}</dd></div><div><dt>Sorumlu</dt><dd>{item.assignedTo||"Atanmadı"}</dd></div><div><dt>Model</dt><dd>{item.provider||"-"} · {item.model||"-"}</dd></div><div><dt>Tarih</dt><dd>{new Date(item.createdAt).toLocaleString("tr-TR")}</dd></div></dl>{item.resolutionNote&&<div className="fornost-ai-feedback-resolution"><b>Karar notu</b><p>{item.resolutionNote}</p><small>{item.resolvedBy} · {item.resolvedAt?new Date(item.resolvedAt).toLocaleString("tr-TR"):""}</small></div>}<div className="fornost-ai-governance-actions">{item.status==="open"&&<button disabled={busy} onClick={()=>void transition(item.id,"in_review")}>İncelemeye Al</button>}{(item.status==="open"||item.status==="in_review")&&<><button disabled={busy} onClick={()=>setDecision({id:item.id,status:"resolved",assignedTo:item.assignedTo||actor,resolutionNote:""})}>Çöz</button><button className="warn" disabled={busy} onClick={()=>setDecision({id:item.id,status:"dismissed",assignedTo:item.assignedTo||actor,resolutionNote:""})}>Geçersiz İşaretle</button></>}{(item.status==="resolved"||item.status==="dismissed")&&<button disabled={busy} onClick={()=>void transition(item.id,"open",item.assignedTo||actor)}>Yeniden Aç</button>}</div>{decision?.id===item.id&&<form className="fornost-ai-feedback-decision" onSubmit={event=>{event.preventDefault();void transition(decision.id,decision.status,decision.assignedTo,decision.resolutionNote);}}><b>{decision.status==="resolved"?"Çözüm kaydı":"Geçersiz bildirim kararı"}</b><label><span>Sorumlu</span><input maxLength={320} value={decision.assignedTo} onChange={event=>setDecision(value=>value?{...value,assignedTo:event.target.value}:value)}/></label><label><span>Zorunlu karar notu</span><textarea rows={3} maxLength={1200} value={decision.resolutionNote} onChange={event=>setDecision(value=>value?{...value,resolutionNote:event.target.value}:value)}/></label><div><button type="button" onClick={()=>setDecision(null)}>Vazgeç</button><button disabled={busy||decision.resolutionNote.trim().length<5}>Kararı Kaydet</button></div></form>}</article>)}</div>}
  </div>;
}
