"use client";
import { FormEvent,useCallback,useEffect,useState } from "react";
import { withBasePath } from "./base-path";
type Role="Admin"|"Editor"|"Viewer";
type Finding={id:string;modelId:string;domain:string;sourceRef:string;title:string;description:string;rootCause:string;correctiveAction:string;preventiveAction:string;owner:string;severity:string;dueDate:string;status:string;state:string;actionNote:string|null;evidenceReference:string|null;evidenceSha256:string|null;createdBy:string;submittedBy:string|null;verifiedBy:string|null};
const initial={modelId:"",domain:"control",sourceRef:"",title:"",description:"",rootCause:"",correctiveAction:"",preventiveAction:"",owner:"",severity:"Medium",dueDate:""};
export default function FornostAiFindings({role}:{role:Role}){
 const[data,setData]=useState<{models:{id:string;systemName:string;modelName:string}[];domains:string[];findings:Finding[];summary:Record<string,number>}>({models:[],domains:[],findings:[],summary:{}}),[form,setForm]=useState(initial),[action,setAction]=useState<{id:string;action:"start"|"submit"|"resolve"|"reopen";note:string;confirmation:string;evidenceReference:string;evidenceSha256:string}|null>(null),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{const response=await fetch(withBasePath("/api/ai/findings"),{cache:"no-store"}),body=await response.json().catch(()=>({}));if(response.ok)setData(body);},[]);
 useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer);},[load]);
 async function create(event:FormEvent){event.preventDefault();setBusy(true);const response=await fetch(withBasePath("/api/ai/findings"),{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(form)}),body=await response.json().catch(()=>({}));setNotice(response.ok?"AI bulgusu CAPA kuyruğuna eklendi.":String(body.error||"Bulgu kaydedilemedi."));if(response.ok){setForm(initial);await load();}setBusy(false);}
 const phrase=(value:string)=>value==="start"?"AKSİYONU BAŞLAT":value==="submit"?"DOĞRULAMAYA GÖNDER":value==="resolve"?"BULGUYU KAPAT":"BULGUYU YENİDEN AÇ";
 async function apply(){if(!action)return;setBusy(true);const response=await fetch(withBasePath("/api/ai/findings"),{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(action)}),body=await response.json().catch(()=>({}));setNotice(response.ok?"Bulgu geçişi ve kanıtı audit izine kaydedildi.":String(body.error||"İşlem uygulanamadı."));if(response.ok){setAction(null);await load();}setBusy(false);}
 const open=(id:string,value:"start"|"submit"|"resolve"|"reopen")=>setAction({id,action:value,note:"",confirmation:"",evidenceReference:"",evidenceSha256:""});
 return <div className="ai-findings"><header><div><small>CAPA · ROOT CAUSE · INDEPENDENT VERIFICATION</small><h3>AI Bulguları ve Düzeltici Aksiyonlar</h3><p>Güvence açıklarını kök neden, SLA, düzeltici ve önleyici aksiyonlarla kanıtlı kapanışa taşıyın.</p></div>{role==="Admin"&&<a href={withBasePath("/api/ai/findings?format=csv")}>Bulgu Kanıt CSV</a>}</header>
 <div className="stats">{[["total","Toplam"],["open","Açık"],["inProgress","Aksiyonda"],["verification","Doğrulamada"],["overdue","Geciken"],["highRisk","Yüksek/kritik"],["resolved","Kapatılan"]].map(([key,label])=><article key={key}><b>{data.summary[key]||0}</b><span>{label}</span></article>)}</div>{notice&&<div className="notice">{notice}</div>}
 {role!=="Viewer"&&<form onSubmit={create}><b>Yeni kaynak bağlantılı AI bulgusu</b><div className="grid"><label><span>AI sistemi</span><select required value={form.modelId} onChange={event=>setForm({...form,modelId:event.target.value})}><option value="">Seçin</option>{data.models.map(model=><option key={model.id} value={model.id}>{model.systemName} · {model.modelName}</option>)}</select></label><label><span>Güvence alanı</span><select value={form.domain} onChange={event=>setForm({...form,domain:event.target.value})}>{data.domains.map(domain=><option key={domain}>{domain}</option>)}</select></label><label><span>Kaynak kayıt/kontrol referansı</span><input required maxLength={160} value={form.sourceRef} onChange={event=>setForm({...form,sourceRef:event.target.value})}/></label><label><span>Önem</span><select value={form.severity} onChange={event=>setForm({...form,severity:event.target.value})}><option>Low</option><option>Medium</option><option>High</option><option>Critical</option></select></label><label><span>SLA tarihi</span><input required type="date" value={form.dueDate} onChange={event=>setForm({...form,dueDate:event.target.value})}/></label><label><span>Sorumlu</span><input required maxLength={320} value={form.owner} onChange={event=>setForm({...form,owner:event.target.value})}/></label></div><label><span>Bulgu başlığı</span><input required minLength={5} maxLength={200} value={form.title} onChange={event=>setForm({...form,title:event.target.value})}/></label>{[["description","Bulgu ve etki"],["rootCause","Kök neden analizi"],["correctiveAction","Düzeltici aksiyon"],["preventiveAction","Tekrarı önleyici aksiyon"]].map(([key,label])=><label key={key}><span>{label}</span><textarea required minLength={20} maxLength={2000} rows={2} value={form[key as keyof typeof form]} onChange={event=>setForm({...form,[key]:event.target.value})}/></label>)}<button disabled={busy}>Bulgu Oluştur</button></form>}
 <div className="list">{data.findings.map(item=><article key={item.id} className={item.state}><header><div><b>{item.title}</b><small>{item.id} · {item.domain} · {item.sourceRef}</small></div><span>{item.state}</span></header><p>{item.description}</p><div className="chips"><span>{item.severity}</span><span>{item.owner}</span><span>SLA: {item.dueDate}</span></div><details><summary>Kök neden ve CAPA</summary><p><b>Kök neden:</b> {item.rootCause}</p><p><b>Düzeltici:</b> {item.correctiveAction}</p><p><b>Önleyici:</b> {item.preventiveAction}</p></details>{item.evidenceSha256&&<code title={item.evidenceSha256}>SHA-256: {item.evidenceSha256}</code>}<footer>{item.status==="open"&&role!=="Viewer"&&<button onClick={()=>open(item.id,"start")}>Başlat</button>}{item.status==="in-progress"&&role!=="Viewer"&&<button onClick={()=>open(item.id,"submit")}>Doğrulamaya Gönder</button>}{item.status==="verification"&&role==="Admin"&&<><button onClick={()=>open(item.id,"resolve")}>Doğrula ve Kapat</button><button className="warn" onClick={()=>open(item.id,"reopen")}>İade Et</button></>}{item.status==="resolved"&&role==="Admin"&&<button className="warn" onClick={()=>open(item.id,"reopen")}>Yeniden Aç</button>}</footer>{action?.id===item.id&&<div className="action"><textarea rows={2} minLength={10} maxLength={1200} placeholder="İşlem açıklaması" value={action.note} onChange={event=>setAction({...action,note:event.target.value})}/>{["submit","resolve"].includes(action.action)&&<><input maxLength={300} placeholder="Kanıt referansı" value={action.evidenceReference} onChange={event=>setAction({...action,evidenceReference:event.target.value})}/><input maxLength={64} placeholder="64 karakter SHA-256" value={action.evidenceSha256} onChange={event=>setAction({...action,evidenceSha256:event.target.value})}/></>}<input placeholder={phrase(action.action)} value={action.confirmation} onChange={event=>setAction({...action,confirmation:event.target.value})}/><div><button onClick={()=>setAction(null)}>Vazgeç</button><button disabled={busy} onClick={()=>void apply()}>İşlemi Uygula</button></div></div>}</article>)}</div></div>;
}
