import asvsManifest from "./asvs-catalog-manifest.json";
import nistManifest from "./nist-catalog-manifest.json";
export type CatalogStatus = { tr: string; en: string; source?: string; reviewed?: string };
const reviewed = "2026-10-05";
const iso = (id: string): CatalogStatus => ({ reviewed, source: `https://www.iso.org/standard/${id}`, tr: "Baskı doğrulandı. Yalnızca yerel hazırlık konuları içerir; LOCAL referansları standart maddesi değildir. Lisanslı metinle madde eşlemesi henüz tamamlanmadı.", en: "Edition verified. Local preparation topics only; LOCAL references are not standard clauses. Mapping against the licensed text is not complete." });
export const catalogStatuses: Record<string, CatalogStatus> = {
  "ISO/IEC 27701:2025": iso("27701"),
  "ISO/IEC 27017:2026": iso("27017"),
  "ISO/IEC 27018:2025": iso("27018"),
  "NIST Cybersecurity Framework (CSF) 2.0": { reviewed, source: "https://nvlpubs.nist.gov/nistpubs/CSWP/NIST.CSWP.29.pdf", tr: "Core kapsamı: 6 fonksiyon, 22 kategori, 106 alt kategorinin tamamı. Türkçe özetlerdir; resmî çeviri veya sertifikasyon kontrol listesi değildir.", en: "Core coverage: all 106 subcategories across 22 categories and 6 functions. Turkish summaries, not an official translation or certification checklist." },
  "PCI DSS 4.0.1": { reviewed, source: "https://www.pcisecuritystandards.org/document_library/", tr: "12 ana gereksinim özeti. Alt gereksinimler, test prosedürleri ve uygulanabilirlik koşulları dahil değildir.", en: "Overview of 12 principal requirements. Subrequirements, testing procedures and applicability conditions are not included." },
  "CIS Controls v8.1": { reviewed, source: "https://www.cisecurity.org/controls/v8-1", tr: "18 ana kontrol özeti. 153 safeguard tam metni için yetkili katalog yükleyin; ticari ürün dağıtımı için CIS kullanım hakkı gerekir.", en: "18 principal control summaries. Import an authorized catalog for all 153 safeguards; commercial product distribution requires CIS usage rights." },
  "KVKK (6698)": { reviewed, source: "https://www.kvkk.gov.tr/Icerik/8170/Yurt-Disina-Kisisel-Veri-Aktariminda-Kullanilacak-Standart-Sozlesmelerde-Dikkat-Edilmesi-Gereken-Hususlara-Iliskin-Kamuoyu-Duyurusu", tr: "Seçilmiş yükümlülükler. 2024 yurt dışına aktarım değişikliği ve standart sözleşme bildirim süresi işlendi. Tüm ikincil düzenlemeler ve Kurul kararları dahil değildir; LOCAL referansları yerel konulardır.", en: "Selected obligations, including the 2024 cross-border transfer change and standard-contract notification deadline. Not all secondary legislation or Board decisions are included; LOCAL references are local topics." },
};
for (const [previous, current] of [["ISO/IEC 27701:2019", "ISO/IEC 27701:2025"], ["ISO/IEC 27017:2015", "ISO/IEC 27017:2026"], ["ISO/IEC 27018:2019", "ISO/IEC 27018:2025"]]) {
  catalogStatuses[previous] = { source: catalogStatuses[current].source, reviewed, tr: `Eski katalog. Yeni baskı: ${current}. Mevcut kayıtlar korunur; otomatik madde dönüşümü yapılmaz.`, en: `Legacy catalog. New edition: ${current}. Existing records are preserved; clauses are not automatically migrated.` };
}
for (const pack of nistManifest) {
  catalogStatuses[pack.name] = {reviewed,source:pack.source,tr:`${pack.count} etkin kayıt; ${pack.withdrawn.length} geri çekilmiş kayıt hariç tutuldu. Resmî İngilizce gereksinimler, mevcut rehberlik ve değerlendirme adımları dahil. Kuruluşa özel parametreler ayrıca belirlenmelidir. Bu tam katalog bir uygulanabilirlik kararı değildir.`,en:`${pack.count} active entries; ${pack.withdrawn.length} withdrawn entries excluded. Official English requirements, available guidance and assessment steps included. Organization-defined parameters require tailoring. Full catalog coverage does not imply applicability.`};
}
catalogStatuses[asvsManifest.name]={reviewed,source:asvsManifest.source,tr:`${asvsManifest.count} gereksinimin tamamı; İngilizce metinler ve L1/L2/L3 düzeyleri dahil. © OWASP Foundation, CC BY-SA 4.0. İçerik lisansı: https://creativecommons.org/licenses/by-sa/4.0/ .`,en:`All ${asvsManifest.count} requirements with English text and L1/L2/L3 levels. © OWASP Foundation, CC BY-SA 4.0. Content license: https://creativecommons.org/licenses/by-sa/4.0/ .`};
export function getCatalogStatus(framework: string): CatalogStatus {
  if (catalogStatuses[framework]) return catalogStatuses[framework];
  if (framework.startsWith("SOC 1")) return {tr:"SOC 1, finansal raporlamaya ilişkin kuruluş ve hizmet kapsamına özel kontrol hedefleri gerektirir; evrensel sabit bir kontrol listesi değildir. Denetçiyle belirlenen hedef ve kontrolleri kurum kataloğu olarak yükleyin.",en:"SOC 1 requires service-specific control objectives relevant to financial reporting; there is no universal fixed control list. Import the objectives and controls agreed with the auditor."};
  if (framework.startsWith("SOC 2") || framework === "SOC 3") return { source: "https://www.aicpa-cima.com/resources/download/2017-trust-services-criteria-with-revised-points-of-focus-2022", tr: "Beş kategoride 61 kriter referansı ve kısa konu başlığı. 2022 points of focus ve tam kriter metni dahil değildir. Denetim kapsamı ve uygulanabilirliği ayrıca belirlenir. Tam yetkili içeriği kurum kataloğu olarak yükleyebilirsiniz.", en: "61 criterion references with brief topic labels across five categories. Full criterion text and revised 2022 points of focus are not included. Scope and applicability require separate decisions. Authorized full content can be imported." };
  if (framework === "ISO/IEC 27001:2022") return { source: "https://www.iso.org/standard/27001", tr: "30 yönetim sistemi alt maddesi ve 93 Ek A kontrolü: toplam 123 referans. Amd 1:2024 iklim hususları 4.1/4.2 özetlerine işlendi. Kısa konu başlıklarıdır; lisanslı tam gereksinim metni değildir.", en: "123 references: 30 management-system subclauses and 93 Annex A controls. Amd 1:2024 climate considerations are included in 4.1/4.2 summaries. Brief topic labels, not the licensed full requirement text." };
  return { tr: "Kısmi veya kullanıcı tanımlı kapsam. Güncel baskı, tüm maddeler ve ikincil düzenlemeler için doğrulama tamamlanmadı. Seçenek olarak bulunması tam kapsam anlamına gelmez.", en: "Partial or user-defined coverage. Current edition, full clauses and secondary legislation have not been fully verified. Availability in the selector does not imply complete coverage." };
}
