"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
import {withBasePath} from "./base-path";
import {incidentRecoveryHours,incidentResponseHours} from "./incidents/domain";
import "./incident-center.css";
type Lang="tr"|"en";
type Incident={id:string;code:string;title:string;category:string;severity:string;detectedDate:string;description:string;businessImpact:string;owner:string;commander:string;reviewer:string;assetRefs:string;riskRef?:string;biaRef?:string;dataClassification:string;personalData:boolean;status:string;rootCause?:string;lessonsLearned?:string;notificationDecision:string;notificationRationale?:string;reopenCount:number;attention:string;updatedAt:string};
type Summary={total:number;active:number;critical:number;breached:number;contained:number;recovery:number;review:number;personalData:number};
const emptySummary:Summary={total:0,active:0,critical:0,breached:0,contained:0,recovery:0,review:0,personalData:0};
const today=()=>new Date().toISOString().slice(0,10);
const emptyForm=(email:string)=>({title:"",category:"account-compromise",severity:"high",detectedDate:today(),description:"",businessImpact:"",owner:email,commander:"",reviewer:"",assetRefs:"",riskRef:"",biaRef:"",dataClassification:"Internal",personalData:false});
const phrases:Record<string,string>={triage:"OLAY TRİAJINI BAŞLAT",contain:"OLAYI KONTROL ALTINA AL",eradicate:"TEHDİDİ ORTADAN KALDIR",recover:"HİZMETİ GERİ YÜKLE",review:"OLAYI İNCELEMEYE GÖNDER",close:"OLAYI KAPAT",reopen:"OLAYI YENİDEN AÇ"};
const nextAction:Record<string,string>={declared:"triage",triage:"contain",contained:"eradicate",eradicated:"recover",recovered:"review",review:"close",closed:"reopen"};
export default function IncidentCenter({lang,currentUser}:{lang:Lang;currentUser:{role:string;email:string}}){
 const tr=lang==="tr",[incidents,setIncidents]=useState<Incident[]>([]),[events,setEvents]=useState<Array<Record<string,string>>>([]),[summary,setSummary]=useState<Summary>(emptySummary),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[query,setQuery]=useState(""),[filter,setFilter]=useState("active"),[form,setForm]=useState<Record<string,string|boolean>|null>(null),[selected,setSelected]=useState<Incident|null>(null),[action,setAction]=useState<{incident:Incident;operation:string;note:string;evidenceReference:string;evidenceSha256:string;rootCause:string;lessonsLearned:string;notificationDecision:string;notificationRationale:string;confirmation:string}|null>(null);
 const apply=(body:{incidents?:Incident[];events?:Array<Record<string,string>>;summary?:Summary})=>{setIncidents(body.incidents||[]);setEvents(body.events||[]);setSummary(body.summary||emptySummary)};
 async function load(){const response=await fetch(withBasePath("/api/incidents"),{cache:"no-store"});if(response.ok)apply(await response.json())}
 useEffect(()=>{let active=true;fetch(withBasePath("/api/incidents"),{cache:"no-store"}).then(x=>x.ok?x.json():null).then(body=>{if(active&&body)apply(body)}).catch(()=>{});return()=>{active=false}},[]);
 async function api(body:Record<string,unknown>){setBusy(true);setNotice("");try{const response=await fetch(withBasePath("/api/incidents"),{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)}),result=await response.json().catch(()=>({}));setNotice(response.ok?(result.message||(tr?"İşlem tamamlandı.":"Completed.")):(result.error||(tr?"İşlem başarısız.":"Operation failed.")));if(response.ok)await load();return response.ok}catch{setNotice(tr?"Sunucuya ulaşılamadı.":"Server unavailable.");return false}finally{setBusy(false)}}
 async function create(event:FormEvent){event.preventDefault();if(form&&await api({action:"create",...form}))setForm(null)}
 const openAction=(incident:Incident)=>{const operation=nextAction[incident.status];setAction({incident,operation,note:"",evidenceReference:"",evidenceSha256:"",rootCause:incident.rootCause||"",lessonsLearned:incident.lessonsLearned||"",notificationDecision:incident.notificationDecision==="pending"?"":incident.notificationDecision,notificationRationale:incident.notificationRationale||"",confirmation:""})};
 async function transition(){if(!action)return;if(await api({action:"transition",incidentId:action.incident.id,...action})){setAction(null);setSelected(null)}}
 const filtered=useMemo(()=>incidents.filter(x=>(filter==="all"||filter==="active"&&x.status!=="closed"||x.status===filter||x.attention===filter)&&`${x.code} ${x.title} ${x.category} ${x.owner} ${x.assetRefs}`.toLocaleLowerCase("tr").includes(query.toLocaleLowerCase("tr"))),[incidents,filter,query]);
 return <section className="incident-page">
  <div className="incident-hero"><div><small>SECURITY INCIDENT · CRISIS · RECOVERY · LESSONS LEARNED</small><h2>{tr?"Güvenlik Olayları ve Kriz Merkezi":"Security Incident & Crisis Center"}</h2><p>{tr?"Olay ilanından containment, recovery, bildirim kararı ve bağımsız kapanışa kadar tek kanıtlı komuta zinciri.":"One evidence-backed command chain from declaration through containment, recovery, notification decision and independent closure."}</p></div><div>{currentUser.role==="Admin"&&<a href={withBasePath("/api/incidents?format=csv")}>Incident CSV</a>}{currentUser.role!=="Viewer"&&<button onClick={()=>setForm(emptyForm(currentUser.email))}>+ {tr?"Olay İlan Et":"Declare Incident"}</button>}</div></div>
  {notice&&<button className="incident-notice" onClick={()=>setNotice("")}>{notice}<b>×</b></button>}
  <div className="incident-kpis">{[[summary.active,tr?"Aktif":"Active"],[summary.critical,tr?"Kritik":"Critical"],[summary.breached,tr?"SLA ihlali":"SLA breach"],[summary.contained,tr?"Kontrol altında":"Contained"],[summary.review,tr?"İncelemede":"In review"],[summary.personalData,tr?"Kişisel veri":"Personal data"]].map(([value,label])=><article key={String(label)}><small>{label}</small><strong>{value}</strong></article>)}</div>
  <div className="incident-toolbar"><input aria-label={tr?"Olay ara":"Search incidents"} placeholder={tr?"Kod, başlık, kategori, sahip veya varlık ara…":"Search code, title, category, owner or asset…"} value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label={tr?"Durum filtresi":"Status filter"} value={filter} onChange={e=>setFilter(e.target.value)}><option value="active">{tr?"Aktif olaylar":"Active incidents"}</option><option value="all">{tr?"Tüm olaylar":"All incidents"}</option><option value="response-breach">Response breach</option><option value="recovery-breach">Recovery breach</option>{["declared","triage","contained","eradicated","recovered","review","closed"].map(x=><option key={x}>{x}</option>)}</select><span>{filtered.length} / {summary.total}</span></div>
  <div className="incident-table-wrap"><table><thead><tr><th>{tr?"Olay":"Incident"}</th><th>{tr?"Kategori":"Category"}</th><th>{tr?"Önem":"Severity"}</th><th>{tr?"Komuta":"Command"}</th><th>{tr?"Varlık/BIA":"Asset/BIA"}</th><th>{tr?"Durum":"Status"}</th></tr></thead><tbody>{filtered.map(x=><tr key={x.id} onClick={()=>setSelected(x)}><td><b>{x.title}</b><small>{x.code} · {x.detectedDate}</small></td><td><b>{x.category}</b><small>{x.dataClassification}{x.personalData?" · Personal data":""}</small></td><td><span className={`incident-badge ${x.severity}`}>{x.severity}</span><small>{tr?"Yanıt":"Response"} {incidentResponseHours(x.severity)}h · R {incidentRecoveryHours(x.severity)}h</small></td><td><b>{x.commander}</b><small>{x.owner}</small></td><td><b>{x.assetRefs}</b><small>{x.biaRef||"—"} · {x.riskRef||"—"}</small></td><td><span className={`incident-state ${x.status}`}>{x.status}</span><small className={String(x.attention).includes("breach")?"danger":""}>{x.attention}</small></td></tr>)}</tbody></table>{!filtered.length&&<div className="incident-empty">{tr?"Filtreyle eşleşen olay yok.":"No incidents match the filter."}</div>}</div>
  {selected&&<div className="incident-overlay" onMouseDown={()=>setSelected(null)}><article className="incident-detail" onMouseDown={e=>e.stopPropagation()}><header><div><small>{selected.code} · {selected.category}</small><h3>{selected.title}</h3></div><button onClick={()=>setSelected(null)}>×</button></header><div><section><small>{tr?"OLAY VE ETKİ":"INCIDENT & IMPACT"}</small><p>{selected.description}</p><b>{tr?"İş etkisi":"Business impact"}</b><p>{selected.businessImpact}</p>{selected.rootCause&&<><b>{tr?"Kök neden":"Root cause"}</b><p>{selected.rootCause}</p></>}{selected.lessonsLearned&&<><b>{tr?"Çıkarılan dersler":"Lessons learned"}</b><p>{selected.lessonsLearned}</p></>}</section><aside><small>{tr?"YÖNETİŞİM":"GOVERNANCE"}</small><b>{selected.severity} · {selected.status}</b><span>Owner: {selected.owner}</span><span>Commander: {selected.commander}</span><span>Reviewer: {selected.reviewer}</span><span>{tr?"Bildirim":"Notification"}: {selected.notificationDecision}</span><span>{tr?"Tekrar":"Reopen"}: {selected.reopenCount}</span></aside></div><footer>{nextAction[selected.status]&&currentUser.role!=="Viewer"&&<button onClick={()=>openAction(selected)}>{tr?"Yaşam döngüsünü ilerlet":"Advance lifecycle"} · {nextAction[selected.status]}</button>}</footer></article></div>}
  {form&&<div className="incident-overlay"><form className="incident-form" onSubmit={create}><header><div><small>CONTROLLED INCIDENT DECLARATION</small><h3>{tr?"Yeni güvenlik olayı":"New security incident"}</h3></div><button type="button" onClick={()=>setForm(null)}>×</button></header><div className="incident-form-grid"><Field wide label={tr?"Olay başlığı":"Incident title"} name="title" form={form} setForm={setForm}/><label>{tr?"Kategori":"Category"}<select value={String(form.category)} onChange={e=>setForm({...form,category:e.target.value})}>{["malware","phishing","account-compromise","data-breach","availability","vulnerability-exploitation","third-party","policy-violation","physical","other"].map(x=><option key={x}>{x}</option>)}</select></label><label>{tr?"Önem":"Severity"}<select value={String(form.severity)} onChange={e=>setForm({...form,severity:e.target.value})}>{["low","medium","high","critical"].map(x=><option key={x}>{x}</option>)}</select></label><Field type="date" label={tr?"Tespit tarihi":"Detection date"} name="detectedDate" form={form} setForm={setForm}/><label>{tr?"Veri sınıfı":"Data classification"}<select value={String(form.dataClassification)} onChange={e=>setForm({...form,dataClassification:e.target.value})}>{["Public","Internal","Restricted","Top Secret"].map(x=><option key={x}>{x}</option>)}</select></label><Field wide area label={tr?"Olay açıklaması":"Incident description"} name="description" form={form} setForm={setForm}/><Field wide area label={tr?"İş etkisi":"Business impact"} name="businessImpact" form={form} setForm={setForm}/><Field label={tr?"Olay sahibi":"Incident owner"} name="owner" form={form} setForm={setForm}/><Field label="Incident commander" name="commander" form={form} setForm={setForm}/><Field label={tr?"Bağımsız reviewer":"Independent reviewer"} name="reviewer" form={form} setForm={setForm}/><Field label={tr?"Varlık referansları":"Asset references"} name="assetRefs" form={form} setForm={setForm}/><Field label={tr?"Risk referansı":"Risk reference"} name="riskRef" form={form} setForm={setForm}/><Field label="BIA reference" name="biaRef" form={form} setForm={setForm}/><label className="check"><input type="checkbox" checked={Boolean(form.personalData)} onChange={e=>setForm({...form,personalData:e.target.checked})}/>{tr?"Kişisel veri etkilenmiş olabilir":"Personal data may be affected"}</label></div><footer><button type="button" className="secondary" onClick={()=>setForm(null)}>{tr?"İptal":"Cancel"}</button><button disabled={busy}>{tr?"Olayı ilan et":"Declare incident"}</button></footer></form></div>}
  {action&&<div className="incident-overlay"><article className="incident-action"><header><div><small>{action.incident.code} · {action.operation}</small><h3>{action.incident.title}</h3></div><button onClick={()=>setAction(null)}>×</button></header><label>{tr?"Açıklama":"Action note"}<textarea value={action.note} onChange={e=>setAction({...action,note:e.target.value})}/></label>{["contain","eradicate","recover","review","close"].includes(action.operation)&&<><label>{tr?"Kanıt referansı":"Evidence reference"}<input value={action.evidenceReference} onChange={e=>setAction({...action,evidenceReference:e.target.value})}/></label><label>SHA-256<input maxLength={64} value={action.evidenceSha256} onChange={e=>setAction({...action,evidenceSha256:e.target.value})}/></label></>}{action.operation==="review"&&<><label>{tr?"Kök neden":"Root cause"}<textarea value={action.rootCause} onChange={e=>setAction({...action,rootCause:e.target.value})}/></label><label>{tr?"Çıkarılan dersler":"Lessons learned"}<textarea value={action.lessonsLearned} onChange={e=>setAction({...action,lessonsLearned:e.target.value})}/></label></>}{["review","close"].includes(action.operation)&&<><label>{tr?"KVKK/GDPR bildirim kararı":"KVKK/GDPR notification decision"}<select value={action.notificationDecision} onChange={e=>setAction({...action,notificationDecision:e.target.value})}><option value="">—</option><option value="required">required</option><option value="not-required">not-required</option></select></label><label>{tr?"Bildirim kararı gerekçesi":"Notification rationale"}<textarea value={action.notificationRationale} onChange={e=>setAction({...action,notificationRationale:e.target.value})}/></label></>}<label>{tr?"Onay ifadesi":"Confirmation phrase"}<input value={action.confirmation} onChange={e=>setAction({...action,confirmation:e.target.value})}/><small>{phrases[action.operation]}</small></label><footer><button className="secondary" onClick={()=>setAction(null)}>{tr?"İptal":"Cancel"}</button><button disabled={busy} onClick={()=>void transition()}>{tr?"İşlemi uygula":"Apply action"}</button></footer></article></div>}
  {events.length>0&&<details className="incident-history"><summary>{tr?"Son olay yaşam döngüsü kayıtları":"Recent incident lifecycle events"}</summary>{events.slice(0,20).map(x=><div key={x.id}><b>{x.action}</b><span>{x.incidentId} · {x.actor}</span><small>{x.detail}</small></div>)}</details>}
 </section>
}
function Field({label,name,form,setForm,wide=false,area=false,type="text"}:{label:string;name:string;form:Record<string,string|boolean>;setForm:(x:Record<string,string|boolean>)=>void;wide?:boolean;area?:boolean;type?:string}){const value=String(form[name]??"");return <label className={wide?"wide":""}>{label}{area?<textarea value={value} onChange={e=>setForm({...form,[name]:e.target.value})}/>:<input type={type} value={value} onChange={e=>setForm({...form,[name]:e.target.value})}/>}</label>}
