"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
import {withBasePath} from "./base-path";
import "./policy-lifecycle.css";

type Lang="tr"|"en";
type Policy={id:string;code:string;title:string;category:string;classification:string;owner:string;reviewer:string;audience:string;reviewFrequencyDays:number;status:string;currentVersionId?:string;nextReview?:string;versionCount:number;activeExceptions:number;pendingAttestations:number;attention:string;updatedAt:string};
type Version={id:string;policyId:string;versionNumber:number;summary:string;content:string;contentSha256:string;controlRefs:string[];regulationRefs:string[];riskRefs:string[];effectiveDate:string;status:string;createdBy:string;submittedBy?:string;approvedBy?:string;publishedBy?:string;updatedAt:string};
type Campaign={id:string;policyId:string;versionId:string;name:string;audience:string;dueDate:string;requiredCount:number;status:string;attestedCount:number;declinedCount:number};
type Attestation={id:string;campaignId:string;policyId:string;versionId:string;policyCode:string;policyTitle:string;campaignName:string;dueDate:string;subjectEmail:string;status:string;note?:string;contentSha256?:string;attestedAt?:string};
type Exception={id:string;policyId:string;versionId:string;scope:string;rationale:string;compensatingControl:string;owner:string;reviewer:string;expiresAt:string;status:string;createdBy:string;submittedBy?:string;decidedBy?:string};
type Summary={total:number;published:number;reviewDue:number;inWorkflow:number;pendingAttestations:number;activeExceptions:number};
const emptySummary:Summary={total:0,published:0,reviewDue:0,inWorkflow:0,pendingAttestations:0,activeExceptions:0};
const emptyPolicy={code:"",title:"",category:"security",classification:"internal",owner:"",reviewer:"",audience:"All employees",reviewFrequencyDays:365};
const emptyVersion={policyId:"",summary:"",content:"",effectiveDate:"",controlRefs:"",regulationRefs:"",riskRefs:""};

export default function PolicyLifecycle({lang,currentUser}:{lang:Lang;currentUser:{role:string;email:string}}){
 const tr=lang==="tr",canWrite=currentUser.role!=="Viewer",[tab,setTab]=useState<"priority"|"policies"|"versions"|"attestations"|"exceptions">("priority"),[policies,setPolicies]=useState<Policy[]>([]),[versions,setVersions]=useState<Version[]>([]),[campaigns,setCampaigns]=useState<Campaign[]>([]),[attestations,setAttestations]=useState<Attestation[]>([]),[exceptions,setExceptions]=useState<Exception[]>([]),[summary,setSummary]=useState<Summary>(emptySummary),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[policyForm,setPolicyForm]=useState<Record<string,unknown>|null>(null),[versionForm,setVersionForm]=useState<Record<string,unknown>|null>(null),[campaignForm,setCampaignForm]=useState<Record<string,unknown>|null>(null),[exceptionForm,setExceptionForm]=useState<Record<string,unknown>|null>(null),[actionForm,setActionForm]=useState<{kind:"version"|"exception"|"retire"|"attest";id:string;operation:string;note:string;evidenceReference:string;evidenceSha256:string;confirmation:string}|null>(null),[selected,setSelected]=useState<Policy|null>(null);
 const policyName=(id:string)=>{const p=policies.find(x=>x.id===id);return p?`${p.code} · ${p.title}`:id},current=useMemo(()=>new Map(policies.map(p=>[p.id,versions.find(v=>v.id===p.currentVersionId)])),[policies,versions]);
 const format=(value?:string)=>value?new Intl.DateTimeFormat(tr?"tr-TR":"en-GB",{dateStyle:"medium"}).format(new Date(`${value.slice(0,10)}T12:00:00Z`)):"—";
 async function load(){const response=await fetch(withBasePath("/api/policy-lifecycle"),{cache:"no-store"});if(!response.ok)return;const body=await response.json();setPolicies(body.documents||[]);setVersions(body.versions||[]);setCampaigns(body.campaigns||[]);setAttestations(body.attestations||[]);setExceptions(body.exceptions||[]);setSummary(body.summary||emptySummary);if(selected)setSelected((body.documents||[]).find((x:Policy)=>x.id===selected.id)||null)}
 useEffect(()=>{let active=true;fetch(withBasePath("/api/policy-lifecycle"),{cache:"no-store"}).then(x=>x.ok?x.json():null).then(body=>{if(active&&body){setPolicies(body.documents||[]);setVersions(body.versions||[]);setCampaigns(body.campaigns||[]);setAttestations(body.attestations||[]);setExceptions(body.exceptions||[]);setSummary(body.summary||emptySummary)}}).catch(()=>{});return()=>{active=false}},[]);
 async function api(body:Record<string,unknown>){setBusy(true);setNotice("");try{const response=await fetch(withBasePath("/api/policy-lifecycle"),{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)}),result=await response.json().catch(()=>({}));setNotice(response.ok?(result.message||(tr?"İşlem tamamlandı.":"Completed.")):(result.error||(tr?"İşlem başarısız.":"Operation failed.")));if(response.ok)await load();return response.ok}catch{setNotice(tr?"Sunucuya ulaşılamadı.":"Server unavailable.");return false}finally{setBusy(false)}}
 async function submitPolicy(e:FormEvent){e.preventDefault();if(policyForm&&await api({action:"save-policy",...policyForm}))setPolicyForm(null)}
 async function submitVersion(e:FormEvent){e.preventDefault();if(versionForm&&await api({action:"create-version",...versionForm,controlRefs:String(versionForm.controlRefs||"").split(/[,\n]/),regulationRefs:String(versionForm.regulationRefs||"").split(/[,\n]/),riskRefs:String(versionForm.riskRefs||"").split(/[,\n]/)}))setVersionForm(null)}
 async function submitCampaign(e:FormEvent){e.preventDefault();if(campaignForm&&await api({action:"create-campaign",...campaignForm,subjects:String(campaignForm.subjects||"").split(/[,\n]/)}))setCampaignForm(null)}
 async function submitException(e:FormEvent){e.preventDefault();if(exceptionForm&&await api({action:"create-exception",...exceptionForm}))setExceptionForm(null)}
 const phrase=(operation:string)=>({submit:"İNCELEMEYE GÖNDER",approve:"POLİTİKAYI ONAYLA",reject:"POLİTİKAYI REDDET",publish:"POLİTİKAYI YAYINLA",retire:"POLİTİKAYI YÜRÜRLÜKTEN KALDIR","submit-exception":"İSTİSNAYI GÖNDER","approve-exception":"İSTİSNAYI ONAYLA","reject-exception":"İSTİSNAYI REDDET","close-exception":"İSTİSNAYI KAPAT",attested:"OKUDUM VE KABUL EDİYORUM",declined:"KABUL ETMİYORUM"}[operation]||"");
 const needsEvidence=actionForm&&["submit","approve","publish","retire","approve-exception","close-exception"].includes(actionForm.operation);
 async function applyAction(){if(!actionForm)return;const common={operation:actionForm.operation,note:actionForm.note,evidenceReference:actionForm.evidenceReference,evidenceSha256:actionForm.evidenceSha256,confirmation:actionForm.confirmation};let body:Record<string,unknown>;if(actionForm.kind==="version")body={action:"version-action",versionId:actionForm.id,...common};else if(actionForm.kind==="exception")body={action:"exception-action",exceptionId:actionForm.id,...common};else if(actionForm.kind==="retire")body={action:"retire-policy",policyId:actionForm.id,...common};else body={action:"attest",attestationId:actionForm.id,decision:actionForm.operation,...common};if(await api(body))setActionForm(null)}
 const act=(kind:"version"|"exception"|"retire"|"attest",id:string,operation:string)=>setActionForm({kind,id,operation,note:"",evidenceReference:"",evidenceSha256:"",confirmation:""});
 const priority=policies.filter(p=>p.attention!==p.status||["draft"].includes(p.status));
 return <section className="plm-page">
  <div className="plm-hero"><div><small>ENTERPRISE POLICY LIFECYCLE</small><h2>{tr?"Politika Merkezi":"Policy Center"}</h2><p>{tr?"Taslak, bağımsız inceleme, kanıtlı onay, yayın, çalışan attestation'ı, süreli istisna ve yürürlükten kaldırmayı tek denetim zincirinde yönetin.":"Govern drafting, independent review, evidence-backed approval, publication, employee attestation, timed exceptions and retirement in one audit chain."}</p></div><div>{currentUser.role==="Admin"&&<a href={withBasePath("/api/policy-lifecycle?format=csv")}>{tr?"Politika CSV":"Policy CSV"}</a>}{canWrite&&<button onClick={()=>setPolicyForm({...emptyPolicy})}>+ {tr?"Politika":"Policy"}</button>}</div></div>
  {notice&&<div className="plm-notice" onClick={()=>setNotice("")}>{notice}<b>×</b></div>}
  <div className="plm-metrics"><Metric value={summary.total} label={tr?"Toplam politika":"Policies"}/><Metric value={summary.published} label={tr?"Yayında":"Published"}/><Metric value={summary.reviewDue} label={tr?"İnceleme zamanı":"Reviews due"}/><Metric value={summary.inWorkflow} label={tr?"İş akışında":"In workflow"}/><Metric value={summary.pendingAttestations} label={tr?"Bekleyen attestation":"Pending attestations"}/><Metric value={summary.activeExceptions} label={tr?"Aktif istisna":"Active exceptions"}/></div>
  <div className="plm-tabs">{(["priority","policies","versions","attestations","exceptions"] as const).map(x=><button key={x} title={x==="attestations"?`${campaigns.length} campaigns`:undefined} className={tab===x?"active":""} onClick={()=>setTab(x)}>{x==="priority"?(tr?"Öncelik Kuyruğu":"Priority Queue"):x==="policies"?(tr?"Politika Envanteri":"Policy Register"):x==="versions"?(tr?"Sürümler ve Yayın":"Versions & Release"):x==="attestations"?`Attestation (${campaigns.length})`:tr?"İstisnalar":"Exceptions"}</button>)}</div>
  {tab==="priority"&&<div className="plm-grid"><section><header><div><small>{tr?"YÖNETİŞİM ÖNCELİĞİ":"GOVERNANCE PRIORITY"}</small><h3>{tr?"Müdahale bekleyen politikalar":"Policies requiring action"}</h3></div><span>{priority.length}</span></header>{priority.slice(0,14).map(p=><PolicyCard key={p.id} p={p} format={format} open={()=>setSelected(p)}/>)}</section><section><header><div><small>{tr?"KİŞİSEL AKSİYON":"PERSONAL ACTION"}</small><h3>{tr?"Attestation bekleyenler":"Pending attestations"}</h3></div><span>{attestations.filter(a=>a.status==="pending").length}</span></header>{attestations.filter(a=>a.status==="pending").slice(0,10).map(a=><article className="plm-personal" key={a.id}><div><b>{a.policyCode} · {a.policyTitle}</b><small>{a.campaignName} · {format(a.dueDate)}</small></div><div><button onClick={()=>act("attest",a.id,"attested")}>{tr?"Kabul":"Accept"}</button><button onClick={()=>act("attest",a.id,"declined")}>{tr?"Reddet":"Decline"}</button></div></article>)}</section></div>}
  {tab==="policies"&&<Table heads={[tr?"Kod / Politika":"Code / Policy",tr?"Kategori":"Category",tr?"Sahip / Reviewer":"Owner / Reviewer",tr?"Sürüm":"Version",tr?"İnceleme":"Review",tr?"Durum":"Status",""]} rows={policies.map(p=>[<span key="policy"><b>{p.code} · {p.title}</b><small>{p.classification} · {p.audience}</small></span>,p.category,<span key="owner"><b>{p.owner}</b><small>{p.reviewer}</small></span>,current.get(p.id)?`v${current.get(p.id)?.versionNumber}`:"—",format(p.nextReview),<State key="status" value={p.attention}/>,<div key="actions"><button onClick={()=>setSelected(p)}>{tr?"Aç":"Open"}</button>{canWrite&&p.status!=="retired"&&<button onClick={()=>setVersionForm({...emptyVersion,policyId:p.id})}>+ {tr?"Sürüm":"Version"}</button>}</div>])} empty={tr?"Politika yok.":"No policy."}/>} 
  {tab==="versions"&&<Table heads={[tr?"Politika":"Policy",tr?"Sürüm / yürürlük":"Version / effective",tr?"Eşlemeler":"Mappings",tr?"İçerik özeti":"Content digest",tr?"Durum":"Status",""]} rows={versions.map(v=>[policyName(v.policyId),<span key="version"><b>v{v.versionNumber}</b><small>{format(v.effectiveDate)} · {v.summary}</small></span>,`${v.controlRefs.length} C · ${v.regulationRefs.length} R · ${v.riskRefs.length} Risk`,<code key="hash">{v.contentSha256.slice(0,12)}…</code>,<State key="status" value={v.status}/>,<VersionActions key="actions" v={v} role={currentUser.role} act={operation=>act("version",v.id,operation)}/>])} empty={tr?"Sürüm yok.":"No version."}/>} 
  {tab==="attestations"&&<><Table heads={[tr?"Politika / Kampanya":"Policy / Campaign",tr?"Katılımcı":"Subject",tr?"Son tarih":"Due",tr?"Durum":"Status",""]} rows={attestations.map(a=>[<span key="campaign"><b>{a.policyCode} · {a.policyTitle}</b><small>{a.campaignName}</small></span>,a.subjectEmail,format(a.dueDate),<State key="status" value={a.status}/>,a.status==="pending"?<div key="action"><button onClick={()=>act("attest",a.id,"attested")}>{tr?"Kabul":"Accept"}</button><button onClick={()=>act("attest",a.id,"declined")}>{tr?"Reddet":"Decline"}</button></div>:<code key="hash">{a.contentSha256?.slice(0,12)||"—"}</code>])} empty={tr?"Attestation yok.":"No attestation."}/>{currentUser.role==="Admin"&&<div className="plm-float"><button onClick={()=>{const p=policies.find(x=>x.currentVersionId);setCampaignForm({policyId:p?.id||"",versionId:p?.currentVersionId||"",name:"",audience:p?.audience||"",dueDate:"",subjects:""})}}>+ {tr?"Kampanya":"Campaign"}</button></div>}</>}
  {tab==="exceptions"&&<><Table heads={[tr?"Politika":"Policy",tr?"Kapsam / gerekçe":"Scope / rationale",tr?"Sahip / Reviewer":"Owner / Reviewer",tr?"Bitiş":"Expiry",tr?"Durum":"Status",""]} rows={exceptions.map(x=>[policyName(x.policyId),<span key="scope"><b>{x.scope}</b><small>{x.rationale}</small></span>,<span key="owner"><b>{x.owner}</b><small>{x.reviewer}</small></span>,format(x.expiresAt),<State key="status" value={x.status}/>,<ExceptionActions key="actions" x={x} role={currentUser.role} act={operation=>act("exception",x.id,operation)}/>])} empty={tr?"İstisna yok.":"No exception."}/>{canWrite&&<div className="plm-float"><button onClick={()=>{const p=policies.find(x=>x.currentVersionId);setExceptionForm({policyId:p?.id||"",versionId:p?.currentVersionId||"",scope:"",rationale:"",compensatingControl:"",owner:currentUser.email,reviewer:p?.reviewer||"",expiresAt:""})}}>+ {tr?"İstisna":"Exception"}</button></div>}</>}
  {selected&&<Modal title={selected.title} close={()=>setSelected(null)}><div className="plm-detail"><div className="plm-tags"><State value={selected.attention}/><span>{selected.code}</span><span>{selected.classification}</span><span>{selected.category}</span></div><p>{selected.audience}</p><dl><div><dt>{tr?"Sahip":"Owner"}</dt><dd>{selected.owner}</dd></div><div><dt>Reviewer</dt><dd>{selected.reviewer}</dd></div><div><dt>{tr?"İnceleme":"Review"}</dt><dd>{format(selected.nextReview)}</dd></div><div><dt>{tr?"Sürümler":"Versions"}</dt><dd>{selected.versionCount}</dd></div></dl>{versions.filter(v=>v.policyId===selected.id).map(v=><article key={v.id}><header><b>v{v.versionNumber} · {v.status}</b><code>{v.contentSha256}</code></header><small>{v.summary}</small><p>{v.content}</p><footer>{[...v.controlRefs,...v.regulationRefs,...v.riskRefs].map(x=><span key={x}>{x}</span>)}</footer></article>)}<footer>{canWrite&&selected.status!=="retired"&&<button onClick={()=>setPolicyForm({...selected,policyId:selected.id})}>{tr?"Metaveriyi düzenle":"Edit metadata"}</button>}{currentUser.role==="Admin"&&selected.status==="published"&&<button onClick={()=>act("retire",selected.id,"retire")}>{tr?"Yürürlükten kaldır":"Retire"}</button>}</footer></div></Modal>}
  {policyForm&&<Modal title={tr?"Politika kaydı":"Policy record"} close={()=>setPolicyForm(null)}><form className="plm-form" onSubmit={submitPolicy}><Input label={tr?"Politika kodu":"Policy code"} value={String(policyForm.code||"")} set={v=>setPolicyForm({...policyForm,code:v})}/><Input label={tr?"Başlık":"Title"} value={String(policyForm.title||"")} set={v=>setPolicyForm({...policyForm,title:v})}/><Select label={tr?"Kategori":"Category"} value={String(policyForm.category)} values={["security","privacy","risk","compliance","technology","people","operations"]} set={v=>setPolicyForm({...policyForm,category:v})}/><Select label={tr?"Sınıf":"Classification"} value={String(policyForm.classification)} values={["public","internal","confidential","restricted"]} set={v=>setPolicyForm({...policyForm,classification:v})}/><Input label={tr?"Politika sahibi":"Policy owner"} type="email" value={String(policyForm.owner||"")} set={v=>setPolicyForm({...policyForm,owner:v})}/><Input label="Reviewer" type="email" value={String(policyForm.reviewer||"")} set={v=>setPolicyForm({...policyForm,reviewer:v})}/><Input wide label={tr?"Hedef kitle":"Audience"} value={String(policyForm.audience||"")} set={v=>setPolicyForm({...policyForm,audience:v})}/><Input label={tr?"İnceleme sıklığı (gün)":"Review frequency (days)"} type="number" value={String(policyForm.reviewFrequencyDays)} set={v=>setPolicyForm({...policyForm,reviewFrequencyDays:Number(v)})}/><FormFooter close={()=>setPolicyForm(null)} busy={busy} tr={tr}/></form></Modal>}
  {versionForm&&<Modal title={tr?"Yeni kontrollü sürüm":"New controlled version"} close={()=>setVersionForm(null)}><form className="plm-form" onSubmit={submitVersion}><Select label={tr?"Politika":"Policy"} value={String(versionForm.policyId)} values={policies.filter(p=>p.status!=="retired").map(p=>p.id)} labels={Object.fromEntries(policies.map(p=>[p.id,`${p.code} · ${p.title}`]))} set={v=>setVersionForm({...versionForm,policyId:v})}/><Input label={tr?"Yürürlük tarihi":"Effective date"} type="date" value={String(versionForm.effectiveDate||"")} set={v=>setVersionForm({...versionForm,effectiveDate:v})}/><Input wide label={tr?"Değişiklik özeti":"Change summary"} value={String(versionForm.summary||"")} set={v=>setVersionForm({...versionForm,summary:v})}/><Text wide label={tr?"Politika içeriği":"Policy content"} value={String(versionForm.content||"")} set={v=>setVersionForm({...versionForm,content:v})}/><Input label={tr?"Kontrol referansları":"Control refs"} value={String(versionForm.controlRefs||"")} set={v=>setVersionForm({...versionForm,controlRefs:v})}/><Input label={tr?"Regülasyon referansları":"Regulation refs"} value={String(versionForm.regulationRefs||"")} set={v=>setVersionForm({...versionForm,regulationRefs:v})}/><Input wide label={tr?"Risk referansları":"Risk refs"} value={String(versionForm.riskRefs||"")} set={v=>setVersionForm({...versionForm,riskRefs:v})}/><FormFooter close={()=>setVersionForm(null)} busy={busy} tr={tr}/></form></Modal>}
  {campaignForm&&<Modal title={tr?"Attestation kampanyası":"Attestation campaign"} close={()=>setCampaignForm(null)}><form className="plm-form" onSubmit={submitCampaign}><PublishedPicker form={campaignForm} set={setCampaignForm} policies={policies} versions={versions} tr={tr}/><Input label={tr?"Kampanya adı":"Campaign name"} value={String(campaignForm.name||"")} set={v=>setCampaignForm({...campaignForm,name:v})}/><Input label={tr?"Son tarih":"Due date"} type="date" value={String(campaignForm.dueDate||"")} set={v=>setCampaignForm({...campaignForm,dueDate:v})}/><Input wide label={tr?"Hedef kitle":"Audience"} value={String(campaignForm.audience||"")} set={v=>setCampaignForm({...campaignForm,audience:v})}/><Text wide label={tr?"Katılımcı e-postaları (satır veya virgül)":"Subject emails (line or comma)"} value={String(campaignForm.subjects||"")} set={v=>setCampaignForm({...campaignForm,subjects:v})}/><FormFooter close={()=>setCampaignForm(null)} busy={busy} tr={tr}/></form></Modal>}
  {exceptionForm&&<Modal title={tr?"Süreli politika istisnası":"Timed policy exception"} close={()=>setExceptionForm(null)}><form className="plm-form" onSubmit={submitException}><PublishedPicker form={exceptionForm} set={setExceptionForm} policies={policies} versions={versions} tr={tr}/><Input label={tr?"İstisna sahibi":"Exception owner"} type="email" value={String(exceptionForm.owner||"")} set={v=>setExceptionForm({...exceptionForm,owner:v})}/><Input label="Reviewer" type="email" value={String(exceptionForm.reviewer||"")} set={v=>setExceptionForm({...exceptionForm,reviewer:v})}/><Input label={tr?"Bitiş":"Expiry"} type="date" value={String(exceptionForm.expiresAt||"")} set={v=>setExceptionForm({...exceptionForm,expiresAt:v})}/><Input wide label={tr?"Kapsam":"Scope"} value={String(exceptionForm.scope||"")} set={v=>setExceptionForm({...exceptionForm,scope:v})}/><Text wide label={tr?"Gerekçe":"Rationale"} value={String(exceptionForm.rationale||"")} set={v=>setExceptionForm({...exceptionForm,rationale:v})}/><Text wide label={tr?"Telafi kontrolü":"Compensating control"} value={String(exceptionForm.compensatingControl||"")} set={v=>setExceptionForm({...exceptionForm,compensatingControl:v})}/><FormFooter close={()=>setExceptionForm(null)} busy={busy} tr={tr}/></form></Modal>}
  {actionForm&&<Modal title={phrase(actionForm.operation)} close={()=>setActionForm(null)}><div className="plm-form"><Text wide label={tr?"Karar / işlem notu":"Decision / action note"} value={actionForm.note} set={v=>setActionForm({...actionForm,note:v})}/>{needsEvidence&&<><Input label={tr?"Kanıt referansı":"Evidence reference"} value={actionForm.evidenceReference} set={v=>setActionForm({...actionForm,evidenceReference:v})}/><Input label="SHA-256" value={actionForm.evidenceSha256} set={v=>setActionForm({...actionForm,evidenceSha256:v})}/></>}<Input wide label={`${tr?"Tam onay ifadesi":"Exact confirmation"}: ${phrase(actionForm.operation)}`} value={actionForm.confirmation} set={v=>setActionForm({...actionForm,confirmation:v})}/><footer><button onClick={()=>setActionForm(null)}>{tr?"Vazgeç":"Cancel"}</button><button disabled={busy} onClick={()=>void applyAction()}>{tr?"Uygula":"Apply"}</button></footer></div></Modal>}
 </section>
}
function VersionActions({v,role,act}:{v:Version;role:string;act:(x:string)=>void}){if(role==="Viewer")return <span>—</span>;return <div>{v.status==="draft"&&<button onClick={()=>act("submit")}>Gönder</button>}{v.status==="review"&&role==="Admin"&&<><button onClick={()=>act("approve")}>Onayla</button><button onClick={()=>act("reject")}>Reddet</button></>}{v.status==="approved"&&role==="Admin"&&<button onClick={()=>act("publish")}>Yayınla</button>}</div>}
function ExceptionActions({x,role,act}:{x:Exception;role:string;act:(x:string)=>void}){if(role==="Viewer")return <span>—</span>;return <div>{x.status==="draft"&&<button onClick={()=>act("submit-exception")}>Gönder</button>}{x.status==="submitted"&&role==="Admin"&&<><button onClick={()=>act("approve-exception")}>Onayla</button><button onClick={()=>act("reject-exception")}>Reddet</button></>}{x.status==="approved"&&role==="Admin"&&<button onClick={()=>act("close-exception")}>Kapat</button>}</div>}
function PublishedPicker({form,set,policies,versions,tr}:{form:Record<string,unknown>;set:(v:Record<string,unknown>)=>void;policies:Policy[];versions:Version[];tr:boolean}){const choices=policies.filter(p=>p.status==="published"&&p.currentVersionId);return <Select label={tr?"Yayındaki politika":"Published policy"} value={String(form.policyId||"")} values={choices.map(p=>p.id)} labels={Object.fromEntries(choices.map(p=>[p.id,`${p.code} · ${p.title}`]))} set={id=>{const p=choices.find(x=>x.id===id);set({...form,policyId:id,versionId:p?.currentVersionId||versions.find(v=>v.policyId===id&&v.status==="published")?.id||"",reviewer:form.reviewer||p?.reviewer||"",audience:form.audience||p?.audience||""})}}/>}
function PolicyCard({p,format,open}:{p:Policy;format:(v?:string)=>string;open:()=>void}){return <article className={`plm-card ${p.attention}`}><header><div><small>{p.code} · {p.category}</small><b>{p.title}</b></div><State value={p.attention}/></header><p>{p.audience}</p><footer><span>{format(p.nextReview)} · {p.versionCount} version · {p.pendingAttestations} pending</span><button onClick={open}>Aç</button></footer></article>}
function Metric({value,label}:{value:number;label:string}){return <article><b>{value}</b><span>{label}</span></article>}
function State({value}:{value:string}){return <span className={`plm-state ${value}`}>{value}</span>}
function Table({heads,rows,empty}:{heads:string[];rows:React.ReactNode[][];empty:string}){return <div className="plm-table"><div className="table-wrap"><table><thead><tr>{heads.map((x,i)=><th key={`${x}-${i}`}>{x}</th>)}</tr></thead><tbody>{rows.length?rows.map((row,i)=><tr key={i}>{row.map((cell,j)=><td key={j}>{cell}</td>)}</tr>):<tr><td colSpan={heads.length}>{empty}</td></tr>}</tbody></table></div></div>}
function Input({label,value,set,type="text",wide=false}:{label:string;value:string;set:(v:string)=>void;type?:string;wide?:boolean}){return <label className={wide?"wide":""}>{label}<input required type={type} value={value} onChange={e=>set(e.target.value)}/></label>}
function Text({label,value,set,wide=false}:{label:string;value:string;set:(v:string)=>void;wide?:boolean}){return <label className={wide?"wide":""}>{label}<textarea required rows={4} value={value} onChange={e=>set(e.target.value)}/></label>}
function Select({label,value,values,labels,set}:{label:string;value:string;values:string[];labels?:Record<string,string>;set:(v:string)=>void}){return <label>{label}<select required value={value} onChange={e=>set(e.target.value)}><option value="">—</option>{values.map(x=><option key={x} value={x}>{labels?.[x]||x}</option>)}</select></label>}
function FormFooter({close,busy,tr}:{close:()=>void;busy:boolean;tr:boolean}){return <footer className="wide"><button type="button" onClick={close}>{tr?"Vazgeç":"Cancel"}</button><button disabled={busy}>{tr?"Kaydet":"Save"}</button></footer>}
function Modal({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <div className="overlay" onMouseDown={close}><div className="modal plm-modal" role="dialog" aria-modal="true" aria-label={title} onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><div><small>FORNOST POLICY LIFECYCLE</small><h2>{title}</h2></div><button aria-label="Close dialog" onClick={close}>×</button></div>{children}</div></div>}
