"use client";

import {FormEvent,useEffect,useMemo,useState} from "react";
import {withBasePath} from "./base-path";
import "./regulatory-intelligence.css";

type Lang="tr"|"en";
type Source={id:string;name:string;authority:string;jurisdiction:string;sourceType:string;url:string;owner:string;reviewFrequencyDays:number;enabled:boolean;lastCheckedAt?:string;nextCheckAt:string;changeCount:number};
type Change={id:string;sourceId:string;sourceName:string;externalRef:string;title:string;summary:string;publishedDate:string;effectiveDate:string;severity:string;changeType:string;applicability:string;status:string;owner:string;reviewer:string;contentSha256:string;totalImpacts:number;openImpacts:number;attention:string;detectedBy:string};
type Impact={id:string;changeId:string;targetType:string;targetRef:string;targetTitle:string;impactLevel:string;requiredAction:string;actionOwner:string;dueDate:string;status:string;evidenceReference?:string;submittedBy?:string;verifiedBy?:string;overdue:boolean};
type RecordRef={id:string;module:string;title:string};
type Summary={sources:number;dueSources:number;open:number;unassessed:number;blocking:number;overdue:number;openImpacts:number;verification:number;closed:number};
const emptySummary:Summary={sources:0,dueSources:0,open:0,unassessed:0,blocking:0,overdue:0,openImpacts:0,verification:0,closed:0};
const targetModules:Record<string,string[]>={control:["Kontroller","Uyum"],policy:[],risk:["Risk Assessment"],asset:["Varlık Envanteri"],vendor:["Tedarikçiler"],process:["BIA"],audit:["Denetim Yönetimi"],evidence:["Kanıtlar"]};

export default function RegulatoryIntelligence({lang,currentUser}:{lang:Lang;currentUser:{role:string;email:string}}){
 const tr=lang==="tr",[tab,setTab]=useState<"overview"|"sources"|"changes"|"impacts">("overview"),[sources,setSources]=useState<Source[]>([]),[changes,setChanges]=useState<Change[]>([]),[impacts,setImpacts]=useState<Impact[]>([]),[records,setRecords]=useState<RecordRef[]>([]),[summary,setSummary]=useState<Summary>(emptySummary),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[sourceOpen,setSourceOpen]=useState(false),[changeOpen,setChangeOpen]=useState(false),[impactOpen,setImpactOpen]=useState(false),[selected,setSelected]=useState<Change|null>(null),[changeAction,setChangeAction]=useState<{change:Change;operation:string;note:string;confirmation:string}|null>(null),[impactAction,setImpactAction]=useState<{impact:Impact;action:string;note:string;evidenceReference:string;evidenceSha256:string;confirmation:string}|null>(null);
 const[sourceForm,setSourceForm]=useState({name:"",authority:"",jurisdiction:"Türkiye",sourceType:"regulator",url:"",owner:"",reviewFrequencyDays:30});
 const[changeForm,setChangeForm]=useState({sourceId:"",externalRef:"",title:"",summary:"",publishedDate:"",effectiveDate:"",severity:"high",changeType:"amendment",owner:"",reviewer:""});
 const[impactForm,setImpactForm]=useState({changeId:"",targetType:"control",targetRef:"",targetTitle:"",impactLevel:"high",requiredAction:"",actionOwner:"",dueDate:""});
 const availableRecords=useMemo(()=>records.filter(x=>(targetModules[impactForm.targetType]||[]).includes(x.module)),[records,impactForm.targetType]);
 const selectedImpacts=selected?impacts.filter(x=>x.changeId===selected.id):[];
 const format=(value?:string)=>value?new Intl.DateTimeFormat(tr?"tr-TR":"en-GB",{dateStyle:"medium"}).format(new Date(value)):"—";
 async function load(){const response=await fetch(withBasePath("/api/regulatory-intelligence"),{cache:"no-store"});if(response.ok){const body=await response.json();setSources(body.sources||[]);setChanges(body.changes||[]);setImpacts(body.impacts||[]);setRecords(body.records||[]);setSummary(body.summary||emptySummary);if(selected)setSelected((body.changes||[]).find((x:Change)=>x.id===selected.id)||null)}}
 useEffect(()=>{let active=true;fetch(withBasePath("/api/regulatory-intelligence"),{cache:"no-store"}).then(x=>x.ok?x.json():null).then(body=>{if(active&&body){setSources(body.sources||[]);setChanges(body.changes||[]);setImpacts(body.impacts||[]);setRecords(body.records||[]);setSummary(body.summary||emptySummary)}}).catch(()=>{});return()=>{active=false}},[]);
 async function api(body:Record<string,unknown>){setBusy(true);setNotice("");const response=await fetch(withBasePath("/api/regulatory-intelligence"),{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)}),result=await response.json().catch(()=>({}));setBusy(false);setNotice(response.ok?(result.message||(tr?"İşlem tamamlandı.":"Completed.")):(result.error||(tr?"İşlem başarısız.":"Operation failed.")));if(response.ok)await load();return response.ok}
 async function saveSource(event:FormEvent){event.preventDefault();if(await api({action:"save-source",...sourceForm})){setSourceOpen(false);setSourceForm({...sourceForm,name:"",authority:"",url:""})}}
 async function saveChange(event:FormEvent){event.preventDefault();if(await api({action:"create-change",...changeForm})){setChangeOpen(false);setChangeForm({...changeForm,externalRef:"",title:"",summary:""})}}
 async function saveImpact(event:FormEvent){event.preventDefault();if(await api({action:"add-impact",...impactForm})){setImpactOpen(false);setImpactForm({...impactForm,targetRef:"",targetTitle:"",requiredAction:""})}}
 function openImpact(change:Change){setSelected(change);setImpactForm({...impactForm,changeId:change.id,actionOwner:change.owner,dueDate:change.effectiveDate});setImpactOpen(true)}
 function chooseRecord(id:string){const row=records.find(x=>x.id===id);setImpactForm({...impactForm,targetRef:id,targetTitle:row?.title||""})}
 async function applyChange(){if(!changeAction)return;if(await api({action:"change-action",changeId:changeAction.change.id,operation:changeAction.operation,note:changeAction.note,confirmation:changeAction.confirmation}))setChangeAction(null)}
 async function applyImpact(){if(!impactAction)return;if(await api({action:"impact-action",impactId:impactAction.impact.id,...impactAction}))setImpactAction(null)}
 const changePhrase=(operation:string)=>operation==="not-applicable"?"KAPSAM DIŞI":operation==="close"?"DEĞİŞİKLİĞİ KAPAT":"DEĞİŞİKLİĞİ YENİDEN AÇ";
 const impactPhrase=(action:string)=>action==="start"?"AKSİYONU BAŞLAT":action==="submit"?"DOĞRULAMAYA GÖNDER":action==="verify"?"ETKİYİ DOĞRULA":"ETKİYİ YENİDEN AÇ";
 return <section className="ri-page">
  <div className="ri-hero"><div><small>{tr?"REGULATORY CHANGE INTELLIGENCE":"REGULATORY CHANGE INTELLIGENCE"}</small><h2>{tr?"Regülasyon Merkezi":"Regulatory Change Center"}</h2><p>{tr?"Düzenleyici kaynakları izleyin; değişikliklerin kontrol, politika, risk, varlık ve süreç etkisini kanıtlı kapanışa kadar yönetin.":"Monitor regulatory sources and govern impact on controls, policies, risks, assets and processes through evidence-backed closure."}</p></div><div>{currentUser.role==="Admin"&&<a href={withBasePath("/api/regulatory-intelligence?format=csv")}>{tr?"Değişiklik CSV":"Changes CSV"}</a>}{currentUser.role==="Admin"&&<button onClick={()=>setSourceOpen(true)}>+ {tr?"Kaynak":"Source"}</button>}{currentUser.role!=="Viewer"&&<button onClick={()=>setChangeOpen(true)}>+ {tr?"Değişiklik":"Change"}</button>}</div></div>
  {notice&&<div className="ri-notice" onClick={()=>setNotice("")}>{notice}<b>×</b></div>}
  <div className="ri-metrics"><Metric value={summary.sources} label={tr?"Aktif kaynak":"Sources"}/><Metric value={summary.dueSources} label={tr?"İzleme zamanı gelen":"Source reviews due"}/><Metric value={summary.unassessed} label={tr?"Etki bekleyen":"Awaiting assessment"}/><Metric value={summary.blocking} label={tr?"Yüksek/kritik açık":"High/critical open"}/><Metric value={summary.openImpacts} label={tr?"Açık aksiyon":"Open actions"}/><Metric value={summary.overdue} label={tr?"Yürürlük geçti":"Past effective date"}/></div>
  <div className="ri-tabs">{(["overview","sources","changes","impacts"] as const).map(x=><button key={x} className={tab===x?"active":""} onClick={()=>setTab(x)}>{x==="overview"?(tr?"Öncelik Kuyruğu":"Priority Queue"):x==="sources"?(tr?"Kaynaklar":"Sources"):x==="changes"?(tr?"Değişiklik Envanteri":"Change Register"):(tr?"Etki ve Aksiyonlar":"Impact & Actions")}</button>)}</div>
  {tab==="overview"&&<div className="ri-grid"><section><header><div><small>{tr?"HORIZON SCAN":"HORIZON SCAN"}</small><h3>{tr?"Yaklaşan ve geciken değişiklikler":"Upcoming and overdue changes"}</h3></div><span>{summary.open}</span></header>{changes.filter(x=>!["closed","not-applicable"].includes(x.status)).slice(0,12).map(x=><ChangeCard key={x.id} item={x} tr={tr} format={format} canWrite={currentUser.role!=="Viewer"} select={()=>setSelected(x)} addImpact={()=>openImpact(x)} action={(operation)=>operation==="start-assessment"?void api({action:"change-action",changeId:x.id,operation,note:"Etki değerlendirmesi başlatıldı",confirmation:""}):setChangeAction({change:x,operation,note:"",confirmation:""})}/>)}</section><section><header><div><small>{tr?"KAYNAK GÖZETİMİ":"SOURCE OVERSIGHT"}</small><h3>{tr?"Gözden geçirme zamanı gelen kaynaklar":"Sources due for review"}</h3></div><span>{summary.dueSources}</span></header>{sources.filter(x=>x.enabled&&x.nextCheckAt<=new Date().toISOString()).map(x=><article className="ri-source-due" key={x.id}><div><b>{x.authority} · {x.name}</b><small>{x.jurisdiction} · {format(x.nextCheckAt)}</small></div><button disabled={busy||currentUser.role==="Viewer"} onClick={()=>void api({action:"source-checked",sourceId:x.id})}>{tr?"İncelendi":"Reviewed"}</button></article>)}</section></div>}
  {tab==="sources"&&<Table heads={[tr?"Kaynak":"Source",tr?"Yetki alanı":"Jurisdiction",tr?"Sahip":"Owner",tr?"Periyot":"Cadence",tr?"Son kontrol":"Last check",tr?"Sonraki":"Next",tr?"Değişiklik":"Changes",""]} rows={sources.map(x=>[<span key="source"><b>{x.authority}</b><small>{x.name}</small></span>,x.jurisdiction,x.owner,`${x.reviewFrequencyDays} ${tr?"gün":"days"}`,format(x.lastCheckedAt),format(x.nextCheckAt),x.changeCount,<button key="review" disabled={busy||currentUser.role==="Viewer"} onClick={()=>void api({action:"source-checked",sourceId:x.id})}>{tr?"İncelendi":"Reviewed"}</button>])} empty={tr?"Henüz regülasyon kaynağı yok.":"No regulatory source yet."}/>} 
  {tab==="changes"&&<Table heads={[tr?"Değişiklik":"Change",tr?"Önem":"Severity",tr?"Yürürlük":"Effective",tr?"Uygulanabilirlik":"Applicability",tr?"Durum":"Status",tr?"Etki":"Impact",""]} rows={changes.map(x=>[<span key="change"><b>{x.title}</b><small>{x.sourceName} · {x.externalRef}</small></span>,<State key="sev" value={x.severity}/>,format(x.effectiveDate),x.applicability,<State key="status" value={x.attention}/>,`${x.totalImpacts-x.openImpacts}/${x.totalImpacts}`,<div key="actions"><button onClick={()=>setSelected(x)}>{tr?"Aç":"Open"}</button>{currentUser.role!=="Viewer"&&!["closed","not-applicable"].includes(x.status)&&<button onClick={()=>openImpact(x)}>+ {tr?"Etki":"Impact"}</button>}</div>])} empty={tr?"Değişiklik kaydı yok.":"No regulatory change."}/>} 
  {tab==="impacts"&&<Table heads={[tr?"Hedef":"Target",tr?"Değişiklik":"Change",tr?"Etki":"Impact",tr?"Sahip / termin":"Owner / due",tr?"Durum":"Status",""]} rows={impacts.map(x=>[<span key="target"><b>{x.targetTitle}</b><small>{x.targetType} · {x.targetRef}</small></span>,changes.find(c=>c.id===x.changeId)?.title||x.changeId,<State key="level" value={x.impactLevel}/>,<span key="owner"><b>{x.actionOwner}</b><small>{format(x.dueDate)}</small></span>,<State key="status" value={x.overdue?"overdue":x.status}/>,<ImpactButtons key="actions" impact={x} role={currentUser.role} open={(action)=>setImpactAction({impact:x,action,note:"",evidenceReference:"",evidenceSha256:"",confirmation:""})}/>])} empty={tr?"Etki kaydı yok.":"No impact record."}/>} 
  {selected&&<Modal title={selected.title} close={()=>setSelected(null)}><div className="ri-detail"><div className="ri-detail-meta"><span>{selected.sourceName}</span><span>{selected.externalRef}</span><State value={selected.severity}/><State value={selected.attention}/></div><p>{selected.summary}</p><dl><div><dt>{tr?"Yayın":"Published"}</dt><dd>{format(selected.publishedDate)}</dd></div><div><dt>{tr?"Yürürlük":"Effective"}</dt><dd>{format(selected.effectiveDate)}</dd></div><div><dt>{tr?"Sahip":"Owner"}</dt><dd>{selected.owner}</dd></div><div><dt>Reviewer</dt><dd>{selected.reviewer}</dd></div></dl><code>SHA-256: {selected.contentSha256}</code><h4>{tr?"Bağlı etkiler ve aksiyonlar":"Linked impacts and actions"}</h4>{selectedImpacts.map(x=><article key={x.id}><div><b>{x.targetTitle}</b><small>{x.targetType} · {x.impactLevel} · {x.status}</small></div><p>{x.requiredAction}</p></article>)}<footer>{currentUser.role!=="Viewer"&&!["closed","not-applicable"].includes(selected.status)&&<button onClick={()=>openImpact(selected)}>+ {tr?"Etki ekle":"Add impact"}</button>}{currentUser.role!=="Viewer"&&selected.status==="triage"&&<button onClick={()=>void api({action:"change-action",changeId:selected.id,operation:"start-assessment",note:"Etki değerlendirmesi başlatıldı",confirmation:""})}>{tr?"Değerlendirmeyi Başlat":"Start Assessment"}</button>}{selected.status!=="closed"&&currentUser.role==="Admin"&&<button onClick={()=>setChangeAction({change:selected,operation:"not-applicable",note:"",confirmation:""})}>{tr?"Kapsam Dışı":"Not Applicable"}</button>}{selected.status==="verification"&&currentUser.role==="Admin"&&<button onClick={()=>setChangeAction({change:selected,operation:"close",note:"",confirmation:""})}>{tr?"Değişikliği Kapat":"Close Change"}</button>}</footer></div></Modal>}
  {sourceOpen&&<Modal title={tr?"Regülasyon kaynağı ekle":"Add regulatory source"} close={()=>setSourceOpen(false)}><form className="ri-form" onSubmit={saveSource}><Input label={tr?"Kaynak adı":"Source name"} value={sourceForm.name} set={name=>setSourceForm({...sourceForm,name})}/><Input label={tr?"Otorite":"Authority"} value={sourceForm.authority} set={authority=>setSourceForm({...sourceForm,authority})}/><Input label={tr?"Yetki alanı":"Jurisdiction"} value={sourceForm.jurisdiction} set={jurisdiction=>setSourceForm({...sourceForm,jurisdiction})}/><label>{tr?"Kaynak türü":"Source type"}<select value={sourceForm.sourceType} onChange={e=>setSourceForm({...sourceForm,sourceType:e.target.value})}><option value="regulator">Regulator</option><option value="legislation">Legislation</option><option value="standard">Standard</option><option value="industry">Industry</option><option value="internal">Internal</option></select></label><Input wide label="HTTPS URL" type="url" value={sourceForm.url} set={url=>setSourceForm({...sourceForm,url})}/><Input label={tr?"Sahip e-posta":"Owner email"} type="email" value={sourceForm.owner} set={owner=>setSourceForm({...sourceForm,owner})}/><Input label={tr?"İnceleme periyodu (gün)":"Review cadence (days)"} type="number" value={String(sourceForm.reviewFrequencyDays)} set={value=>setSourceForm({...sourceForm,reviewFrequencyDays:Number(value)})}/><FormFooter close={()=>setSourceOpen(false)} busy={busy} tr={tr}/></form></Modal>}
  {changeOpen&&<Modal title={tr?"Regülasyon değişikliği kaydet":"Record regulatory change"} close={()=>setChangeOpen(false)}><form className="ri-form" onSubmit={saveChange}><label>{tr?"Kaynak":"Source"}<select required value={changeForm.sourceId} onChange={e=>setChangeForm({...changeForm,sourceId:e.target.value})}><option value="">—</option>{sources.filter(x=>x.enabled).map(x=><option key={x.id} value={x.id}>{x.authority} · {x.name}</option>)}</select></label><Input label={tr?"Dış referans":"External reference"} value={changeForm.externalRef} set={externalRef=>setChangeForm({...changeForm,externalRef})}/><Input wide label={tr?"Başlık":"Title"} value={changeForm.title} set={title=>setChangeForm({...changeForm,title})}/><label className="wide">{tr?"Değişiklik özeti":"Change summary"}<textarea required minLength={20} rows={4} value={changeForm.summary} onChange={e=>setChangeForm({...changeForm,summary:e.target.value})}/></label><Input label={tr?"Yayın tarihi":"Published date"} type="date" value={changeForm.publishedDate} set={publishedDate=>setChangeForm({...changeForm,publishedDate})}/><Input label={tr?"Yürürlük tarihi":"Effective date"} type="date" value={changeForm.effectiveDate} set={effectiveDate=>setChangeForm({...changeForm,effectiveDate})}/><label>{tr?"Önem":"Severity"}<select value={changeForm.severity} onChange={e=>setChangeForm({...changeForm,severity:e.target.value})}>{["low","medium","high","critical"].map(x=><option key={x}>{x}</option>)}</select></label><label>{tr?"Tür":"Type"}<select value={changeForm.changeType} onChange={e=>setChangeForm({...changeForm,changeType:e.target.value})}>{["new-regulation","amendment","guidance","enforcement","deadline","consultation"].map(x=><option key={x}>{x}</option>)}</select></label><Input label={tr?"Sahip":"Owner"} type="email" value={changeForm.owner} set={owner=>setChangeForm({...changeForm,owner})}/><Input label="Reviewer" type="email" value={changeForm.reviewer} set={reviewer=>setChangeForm({...changeForm,reviewer})}/><FormFooter close={()=>setChangeOpen(false)} busy={busy} tr={tr}/></form></Modal>}
  {impactOpen&&<Modal title={tr?"Etki ve düzeltici aksiyon":"Impact and remediation action"} close={()=>setImpactOpen(false)}><form className="ri-form" onSubmit={saveImpact}><label>{tr?"Hedef türü":"Target type"}<select value={impactForm.targetType} onChange={e=>setImpactForm({...impactForm,targetType:e.target.value,targetRef:"",targetTitle:""})}>{Object.keys(targetModules).map(x=><option key={x}>{x}</option>)}</select></label><label>{tr?"Mevcut kayıt":"Existing record"}<select value={availableRecords.some(x=>x.id===impactForm.targetRef)?impactForm.targetRef:""} onChange={e=>chooseRecord(e.target.value)}><option value="">{tr?"Manuel referans":"Manual reference"}</option>{availableRecords.map(x=><option key={x.id} value={x.id}>{x.id} · {x.title}</option>)}</select></label><Input label={tr?"Hedef referansı":"Target reference"} value={impactForm.targetRef} set={targetRef=>setImpactForm({...impactForm,targetRef})}/><Input label={tr?"Hedef başlığı":"Target title"} value={impactForm.targetTitle} set={targetTitle=>setImpactForm({...impactForm,targetTitle})}/><label>{tr?"Etki seviyesi":"Impact level"}<select value={impactForm.impactLevel} onChange={e=>setImpactForm({...impactForm,impactLevel:e.target.value})}>{["low","medium","high","critical"].map(x=><option key={x}>{x}</option>)}</select></label><Input label={tr?"Aksiyon sahibi":"Action owner"} type="email" value={impactForm.actionOwner} set={actionOwner=>setImpactForm({...impactForm,actionOwner})}/><label className="wide">{tr?"Gerekli değişiklik / aksiyon":"Required change / action"}<textarea required minLength={10} rows={3} value={impactForm.requiredAction} onChange={e=>setImpactForm({...impactForm,requiredAction:e.target.value})}/></label><Input label={tr?"Termin":"Due date"} type="date" value={impactForm.dueDate} set={dueDate=>setImpactForm({...impactForm,dueDate})}/><FormFooter close={()=>setImpactOpen(false)} busy={busy} tr={tr}/></form></Modal>}
  {changeAction&&<Modal title={tr?"Değişiklik kararı":"Change decision"} close={()=>setChangeAction(null)}><div className="ri-form"><label className="wide">{tr?"Karar / kapanış gerekçesi":"Decision / closure rationale"}<textarea rows={4} value={changeAction.note} onChange={e=>setChangeAction({...changeAction,note:e.target.value})}/></label><Input wide label={`${tr?"Onay":"Confirmation"}: ${changePhrase(changeAction.operation)}`} value={changeAction.confirmation} set={confirmation=>setChangeAction({...changeAction,confirmation})}/><footer><button onClick={()=>setChangeAction(null)}>{tr?"Vazgeç":"Cancel"}</button><button disabled={busy} onClick={()=>void applyChange()}>{tr?"Kararı Uygula":"Apply Decision"}</button></footer></div></Modal>}
  {impactAction&&<Modal title={tr?"Etki aksiyonu":"Impact action"} close={()=>setImpactAction(null)}><div className="ri-form"><label className="wide">{tr?"İşlem notu":"Action note"}<textarea rows={3} value={impactAction.note} onChange={e=>setImpactAction({...impactAction,note:e.target.value})}/></label>{["submit","verify"].includes(impactAction.action)&&<><Input label={tr?"Kanıt referansı":"Evidence reference"} value={impactAction.evidenceReference} set={evidenceReference=>setImpactAction({...impactAction,evidenceReference})}/><Input label="SHA-256" value={impactAction.evidenceSha256} set={evidenceSha256=>setImpactAction({...impactAction,evidenceSha256})}/></>}<Input wide label={`${tr?"Onay":"Confirmation"}: ${impactPhrase(impactAction.action)}`} value={impactAction.confirmation} set={confirmation=>setImpactAction({...impactAction,confirmation})}/><footer><button onClick={()=>setImpactAction(null)}>{tr?"Vazgeç":"Cancel"}</button><button disabled={busy} onClick={()=>void applyImpact()}>{tr?"Uygula":"Apply"}</button></footer></div></Modal>}
 </section>
}

function Metric({value,label}:{value:number;label:string}){return <article><b>{value}</b><span>{label}</span></article>}
function State({value}:{value:string}){return <span className={`ri-state ${value}`}>{value}</span>}
function Table({heads,rows,empty}:{heads:string[];rows:React.ReactNode[][];empty:string}){return <div className="ri-table"><div className="table-wrap"><table><thead><tr>{heads.map((x,i)=><th key={`${x}-${i}`}>{x}</th>)}</tr></thead><tbody>{rows.length?rows.map((row,i)=><tr key={i}>{row.map((cell,j)=><td key={j}>{cell}</td>)}</tr>):<tr><td colSpan={heads.length}>{empty}</td></tr>}</tbody></table></div></div>}
function ChangeCard({item,tr,format,canWrite,select,addImpact,action}:{item:Change;tr:boolean;format:(v?:string)=>string;canWrite:boolean;select:()=>void;addImpact:()=>void;action:(x:string)=>void}){return <article className={`ri-change ${item.attention}`}><header><div><small>{item.sourceName} · {item.externalRef}</small><b>{item.title}</b></div><State value={item.attention}/></header><p>{item.summary}</p><div className="ri-change-meta"><span>{format(item.effectiveDate)}</span><span>{item.openImpacts}/{item.totalImpacts} {tr?"açık etki":"open impacts"}</span><span>{item.owner}</span></div><footer><button onClick={select}>{tr?"Detay":"Details"}</button>{canWrite&&item.status==="triage"&&<button onClick={()=>action("start-assessment")}>{tr?"Değerlendir":"Assess"}</button>}{canWrite&&!["closed","not-applicable"].includes(item.status)&&<button onClick={addImpact}>+ {tr?"Etki":"Impact"}</button>}</footer></article>}
function ImpactButtons({impact,role,open}:{impact:Impact;role:string;open:(x:string)=>void}){if(role==="Viewer")return <span>—</span>;if(impact.status==="open")return <button onClick={()=>open("start")}>Başlat</button>;if(impact.status==="in-progress")return <button onClick={()=>open("submit")}>Gönder</button>;if(impact.status==="verification"&&role==="Admin")return <><button onClick={()=>open("verify")}>Doğrula</button><button onClick={()=>open("reopen")}>İade</button></>;if(impact.status==="completed"&&role==="Admin")return <button onClick={()=>open("reopen")}>Yeniden aç</button>;return <span>—</span>}
function Input({label,value,set,type="text",wide=false}:{label:string;value:string;set:(value:string)=>void;type?:string;wide?:boolean}){return <label className={wide?"wide":""}>{label}<input required type={type} value={value} onChange={e=>set(e.target.value)}/></label>}
function FormFooter({close,busy,tr}:{close:()=>void;busy:boolean;tr:boolean}){return <footer><button type="button" onClick={close}>{tr?"Vazgeç":"Cancel"}</button><button disabled={busy}>{tr?"Kaydet":"Save"}</button></footer>}
function Modal({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <div className="overlay" onMouseDown={close}><div className="modal ri-modal" role="dialog" aria-modal="true" aria-label={title} onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><div><small>FORNOST REGULATORY INTELLIGENCE</small><h2>{title}</h2></div><button aria-label="Close dialog" onClick={close}>×</button></div>{children}</div></div>}
