"use client";
import { ChangeEvent, FormEvent, useEffect, useState } from "react";
import { withBasePath } from "./base-path";
import type { CatalogKey, CatalogMap } from "./catalogs";

type Lang = "tr" | "en";
type Config = { tenantId:string;clientId:string;smtpHost:string;smtpPort:string;senderEmail:string;reminderDays:string;ssoEnabled:boolean;remindersEnabled:boolean;tlsMode:string;domain:string;minimumTls:string;forceHttps:boolean;hstsEnabled:boolean };
const defaults: Config = { tenantId:"",clientId:"",smtpHost:"",smtpPort:"587",senderEmail:"",reminderDays:"15",ssoEnabled:false,remindersEnabled:true,tlsMode:"managed",domain:"",minimumTls:"1.2",forceHttps:true,hstsEnabled:true };

export default function Settings({ lang, currentUser, catalogs, onCatalogChange }:{ lang:Lang;currentUser:any;catalogs:CatalogMap;onCatalogChange:()=>Promise<void> }) {
  const tr=lang==="tr",[cfg,setCfg]=useState(defaults),[secret,setSecret]=useState(""),[certPassword,setCertPassword]=useState(""),[certFile,setCertFile]=useState<File|null>(null),[certError,setCertError]=useState(""),[message,setMessage]=useState("");
  useEffect(()=>{try{const x=localStorage.getItem("fornost-grc-settings");if(x)setCfg({...defaults,...JSON.parse(x)})}catch{}},[]);
  const set=(k:keyof Config,v:any)=>{setCfg(x=>({...x,[k]:v}));setMessage("")};
  function chooseCertificate(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0]||null;setCertError("");if(!file){setCertFile(null);return}const ext=file.name.toLowerCase().split(".").pop();if(!["pfx","p12","pem","crt","cer"].includes(ext||"")){setCertFile(null);e.target.value="";setCertError(tr?"Yalnız PFX, P12, PEM, CRT veya CER dosyası seçilebilir.":"Only PFX, P12, PEM, CRT or CER files are accepted.");return}if(file.size>5*1024*1024){setCertFile(null);e.target.value="";setCertError(tr?"Sertifika dosyası 5 MB'dan küçük olmalıdır.":"The certificate file must be smaller than 5 MB.");return}setCertFile(file)}
  function save(e:FormEvent){e.preventDefault();localStorage.setItem("fornost-grc-settings",JSON.stringify(cfg));setSecret("");setCertPassword("");setCertFile(null);setMessage(tr?"Ayarlar kaydedildi. Sertifika ve parolalar tarayıcıda saklanmadı.":"Settings saved. Certificates and passwords were not stored in the browser.")}
  return <>
    <section className="module-head settings-head"><div><h2>{tr?"Platform Ayarları":"Platform Settings"}</h2><p>{tr?"Ana veri listeleri, Entra ID, SMTP, HTTPS/TLS, risk hatırlatmaları ve yerel hesapları yönetin.":"Manage master data, Entra ID, SMTP, HTTPS/TLS, risk reminders and local accounts."}</p></div><span className="admin-badge">{tr?"Yalnızca Yönetici":"Administrators only"}</span></section>
    {currentUser.role==="Admin"&&<CatalogManager lang={lang} catalogs={catalogs} onChange={onCatalogChange}/>}
    <form className="settings-grid" onSubmit={save}>
      <Card title="Microsoft Entra ID SSO" desc={tr?"Kurumsal kullanıcı girişi":"Corporate sign-in"} status={cfg.ssoEnabled?(tr?"Etkin":"Enabled"):(tr?"Taslak":"Draft")}><Toggle checked={cfg.ssoEnabled} onChange={v=>set("ssoEnabled",v)} label={tr?"Entra ID SSO'yu etkinleştir":"Enable Entra ID SSO"}/><Input label="Tenant ID" value={cfg.tenantId} onChange={v=>set("tenantId",v)}/><Input label="Client ID" value={cfg.clientId} onChange={v=>set("clientId",v)}/></Card>
      <Card title="SMTP Relay" desc={tr?"Risk bildirim e-postaları":"Risk notification emails"} status={cfg.smtpHost?(tr?"Yapılandırıldı":"Configured"):(tr?"Eksik":"Incomplete")}><Input label={tr?"SMTP Sunucusu":"SMTP Server"} value={cfg.smtpHost} onChange={v=>set("smtpHost",v)}/><Input label="Port" value={cfg.smtpPort} onChange={v=>set("smtpPort",v)} type="number"/><Input label={tr?"Gönderici E-posta":"Sender Email"} value={cfg.senderEmail} onChange={v=>set("senderEmail",v)} type="email"/><Input label={tr?"Parola / Secret":"Password / Secret"} value={secret} onChange={setSecret} type="password" placeholder={tr?"Kaydedildikten sonra gösterilmez":"Hidden after saving"}/></Card>
      <Card title={tr?"HTTPS / TLS Güvenliği":"HTTPS / TLS Security"} desc={tr?"Alan adı, sertifika ve güvenli protokol ayarları":"Domain, certificate and secure protocol settings"} status={cfg.tlsMode==="managed"?(tr?"Platform Korumalı":"Platform Managed"):(cfg.domain?(tr?"Bağlama Hazır":"Ready to Bind"):(tr?"Eksik":"Incomplete"))} wide>
        <label className="setting-field wide"><span>{tr?"Sertifika Yönetimi":"Certificate Management"}</span><select value={cfg.tlsMode} onChange={e=>set("tlsMode",e.target.value)}><option value="managed">{tr?"Platform tarafından yönetilen SSL (önerilen)":"Platform-managed SSL (recommended)"}</option><option value="custom">{tr?"Özel alan adı / Azure App Service":"Custom domain / Azure App Service"}</option></select></label>
        <Input label={tr?"Alan Adı (FQDN)":"Domain (FQDN)"} value={cfg.domain} onChange={v=>set("domain",v.trim())} placeholder="grc.firma.com"/>
        <label className="setting-field"><span>{tr?"Minimum TLS Sürümü":"Minimum TLS Version"}</span><select value={cfg.minimumTls} onChange={e=>set("minimumTls",e.target.value)}><option value="1.2">TLS 1.2</option><option value="1.3">TLS 1.3</option></select></label>
        <Toggle checked={cfg.forceHttps} onChange={v=>set("forceHttps",v)} label={tr?"HTTP isteklerini HTTPS'e yönlendir":"Redirect HTTP requests to HTTPS"}/><Toggle checked={cfg.hstsEnabled} onChange={v=>set("hstsEnabled",v)} label={tr?"HSTS güvenlik başlığını etkinleştir":"Enable HSTS security header"}/>
        {cfg.tlsMode==="custom"&&<><label className="setting-field wide certificate-upload"><span>{tr?"SSL Sertifikası":"SSL Certificate"}</span><input type="file" accept=".pfx,.p12,.pem,.crt,.cer,application/x-pkcs12,application/x-pem-file" onChange={chooseCertificate}/><small>{tr?"PFX/P12 veya PEM/CRT/CER · En fazla 5 MB.":"PFX/P12 or PEM/CRT/CER · Maximum 5 MB."}</small>{certError&&<em>{certError}</em>}</label><Input label={tr?"Sertifika Parolası":"Certificate Password"} value={certPassword} onChange={setCertPassword} type="password" placeholder={tr?"Kalıcı olarak saklanmaz":"Never stored persistently"}/><div className="tls-state"><b>{tr?"Seçilen sertifika":"Selected certificate"}</b><span>{certFile?.name||(tr?"Henüz seçilmedi":"Not selected")}</span></div></>}
        <div className="security-note wide"><b>{tr?"Güvenli çalışma modeli":"Secure operating model"}</b><p>{tr?"TLS sonlandırması barındırma katmanında yapılır; sertifika ve parola yerel ayarlara yazılmaz.":"TLS terminates at the hosting layer; certificates and passwords are not written to local settings."}</p></div>
      </Card>
      <Card title={tr?"Risk Hatırlatmaları":"Risk Reminders"} desc={tr?"Sonraki değerlendirme tarihine göre otomatik bildirim":"Automatic notifications based on the next review date"} status={cfg.remindersEnabled?(tr?"Etkin":"Enabled"):(tr?"Kapalı":"Disabled")} wide><Toggle checked={cfg.remindersEnabled} onChange={v=>set("remindersEnabled",v)} label={tr?"Otomatik hatırlatmaları etkinleştir":"Enable automatic reminders"}/><Input label={tr?"Kaç Gün Önce":"Days Before"} value={cfg.reminderDays} onChange={v=>set("reminderDays",v)} type="number"/><div className="reminder-rule wide"><b>{tr?"Alıcı kuralı":"Recipient rule"}</b><p>{tr?`Açık risklerde ${cfg.reminderDays||15} gün önce aktif kullanıcılara ve risk sahibi e-postasına bildirim gönderilir.`:`For open risks, reminders are sent ${cfg.reminderDays||15} days before review to active users and the risk-owner email.`}</p></div></Card>
      <div className="settings-footer">{message&&<span>{message}</span>}<button className="primary">{tr?"Ayarları Kaydet":"Save Settings"}</button></div>
    </form>
    {currentUser.role==="Admin"&&<LocalUsers lang={lang}/>}
  </>;
}

const catalogLabels:Record<CatalogKey,{tr:string;en:string}>={
  riskCategories:{tr:"Risk Kategorileri",en:"Risk Categories"},biaCategories:{tr:"BIA Süreç Kategorileri",en:"BIA Process Categories"},assetTypes:{tr:"Varlık Türleri",en:"Asset Types"},businessUnits:{tr:"İş Birimleri",en:"Business Units"},criticalities:{tr:"Kritiklik Seviyeleri",en:"Criticality Levels"},dataClassifications:{tr:"Veri Sınıfları",en:"Data Classifications"},environments:{tr:"Ortamlar",en:"Environments"},
};
function CatalogManager({lang,catalogs,onChange}:{lang:Lang;catalogs:CatalogMap;onChange:()=>Promise<void>}){
  const tr=lang==="tr",[drafts,setDrafts]=useState<Partial<Record<CatalogKey,string>>>({}),[message,setMessage]=useState("");
  async function add(key:CatalogKey,e:FormEvent){e.preventDefault();const value=(drafts[key]||"").trim();if(!value)return;const r=await fetch(withBasePath("/api/catalogs"),{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({catalog:key,value})}),j=await r.json().catch(()=>({}));setMessage(r.ok?(tr?"Liste değeri eklendi.":"List value added."):j.error);if(r.ok){setDrafts(x=>({...x,[key]:""}));await onChange()}}
  async function remove(key:CatalogKey,value:string){if(!confirm(tr?`“${value}” yeni kayıtlardaki seçim listesinden kaldırılsın mı? Mevcut kayıtlar değişmez.`:`Remove “${value}” from future selections? Existing records will remain unchanged.`))return;const r=await fetch(withBasePath(`/api/catalogs?catalog=${encodeURIComponent(key)}&value=${encodeURIComponent(value)}`),{method:"DELETE"}),j=await r.json().catch(()=>({}));setMessage(r.ok?(tr?"Liste değeri kaldırıldı.":"List value removed."):j.error);if(r.ok)await onChange()}
  return <section className="settings-card catalog-manager"><div className="settings-card-head"><div><h3>{tr?"Ana Veri / Liste Yönetimi":"Master Data / List Management"}</h3><p>{tr?"Risk, BIA ve varlık envanterindeki seçim listelerini merkezi olarak yönetin.":"Centrally manage selection lists used by Risk, BIA and Asset Inventory."}</p></div><span>{tr?"Canlı":"Live"}</span></div>{message&&<div className="catalog-message">{message}</div>}<div className="catalog-grid">{(Object.keys(catalogLabels) as CatalogKey[]).map(key=><article key={key}><header><b>{catalogLabels[key][lang]}</b><span>{catalogs[key]?.length||0}</span></header><div className="catalog-values">{(catalogs[key]||[]).map(value=><div key={value}><span>{value}</span><button type="button" onClick={()=>remove(key,value)} aria-label={`${value} ${tr?"sil":"delete"}`}>×</button></div>)}</div><form onSubmit={e=>add(key,e)}><input value={drafts[key]||""} maxLength={100} minLength={2} onChange={e=>setDrafts(x=>({...x,[key]:e.target.value}))} placeholder={tr?"Yeni değer...":"New value..."}/><button className="primary">{tr?"Ekle":"Add"}</button></form></article>)}</div><footer>{tr?"Bir değer silindiğinde mevcut kayıtların tarihsel değeri korunur; yalnız yeni seçimlerden kaldırılır.":"Deleting a value preserves historical records and only removes it from future selections."}</footer></section>;
}

function LocalUsers({lang}:{lang:Lang}){const tr=lang==="tr",[users,setUsers]=useState<any[]>([]),[message,setMessage]=useState("");async function load(){const r=await fetch(withBasePath("/api/users"),{cache:"no-store"});if(r.ok)setUsers((await r.json()).users||[])}useEffect(()=>{load()},[]);async function add(e:FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget),r=await fetch(withBasePath("/api/users"),{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(Object.fromEntries(fd))}),j=await r.json();setMessage(r.ok?(tr?"Yerel hesap oluşturuldu.":"Local account created."):j.error);if(r.ok){e.currentTarget.reset();load()}}return <section className="settings-card local-users"><div className="settings-card-head"><div><h3>{tr?"Yerel Kullanıcı Hesapları":"Local User Accounts"}</h3><p>{tr?"Entra SSO kullanılamadığında giriş yapabilecek kontrollü hesaplar.":"Controlled fallback accounts for use when Entra SSO is unavailable."}</p></div><span>{users.length} {tr?"hesap":"accounts"}</span></div><form className="settings-fields" onSubmit={add}><NativeInput name="name" label={tr?"Ad Soyad":"Full Name"}/><NativeInput name="email" label="E-posta" type="email"/><NativeInput name="password" label={tr?"Geçici Güçlü Parola":"Temporary Strong Password"} type="password"/><label className="setting-field"><span>{tr?"Rol":"Role"}</span><select name="role"><option>Viewer</option><option>Editor</option><option>Admin</option></select></label><p className="wide local-policy">{tr?"En az 12 karakter; büyük/küçük harf, sayı ve özel karakter.":"Minimum 12 characters with upper/lowercase, number and symbol."}</p><button className="primary card-action">{tr?"Yerel Hesap Oluştur":"Create Local Account"}</button>{message&&<span className="local-message">{message}</span>}</form><div className="local-user-list">{users.map(u=><div key={u.id}><b>{u.name}</b><span>{u.email}</span><em>{u.role} · {u.status}</em></div>)}</div></section>}
function Card({title,desc,status,children,wide=false}:{title:string;desc:string;status:string;children:any;wide?:boolean}){return <section className={`settings-card${wide?" settings-card-wide":""}`}><div className="settings-card-head"><div><h3>{title}</h3><p>{desc}</p></div><span>{status}</span></div><div className="settings-fields">{children}</div></section>}
function Input({label,value,onChange,type="text",placeholder=""}:{label:string;value:string;onChange:(v:string)=>void;type?:string;placeholder?:string}){return <label className="setting-field"><span>{label}</span><input type={type} value={value} placeholder={placeholder} onChange={e=>onChange(e.target.value)}/></label>}
function NativeInput({name,label,type="text"}:{name:string;label:string;type?:string}){return <label className="setting-field"><span>{label}</span><input name={name} type={type} required minLength={type==="password"?12:undefined}/></label>}
function Toggle({checked,onChange,label}:{checked:boolean;onChange:(v:boolean)=>void;label:string}){return <label className="setting-toggle wide"><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)}/><i/><span>{label}</span></label>}
