"use client";
import { ChangeEvent, FormEvent, useEffect, useState } from "react";
import { withBasePath } from "./base-path";
import type { CatalogKey, CatalogMap } from "./catalogs";
import IntegrationSettings from "./integration-settings";
import AiSettings from "./ai-settings";
import "./integration-settings.css";

type Lang = "tr" | "en";
export type SettingsPage = "system" | "ai" | "catalogs" | "workflow" | "email" | "identity";
type Config = { reminderDays:string;remindersEnabled:boolean;tlsMode:string;domain:string;minimumTls:string;forceHttps:boolean;hstsEnabled:boolean;organizationName:string;timezone:string;dateFormat:string;sessionTimeoutMinutes:string;auditRetentionDays:string;telemetryEnabled:boolean };
const defaults: Config = { reminderDays:"15",remindersEnabled:true,tlsMode:"managed",domain:"",minimumTls:"1.2",forceHttps:true,hstsEnabled:true,organizationName:"Fornost Enterprise",timezone:"Europe/Istanbul",dateFormat:"DD.MM.YYYY",sessionTimeoutMinutes:"30",auditRetentionDays:"365",telemetryEnabled:false };

export default function Settings({ lang, currentUser, catalogs, onCatalogChange, onDataChange, page }:{ lang:Lang;currentUser:any;catalogs:CatalogMap;onCatalogChange:()=>Promise<void>;onDataChange?:()=>Promise<void>;page:SettingsPage }) {
  const tr=lang==="tr",[cfg,setCfg]=useState(defaults),[certPassword,setCertPassword]=useState(""),[certFile,setCertFile]=useState<File|null>(null),[certError,setCertError]=useState(""),[message,setMessage]=useState("");
  useEffect(()=>{try{const x=localStorage.getItem("fornost-grc-settings");if(x)setCfg({...defaults,...JSON.parse(x)})}catch{}},[]);
  const set=(k:keyof Config,v:any)=>{setCfg(x=>({...x,[k]:v}));setMessage("")};
  function chooseCertificate(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0]||null;setCertError("");if(!file){setCertFile(null);return}const ext=file.name.toLowerCase().split(".").pop();if(!["pfx","p12","pem","crt","cer"].includes(ext||"")){setCertFile(null);e.target.value="";setCertError(tr?"Yalnız PFX, P12, PEM, CRT veya CER dosyası seçilebilir.":"Only PFX, P12, PEM, CRT or CER files are accepted.");return}if(file.size>5*1024*1024){setCertFile(null);e.target.value="";setCertError(tr?"Sertifika dosyası 5 MB'dan küçük olmalıdır.":"The certificate file must be smaller than 5 MB.");return}setCertFile(file)}
  function save(e:FormEvent){e.preventDefault();localStorage.setItem("fornost-grc-settings",JSON.stringify(cfg));setCertPassword("");setCertFile(null);setMessage(tr?"Yerel platform tercihleri kaydedildi. Sertifika ve parolalar tarayıcıda saklanmadı.":"Local platform preferences saved. Certificates and passwords were not stored in the browser.")}
  const headings:Record<SettingsPage,{tr:[string,string];en:[string,string]}>= {
    system:{tr:["Sistem Ayarları","HTTPS/TLS güvenliği ve risk hatırlatma kurallarını yönetin."],en:["System Settings","Manage HTTPS/TLS security and risk reminder rules."]},
    ai:{tr:["AI Ayarları","Model gateway, veri paylaşım sınırları, fallback ve operasyon politikasını yönetin."],en:["AI Settings","Manage the model gateway, data-sharing boundaries, fallback and operating policy."]},
    catalogs:{tr:["Ana Veri Yönetimi","Risk, BIA ve varlık envanterinde kullanılan seçim listelerini yönetin."],en:["Master Data Management","Manage selection lists used across Risk, BIA and Asset Inventory."]},
    workflow:{tr:["İş Akışı Entegrasyonları","Jira ve diğer ticketing sistemleriyle GRC aksiyonlarını bağlayın."],en:["Workflow Integrations","Connect GRC actions with Jira and other ticketing systems."]},
    email:{tr:["E-posta ve Bildirimler","SMTP, Graph veya e-posta API kanalını yapılandırıp test edin."],en:["Email & Notifications","Configure and test SMTP, Graph or email API delivery."]},
    identity:{tr:["Kimlik ve Erişim","Entra, Okta, OIDC, SAML, LDAP/LDAPS ve yerel kullanıcıları yönetin."],en:["Identity & Access","Manage Entra, Okta, OIDC, SAML, LDAP/LDAPS and local users."]},
  };
  const [title,description]=headings[page][lang];
  if(currentUser.role!=="Admin")return <section className="settings-empty"><b>{tr?"Yönetici yetkisi gerekli":"Administrator access required"}</b><p>{tr?"Bu yönetim ekranını yalnızca Admin rolündeki kullanıcılar açabilir.":"Only users with the Admin role can open this management page."}</p></section>;
  return <>
    <section className="module-head settings-head"><div><small>{tr?"YÖNETİM KONSOLU":"ADMIN CONSOLE"}</small><h2>{title}</h2><p>{description}</p></div><span className="admin-badge">{tr?"Yalnızca Yönetici":"Administrators only"}</span></section>
    {page==="workflow"&&<IntegrationSettings lang={lang} kind="ticketing"/>}
    {page==="email"&&<IntegrationSettings lang={lang} kind="email"/>}
    {page==="ai"&&<AiSettings lang={lang}/>}
    {page==="identity"&&<><IntegrationSettings lang={lang} kind="identity"/><LocalUsers lang={lang}/></>}
    {page==="catalogs"&&<CatalogManager lang={lang} catalogs={catalogs} onChange={onCatalogChange}/>}
    {page==="system"&&<form className="settings-grid" onSubmit={save}>
      <Card title={tr?"HTTPS / TLS Güvenliği":"HTTPS / TLS Security"} desc={tr?"Alan adı, sertifika ve güvenli protokol ayarları":"Domain, certificate and secure protocol settings"} status={cfg.tlsMode==="managed"?(tr?"Platform Korumalı":"Platform Managed"):(cfg.domain?(tr?"Bağlama Hazır":"Ready to Bind"):(tr?"Eksik":"Incomplete"))} wide>
        <label className="setting-field wide"><span>{tr?"Sertifika Yönetimi":"Certificate Management"}</span><select value={cfg.tlsMode} onChange={e=>set("tlsMode",e.target.value)}><option value="managed">{tr?"Platform tarafından yönetilen SSL (önerilen)":"Platform-managed SSL (recommended)"}</option><option value="custom">{tr?"Özel alan adı / Azure App Service":"Custom domain / Azure App Service"}</option></select></label>
        <Input label={tr?"Alan Adı (FQDN)":"Domain (FQDN)"} value={cfg.domain} onChange={v=>set("domain",v.trim())} placeholder="grc.firma.com"/>
        <label className="setting-field"><span>{tr?"Minimum TLS Sürümü":"Minimum TLS Version"}</span><select value={cfg.minimumTls} onChange={e=>set("minimumTls",e.target.value)}><option value="1.2">TLS 1.2</option><option value="1.3">TLS 1.3</option></select></label>
        <Toggle checked={cfg.forceHttps} onChange={v=>set("forceHttps",v)} label={tr?"HTTP isteklerini HTTPS'e yönlendir":"Redirect HTTP requests to HTTPS"}/><Toggle checked={cfg.hstsEnabled} onChange={v=>set("hstsEnabled",v)} label={tr?"HSTS güvenlik başlığını etkinleştir":"Enable HSTS security header"}/>
        {cfg.tlsMode==="custom"&&<><label className="setting-field wide certificate-upload"><span>{tr?"SSL Sertifikası":"SSL Certificate"}</span><input type="file" accept=".pfx,.p12,.pem,.crt,.cer,application/x-pkcs12,application/x-pem-file" onChange={chooseCertificate}/><small>{tr?"PFX/P12 veya PEM/CRT/CER · En fazla 5 MB.":"PFX/P12 or PEM/CRT/CER · Maximum 5 MB."}</small>{certError&&<em>{certError}</em>}</label><Input label={tr?"Sertifika Parolası":"Certificate Password"} value={certPassword} onChange={setCertPassword} type="password" placeholder={tr?"Kalıcı olarak saklanmaz":"Never stored persistently"}/><div className="tls-state"><b>{tr?"Seçilen sertifika":"Selected certificate"}</b><span>{certFile?.name||(tr?"Henüz seçilmedi":"Not selected")}</span></div></>}
        <div className="security-note wide"><b>{tr?"Güvenli çalışma modeli":"Secure operating model"}</b><p>{tr?"TLS sonlandırması barındırma katmanında yapılır; sertifika ve parola yerel ayarlara yazılmaz.":"TLS terminates at the hosting layer; certificates and passwords are not written to local settings."}</p></div>
      </Card>
      <Card title={tr?"Organizasyon ve Yerelleştirme":"Organization & Localization"} desc={tr?"Kurum adı, saat dilimi ve tarih gösterimi":"Organization name, time zone and date presentation"} status={tr?"Kurumsal":"Enterprise"}>
        <Input label={tr?"Organizasyon Adı":"Organization Name"} value={cfg.organizationName} onChange={v=>set("organizationName",v)} placeholder="Fornost Enterprise"/>
        <label className="setting-field"><span>{tr?"Saat Dilimi":"Time Zone"}</span><select value={cfg.timezone} onChange={e=>set("timezone",e.target.value)}><option value="Europe/Istanbul">Europe/Istanbul</option><option value="Europe/London">Europe/London</option><option value="Europe/Berlin">Europe/Berlin</option><option value="UTC">UTC</option></select></label>
        <label className="setting-field"><span>{tr?"Tarih Biçimi":"Date Format"}</span><select value={cfg.dateFormat} onChange={e=>set("dateFormat",e.target.value)}><option value="DD.MM.YYYY">DD.MM.YYYY</option><option value="YYYY-MM-DD">YYYY-MM-DD</option><option value="MM/DD/YYYY">MM/DD/YYYY</option></select></label>
      </Card>
      <Card title={tr?"Oturum ve Veri Saklama":"Session & Data Retention"} desc={tr?"Yönetim oturumu ve denetim izi saklama sınırları":"Administrative session and audit-trail retention boundaries"} status={tr?"Güvenli Varsayılan":"Secure Default"}>
        <Input label={tr?"Oturum Zaman Aşımı (dk)":"Session Timeout (min)"} value={cfg.sessionTimeoutMinutes} onChange={v=>set("sessionTimeoutMinutes",v)} type="number"/>
        <Input label={tr?"Audit Saklama (gün)":"Audit Retention (days)"} value={cfg.auditRetentionDays} onChange={v=>set("auditRetentionDays",v)} type="number"/>
        <Toggle checked={cfg.telemetryEnabled} onChange={v=>set("telemetryEnabled",v)} label={tr?"Anonim ürün telemetrisine izin ver":"Allow anonymous product telemetry"}/>
        <div className="security-note wide"><b>{tr?"On-prem veri sınırı":"On-prem data boundary"}</b><p>{tr?"Telemetri varsayılan olarak kapalıdır; kayıt içerikleri, kanıtlar ve kullanıcı kimlikleri dışarı gönderilmez.":"Telemetry is disabled by default; record content, evidence and user identities never leave the deployment."}</p></div>
      </Card>
      <Card title={tr?"Risk Hatırlatmaları":"Risk Reminders"} desc={tr?"Sonraki değerlendirme tarihine göre otomatik bildirim":"Automatic notifications based on the next review date"} status={cfg.remindersEnabled?(tr?"Etkin":"Enabled"):(tr?"Kapalı":"Disabled")} wide><Toggle checked={cfg.remindersEnabled} onChange={v=>set("remindersEnabled",v)} label={tr?"Otomatik hatırlatmaları etkinleştir":"Enable automatic reminders"}/><Input label={tr?"Kaç Gün Önce":"Days Before"} value={cfg.reminderDays} onChange={v=>set("reminderDays",v)} type="number"/><div className="reminder-rule wide"><b>{tr?"Alıcı kuralı":"Recipient rule"}</b><p>{tr?`Açık risklerde ${cfg.reminderDays||15} gün önce aktif kullanıcılara ve risk sahibi e-postasına bildirim gönderilir.`:`For open risks, reminders are sent ${cfg.reminderDays||15} days before review to active users and the risk-owner email.`}</p></div></Card>
      <div className="settings-footer">{message&&<span>{message}</span>}<button className="primary">{tr?"Ayarları Kaydet":"Save Settings"}</button></div>
    </form>}
    {page==="system"&&<DemoDataManager lang={lang} onDataChange={onDataChange}/>}
  </>;
}

type DemoInventory={present:number;total:number;missing:number;modules:Record<string,{present:number;total:number}>};
function DemoDataManager({lang,onDataChange}:{lang:Lang;onDataChange?:()=>Promise<void>}){
  const tr=lang==="tr",[inventory,setInventory]=useState<DemoInventory|null>(null),[busy,setBusy]=useState(false),[confirmation,setConfirmation]=useState(""),[message,setMessage]=useState("");
  async function load(){const response=await fetch(withBasePath("/api/grc/demo"),{cache:"no-store"});if(response.ok)setInventory(await response.json())}
  useEffect(()=>{void load()},[]);
  async function restore(){setBusy(true);setMessage("");try{const response=await fetch(withBasePath("/api/grc/demo"),{method:"POST"}),body=await response.json().catch(()=>({}));setMessage(response.ok?(tr?`${body.restored||0} örnek kayıt geri yüklendi.`:`${body.restored||0} sample records restored.`):String(body.error||"Error"));if(response.ok){await load();await onDataChange?.()}}finally{setBusy(false)}}
  async function remove(){setBusy(true);setMessage("");try{const response=await fetch(withBasePath("/api/grc/demo"),{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({confirmation})}),body=await response.json().catch(()=>({}));setMessage(response.ok?(tr?`${body.removed||0} örnek kayıt kaldırıldı. Kurum kayıtlarına dokunulmadı.`:`${body.removed||0} sample records removed. Organization records were preserved.`):String(body.error||"Error"));if(response.ok){setConfirmation("");await load();await onDataChange?.()}}finally{setBusy(false)}}
  return <section className="settings-card demo-data-manager"><div className="settings-card-head"><div><h3>{tr?"Örnek Veri Yaşam Döngüsü":"Sample Data Lifecycle"}</h3><p>{tr?"Sekiz çekirdek modüldeki kurgusal kayıtları yeniden yükleyin veya yalnız örnek kayıtları kaldırın.":"Restore or remove only the fictional records across the eight core modules."}</p></div><span>{inventory?`${inventory.present}/${inventory.total}`:"—"}</span></div><div className="demo-data-summary">{Object.entries(inventory?.modules||{}).map(([module,count])=><div key={module}><b>{module}</b><span>{count.present}/{count.total}</span></div>)}</div><div className="demo-data-actions"><button type="button" disabled={busy||inventory?.missing===0} onClick={()=>void restore()}>{tr?"Eksik Örnekleri Geri Yükle":"Restore Missing Samples"}</button><label><span>{tr?"Kaldırmak için ÖRNEKLERİ KALDIR yazın":"Type ÖRNEKLERİ KALDIR to remove"}</span><input value={confirmation} onChange={event=>setConfirmation(event.target.value)} autoComplete="off"/></label><button type="button" className="danger" disabled={busy||!inventory?.present||confirmation!=="ÖRNEKLERİ KALDIR"} onClick={()=>void remove()}>{tr?"Örnek Kayıtları Kaldır":"Remove Sample Records"}</button></div>{message&&<p className="demo-data-message" aria-live="polite">{message}</p>}<footer>{tr?"İşlem yalnız RSK/BIA/AST/CMP/VEN/CTL/EVD/AUD örnek kimliklerini hedefler. Sonradan eklenen kurum kayıtları korunur.":"Only the known RSK/BIA/AST/CMP/VEN/CTL/EVD/AUD sample identifiers are targeted. Organization records added later are preserved."}</footer></section>
}

const catalogLabels:Record<CatalogKey,{tr:string;en:string}>={
  riskCategories:{tr:"Risk Kategorileri",en:"Risk Categories"},biaCategories:{tr:"BIA Süreç Kategorileri",en:"BIA Process Categories"},assetTypes:{tr:"Varlık Türleri",en:"Asset Types"},businessUnits:{tr:"İş Birimleri",en:"Business Units"},criticalities:{tr:"Kritiklik Seviyeleri",en:"Criticality Levels"},dataClassifications:{tr:"Veri Sınıfları",en:"Data Classifications"},environments:{tr:"Ortamlar",en:"Environments"},
};
function CatalogManager({lang,catalogs,onChange}:{lang:Lang;catalogs:CatalogMap;onChange:()=>Promise<void>}){
  const tr=lang==="tr",[drafts,setDrafts]=useState<Partial<Record<CatalogKey,string>>>({}),[message,setMessage]=useState("");
  async function add(key:CatalogKey,e:FormEvent){e.preventDefault();const value=(drafts[key]||"").trim();if(!value)return;const r=await fetch(withBasePath("/api/catalogs"),{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({catalog:key,value})}),j=await r.json().catch(()=>({}));setMessage(r.ok?(tr?"Liste değeri eklendi.":"List value added."):j.error);if(r.ok){setDrafts(x=>({...x,[key]:""}));await onChange()}}
  async function remove(key:CatalogKey,value:string){if(!confirm(tr?`“${value}” yeni kayıtlardaki seçim listesinden kaldırılsın mı? Mevcut kayıtlar değişmez.`:`Remove “${value}” from future selections? Existing records will remain unchanged.`))return;const r=await fetch(withBasePath(`/api/catalogs?catalog=${encodeURIComponent(key)}&value=${encodeURIComponent(value)}`),{method:"DELETE"}),j=await r.json().catch(()=>({}));setMessage(r.ok?(tr?"Liste değeri kaldırıldı.":"List value removed."):j.error);if(r.ok)await onChange()}
  return <section className="settings-card catalog-manager"><div className="settings-card-head"><div><h3>{tr?"Ana Veri / Liste Yönetimi":"Master Data / List Management"}</h3><p>{tr?"Risk, BIA ve varlık envanterindeki seçim listelerini merkezi olarak yönetin.":"Centrally manage selection lists used by Risk, BIA and Asset Inventory."}</p></div><span>{tr?"Canlı":"Live"}</span></div>{message&&<div className="catalog-message">{message}</div>}<div className="catalog-grid">{(Object.keys(catalogLabels) as CatalogKey[]).map(key=><article key={key}><header><b>{catalogLabels[key][lang]}</b><span>{catalogs[key]?.length||0}</span></header><div className="catalog-values">{(catalogs[key]||[]).map(value=><div key={value}><span>{value}</span><button type="button" onClick={()=>remove(key,value)} aria-label={`${value} ${tr?"sil":"delete"}`}>×</button></div>)}</div><form onSubmit={e=>add(key,e)}><input value={drafts[key]||""} maxLength={100} minLength={2} onChange={e=>setDrafts(x=>({...x,[key]:e.target.value}))} placeholder={tr?"Yeni değer...":"New value..."}/><button className="primary">{tr?"Ekle":"Add"}</button></form></article>)}</div><footer>{tr?"Bir değer silindiğinde mevcut kayıtların tarihsel değeri korunur; yalnız yeni seçimlerden kaldırılır.":"Deleting a value preserves historical records and only removes it from future selections."}</footer></section>;
}

type LocalUser={id:string;name:string;email:string;role:"Admin"|"Editor"|"Viewer";status:"Active"|"Disabled";failed_attempts?:number;locked_until?:string};
function LocalUsers({lang}:{lang:Lang}){
  const tr=lang==="tr",[users,setUsers]=useState<LocalUser[]>([]),[message,setMessage]=useState(""),[busyId,setBusyId]=useState("");
  async function load(){const response=await fetch(withBasePath("/api/users"),{cache:"no-store"});if(response.ok)setUsers((await response.json()).users||[])}
  useEffect(()=>{void load()},[]);
  async function add(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,fd=new FormData(form),response=await fetch(withBasePath("/api/users"),{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(Object.fromEntries(fd))}),body=await response.json().catch(()=>({}));setMessage(response.ok?(tr?"Yerel hesap oluşturuldu.":"Local account created."):String(body.error||"Error"));if(response.ok){form.reset();await load()}}
  function change(id:string,key:"role"|"status",value:string){setUsers(current=>current.map(user=>user.id===id?{...user,[key]:value}:user) as LocalUser[])}
  async function save(user:LocalUser){setBusyId(user.id);const response=await fetch(withBasePath("/api/users"),{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:user.id,role:user.role,status:user.status})}),body=await response.json().catch(()=>({}));setMessage(response.ok?(tr?"Kullanıcı rolü ve durumu güncellendi.":"User role and status updated."):String(body.error||"Error"));await load();setBusyId("")}
  return <section className="settings-card local-users"><div className="settings-card-head"><div><h3>{tr?"Yerel Kullanıcı Hesapları":"Local User Accounts"}</h3><p>{tr?"Entra SSO kullanılamadığında giriş yapabilecek kontrollü hesaplar.":"Controlled fallback accounts for use when Entra SSO is unavailable."}</p></div><span>{users.length} {tr?"hesap":"accounts"}</span></div><form className="settings-fields" onSubmit={add}><NativeInput name="name" label={tr?"Ad Soyad":"Full Name"}/><NativeInput name="email" label="E-posta" type="email"/><NativeInput name="password" label={tr?"Geçici Güçlü Parola":"Temporary Strong Password"} type="password"/><label className="setting-field"><span>{tr?"Rol":"Role"}</span><select name="role"><option>Viewer</option><option>Editor</option><option>Admin</option></select></label><p className="wide local-policy">{tr?"En az 12 karakter; büyük/küçük harf, sayı ve özel karakter.":"Minimum 12 characters with upper/lowercase, number and symbol."}</p><button className="primary card-action">{tr?"Yerel Hesap Oluştur":"Create Local Account"}</button>{message&&<span className="local-message" aria-live="polite">{message}</span>}</form><div className="local-user-list">{users.map(user=><div key={user.id}><span className="local-user-identity"><b>{user.name}</b><small>{user.email}</small></span><label><span className="sr-only">{tr?"Rol":"Role"}</span><select value={user.role} onChange={event=>change(user.id,"role",event.target.value)}><option>Viewer</option><option>Editor</option><option>Admin</option></select></label><label><span className="sr-only">{tr?"Durum":"Status"}</span><select value={user.status} onChange={event=>change(user.id,"status",event.target.value)}><option value="Active">{tr?"Aktif":"Active"}</option><option value="Disabled">{tr?"Devre dışı":"Disabled"}</option></select></label><span className="local-user-security">{Number(user.failed_attempts||0)>0?`${user.failed_attempts} ${tr?"hatalı giriş":"failed attempts"}`:(tr?"Giriş sorunu yok":"No sign-in issue")}</span><button type="button" disabled={busyId===user.id} onClick={()=>void save(user)}>{tr?"Kaydet":"Save"}</button></div>)}</div></section>
}
function Card({title,desc,status,children,wide=false}:{title:string;desc:string;status:string;children:any;wide?:boolean}){return <section className={`settings-card${wide?" settings-card-wide":""}`}><div className="settings-card-head"><div><h3>{title}</h3><p>{desc}</p></div><span>{status}</span></div><div className="settings-fields">{children}</div></section>}
function Input({label,value,onChange,type="text",placeholder=""}:{label:string;value:string;onChange:(v:string)=>void;type?:string;placeholder?:string}){return <label className="setting-field"><span>{label}</span><input type={type} autoComplete={type==="password"?"new-password":undefined} value={value} placeholder={placeholder} onChange={e=>onChange(e.target.value)}/></label>}
function NativeInput({name,label,type="text"}:{name:string;label:string;type?:string}){return <label className="setting-field"><span>{label}</span><input name={name} type={type} autoComplete={type==="password"?"new-password":undefined} required minLength={type==="password"?12:undefined}/></label>}
function Toggle({checked,onChange,label}:{checked:boolean;onChange:(v:boolean)=>void;label:string}){return <label className="setting-toggle wide"><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)}/><i/><span>{label}</span></label>}
