"use client";

import {FormEvent,useEffect,useMemo,useState} from "react";
import {withBasePath} from "./base-path";
import {TPRM_CONTROLS,type TprmControl} from "./third-party-risk/domain";
import "./third-party-risk.css";

type Lang="tr"|"en";
type Vendor={vendorId:string;name:string;service:string;legalEntity?:string;category?:string;criticality:string;dataClassification?:string;dataAccess?:string;hostingLocation?:string;businessOwner?:string;riskOwner?:string;reviewer?:string;contact?:string;contractEnd?:string;nextReview?:string;exitPlan?:string;status:string;openFindings?:number;openCritical?:number;assessmentCount?:number;attention?:string};
type Assessment={id:string;vendorId:string;cycleNumber:number;impact:number;likelihood:number;controlMaturity:number;questionnaire:Record<TprmControl,boolean>;coverage:number;inherentScore:number;residualScore:number;riskTier:string;criticalGaps:string[];treatmentPlan:string;status:string;createdBy:string;submittedBy?:string;decidedBy?:string;updatedAt:string};
type Finding={id:string;assessmentId:string;vendorId:string;title:string;severity:string;description:string;owner:string;dueDate:string;status:string;overdue:boolean};
type Summary={total:number;unmanaged:number;critical:number;reviewDue:number;openFindings:number;overdueFindings:number;highRisk:number;contractsDue:number};
const emptySummary:Summary={total:0,unmanaged:0,critical:0,reviewDue:0,openFindings:0,overdueFindings:0,highRisk:0,contractsDue:0};
const controlLabels:Record<TprmControl,[string,string]>={securityProgram:["Bilgi güvenliği programı","Security program"],accessControl:["Erişim ve ayrıcalık kontrolü","Access control"],encryption:["Aktarımda ve depoda şifreleme","Encryption at rest/in transit"],logging:["Loglama ve izleme","Logging and monitoring"],vulnerabilityManagement:["Zafiyet ve yama yönetimi","Vulnerability management"],incidentNotification:["Olay bildirim SLA'sı","Incident notification SLA"],bcdr:["BC/DR ve kurtarma testi","BC/DR and recovery testing"],subprocessorGovernance:["Alt yüklenici yönetişimi","Subprocessor governance"],dataDeletion:["Veri iade/silme taahhüdü","Data return/deletion"],auditRights:["Denetim hakkı","Audit rights"],dataPortability:["Taşınabilirlik ve exit desteği","Portability and exit support"],dpa:["DPA / gizlilik eki","DPA / privacy exhibit"]};
const blankControls=Object.fromEntries(TPRM_CONTROLS.map(x=>[x,false])) as Record<TprmControl,boolean>;
const emptyVendor={vendorId:"",name:"",service:"",legalEntity:"",category:"SaaS",criticality:"high",dataClassification:"confidential",dataAccess:"",hostingLocation:"",businessOwner:"",riskOwner:"",reviewer:"",contact:"",contractEnd:"",nextReview:"",exitPlan:"",impact:4,likelihood:3,controlMaturity:2,treatmentPlan:"",...blankControls};

export default function ThirdPartyRisk({lang,currentUser}:{lang:Lang;currentUser:{role:string;email:string}}){
 const tr=lang==="tr",canWrite=currentUser.role!=="Viewer",[tab,setTab]=useState<"overview"|"vendors"|"assessments"|"findings">("overview"),[vendors,setVendors]=useState<Vendor[]>([]),[profiles,setProfiles]=useState<Vendor[]>([]),[assessments,setAssessments]=useState<Assessment[]>([]),[findings,setFindings]=useState<Finding[]>([]),[summary,setSummary]=useState<Summary>(emptySummary),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[vendorForm,setVendorForm]=useState<Record<string,unknown>|null>(null),[renewForm,setRenewForm]=useState<(Record<string,unknown>&{vendorId:string})|null>(null),[findingForm,setFindingForm]=useState<{assessmentId:string;title:string;severity:string;description:string;owner:string;dueDate:string}|null>(null),[actionForm,setActionForm]=useState<{kind:"assessment"|"finding"|"offboard";id:string;operation:string;note:string;evidenceReference:string;evidenceSha256:string;confirmation:string}|null>(null),[selected,setSelected]=useState<Vendor|null>(null);
 const vendorName=(id:string)=>vendors.find(v=>v.vendorId===id)?.name||id,latest=useMemo(()=>{const result=new Map<string,Assessment>();for(const assessment of assessments)if(!result.has(assessment.vendorId))result.set(assessment.vendorId,assessment);return result},[assessments]);
 const format=(v?:string)=>v?new Intl.DateTimeFormat(tr?"tr-TR":"en-GB",{dateStyle:"medium"}).format(new Date(`${v.slice(0,10)}T12:00:00Z`)):"—";
 async function load(){const response=await fetch(withBasePath("/api/third-party-risk"),{cache:"no-store"});if(!response.ok)return;const body=await response.json();setVendors(body.vendors||[]);setProfiles(body.profiles||[]);setAssessments(body.assessments||[]);setFindings(body.findings||[]);setSummary(body.summary||emptySummary);if(selected)setSelected((body.vendors||[]).find((x:Vendor)=>x.vendorId===selected.vendorId)||null)}
 useEffect(()=>{let active=true;fetch(withBasePath("/api/third-party-risk"),{cache:"no-store"}).then(x=>x.ok?x.json():null).then(body=>{if(active&&body){setVendors(body.vendors||[]);setProfiles(body.profiles||[]);setAssessments(body.assessments||[]);setFindings(body.findings||[]);setSummary(body.summary||emptySummary)}}).catch(()=>{});return()=>{active=false}},[]);
 async function api(body:Record<string,unknown>){setBusy(true);setNotice("");try{const response=await fetch(withBasePath("/api/third-party-risk"),{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)}),result=await response.json().catch(()=>({}));setNotice(response.ok?(result.message||(tr?"İşlem tamamlandı.":"Completed.")):(result.error||(tr?"İşlem başarısız.":"Operation failed.")));if(response.ok)await load();return response.ok}catch{setNotice(tr?"Sunucuya ulaşılamadı.":"Server unavailable.");return false}finally{setBusy(false)}}
 function startVendor(v?:Vendor){setVendorForm({...emptyVendor,...(v?{vendorId:v.vendorId,name:v.name,service:v.service,criticality:["low","medium","high","critical"].includes(v.criticality)?v.criticality:"high"}:{})})}
 async function saveVendor(e:FormEvent){e.preventDefault();if(vendorForm&&await api({action:"save-vendor",...vendorForm}))setVendorForm(null)}
 function startRenew(v:Vendor){const old=latest.get(v.vendorId);setRenewForm({vendorId:v.vendorId,impact:old?.impact||4,likelihood:old?.likelihood||3,controlMaturity:old?.controlMaturity||2,treatmentPlan:old?.treatmentPlan||"",...(old?.questionnaire||blankControls)})}
 async function saveRenew(e:FormEvent){e.preventDefault();if(renewForm&&await api({action:"renew-assessment",...renewForm}))setRenewForm(null)}
 function assessmentAction(a:Assessment,operation:string){setActionForm({kind:"assessment",id:a.id,operation,note:"",evidenceReference:"",evidenceSha256:"",confirmation:""})}
 function findingAction(f:Finding,operation:string){setActionForm({kind:"finding",id:f.id,operation,note:"",evidenceReference:"",evidenceSha256:"",confirmation:""})}
 async function applyAction(){if(!actionForm)return;const body=actionForm.kind==="assessment"?{action:"assessment-action",assessmentId:actionForm.id,...actionForm}:actionForm.kind==="finding"?{action:"finding-action",findingId:actionForm.id,...actionForm}:{action:"offboard",vendorId:actionForm.id,...actionForm};if(await api(body))setActionForm(null)}
 const phrase=(operation:string)=>({submit:"İNCELEMEYE GÖNDER",approve:"TEDARİKÇİYİ ONAYLA",conditional:"KOŞULLU ONAYLA",reject:"TEDARİKÇİYİ REDDET",start:"BULGUYU BAŞLAT","submit-finding":"BULGUYU DOĞRULAMAYA GÖNDER","verify-finding":"BULGUYU KAPAT","reopen-finding":"BULGUYU YENİDEN AÇ",offboard:"TEDARİKÇİYİ KAPAT"}[operation]||"");
 const actionNeedsEvidence=actionForm&&["submit","approve","conditional","submit-finding","verify-finding","offboard"].includes(actionForm.operation);
 return <section className="tprm-page">
  <div className="tprm-hero"><div><small>THIRD-PARTY RISK MANAGEMENT 2.0</small><h2>{tr?"Tedarikçi Risk Merkezi":"Third-Party Risk Center"}</h2><p>{tr?"Onboarding, due diligence, sözleşme kontrolleri, risk kararı, CAPA, yeniden değerlendirme ve çıkışı tek kanıt zincirinde yönetin.":"Govern onboarding, due diligence, contracts, risk decisions, CAPA, reassessment and exit in one evidence chain."}</p></div><div>{currentUser.role==="Admin"&&<a href={withBasePath("/api/third-party-risk?format=csv")}>TPRM CSV</a>}{canWrite&&<button onClick={()=>startVendor()}>+ {tr?"Tedarikçi":"Third Party"}</button>}</div></div>
  {notice&&<div className="tprm-notice" onClick={()=>setNotice("")}>{notice}<b>×</b></div>}
  <div className="tprm-metrics"><Metric value={summary.total} label={tr?"Toplam üçüncü taraf":"Third parties"}/><Metric value={summary.unmanaged} label={tr?"TPRM dışı kayıt":"Unmanaged"}/><Metric value={summary.highRisk} label={tr?"Yüksek/kritik risk":"High/critical risk"}/><Metric value={summary.reviewDue} label={tr?"İnceleme zamanı":"Reviews due"}/><Metric value={summary.openFindings} label={tr?"Açık CAPA":"Open CAPA"}/><Metric value={summary.contractsDue} label={tr?"90 günde sözleşme":"Contracts in 90d"}/></div>
  <div className="tprm-tabs">{(["overview","vendors","assessments","findings"] as const).map(x=><button key={x} className={tab===x?"active":""} onClick={()=>setTab(x)}>{x==="overview"?(tr?"Risk Kuyruğu":"Risk Queue"):x==="vendors"?(tr?"Tedarikçi Envanteri":"Third Parties"):x==="assessments"?(tr?"Due Diligence":"Due Diligence"):(tr?"Bulgular ve CAPA":"Findings & CAPA")}</button>)}</div>
  {tab==="overview"&&<div className="tprm-grid"><section><header><div><small>{tr?"RİSK ÖNCELİĞİ":"RISK PRIORITY"}</small><h3>{tr?"Müdahale bekleyen tedarikçiler":"Third parties requiring action"}</h3></div><span>{summary.reviewDue+summary.highRisk}</span></header>{profiles.filter(v=>v.attention!==v.status||["critical","high"].includes(latest.get(v.vendorId)?.riskTier||"")).slice(0,12).map(v=><VendorCard key={v.vendorId} vendor={v} assessment={latest.get(v.vendorId)} tr={tr} format={format} open={()=>setSelected(v)}/>)}</section><section><header><div><small>{tr?"KAPSAM BOŞLUĞU":"COVERAGE GAP"}</small><h3>{tr?"TPRM profiline alınmamış kayıtlar":"Records outside TPRM"}</h3></div><span>{summary.unmanaged}</span></header>{vendors.filter(v=>v.status==="unmanaged").slice(0,10).map(v=><article className="tprm-unmanaged" key={v.vendorId}><div><b>{v.name}</b><small>{v.service}</small></div>{canWrite&&<button onClick={()=>startVendor(v)}>{tr?"Kapsama al":"Adopt"}</button>}</article>)}</section></div>}
  {tab==="vendors"&&<Table heads={[tr?"Tedarikçi / hizmet":"Third party / service",tr?"Kritiklik":"Criticality",tr?"Risk":"Risk",tr?"İnceleme":"Review",tr?"Sözleşme":"Contract",tr?"Durum":"Status",""]} rows={vendors.map(v=>[<span key="vendor"><b>{v.name}</b><small>{v.service} · {v.vendorId}</small></span>,<State key="criticality" value={v.criticality}/>,<State key="risk" value={latest.get(v.vendorId)?.riskTier||"unassessed"}/>,format(v.nextReview),format(v.contractEnd),<State key="status" value={v.attention||v.status}/>,<div key="actions"><button onClick={()=>setSelected(v)}>{tr?"Aç":"Open"}</button>{canWrite&&v.status==="unmanaged"&&<button onClick={()=>startVendor(v)}>{tr?"Kapsama al":"Adopt"}</button>}{canWrite&&!["unmanaged","offboarded","rejected"].includes(v.status)&&<button onClick={()=>startRenew(v)}>{tr?"Yenile":"Renew"}</button>}</div>])} empty={tr?"Tedarikçi kaydı yok.":"No third party."}/>} 
  {tab==="assessments"&&<Table heads={[tr?"Tedarikçi":"Third party",tr?"Döngü":"Cycle",tr?"Kontrol kapsamı":"Control coverage",tr?"Doğal / kalıntı":"Inherent / residual",tr?"Kritik boşluk":"Critical gaps",tr?"Durum":"Status",""]} rows={assessments.map(a=>[vendorName(a.vendorId),`#${a.cycleNumber}`,`${a.coverage}%`,`${a.inherentScore} / ${a.residualScore} · ${a.riskTier}`,a.criticalGaps.length,<State key="status" value={a.status}/>,<AssessmentButtons key="actions" assessment={a} role={currentUser.role} act={operation=>assessmentAction(a,operation)} addFinding={()=>setFindingForm({assessmentId:a.id,title:"",severity:"high",description:"",owner:"",dueDate:""})}/>])} empty={tr?"Değerlendirme yok.":"No assessment."}/>} 
  {tab==="findings"&&<Table heads={[tr?"Bulgu":"Finding",tr?"Tedarikçi":"Third party",tr?"Önem":"Severity",tr?"Sahip / termin":"Owner / due",tr?"Durum":"Status",""]} rows={findings.map(f=>[<span key="finding"><b>{f.title}</b><small>{f.description}</small></span>,vendorName(f.vendorId),<State key="severity" value={f.severity}/>,<span key="owner"><b>{f.owner}</b><small>{format(f.dueDate)}</small></span>,<State key="status" value={f.overdue?"overdue":f.status}/>,<FindingButtons key="actions" finding={f} role={currentUser.role} act={operation=>findingAction(f,operation)}/>])} empty={tr?"Bulgu kaydı yok.":"No finding."}/>} 
  {selected&&<Modal title={selected.name} close={()=>setSelected(null)}><div className="tprm-detail"><div className="tprm-detail-meta"><State value={selected.criticality}/><State value={selected.attention||selected.status}/><span>{latest.get(selected.vendorId)?.riskTier||"unassessed"}</span></div><p>{selected.service}</p><dl><div><dt>{tr?"Risk sahibi":"Risk owner"}</dt><dd>{selected.riskOwner||"—"}</dd></div><div><dt>Reviewer</dt><dd>{selected.reviewer||"—"}</dd></div><div><dt>{tr?"Veri / lokasyon":"Data / location"}</dt><dd>{selected.dataClassification||"—"} · {selected.hostingLocation||"—"}</dd></div><div><dt>{tr?"Sözleşme":"Contract"}</dt><dd>{format(selected.contractEnd)}</dd></div></dl><h4>{tr?"Çıkış planı":"Exit plan"}</h4><p>{selected.exitPlan||"—"}</p><h4>{tr?"Açık bulgular":"Open findings"}</h4>{findings.filter(f=>f.vendorId===selected.vendorId&&f.status!=="closed").map(f=><article key={f.id}><b>{f.title}</b><small>{f.severity} · {f.owner} · {format(f.dueDate)}</small></article>)}<footer>{canWrite&&!["unmanaged","offboarded","rejected"].includes(selected.status)&&<button onClick={()=>startRenew(selected)}>{tr?"Yeniden değerlendir":"Reassess"}</button>}{currentUser.role==="Admin"&&!["unmanaged","offboarded","rejected"].includes(selected.status)&&<button onClick={()=>setActionForm({kind:"offboard",id:selected.vendorId,operation:"offboard",note:"",evidenceReference:"",evidenceSha256:"",confirmation:""})}>{tr?"Kanıtlı çıkış":"Evidence-backed exit"}</button>}</footer></div></Modal>}
  {vendorForm&&<Modal title={tr?"Tedarikçi onboarding ve ilk değerlendirme":"Third-party onboarding and initial assessment"} close={()=>setVendorForm(null)}><form className="tprm-form" onSubmit={saveVendor}><VendorFields form={vendorForm} set={setVendorForm} tr={tr}/><AssessmentFields form={vendorForm} set={setVendorForm} tr={tr}/><FormFooter close={()=>setVendorForm(null)} busy={busy} tr={tr}/></form></Modal>}
  {renewForm&&<Modal title={`${vendorName(renewForm.vendorId)} · ${tr?"Yeniden değerlendirme":"Reassessment"}`} close={()=>setRenewForm(null)}><form className="tprm-form" onSubmit={saveRenew}><AssessmentFields form={renewForm} set={x=>setRenewForm({...renewForm,...x})} tr={tr}/><FormFooter close={()=>setRenewForm(null)} busy={busy} tr={tr}/></form></Modal>}
  {findingForm&&<Modal title={tr?"Tedarikçi bulgusu / CAPA":"Third-party finding / CAPA"} close={()=>setFindingForm(null)}><form className="tprm-form" onSubmit={async e=>{e.preventDefault();if(await api({action:"add-finding",...findingForm}))setFindingForm(null)}}><Input label={tr?"Bulgu başlığı":"Finding title"} value={findingForm.title} set={title=>setFindingForm({...findingForm,title})}/><label>{tr?"Önem":"Severity"}<select value={findingForm.severity} onChange={e=>setFindingForm({...findingForm,severity:e.target.value})}>{["low","medium","high","critical"].map(x=><option key={x}>{x}</option>)}</select></label><label className="wide">{tr?"Açıklama ve düzeltici aksiyon":"Description and corrective action"}<textarea required rows={3} value={findingForm.description} onChange={e=>setFindingForm({...findingForm,description:e.target.value})}/></label><Input label={tr?"Aksiyon sahibi e-posta":"Action owner email"} type="email" value={findingForm.owner} set={owner=>setFindingForm({...findingForm,owner})}/><Input label={tr?"Termin":"Due date"} type="date" value={findingForm.dueDate} set={dueDate=>setFindingForm({...findingForm,dueDate})}/><FormFooter close={()=>setFindingForm(null)} busy={busy} tr={tr}/></form></Modal>}
  {actionForm&&<Modal title={phrase(actionForm.operation)} close={()=>setActionForm(null)}><div className="tprm-form"><label className="wide">{tr?"Karar / işlem notu":"Decision / action note"}<textarea rows={4} value={actionForm.note} onChange={e=>setActionForm({...actionForm,note:e.target.value})}/></label>{actionNeedsEvidence&&<><Input label={tr?"Kanıt referansı":"Evidence reference"} value={actionForm.evidenceReference} set={evidenceReference=>setActionForm({...actionForm,evidenceReference})}/><Input label="SHA-256" value={actionForm.evidenceSha256} set={evidenceSha256=>setActionForm({...actionForm,evidenceSha256})}/></>}<Input wide label={`${tr?"Onay":"Confirmation"}: ${phrase(actionForm.operation)}`} value={actionForm.confirmation} set={confirmation=>setActionForm({...actionForm,confirmation})}/><footer><button onClick={()=>setActionForm(null)}>{tr?"Vazgeç":"Cancel"}</button><button disabled={busy} onClick={()=>void applyAction()}>{tr?"Uygula":"Apply"}</button></footer></div></Modal>}
 </section>
}

function VendorFields({form,set,tr}:{form:Record<string,unknown>;set:(v:Record<string,unknown>)=>void;tr:boolean}){const change=(key:string,value:unknown)=>set({...form,[key]:value});return <><div className="tprm-section-title"><b>{tr?"Kurumsal profil ve sözleşme":"Corporate profile and contract"}</b><span>{tr?"Hesap verebilir sahiplik ve yaşam döngüsü tarihleri":"Accountable ownership and lifecycle dates"}</span></div><Input label={tr?"Tedarikçi adı":"Third-party name"} value={String(form.name||"")} set={v=>change("name",v)}/><Input label={tr?"Hizmet":"Service"} value={String(form.service||"")} set={v=>change("service",v)}/><Input label={tr?"Tüzel kişilik":"Legal entity"} value={String(form.legalEntity||"")} set={v=>change("legalEntity",v)}/><Input label={tr?"Kategori":"Category"} value={String(form.category||"")} set={v=>change("category",v)}/><Select label={tr?"Kritiklik":"Criticality"} value={String(form.criticality)} values={["low","medium","high","critical"]} set={v=>change("criticality",v)}/><Select label={tr?"Veri sınıfı":"Data class"} value={String(form.dataClassification)} values={["public","internal","confidential","restricted"]} set={v=>change("dataClassification",v)}/><Input label={tr?"İş sahibi e-posta":"Business owner email"} type="email" value={String(form.businessOwner||"")} set={v=>change("businessOwner",v)}/><Input label={tr?"Risk sahibi e-posta":"Risk owner email"} type="email" value={String(form.riskOwner||"")} set={v=>change("riskOwner",v)}/><Input label="Reviewer email" type="email" value={String(form.reviewer||"")} set={v=>change("reviewer",v)}/><Input label={tr?"Tedarikçi iletişim":"Vendor contact"} type="email" value={String(form.contact||"")} set={v=>change("contact",v)}/><Input label={tr?"Sözleşme bitişi":"Contract end"} type="date" value={String(form.contractEnd||"")} set={v=>change("contractEnd",v)}/><Input label={tr?"Sonraki inceleme":"Next review"} type="date" value={String(form.nextReview||"")} set={v=>change("nextReview",v)}/><Input wide label={tr?"Veri erişimi / işleme kapsamı":"Data access / processing scope"} value={String(form.dataAccess||"")} set={v=>change("dataAccess",v)}/><Input wide label={tr?"Barındırma ve veri lokasyonu":"Hosting and data location"} value={String(form.hostingLocation||"")} set={v=>change("hostingLocation",v)}/><label className="wide">{tr?"Çıkış, veri iadesi ve hizmet geçiş planı":"Exit, data return and service transition plan"}<textarea required rows={3} value={String(form.exitPlan||"")} onChange={e=>change("exitPlan",e.target.value)}/></label></>}
function AssessmentFields({form,set,tr}:{form:Record<string,unknown>;set:(v:Record<string,unknown>)=>void;tr:boolean}){const change=(key:string,value:unknown)=>set({...form,[key]:value});return <><div className="tprm-section-title wide"><b>{tr?"Due diligence ve risk skoru":"Due diligence and risk score"}</b><span>{tr?"12 kontrol alanı, doğal risk ve kontrol olgunluğu":"12 control domains, inherent risk and control maturity"}</span></div><Select label={tr?"Etki (1-5)":"Impact (1-5)"} value={String(form.impact)} values={["1","2","3","4","5"]} set={v=>change("impact",Number(v))}/><Select label={tr?"Olasılık (1-5)":"Likelihood (1-5)"} value={String(form.likelihood)} values={["1","2","3","4","5"]} set={v=>change("likelihood",Number(v))}/><Select label={tr?"Kontrol olgunluğu (1-5)":"Control maturity (1-5)"} value={String(form.controlMaturity)} values={["1","2","3","4","5"]} set={v=>change("controlMaturity",Number(v))}/><label className="wide">{tr?"Risk iyileştirme / kabul planı":"Risk treatment / acceptance plan"}<textarea required rows={3} value={String(form.treatmentPlan||"")} onChange={e=>change("treatmentPlan",e.target.value)}/></label><div className="tprm-checks wide">{TPRM_CONTROLS.map(key=><label key={key}><input type="checkbox" checked={Boolean(form[key])} onChange={e=>change(key,e.target.checked)}/><span>{controlLabels[key][tr?0:1]}</span></label>)}</div></>}
function AssessmentButtons({assessment,role,act,addFinding}:{assessment:Assessment;role:string;act:(x:string)=>void;addFinding:()=>void}){if(role==="Viewer")return <span>—</span>;return <div className="tprm-row-actions">{assessment.status==="draft"&&<button onClick={()=>act("submit")}>Gönder</button>}{assessment.status==="submitted"&&role==="Admin"&&<><button onClick={()=>act("approve")}>Onayla</button><button onClick={()=>act("conditional")}>Koşullu</button><button onClick={()=>act("reject")}>Reddet</button></>} {!["rejected","superseded"].includes(assessment.status)&&<button onClick={addFinding}>+ CAPA</button>}</div>}
function FindingButtons({finding,role,act}:{finding:Finding;role:string;act:(x:string)=>void}){if(role==="Viewer")return <span>—</span>;if(finding.status==="open")return <button onClick={()=>act("start")}>Başlat</button>;if(finding.status==="in-progress")return <button onClick={()=>act("submit-finding")}>Gönder</button>;if(finding.status==="verification"&&role==="Admin")return <><button onClick={()=>act("verify-finding")}>Kapat</button><button onClick={()=>act("reopen-finding")}>İade</button></>;if(finding.status==="closed"&&role==="Admin")return <button onClick={()=>act("reopen-finding")}>Yeniden aç</button>;return <span>—</span>}
function VendorCard({vendor,assessment,tr,format,open}:{vendor:Vendor;assessment?:Assessment;tr:boolean;format:(v?:string)=>string;open:()=>void}){return <article className={`tprm-card ${vendor.attention}`}><header><div><small>{vendor.category} · {vendor.vendorId}</small><b>{vendor.name}</b></div><State value={vendor.attention||vendor.status}/></header><p>{vendor.service}</p><div><span>{tr?"Kalıntı risk":"Residual risk"}: <b>{assessment?.residualScore||"—"} · {assessment?.riskTier||"unassessed"}</b></span><span>{tr?"İnceleme":"Review"}: {format(vendor.nextReview)}</span><span>CAPA: {vendor.openFindings||0}</span></div><footer><button onClick={open}>{tr?"Detay":"Details"}</button></footer></article>}
function Metric({value,label}:{value:number;label:string}){return <article><b>{value}</b><span>{label}</span></article>}
function State({value}:{value:string}){return <span className={`tprm-state ${value}`}>{value}</span>}
function Table({heads,rows,empty}:{heads:string[];rows:React.ReactNode[][];empty:string}){return <div className="tprm-table"><div className="table-wrap"><table><thead><tr>{heads.map((x,i)=><th key={`${x}-${i}`}>{x}</th>)}</tr></thead><tbody>{rows.length?rows.map((row,i)=><tr key={i}>{row.map((cell,j)=><td key={j}>{cell}</td>)}</tr>):<tr><td colSpan={heads.length}>{empty}</td></tr>}</tbody></table></div></div>}
function Input({label,value,set,type="text",wide=false}:{label:string;value:string;set:(v:string)=>void;type?:string;wide?:boolean}){return <label className={wide?"wide":""}>{label}<input required type={type} value={value} onChange={e=>set(e.target.value)}/></label>}
function Select({label,value,values,set}:{label:string;value:string;values:string[];set:(v:string)=>void}){return <label>{label}<select value={value} onChange={e=>set(e.target.value)}>{values.map(x=><option key={x}>{x}</option>)}</select></label>}
function FormFooter({close,busy,tr}:{close:()=>void;busy:boolean;tr:boolean}){return <footer className="wide"><button type="button" onClick={close}>{tr?"Vazgeç":"Cancel"}</button><button disabled={busy}>{tr?"Kaydet":"Save"}</button></footer>}
function Modal({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <div className="overlay" onMouseDown={close}><div className="modal tprm-modal" role="dialog" aria-modal="true" aria-label={title} onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><div><small>FORNOST TPRM 2.0</small><h2>{title}</h2></div><button aria-label="Close dialog" onClick={close}>×</button></div>{children}</div></div>}
