import { createAiFinding,writeAiFindingTransition } from "@/app/ai/finding-transitions";
import { aiRecordQueryId,readAiRecords } from "@/app/ai/record-reads";
import { NextRequest,NextResponse } from "next/server";
import { requireRole } from "../../auth/security";
import { AI_FINDING_DOMAINS,AI_FINDING_SEVERITIES,findingAttention,validateAiFinding,validateFindingAction } from "@/app/ai/findings";
import { cleanAiText } from "@/app/ai/security";
import { aiRuntime,recordAiEvent } from "@/app/ai/storage";
const json=(data:unknown,status=200)=>NextResponse.json(data,{status,headers:{"cache-control":"no-store"}}),cell=(value:unknown)=>{const raw=String(value??""),safe=/^[=+\-@]/.test(raw)?`'${raw}`:raw;return `"${safe.replace(/"/g,'""')}"`;},map=(row:Record<string,unknown>)=>({id:row.id,modelId:row.model_id,domain:row.domain,sourceRef:row.source_ref,title:row.title,description:row.description,rootCause:row.root_cause,correctiveAction:row.corrective_action,preventiveAction:row.preventive_action,owner:row.owner,severity:row.severity,dueDate:row.due_date,status:row.status,state:findingAttention(String(row.status),String(row.severity),String(row.due_date)),actionNote:row.action_note,evidenceReference:row.evidence_reference,evidenceSha256:row.evidence_sha256,verificationEvidenceReference:row.verification_evidence_reference,verificationEvidenceSha256:row.verification_evidence_sha256,createdBy:row.created_by,submittedBy:row.submitted_by,verifiedBy:row.verified_by,updatedAt:row.updated_at});
export async function GET(req:NextRequest){const access=await requireRole(req,["Admin","Editor","Viewer"]);if(access.response)return access.response;let recordId:string|null,modelId:string|null;try{recordId=aiRecordQueryId(req.nextUrl.searchParams);modelId=aiRecordQueryId(req.nextUrl.searchParams,'modelId');}catch{return json({error:"Geçerli bir kayıt kimliği gereklidir."},400);}const{DB}=await aiRuntime(),[models,result]=await Promise.all([DB.prepare("SELECT id,system_name,model_name,status FROM ai_model_inventory WHERE status!='retired' ORDER BY system_name LIMIT 500").all<Record<string,unknown>>(),readAiRecords(DB,"findings",recordId,modelId)]),findings=(result.results||[]).map(map),format=req.nextUrl.searchParams.get("format");if(format){if(access.actor.role!=="Admin")return json({error:"Bulgu kanıt çıktısı yalnız Admin tarafından alınabilir."},403);const rows=[["Bulgu","Model","Alan","Kaynak","Başlık","Önem","Sorumlu","SLA","Durum","Kanıt","SHA-256","Doğrulayan"],...findings.map(item=>[item.id,item.modelId,item.domain,item.sourceRef,item.title,item.severity,item.owner,item.dueDate,item.state,item.evidenceReference||"",item.evidenceSha256||"",item.verifiedBy||""])];await recordAiEvent(DB,{actor:access.actor.email,action:"ai-finding-export",contextRefs:findings.map(item=>String(item.id)).slice(0,80),status:"success",detail:`${findings.length} bounded records; formula-safe csv`});return new NextResponse(`\uFEFF${rows.map(row=>row.map(cell).join(",")).join("\n")}`,{headers:{"cache-control":"no-store","content-type":"text/csv; charset=utf-8","content-disposition":"attachment; filename=fornost-ai-findings.csv"}});}return json({domains:AI_FINDING_DOMAINS,severities:AI_FINDING_SEVERITIES,models:(models.results||[]).map(row=>({id:row.id,systemName:row.system_name,modelName:row.model_name,status:row.status})),findings,summary:{total:findings.length,open:findings.filter(item=>item.status==="open").length,inProgress:findings.filter(item=>item.status==="in-progress").length,verification:findings.filter(item=>item.status==="verification").length,overdue:findings.filter(item=>item.state==="overdue").length,highRisk:findings.filter(item=>["High","Critical"].includes(String(item.severity))&&! ["resolved","dismissed"].includes(String(item.status))).length,resolved:findings.filter(item=>item.status==="resolved").length}});}
export async function POST(req:NextRequest){const access=await requireRole(req,["Admin","Editor"]);if(access.response)return access.response;if(Number(req.headers.get("content-length")||0)>32_768)return json({error:"Bulgu isteği çok büyük."},413);const body=await req.json().catch(()=>({}));let value;try{value=validateAiFinding(body);}catch(error){return json({error:error instanceof Error?error.message:"Bulgu doğrulanamadı."},400);}const{DB}=await aiRuntime();try{const result=await createAiFinding(DB,value,access.actor.email);return json(result.status===201?{id:result.id}:{error:result.error},result.status);}catch{return json({error:"Bulgu oluşturulamadı. Güncel listeyi kontrol edip tekrar deneyin."},503);}}

export async function PATCH(req:NextRequest){
 const access=await requireRole(req,["Admin","Editor"]);if(access.response)return access.response;
 const body=await req.json().catch(()=>null);if(!body||typeof body!=="object"||Array.isArray(body))return json({error:"Geçerli işlem gövdesi gereklidir."},400);
 const id=cleanAiText(body.id,100);let action;
 try{action=validateFindingAction(body);}catch(error){return json({error:error instanceof Error?error.message:"İşlem geçersiz."},400);}
 const{DB}=await aiRuntime(),row=await DB.prepare("SELECT * FROM ai_findings WHERE id=?").bind(id).first<Record<string,unknown>>();if(!row)return json({error:"AI bulgusu bulunamadı."},404);
 const expectedUpdatedAt=cleanAiText(body.expectedUpdatedAt,40);if(!expectedUpdatedAt||row.updated_at!==expectedUpdatedAt)return json({error:"Bulgu değişti. Güncel kaydı inceleyip işlemi yeniden açın."},409);
 const transitions:Record<string,Record<string,string>>={open:{start:"in-progress"},"in-progress":{submit:"verification"},verification:{resolve:"resolved",reopen:"in-progress"},resolved:{reopen:"in-progress"}},next=transitions[String(row.status)]?.[action.action];
 if(!next)return json({error:`${action.action} işlemi ${row.status} durumundan uygulanamaz.`},409);
 if(["resolve","reopen"].includes(action.action)&&access.actor.role!=="Admin")return json({error:"Doğrulama ve yeniden açma yalnız Admin tarafından yapılabilir."},403);
 if(action.action==="resolve"&&String(row.submitted_by||"").trim().toLowerCase()===access.actor.email.trim().toLowerCase())return json({error:"Aksiyonu doğrulamaya gönderen kişi aynı bulguyu kapatamaz."},409);
 if(action.action==="reopen"&&await DB.prepare("SELECT id FROM ai_findings WHERE model_id=? AND domain=? AND source_ref=? AND status!='resolved' AND id!=?").bind(row.model_id,row.domain,row.source_ref,id).first())return json({error:"Bu kaynak için başka bir çözülmemiş bulgu varken eski kayıt açılamaz."},409);
 try{const result=await writeAiFindingTransition(DB,row,action,next,access.actor.email,expectedUpdatedAt);return json(result.status===200?{ok:true,status:next,updatedAt:result.updatedAt}:{error:result.error},result.status);}
 catch{return json({error:"Bulgu işlemi tamamlanamadı. Güncel kaydı kontrol edip tekrar deneyin."},503);}
}
