import { NextRequest,NextResponse } from "next/server";
import { requireRole } from "../../auth/security";
import { AI_FINDING_DOMAINS,AI_FINDING_SEVERITIES,findingAttention,validateAiFinding,validateFindingAction } from "@/app/ai/findings";
import { cleanAiText } from "@/app/ai/security";
import { aiRuntime,recordAiEvent } from "@/app/ai/storage";
const json=(data:unknown,status=200)=>NextResponse.json(data,{status,headers:{"cache-control":"no-store"}}),cell=(value:unknown)=>{const raw=String(value??""),safe=/^[=+\-@]/.test(raw)?`'${raw}`:raw;return `"${safe.replace(/"/g,'""')}"`;},map=(row:Record<string,unknown>)=>({id:row.id,modelId:row.model_id,domain:row.domain,sourceRef:row.source_ref,title:row.title,description:row.description,rootCause:row.root_cause,correctiveAction:row.corrective_action,preventiveAction:row.preventive_action,owner:row.owner,severity:row.severity,dueDate:row.due_date,status:row.status,state:findingAttention(String(row.status),String(row.severity),String(row.due_date)),actionNote:row.action_note,evidenceReference:row.evidence_reference,evidenceSha256:row.evidence_sha256,verificationEvidenceReference:row.verification_evidence_reference,verificationEvidenceSha256:row.verification_evidence_sha256,createdBy:row.created_by,submittedBy:row.submitted_by,verifiedBy:row.verified_by,updatedAt:row.updated_at});
export async function GET(req:NextRequest){const access=await requireRole(req,["Admin","Editor","Viewer"]);if(access.response)return access.response;const{DB}=await aiRuntime(),[models,result]=await Promise.all([DB.prepare("SELECT id,system_name,model_name,status FROM ai_model_inventory WHERE status!='retired' ORDER BY system_name LIMIT 500").all<Record<string,unknown>>(),DB.prepare("SELECT * FROM ai_findings ORDER BY CASE severity WHEN 'Critical' THEN 0 WHEN 'High' THEN 1 WHEN 'Medium' THEN 2 ELSE 3 END,due_date,updated_at DESC LIMIT 500").all<Record<string,unknown>>()]),findings=(result.results||[]).map(map),format=req.nextUrl.searchParams.get("format");if(format){if(access.actor.role!=="Admin")return json({error:"Bulgu kanıt çıktısı yalnız Admin tarafından alınabilir."},403);const rows=[["Bulgu","Model","Alan","Kaynak","Başlık","Önem","Sorumlu","SLA","Durum","Kanıt","SHA-256","Doğrulayan"],...findings.map(item=>[item.id,item.modelId,item.domain,item.sourceRef,item.title,item.severity,item.owner,item.dueDate,item.state,item.evidenceReference||"",item.evidenceSha256||"",item.verifiedBy||""])];await recordAiEvent(DB,{actor:access.actor.email,action:"ai-finding-export",contextRefs:findings.map(item=>String(item.id)).slice(0,80),status:"success",detail:`${findings.length} bounded records; formula-safe csv`});return new NextResponse(`\uFEFF${rows.map(row=>row.map(cell).join(",")).join("\n")}`,{headers:{"cache-control":"no-store","content-type":"text/csv; charset=utf-8","content-disposition":"attachment; filename=fornost-ai-findings.csv"}});}return json({domains:AI_FINDING_DOMAINS,severities:AI_FINDING_SEVERITIES,models:(models.results||[]).map(row=>({id:row.id,systemName:row.system_name,modelName:row.model_name,status:row.status})),findings,summary:{total:findings.length,open:findings.filter(item=>item.status==="open").length,inProgress:findings.filter(item=>item.status==="in-progress").length,verification:findings.filter(item=>item.status==="verification").length,overdue:findings.filter(item=>item.state==="overdue").length,highRisk:findings.filter(item=>["High","Critical"].includes(String(item.severity))&&! ["resolved","dismissed"].includes(String(item.status))).length,resolved:findings.filter(item=>item.status==="resolved").length}});}
export async function POST(req:NextRequest){const access=await requireRole(req,["Admin","Editor"]);if(access.response)return access.response;if(Number(req.headers.get("content-length")||0)>32_768)return json({error:"Bulgu isteği çok büyük."},413);const body=await req.json().catch(()=>({}));let value;try{value=validateAiFinding(body);}catch(error){return json({error:error instanceof Error?error.message:"Bulgu doğrulanamadı."},400);}const{DB}=await aiRuntime();if(!(await DB.prepare("SELECT id FROM ai_model_inventory WHERE id=? AND status!='retired'").bind(value.modelId).first()))return json({error:"Etkin AI modeli bulunamadı."},409);const id=`AIF-${crypto.randomUUID()}`,now=new Date().toISOString();try{await DB.prepare("INSERT INTO ai_findings(id,model_id,domain,source_ref,title,description,root_cause,corrective_action,preventive_action,owner,severity,due_date,status,created_by,created_at,updated_by,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,'open',?,?,?,?)").bind(id,value.modelId,value.domain,value.sourceRef,value.title,value.description,value.rootCause,value.correctiveAction,value.preventiveAction,value.owner,value.severity,value.dueDate,access.actor.email,now,access.actor.email,now).run();}catch{return json({error:"Bu kaynak için çözülmemiş bulgu zaten var."},409);}await recordAiEvent(DB,{actor:access.actor.email,action:"ai-finding-create",contextRefs:[value.modelId,value.sourceRef,id],status:"success",detail:`${value.domain}; ${value.severity}; due ${value.dueDate}`});return json({id},201);}
export async function PATCH(req:NextRequest){
 const access=await requireRole(req,["Admin","Editor"]);if(access.response)return access.response;
 const body=await req.json().catch(()=>({})),id=cleanAiText(body.id,100);let action;
 try{action=validateFindingAction(body);}catch(error){return json({error:error instanceof Error?error.message:"İşlem geçersiz."},400);}
 const{DB}=await aiRuntime(),row=await DB.prepare("SELECT * FROM ai_findings WHERE id=?").bind(id).first<Record<string,unknown>>();if(!row)return json({error:"AI bulgusu bulunamadı."},404);
 const transitions:Record<string,Record<string,string>>={open:{start:"in-progress"},"in-progress":{submit:"verification"},verification:{resolve:"resolved",reopen:"in-progress"},resolved:{reopen:"in-progress"}},next=transitions[String(row.status)]?.[action.action];
 if(!next)return json({error:`${action.action} işlemi ${row.status} durumundan uygulanamaz.`},409);
 if(["resolve","reopen"].includes(action.action)&&access.actor.role!=="Admin")return json({error:"Doğrulama ve yeniden açma yalnız Admin tarafından yapılabilir."},403);
 if(action.action==="resolve"&&row.submitted_by===access.actor.email)return json({error:"Aksiyonu doğrulamaya gönderen kişi aynı bulguyu kapatamaz."},409);
 if(action.action==="reopen"&&await DB.prepare("SELECT id FROM ai_findings WHERE model_id=? AND domain=? AND source_ref=? AND status!='resolved' AND id!=?").bind(row.model_id,row.domain,row.source_ref,id).first())return json({error:"Bu kaynak için başka bir çözülmemiş bulgu varken eski kayıt açılamaz."},409);
 const now=new Date().toISOString(),submittedBy=action.action==="submit"?access.actor.email:row.submitted_by,submittedAt=action.action==="submit"?now:row.submitted_at,verifiedBy=action.action==="resolve"?access.actor.email:action.action==="reopen"?null:row.verified_by,verifiedAt=action.action==="resolve"?now:action.action==="reopen"?null:row.verified_at,reopenedBy=action.action==="reopen"?access.actor.email:row.reopened_by,reopenedAt=action.action==="reopen"?now:row.reopened_at;
 await DB.prepare("UPDATE ai_findings SET status=?,action_note=?,evidence_reference=?,evidence_sha256=?,verification_evidence_reference=?,verification_evidence_sha256=?,updated_by=?,updated_at=?,submitted_by=?,submitted_at=?,verified_by=?,verified_at=?,reopened_by=?,reopened_at=? WHERE id=?").bind(next,action.note,action.action==="submit"?action.evidenceReference:row.evidence_reference,action.action==="submit"?action.evidenceSha256:row.evidence_sha256,action.action==="resolve"?action.evidenceReference:row.verification_evidence_reference,action.action==="resolve"?action.evidenceSha256:row.verification_evidence_sha256,access.actor.email,now,submittedBy,submittedAt,verifiedBy,verifiedAt,reopenedBy,reopenedAt,id).run();
 await recordAiEvent(DB,{actor:access.actor.email,action:`ai-finding-${action.action}`,promptHash:(["submit","resolve"].includes(action.action)?action.evidenceSha256:String(row.evidence_sha256||""))||undefined,contextRefs:[String(row.model_id),String(row.source_ref),id],status:"success",detail:`${row.severity}; ${row.status}->${next}; separation-of-duties`});return json({ok:true,status:next});
}
