import { NextRequest,NextResponse } from "next/server";
import { requireRole } from "../../auth/security";
import { validateUseCase } from "@/app/ai/governance";
import { aiRuntime,recordAiEvent } from "@/app/ai/storage";
import { cleanAiText,redactSensitiveText } from "@/app/ai/security";

const json=(data:unknown,status=200)=>NextResponse.json(data,{status,headers:{"cache-control":"no-store"}});
function controls(value:unknown){try{const parsed=JSON.parse(String(value||"[]"));return Array.isArray(parsed)?parsed:[];}catch{return [];}}
const mapped=(row:Record<string,unknown>)=>({id:row.id,name:row.name,purpose:row.purpose,owner:row.owner,dataClassification:row.data_classification,impactLevel:row.impact_level,decisionRole:row.decision_role,controls:controls(row.controls_json),status:row.status,reviewDate:row.review_date,createdBy:row.created_by,createdAt:row.created_at,updatedAt:row.updated_at,approvedBy:row.approved_by,approvedAt:row.approved_at,decisionNote:row.decision_note});

export async function GET(req:NextRequest){const access=await requireRole(req,["Admin"]);if(access.response)return access.response;const {DB}=await aiRuntime(),[rows,health]=await Promise.all([DB.prepare("SELECT * FROM ai_use_cases ORDER BY CASE status WHEN 'draft' THEN 0 WHEN 'approved' THEN 1 ELSE 2 END,review_date,name LIMIT 250").all<Record<string,unknown>>(),DB.prepare("SELECT profile,provider,model,operation,status,latency_ms,detail,created_at FROM ai_provider_health ORDER BY created_at DESC LIMIT 50").all<Record<string,unknown>>()]);return json({useCases:(rows.results||[]).map(mapped),health:health.results||[]});}
export async function POST(req:NextRequest){
  const access=await requireRole(req,["Admin"]);if(access.response)return access.response;if(Number(req.headers.get("content-length")||0)>16_384)return json({error:"AI kullanım senaryosu isteği çok büyük."},413);
  const body=await req.json().catch(()=>({}));let value;try{value=validateUseCase(body);}catch(error){return json({error:error instanceof Error?error.message:"Kayıt doğrulanamadı."},400);}
  const {DB}=await aiRuntime(),id=`AIUC-${crypto.randomUUID()}`,now=new Date().toISOString();await DB.prepare("INSERT INTO ai_use_cases(id,name,purpose,owner,data_classification,impact_level,decision_role,controls_json,status,review_date,created_by,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(id,value.name,value.purpose,value.owner,value.dataClassification,value.impactLevel,value.decisionRole,JSON.stringify(value.controls),"draft",value.reviewDate,access.actor.email,now,now).run();await recordAiEvent(DB,{actor:access.actor.email,action:"governance-create",status:"success",detail:`AI use case ${id} created`});const row=await DB.prepare("SELECT * FROM ai_use_cases WHERE id=?").bind(id).first<Record<string,unknown>>();return json({useCase:mapped(row||{})},201);
}
export async function PUT(req:NextRequest){
  const access=await requireRole(req,["Admin"]);if(access.response)return access.response;const body=await req.json().catch(()=>({})),id=cleanAiText(body.id,100);let value;try{value=validateUseCase(body);}catch(error){return json({error:error instanceof Error?error.message:"Kayıt doğrulanamadı."},400);}
  const {DB}=await aiRuntime(),now=new Date().toISOString(),result=await DB.prepare("UPDATE ai_use_cases SET name=?,purpose=?,owner=?,data_classification=?,impact_level=?,decision_role=?,controls_json=?,review_date=?,updated_at=? WHERE id=? AND status='draft'").bind(value.name,value.purpose,value.owner,value.dataClassification,value.impactLevel,value.decisionRole,JSON.stringify(value.controls),value.reviewDate,now,id).run();if(Number(result.meta?.changes||0)!==1)return json({error:"Yalnız taslak kullanım senaryoları düzenlenebilir."},409);await recordAiEvent(DB,{actor:access.actor.email,action:"governance-edit",status:"success",detail:`AI use case ${id} edited`});return json({ok:true});
}
export async function PATCH(req:NextRequest){
  const access=await requireRole(req,["Admin"]);if(access.response)return access.response;const body=await req.json().catch(()=>({})),id=cleanAiText(body.id,100),status=cleanAiText(body.status,20),note=redactSensitiveText(body.note,800),confirmation=cleanAiText(body.confirmation,20);if(!id||!["approved","suspended"].includes(status)||note.length<5||confirmation!==(status==="approved"?"ONAYLA":"ASKIYA AL"))return json({error:"Karar notu ve doğru onay metni gereklidir."},400);
  const {DB}=await aiRuntime(),now=new Date().toISOString(),result=await DB.prepare("UPDATE ai_use_cases SET status=?,approved_by=?,approved_at=?,decision_note=?,updated_at=? WHERE id=? AND status<>?").bind(status,access.actor.email,now,note,now,id,status).run();if(Number(result.meta?.changes||0)!==1)return json({error:"Kullanım senaryosu bulunamadı veya zaten bu durumda."},409);await recordAiEvent(DB,{actor:access.actor.email,action:`governance-${status}`,status:"success",detail:`AI use case ${id} ${status}`});return json({ok:true});
}
export async function DELETE(req:NextRequest){const access=await requireRole(req,["Admin"]);if(access.response)return access.response;const body=await req.json().catch(()=>({})),id=cleanAiText(body.id,100);if(body.confirmation!=="SİL")return json({error:"SİL onayı gereklidir."},400);const {DB}=await aiRuntime(),result=await DB.prepare("DELETE FROM ai_use_cases WHERE id=? AND status='draft'").bind(id).run();if(Number(result.meta?.changes||0)!==1)return json({error:"Yalnız taslak kullanım senaryoları silinebilir."},409);await recordAiEvent(DB,{actor:access.actor.email,action:"governance-delete",status:"success",detail:`AI use case ${id} deleted`});return json({ok:true});}
