import fs from "node:fs/promises";
import path from "node:path";
import { chromium } from "@playwright/test";

const baseUrl=(process.env.FORNOST_PROD_URL||"https://app.fornostsecurity.com").replace(/\/$/,"");
const baseOrigin=new URL(baseUrl).origin;
const accessId=process.env.CF_ACCESS_CLIENT_ID||"";
const accessSecret=process.env.CF_ACCESS_CLIENT_SECRET||"";
const email=process.env.FORNOST_SMOKE_EMAIL||"";
const password=process.env.FORNOST_SMOKE_PASSWORD||"";
const accessHeaders={};if(accessId&&accessSecret){accessHeaders["CF-Access-Client-Id"]=accessId;accessHeaders["CF-Access-Client-Secret"]=accessSecret}
const outDir=path.resolve("qa-artifacts-release-gate");await fs.rm(outDir,{recursive:true,force:true});await fs.mkdir(outDir,{recursive:true});
const tr=["Gösterge Paneli","Benim İşlerim","Risk Değerlendirmesi","Risk İştahı ve KRI","İş Etki Analizi (BIA)","İş Sürekliliği ve Dayanıklılık","Varlık Envanteri","Uyum Yönetimi","Politika Merkezi","Tedarikçi Yönetimi","Kontrol Kütüphanesi","Kanıt Kütüphanesi","Kanıt Otomasyonu","Regülasyon Merkezi","Güvenlik Olayları ve Kriz","Bulgular ve CAPA","Denetim Yönetimi","Bağlantılı GRC Haritası","Raporlama","AI Yönetişimi","Ask Fornost","Sistem Ayarları","AI Ayarları","Ana Veri Yönetimi","İş Akışı Entegrasyonları","E-posta ve Bildirimler","Kimlik ve Erişim"];
const en=["Dashboard","My Work","Risk Assessment","Risk Appetite & KRI","Business Impact Analysis (BIA)","Business Continuity & Resilience","Asset Inventory","Compliance Management","Policy Center","Vendor Management","Control Library","Evidence Library","Evidence Automation","Regulatory Change Center","Security Incidents & Crisis","Findings & CAPA","Audit Management","Connected GRC Map","Reporting","AI Governance","Ask Fornost","System Settings","AI Settings","Master Data","Workflow Integrations","Email & Notifications","Identity & Access"];
const required={"Risk Assessment":["title","category","businessUnit","owner","asset","inherentLikelihood","inherentImpact","treatment","status","nextReview"],BIA:["process","processCategory","businessUnit","owner","criticality","asset","rto","rpo","status"],"Varlık Envanteri":["title","assetType","businessUnit","owner","criticality","status"],Uyum:["framework","controlRef","controlTitle","owner","status"],Tedarikçiler:["title","service","owner","criticality","riskLevel","status"],Kontroller:["controlRef","controlTitle","owner","frequency","implementation","status"],Kanıtlar:["evidenceTitle","controlRef","owner","period","status"],"Denetim Yönetimi":["auditName","auditType","auditOwner","startDate","endDate","requirementRef","requirementTitle","owner","businessUnit","dueDate","status","progress"]};
const report={target:baseUrl,startedAt:new Date().toISOString(),findings:[],modules:{tr:[],en:[]},forms:[],tables:[],records:{},sidebar:{},language:{},runtime:{}};
const finding=(severity,area,title,detail="")=>report.findings.push({severity,area,title,detail});
const isCloudflareInsights=value=>/static\.cloudflareinsights\.com|beacon\.min\.js/i.test(String(value||""));
async function login(context){const r=await context.request.post(`${baseUrl}/api/auth`,{headers:{...accessHeaders,origin:baseUrl,"content-type":"application/json"},data:{action:"login",email,password}});if(r.status()!==200)throw new Error(`login ${r.status()} ${String(await r.text()).slice(0,300)}`)}
async function auditSurface(page,lang,module,scopeSelector="body",kind="page"){
 const surface=await page.evaluate(({lang,module,scopeSelector,kind})=>{
  const scope=document.querySelector(scopeSelector)||document.body;
  const vis=e=>{const s=getComputedStyle(e),r=e.getBoundingClientRect();return s.display!=="none"&&s.visibility!=="hidden"&&Number(s.opacity)!==0&&r.width>0&&r.height>0};
  const accessibleName=el=>{const id=el.id,label=id?document.querySelector(`label[for="${CSS.escape(id)}"]`):null;return String(el.getAttribute("aria-label")||el.getAttribute("aria-labelledby")||(el.closest("label")?.textContent)||(label?.textContent)||"").replace(/\s+/g," ").trim()};
  const forms=[...scope.querySelectorAll("form")].filter(vis).map((form,i)=>{const controls=[...form.querySelectorAll("input,select,textarea")].filter(vis).filter(el=>el.getAttribute("type")!=="hidden");return{index:i,kind,controls:controls.length,unlabeled:controls.filter(el=>!accessibleName(el)).map(el=>({tag:el.tagName,type:el.getAttribute("type"),name:el.getAttribute("name"),placeholder:el.getAttribute("placeholder")}))}});
  const tables=[...scope.querySelectorAll("table")].filter(vis).map((table,i)=>{const headerCells=[...table.querySelectorAll("thead tr:last-child th")],headers=headerCells.reduce((n,x)=>n+(x.colSpan||1),0),blankHeaders=headerCells.filter(x=>!(x.textContent||"").trim()&&!x.getAttribute("aria-label")&&!x.getAttribute("title")).length,rows=[...table.querySelectorAll("tbody tr")].filter(vis),badRows=rows.filter(r=>{const cells=[...r.querySelectorAll(":scope > td")].reduce((n,x)=>n+(x.colSpan||1),0);return headers&&cells&&cells!==headers}).length;return{index:i,kind,headers,blankHeaders,rows:rows.length,badRows,overflow:table.scrollWidth>table.clientWidth};});
  const textNodes=[...scope.querySelectorAll("button,label,th,h1,h2,h3,h4,legend")].filter(vis).map(x=>(x.textContent||x.getAttribute("aria-label")||"").replace(/\s+/g," ").trim()).filter(Boolean);
  const turkishTokens=/\b(Kaydet|İptal|Sil|Düzenle|Ekle|Yükle|İndir|Kapat|Seç|Temizle|Yeni|Güncelle|Durum|Sahip|Kanıt|Tedarikçi|Varlık|Kayıt)\b/i;
  const englishTokens=/\b(Save|Cancel|Delete|Edit|Add|Upload|Download|Close|Select|Clear|New|Update|Status|Owner|Evidence|Vendor|Asset|Record)\b/i;
  const leaks=textNodes.filter(t=>lang==="en"?turkishTokens.test(t):englishTokens.test(t)).filter(t=>!/\b(AI|GRC|CAPA|KRI|SOC|ISO|PCI|DORA)\b/i.test(t)).slice(0,30);
  return{lang,module,kind,forms,tables,leaks,htmlLang:document.documentElement.lang,title:document.title,horizontalOverflow:document.documentElement.scrollWidth>window.innerWidth+4};
 },{lang,module,scopeSelector,kind});
 for(const f of surface.forms)if(f.unlabeled.length)finding("high",`${lang}:${module}`,`Unlabeled visible ${kind} form controls`,JSON.stringify(f.unlabeled.slice(0,10)));
 for(const t of surface.tables){if(t.blankHeaders)finding("low",`${lang}:${module}`,`Unlabeled table header cells`,`${t.blankHeaders}/${t.headers}`);if(t.badRows)finding("high",`${lang}:${module}`,"Table row/header column-span mismatch",`${t.badRows} row(s)`)}
 if(kind==="page"&&surface.horizontalOverflow)finding("high",`${lang}:${module}`,"Unexpected page horizontal overflow");
 if(surface.leaks.length)finding("medium",`${lang}:${module}`,"High-confidence mixed-language UI strings",surface.leaks.join(" | "));
 report.forms.push(...surface.forms.map(x=>({...x,lang,module})));report.tables.push(...surface.tables.map(x=>({...x,lang,module})));return surface;
}
async function auditSafeDialog(page,lang,module){
 const candidates=page.locator("main button").filter({hasText:lang==="tr"?/^(Yeni|Ekle|Oluştur)(\b|\s)/i:/^(New|Add|Create)(\b|\s)/i});
 const count=await candidates.count();
 for(let i=0;i<Math.min(count,6);i++){
  const button=candidates.nth(i);if(!(await button.isVisible().catch(()=>false)))continue;const text=((await button.textContent().catch(()=>""))||"").trim();if(/Import|Export|İçe Aktar|Dışa Aktar|Demo|Sample|Chat/i.test(text))continue;
  try{await button.click({timeout:2500});await page.waitForTimeout(250);const dialog=page.locator('[role="dialog"],.modal,.dialog,.drawer').filter({visible:true}).last();if(await dialog.count()&&await dialog.isVisible().catch(()=>false)){const selector=await dialog.evaluate(el=>{if(!el.id)el.id=`qa-dialog-${crypto.randomUUID()}`;return `#${CSS.escape(el.id)}`});await auditSurface(page,lang,module,selector,"dialog");await page.keyboard.press("Escape");await page.waitForTimeout(150);return true}await page.keyboard.press("Escape")}catch{await page.keyboard.press("Escape").catch(()=>{})}
 }return false;
}
async function auditNav(page,labels,lang){for(const label of labels){const b=page.locator(`nav button[aria-label=${JSON.stringify(label)}]`).first();if(!(await b.count())){finding("high",`${lang}:navigation`,"Navigation item missing",label);report.modules[lang].push({label,status:"missing"});continue}try{await b.evaluate(el=>el.click());await page.waitForTimeout(300);const s=await auditSurface(page,lang,label);const dialogAudited=await auditSafeDialog(page,lang,label);report.modules[lang].push({label,status:"ok",forms:s.forms.length,tables:s.tables.length,dialogAudited,leaks:s.leaks.length})}catch(e){finding("high",`${lang}:${label}`,"Module render/navigation failed",e.message);report.modules[lang].push({label,status:"error",error:e.message})}}}
async function switchEnglish(page){const button=page.locator(".language-switch button").filter({hasText:/^EN$/}).first();if(!(await button.count()))return false;try{await button.click();await page.waitForFunction(()=>document.documentElement.lang==="en",undefined,{timeout:5000});await page.locator('nav button[aria-label="Dashboard"]').first().waitFor({state:"attached",timeout:5000});return true}catch{return false}}
async function auditRecords(context){const r=await context.request.get(`${baseUrl}/api/grc`,{headers:{...accessHeaders,origin:baseUrl}});if(r.status()!==200){finding("critical","records","Authenticated /api/grc failed",`HTTP ${r.status()}`);return}const body=await r.json(),rows=Array.isArray(body.rows)?body.rows:[];const ids=new Set(),codes=new Set();let duplicates=0,badJson=0,missing=0,badDates=0;const byModule={};for(const row of rows){byModule[row.module]=(byModule[row.module]||0)+1;if(ids.has(row.id))duplicates++;ids.add(row.id);if(row.record_code){if(codes.has(row.record_code))duplicates++;codes.add(row.record_code)}let data={};try{data=JSON.parse(String(row.data_json||"{}"))}catch{badJson++;continue}for(const key of required[row.module]||[])if(data[key]===undefined||data[key]===null||data[key]==="")missing++;for(const k of ["nextReview","lastReview","startDate","endDate","dueDate","contractEnd","eolDate"]){if(data[k]&&!/^\d{4}-\d{2}-\d{2}$/.test(String(data[k])))badDates++;}}
 report.records={total:rows.length,byModule,duplicates,badJson,missingRequiredValues:missing,badDateValues:badDates};if(duplicates)finding("critical","records","Duplicate record id/code detected",String(duplicates));if(badJson)finding("critical","records","Malformed data_json detected",String(badJson));if(missing)finding("high","records","Required record fields missing",String(missing));if(badDates)finding("medium","records","Invalid date format in records",String(badDates));}
async function auditSidebarTooltip(page){
 const toggles=page.locator('button[aria-label],button[title]');let compact=null;for(let i=0;i<await toggles.count();i++){const b=toggles.nth(i),name=`${await b.getAttribute("aria-label")||""} ${await b.getAttribute("title")||""}`;if(/daralt|compact|collapse|küçült/i.test(name)){compact=b;break}}
 if(!compact){report.sidebar={controlFound:false};finding("low","navigation","Compact sidebar control not found by accessible name");return}
 await compact.click();await page.waitForTimeout(250);const item=page.locator('nav button[aria-label="Risk Değerlendirmesi"]').first();if(!(await item.count())){report.sidebar={controlFound:true,itemFound:false};return}
 await item.hover();await page.waitForTimeout(250);const result=await item.evaluate((el,label)=>{const nodes=[...document.querySelectorAll('[role="tooltip"],.nav-tooltip,.sidebar-tooltip,.menu-tooltip')].filter(x=>{const s=getComputedStyle(x),r=x.getBoundingClientRect();return s.display!=="none"&&s.visibility!=="hidden"&&r.width>0&&r.height>0});const dom=nodes.some(x=>(x.textContent||"").includes(label));const chain=[el,el.parentElement,el.parentElement?.parentElement].filter(Boolean);const pseudo=chain.some(x=>["::before","::after"].some(p=>String(getComputedStyle(x,p).content||"").replace(/^['"]|['"]$/g,"").includes(label)));return{dom,pseudo}},"Risk Değerlendirmesi");report.sidebar={controlFound:true,itemFound:true,tooltipVisible:result.dom||result.pseudo,mechanism:result.dom?"dom":result.pseudo?"pseudo":"none"};if(!report.sidebar.tooltipVisible)finding("medium","navigation","Collapsed sidebar tooltip not exposed on hover","Risk Değerlendirmesi");
}
if(!email||!password||!accessId||!accessSecret)throw new Error("Release gate QA requires production smoke and Cloudflare Access credentials.");
const browser=await chromium.launch({headless:true});try{const context=await browser.newContext({viewport:{width:1536,height:960}});await login(context);await auditRecords(context);const page=await context.newPage();await page.route("**/*",async route=>{const req=route.request(),url=new URL(req.url());if(url.origin===baseOrigin&&accessId&&accessSecret)await route.continue({headers:{...req.headers(),...accessHeaders}});else await route.continue()});const errors=[];page.on("console",m=>{if(m.type()!=="error")return;const text=m.text(),source=m.location()?.url||"";if(isCloudflareInsights(text)||isCloudflareInsights(source))return;errors.push({type:"console",text,url:page.url(),source})});page.on("pageerror",e=>errors.push({type:"page",text:e.message,url:page.url()}));page.on("requestfailed",req=>{try{const u=new URL(req.url());if(u.origin!==baseOrigin||isCloudflareInsights(u.href))return;const reason=req.failure()?.errorText||"";if(/ERR_ABORTED/i.test(reason))return;errors.push({type:"request",text:reason,url:u.href})}catch{}});await page.goto(baseUrl,{waitUntil:"domcontentloaded",timeout:60000});await page.waitForLoadState("networkidle",{timeout:30000}).catch(()=>{});await auditNav(page,tr,"tr");await auditSidebarTooltip(page);const switched=await switchEnglish(page);report.language={englishSwitch:switched,htmlLang:await page.locator("html").getAttribute("lang"),dashboardNavPresent:Boolean(await page.locator('nav button[aria-label="Dashboard"]').count())};if(!switched)finding("high","i18n","Exact English language switch failed",JSON.stringify(report.language));else await auditNav(page,en,"en");report.runtime.errors=errors;if(errors.length)finding("high","runtime","First-party console/page/request errors during deep QA",JSON.stringify(errors.slice(0,10)));await context.close()}finally{await browser.close()}
const rank={critical:0,high:1,medium:2,low:3,info:4};report.findings.sort((a,b)=>(rank[a.severity]??9)-(rank[b.severity]??9));report.finishedAt=new Date().toISOString();report.summary={findings:report.findings.length,critical:report.findings.filter(x=>x.severity==="critical").length,high:report.findings.filter(x=>x.severity==="high").length,medium:report.findings.filter(x=>x.severity==="medium").length,low:report.findings.filter(x=>x.severity==="low").length,trModulesPassed:report.modules.tr.filter(x=>x.status==="ok").length,enModulesPassed:report.modules.en.filter(x=>x.status==="ok").length,dialogFormsAudited:report.modules.tr.filter(x=>x.dialogAudited).length+report.modules.en.filter(x=>x.dialogAudited).length,formsAudited:report.forms.length,tablesAudited:report.tables.length,recordsAudited:report.records.total||0};await fs.writeFile(path.join(outDir,"release-gate-qa.json"),JSON.stringify(report,null,2));console.log("RELEASE_GATE_QA",JSON.stringify(report.summary));for(const f of report.findings.slice(0,100))console.log(`${f.severity.toUpperCase()} [${f.area}] ${f.title}${f.detail?` — ${f.detail}`:""}`);if(report.summary.critical>0)process.exitCode=2;
