import fs from "node:fs/promises";
import path from "node:path";
import { chromium } from "@playwright/test";

const baseUrl=(process.env.FORNOST_PROD_URL||"https://app.fornostsecurity.com").replace(/\/$/,"");
const accessId=process.env.CF_ACCESS_CLIENT_ID||"";
const accessSecret=process.env.CF_ACCESS_CLIENT_SECRET||"";
const email=process.env.FORNOST_SMOKE_EMAIL||"";
const password=process.env.FORNOST_SMOKE_PASSWORD||"";
const headers={};if(accessId&&accessSecret){headers["CF-Access-Client-Id"]=accessId;headers["CF-Access-Client-Secret"]=accessSecret}
const outDir=path.resolve("qa-artifacts-release-gate");await fs.rm(outDir,{recursive:true,force:true});await fs.mkdir(outDir,{recursive:true});
const tr=["Gösterge Paneli","Benim İşlerim","Risk Değerlendirmesi","Risk İştahı ve KRI","İş Etki Analizi (BIA)","İş Sürekliliği ve Dayanıklılık","Varlık Envanteri","Uyum Yönetimi","Politika Merkezi","Tedarikçi Yönetimi","Kontrol Kütüphanesi","Kanıt Kütüphanesi","Kanıt Otomasyonu","Regülasyon Merkezi","Güvenlik Olayları ve Kriz","Bulgular ve CAPA","Denetim Yönetimi","Bağlantılı GRC Haritası","Raporlama","AI Yönetişimi","Ask Fornost","Sistem Ayarları","AI Ayarları","Ana Veri Yönetimi","İş Akışı Entegrasyonları","E-posta ve Bildirimler","Kimlik ve Erişim"];
const en=["Dashboard","My Work","Risk Assessment","Risk Appetite & KRI","Business Impact Analysis (BIA)","Business Continuity & Resilience","Asset Inventory","Compliance Management","Policy Center","Vendor Management","Control Library","Evidence Library","Evidence Automation","Regulatory Change Center","Security Incidents & Crisis","Findings & CAPA","Audit Management","Connected GRC Map","Reporting","AI Governance","Ask Fornost","System Settings","AI Settings","Master Data","Workflow Integrations","Email & Notifications","Identity & Access"];
const required={"Risk Assessment":["title","category","businessUnit","owner","asset","inherentLikelihood","inherentImpact","treatment","status","nextReview"],BIA:["process","processCategory","businessUnit","owner","criticality","asset","rto","rpo","status"],"Varlık Envanteri":["title","assetType","businessUnit","owner","criticality","status"],Uyum:["framework","controlRef","controlTitle","owner","status"],Tedarikçiler:["title","service","owner","criticality","riskLevel","status"],Kontroller:["controlRef","controlTitle","owner","frequency","implementation","status"],Kanıtlar:["evidenceTitle","controlRef","owner","period","status"],"Denetim Yönetimi":["auditName","auditType","auditOwner","startDate","endDate","requirementRef","requirementTitle","owner","businessUnit","dueDate","status","progress"]};
const report={target:baseUrl,startedAt:new Date().toISOString(),findings:[],modules:{tr:[],en:[]},forms:[],tables:[],records:{},sidebar:{},runtime:{}};
const finding=(severity,area,title,detail="")=>report.findings.push({severity,area,title,detail});
const visible=async(locator)=>{try{return await locator.isVisible()}catch{return false}};
async function login(context){const r=await context.request.post(`${baseUrl}/api/auth`,{headers:{...headers,origin:baseUrl,"content-type":"application/json"},data:{action:"login",email,password}});if(r.status()!==200)throw new Error(`login ${r.status()} ${String(await r.text()).slice(0,300)}`)}
async function auditSurface(page,lang,module){
 const surface=await page.evaluate(({lang,module})=>{
  const vis=e=>{const s=getComputedStyle(e),r=e.getBoundingClientRect();return s.display!=="none"&&s.visibility!=="hidden"&&Number(s.opacity)!==0&&r.width>0&&r.height>0};
  const forms=[...document.querySelectorAll("form")].filter(vis).map((form,i)=>{const controls=[...form.querySelectorAll("input,select,textarea")].filter(vis);return{index:i,controls:controls.length,unlabeled:controls.filter(el=>{const id=el.id;return!(el.closest("label")||(id&&document.querySelector(`label[for=\"${CSS.escape(id)}\"]`))||el.getAttribute("aria-label")||el.getAttribute("aria-labelledby"))}).map(el=>({tag:el.tagName,type:el.getAttribute("type"),name:el.getAttribute("name"),placeholder:el.getAttribute("placeholder")})),requiredWithoutMark:controls.filter(el=>el.required&&!el.getAttribute("aria-required")).length}});
  const tables=[...document.querySelectorAll("table")].filter(vis).map((table,i)=>{const heads=[...table.querySelectorAll("thead th")].map(x=>(x.textContent||"").trim()),rows=[...table.querySelectorAll("tbody tr")].filter(vis),badRows=rows.filter(r=>{const cells=r.querySelectorAll(":scope > td").length;return heads.length&&cells&&cells!==heads.length}).length;return{index:i,headers:heads.length,blankHeaders:heads.filter(x=>!x).length,rows:rows.length,badRows,overflow:table.scrollWidth>table.clientWidth};});
  const controls=[...document.querySelectorAll("button,label,th,h1,h2,h3,h4,legend,option")].filter(vis).map(x=>(x.textContent||x.getAttribute("aria-label")||"").replace(/\s+/g," ").trim()).filter(Boolean);
  const trLeak=/\b(Kaydet|İptal|Sil|Düzenle|Ekle|Ara|Filtre|Yükle|İndir|Göster|Kapat|Aç|Seç|Temizle|Yeni|Güncelle|Durum|Sahip|Kanıt|Denetim|Tedarikçi|Varlık|Kayıt)\b/i;
  const enLeak=/\b(Save|Cancel|Delete|Edit|Add|Search|Filter|Upload|Download|Show|Close|Open|Select|Clear|New|Update|Status|Owner|Evidence|Audit|Vendor|Asset|Record)\b/i;
  return{lang,module,forms,tables,leaks:controls.filter(t=>lang==="en"?trLeak.test(t):enLeak.test(t)).slice(0,40),htmlLang:document.documentElement.lang,title:document.title,horizontalOverflow:document.documentElement.scrollWidth>window.innerWidth+4};
 },{lang,module});
 for(const f of surface.forms){if(f.unlabeled.length)finding("high",`${lang}:${module}`,"Unlabeled visible form controls",JSON.stringify(f.unlabeled.slice(0,10)));}
 for(const t of surface.tables){if(t.blankHeaders)finding("medium",`${lang}:${module}`,"Blank table headers",`${t.blankHeaders}/${t.headers}`);if(t.badRows)finding("high",`${lang}:${module}`,"Table row/header column mismatch",`${t.badRows} row(s)`);}
 if(surface.horizontalOverflow)finding("high",`${lang}:${module}`,"Unexpected page horizontal overflow");
 if(surface.leaks.length)finding("medium",`${lang}:${module}`,"Possible mixed-language UI strings",surface.leaks.join(" | "));
 report.forms.push(...surface.forms.map(x=>({...x,lang,module})));report.tables.push(...surface.tables.map(x=>({...x,lang,module})));return surface;
}
async function switchLanguage(page,target){
 const candidates=target==="en"?[page.getByRole("button",{name:/English|EN|İngilizce/i}),page.locator('button[title*="English" i],button[aria-label*="English" i],button:has-text("EN")')]:[page.getByRole("button",{name:/Türkçe|TR|Turkish/i}),page.locator('button[title*="Türk" i],button[aria-label*="Türk" i],button:has-text("TR")')];
 for(const c of candidates){if(await c.count()){try{await c.first().click();await page.waitForTimeout(400);return true}catch{}}}return false;
}
async function auditNav(page,labels,lang){for(const label of labels){const b=page.locator(`nav button[aria-label=${JSON.stringify(label)}]`).first();if(!(await b.count())){finding("high",`${lang}:navigation`,"Navigation item missing",label);report.modules[lang].push({label,status:"missing"});continue}try{await b.evaluate(el=>el.click());await page.waitForTimeout(350);const s=await auditSurface(page,lang,label);report.modules[lang].push({label,status:"ok",forms:s.forms.length,tables:s.tables.length,leaks:s.leaks.length})}catch(e){finding("high",`${lang}:${label}`,"Module render/navigation failed",e.message);report.modules[lang].push({label,status:"error",error:e.message})}}}
async function auditRecords(context){const r=await context.request.get(`${baseUrl}/api/grc`,{headers:{...headers,origin:baseUrl}});if(r.status()!==200){finding("critical","records","Authenticated /api/grc failed",`HTTP ${r.status()}`);return}const body=await r.json(),rows=Array.isArray(body.rows)?body.rows:[];const ids=new Set(),codes=new Set();let duplicates=0,badJson=0,missing=0,badDates=0;const byModule={};for(const row of rows){byModule[row.module]=(byModule[row.module]||0)+1;if(ids.has(row.id))duplicates++;ids.add(row.id);if(row.record_code){if(codes.has(row.record_code))duplicates++;codes.add(row.record_code)}let data={};try{data=JSON.parse(String(row.data_json||"{}"))}catch{badJson++;continue}for(const key of required[row.module]||[])if(data[key]===undefined||data[key]===null||data[key]==="")missing++;for(const k of ["nextReview","lastReview","startDate","endDate","dueDate","contractEnd","eolDate"]){if(data[k]&&!/^\d{4}-\d{2}-\d{2}$/.test(String(data[k])))badDates++;}}
 report.records={total:rows.length,byModule,duplicates,badJson,missingRequiredValues:missing,badDateValues:badDates};if(duplicates)finding("critical","records","Duplicate record id/code detected",String(duplicates));if(badJson)finding("critical","records","Malformed data_json detected",String(badJson));if(missing)finding("high","records","Required record fields missing",String(missing));if(badDates)finding("medium","records","Invalid date format in records",String(badDates));}
async function auditSidebarTooltip(page){const compact=page.getByRole("button",{name:"Menüyü daralt",exact:true});if(await compact.count()){await compact.click();await page.waitForTimeout(250);const item=page.locator('nav button[aria-label="Risk Değerlendirmesi"]').first();if(await item.count()){await item.hover();await page.waitForTimeout(250);const tip=page.getByRole("tooltip").filter({hasText:"Risk Değerlendirmesi"});report.sidebar.tooltipVisible=await tip.count()>0&&await visible(tip.first());if(!report.sidebar.tooltipVisible)finding("medium","navigation","Collapsed sidebar tooltip not exposed on hover","Risk Değerlendirmesi");}}}
if(!email||!password||!accessId||!accessSecret)throw new Error("Release gate QA requires production smoke and Cloudflare Access credentials.");
const browser=await chromium.launch({headless:true});try{const context=await browser.newContext({viewport:{width:1536,height:960},extraHTTPHeaders:headers});await login(context);await auditRecords(context);const page=await context.newPage();const errors=[];page.on("console",m=>{if(m.type()==="error")errors.push({type:"console",text:m.text(),url:page.url()})});page.on("pageerror",e=>errors.push({type:"page",text:e.message,url:page.url()}));await page.goto(baseUrl,{waitUntil:"networkidle",timeout:60000});await page.waitForTimeout(900);await auditNav(page,tr,"tr");await auditSidebarTooltip(page);const switched=await switchLanguage(page,"en");if(!switched)finding("high","i18n","English language switch not found");else{await page.waitForTimeout(500);await auditNav(page,en,"en");}report.runtime.errors=errors;if(errors.length)finding("high","runtime","Console/page errors during deep QA",JSON.stringify(errors.slice(0,10)));await context.close()}finally{await browser.close()}
const rank={critical:0,high:1,medium:2,low:3,info:4};report.findings.sort((a,b)=>(rank[a.severity]??9)-(rank[b.severity]??9));report.finishedAt=new Date().toISOString();report.summary={findings:report.findings.length,critical:report.findings.filter(x=>x.severity==="critical").length,high:report.findings.filter(x=>x.severity==="high").length,medium:report.findings.filter(x=>x.severity==="medium").length,trModulesPassed:report.modules.tr.filter(x=>x.status==="ok").length,enModulesPassed:report.modules.en.filter(x=>x.status==="ok").length,formsAudited:report.forms.length,tablesAudited:report.tables.length,recordsAudited:report.records.total||0};await fs.writeFile(path.join(outDir,"release-gate-qa.json"),JSON.stringify(report,null,2));console.log("RELEASE_GATE_QA",JSON.stringify(report.summary));for(const f of report.findings.slice(0,80))console.log(`${f.severity.toUpperCase()} [${f.area}] ${f.title}${f.detail?` — ${f.detail}`:""}`);if(report.summary.critical>0)process.exitCode=2;
