import { NextRequest, NextResponse } from "next/server";
import { constantTimeEqual, requireRole, type AppRole } from "../auth/security";
import { clean, decryptSecret, encryptSecret, safeHttpUrl } from "../integrations/security";
import { controlHealth, evidenceFreshness, nextControlRun, remediationDueDate, validateContinuousControl } from "../../evidence/continuous-controls";
import { reconcileApprovedRetests } from "../../continuous-assurance-runtime";

type Env = Record<string,unknown> & { DB:D1Database };
type SourceRow={id:string;name:string;vendor:string;category:string;driver:string;enabled:number;config_json:string;secret_ciphertext:string|null;last_test_status:string|null;last_test_at:string|null};
type RuleRow={id:string;name:string;source_id:string;control_refs:string;json_path:string;operator:string;expected:string;schedule:string;enabled:number;last_status:string|null;last_run_at:string|null;freshness_hours:number;failure_threshold:number;consecutive_failures:number;auto_finding:number;remediation_owner:string;remediation_due_days:number;next_run_at:string|null;last_evidence_at:string|null};
type FindingRow={id:string;rule_id:string;evidence_id:string|null;title:string;severity:string;owner:string;due_date:string;status:string;detail:string;occurrence_count:number;created_at:string;updated_at:string;acknowledged_by:string|null;acknowledged_at:string|null;closure_note:string|null;closure_evidence_ref:string|null;closure_evidence_sha256:string|null;closed_by:string|null;closed_at:string|null};
type DetectedPath={path:string;type:"object"|"array"|"string"|"number"|"boolean"|"null"};
type ControlSuggestion={ref:string;title:string;score:number;matches:string[]};
const schema=[
`CREATE TABLE IF NOT EXISTS evidence_automation_sources(id TEXT PRIMARY KEY,name TEXT NOT NULL,vendor TEXT NOT NULL,category TEXT NOT NULL,driver TEXT NOT NULL,enabled INTEGER NOT NULL DEFAULT 1,config_json TEXT NOT NULL,secret_ciphertext TEXT,last_test_status TEXT,last_test_at TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,updated_by TEXT NOT NULL)`,
`CREATE TABLE IF NOT EXISTS evidence_automation_rules(id TEXT PRIMARY KEY,name TEXT NOT NULL,source_id TEXT NOT NULL,control_refs TEXT NOT NULL,json_path TEXT NOT NULL,operator TEXT NOT NULL,expected TEXT NOT NULL,schedule TEXT NOT NULL,enabled INTEGER NOT NULL DEFAULT 1,last_status TEXT,last_run_at TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,updated_by TEXT NOT NULL)`,
`CREATE TABLE IF NOT EXISTS evidence_automation_runs(id TEXT PRIMARY KEY,rule_id TEXT NOT NULL,rule_name TEXT NOT NULL,source_name TEXT NOT NULL,status TEXT NOT NULL,score INTEGER NOT NULL,detail TEXT NOT NULL,response_hash TEXT NOT NULL,evidence_id TEXT,created_at TEXT NOT NULL,actor TEXT NOT NULL)`,
`CREATE TABLE IF NOT EXISTS evidence_automation_findings(id TEXT PRIMARY KEY,rule_id TEXT NOT NULL,evidence_id TEXT,title TEXT NOT NULL,severity TEXT NOT NULL,owner TEXT NOT NULL,due_date TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'open',detail TEXT NOT NULL,occurrence_count INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,acknowledged_by TEXT,acknowledged_at TEXT,closure_note TEXT,closure_evidence_ref TEXT,closure_evidence_sha256 TEXT,closed_by TEXT,closed_at TEXT)`,
`CREATE UNIQUE INDEX IF NOT EXISTS evidence_automation_findings_open_idx ON evidence_automation_findings(rule_id) WHERE status!='closed'`,
`CREATE INDEX IF NOT EXISTS evidence_automation_findings_status_due_idx ON evidence_automation_findings(status,due_date)`,
`CREATE TABLE IF NOT EXISTS simple_grc_records(id TEXT PRIMARY KEY,module TEXT NOT NULL,data_json TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL)`,
];
async function runtime(){const {env}=await import("cloudflare:workers");return env as unknown as Env}
const ruleColumns:Record<string,string>={freshness_hours:"INTEGER NOT NULL DEFAULT 24",failure_threshold:"INTEGER NOT NULL DEFAULT 1",consecutive_failures:"INTEGER NOT NULL DEFAULT 0",auto_finding:"INTEGER NOT NULL DEFAULT 1",remediation_owner:"TEXT NOT NULL DEFAULT ''",remediation_due_days:"INTEGER NOT NULL DEFAULT 7",next_run_at:"TEXT",last_evidence_at:"TEXT"};
const runColumns:Record<string,string>={trigger_type:"TEXT NOT NULL DEFAULT 'manual'",duration_ms:"INTEGER NOT NULL DEFAULT 0",error_code:"TEXT"};
async function addMissingColumns(db:D1Database,table:string,columns:Record<string,string>){const info=await db.prepare(`PRAGMA table_info(${table})`).all<{name:string}>(),present=new Set(info.results.map(x=>x.name));for(const[name,definition]of Object.entries(columns))if(!present.has(name))await db.prepare(`ALTER TABLE ${table} ADD COLUMN ${name} ${definition}`).run()}
async function ready(db:D1Database){for(const sql of schema)await db.prepare(sql).run();await addMissingColumns(db,"evidence_automation_rules",ruleColumns);await addMissingColumns(db,"evidence_automation_runs",runColumns);await db.prepare("CREATE INDEX IF NOT EXISTS evidence_automation_rules_due_idx ON evidence_automation_rules(enabled,next_run_at)").run();await db.prepare("CREATE INDEX IF NOT EXISTS evidence_automation_runs_rule_created_idx ON evidence_automation_runs(rule_id,created_at)").run()}
function json(data:unknown,status=200){return NextResponse.json(data,{status,headers:{"cache-control":"no-store"}})}
function envText(env:Env,key:string){return String(env[key]??"").trim()}
function privateAllowed(env:Env){return ["true","1"].includes(envText(env,"FORNOST_ALLOW_PRIVATE_CONNECTORS").toLowerCase())}
function config(body:Record<string,unknown>){return {baseUrl:clean(body.baseUrl,2048),authType:clean(body.authType,30)||"bearer",headerName:clean(body.headerName,80)||"x-api-key"}}
async function sha256(value:string){const bytes=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value));return [...new Uint8Array(bytes)].map(x=>x.toString(16).padStart(2,"0")).join("")}
function pick(input:unknown,path:string){if(!path||path==="$"||path===".")return input;return path.replace(/^\$\.?/,"").split(".").filter(Boolean).reduce<unknown>((value,key)=>value&&typeof value==="object"?(value as Record<string,unknown>)[key]:undefined,input)}
function evaluate(value:unknown,operator:string,expected:string){if(operator==="exists")return value!==undefined&&value!==null&&value!=="";if(operator==="eq")return String(value)===expected;if(operator==="contains")return String(value).toLowerCase().includes(expected.toLowerCase());const actual=Number(value),target=Number(expected);if(!Number.isFinite(actual)||!Number.isFinite(target))return false;return operator==="gte"?actual>=target:operator==="lte"?actual<=target:false}
function publicSource(row:SourceRow){return {id:row.id,name:row.name,vendor:row.vendor,category:row.category,driver:row.driver,enabled:!!row.enabled,config:JSON.parse(row.config_json||"{}"),hasSecret:!!row.secret_ciphertext,lastTestStatus:row.last_test_status,lastTestAt:row.last_test_at}}
function publicRule(row:RuleRow,now=new Date()){return {id:row.id,name:row.name,sourceId:row.source_id,controlRefs:row.control_refs,jsonPath:row.json_path,operator:row.operator,expected:row.expected,schedule:row.schedule,enabled:!!row.enabled,lastStatus:row.last_status,lastRunAt:row.last_run_at,freshnessHours:row.freshness_hours,failureThreshold:row.failure_threshold,consecutiveFailures:row.consecutive_failures,autoFinding:!!row.auto_finding,remediationOwner:row.remediation_owner,remediationDueDays:row.remediation_due_days,nextRunAt:row.next_run_at,lastEvidenceAt:row.last_evidence_at,freshness:evidenceFreshness(row.last_evidence_at,row.freshness_hours,now),health:controlHealth({enabled:!!row.enabled,lastStatus:row.last_status,lastEvidenceAt:row.last_evidence_at,freshnessHours:row.freshness_hours,consecutiveFailures:row.consecutive_failures},now)}}
function publicFinding(row:FindingRow){return {id:row.id,ruleId:row.rule_id,evidenceId:row.evidence_id,title:row.title,severity:row.severity,owner:row.owner,dueDate:row.due_date,status:row.status,detail:row.detail,occurrenceCount:row.occurrence_count,createdAt:row.created_at,updatedAt:row.updated_at,acknowledgedBy:row.acknowledged_by,acknowledgedAt:row.acknowledged_at,closureNote:row.closure_note,closureEvidenceRef:row.closure_evidence_ref,closureEvidenceSha256:row.closure_evidence_sha256,closedBy:row.closed_by,closedAt:row.closed_at}}

function jsonValueType(value:unknown):DetectedPath["type"]{if(value===null)return"null";if(Array.isArray(value))return"array";const kind=typeof value;return kind==="string"||kind==="number"||kind==="boolean"?kind:"object"}
function discoverJsonPaths(payload:unknown){const paths:DetectedPath[]=[];const queue:Array<{value:unknown;path:string}>=[{value:payload,path:"$"}];let visited=0;while(queue.length&&visited<240&&paths.length<80){const current=queue.shift()!;visited+=1;const type=jsonValueType(current.value);if(current.path!=="$")paths.push({path:current.path,type});if(type==="object"&&current.value){for(const [key,value] of Object.entries(current.value as Record<string,unknown>).slice(0,40))queue.push({value,path:`${current.path}.${key.replace(/\./g,"_")}`})}else if(type==="array"){for(const [index,value] of (current.value as unknown[]).slice(0,3).entries())queue.push({value,path:`${current.path}.${index}`})}}return {rootType:jsonValueType(payload),paths,totalPaths:paths.length,truncated:queue.length>0||visited>=240}}
const domainKeywords:Record<string,string[]>={
 "Cloud & SaaS":["cloud","saas","azure","aws","m365","tenant","configuration","service"],
 "Firewall & Network":["firewall","network","segmentation","rule","traffic","vpn","gateway"],
 "XDR, EDR & SIEM":["endpoint","edr","xdr","siem","logging","monitoring","detection","incident","malware","alert"],
 "IAM, PAM & IGA":["identity","access","account","authentication","authorization","mfa","privileged","pam","iam"],
 "Data, DB & Application":["data","database","application","vulnerability","patch","scan","secure","dlp"],
 "Work & Custom":["ticket","workflow","change","incident","remediation","issue","integration"],
};
const ignoredTokens=new Set(["https","api","rest","json","com","www","microsoft","generic","service","the","and","for","with","from"]);
function words(value:unknown){return [...new Set(clean(value,4000).normalize("NFKC").toLocaleLowerCase("en-US").split(/[^a-z0-9çğıöşü_-]+/i).flatMap(part=>part.split(/[_-]+/)).map(part=>part.trim()).filter(part=>part.length>=3&&!ignoredTokens.has(part)))];}
async function suggestControls(db:D1Database,source:SourceRow,paths:DetectedPath[]):Promise<ControlSuggestion[]>{const rows=await db.prepare("SELECT id,data_json FROM simple_grc_records WHERE module='Kontroller' ORDER BY updated_at DESC LIMIT 1200").all<{id:string;data_json:string}>();const sourceTokens=[...new Set([...words(source.name),...words(source.vendor),...(domainKeywords[source.category]||[]),...paths.slice(0,30).flatMap(path=>words(path.path))])].slice(0,80);const suggestions:ControlSuggestion[]=[];for(const row of rows.results){let data:Record<string,unknown>={};try{const parsed=JSON.parse(row.data_json);if(parsed&&typeof parsed==="object"&&!Array.isArray(parsed))data=parsed}catch{}const ref=clean(data.controlId||data.controlCode||data.code||data.reference||row.id,160);const title=clean(data.controlTitle||data.title||data.name||data.objective||ref,240);const haystack=clean([ref,title,data.description,data.objective,data.category,data.type,data.frameworkRefs,data.framework].filter(Boolean).join(" "),6000).normalize("NFKC").toLocaleLowerCase("en-US");const matches=sourceTokens.filter(token=>haystack.includes(token)).slice(0,8);if(!matches.length)continue;const score=matches.reduce((sum,token)=>sum+(title.toLocaleLowerCase("en-US").includes(token)?3:1),0);suggestions.push({ref,title,score,matches})}return suggestions.sort((a,b)=>b.score-a.score||a.ref.localeCompare(b.ref)).slice(0,8)}

export async function GET(req:NextRequest){const access=await requireRole(req,["Admin","Editor","Viewer"]);if(access.response)return access.response;const env=await runtime();await ready(env.DB);const [sources,rules,runs,findings]=await Promise.all([env.DB.prepare("SELECT * FROM evidence_automation_sources ORDER BY name").all<SourceRow>(),env.DB.prepare("SELECT * FROM evidence_automation_rules ORDER BY name").all<RuleRow>(),env.DB.prepare("SELECT id,rule_name,source_name,status,score,detail,evidence_id,created_at,trigger_type,duration_ms,error_code FROM evidence_automation_runs ORDER BY created_at DESC LIMIT 100").all<Record<string,unknown>>(),env.DB.prepare("SELECT * FROM evidence_automation_findings ORDER BY CASE status WHEN 'open' THEN 0 WHEN 'acknowledged' THEN 1 ELSE 2 END,due_date,created_at DESC LIMIT 100").all<FindingRow>()]),now=new Date(),publicRules=rules.results.map(r=>publicRule(r,now));return json({sources:sources.results.map(publicSource),rules:publicRules,runs:runs.results.map(r=>({id:r.id,ruleName:r.rule_name,sourceName:r.source_name,status:r.status,score:r.score,detail:r.detail,evidenceId:r.evidence_id,createdAt:r.created_at,triggerType:r.trigger_type,durationMs:r.duration_ms,errorCode:r.error_code})),findings:findings.results.map(publicFinding),summary:{healthy:publicRules.filter(r=>r.health==="healthy").length,failing:publicRules.filter(r=>r.health==="failing").length,stale:publicRules.filter(r=>r.health==="stale"||r.health==="missing").length,due:publicRules.filter(r=>r.enabled&&(!r.nextRunAt||r.nextRunAt<=now.toISOString())).length,openFindings:findings.results.filter(r=>r.status!=="closed").length}})}

export async function POST(req:NextRequest){if(Number(req.headers.get("content-length")||0)>65_536)return json({error:"İstek boyutu çok büyük."},413);const body=await req.json().catch(()=>({})) as Record<string,unknown>,action=clean(body.action,40),roles:AppRole[]=action==="run-rule"||action==="run-due"||action==="acknowledge-finding"?["Admin","Editor"]:["Admin"],env=await runtime(),configuredToken=envText(env,"FORNOST_SCHEDULER_TOKEN"),presentedToken=req.headers.get("x-fornost-scheduler-token")||"",scheduled=action==="run-due"&&configuredToken.length>=32&&presentedToken.length>=32&&constantTimeEqual(configuredToken,presentedToken);let actorEmail="system:scheduler";if(!scheduled){const access=await requireRole(req,roles);if(access.response)return access.response;actorEmail=access.actor.email}await ready(env.DB);try{
 if(action==="save-source"){const requestedId=clean(body.sourceId,80),name=clean(body.name,150),vendor=clean(body.vendor,150)||name,category=clean(body.category,80),driver=clean(body.driver,40)||"rest-json",cfg=config(body),secret=clean(body.secret,4096);if(!name||!safeHttpUrl(cfg.baseUrl,privateAllowed(env)))return json({error:"Kaynak adı ve güvenli bir API adresi gerekli."},400);const existing=requestedId?await env.DB.prepare("SELECT * FROM evidence_automation_sources WHERE id=?").bind(requestedId).first<SourceRow>():null;if(requestedId&&!existing)return json({error:"Güncellenecek kanıt kaynağı bulunamadı."},404);let encrypted=existing?.secret_ciphertext||null;if(secret){const key=envText(env,"FORNOST_SETTINGS_ENCRYPTION_KEY");if(!key)return json({error:"Entegrasyon şifreleme anahtarı yapılandırılmamış."},503);encrypted=await encryptSecret(secret,key)}const id=existing?.id||crypto.randomUUID(),now=new Date().toISOString();if(existing)await env.DB.prepare("UPDATE evidence_automation_sources SET name=?,vendor=?,category=?,driver=?,config_json=?,secret_ciphertext=?,last_test_status=NULL,last_test_at=NULL,updated_at=?,updated_by=? WHERE id=?").bind(name,vendor,category,driver,JSON.stringify(cfg),encrypted,now,actorEmail,id).run();else await env.DB.prepare("INSERT INTO evidence_automation_sources(id,name,vendor,category,driver,enabled,config_json,secret_ciphertext,created_at,updated_at,updated_by) VALUES(?,?,?,?,?,1,?,?,?,?,?)").bind(id,name,vendor,category,driver,JSON.stringify(cfg),encrypted,now,now,actorEmail).run();return json({ok:true,sourceId:id,message:existing?"Kanıt kaynağı güvenli biçimde güncellendi.":"Kanıt kaynağı güvenli biçimde kaydedildi."})}
 if(action==="save-rule"){const name=clean(body.name,150),sourceId=clean(body.sourceId,80),controlRefs=clean(body.controlRefs,1000),jsonPath=clean(body.jsonPath,300),operator=clean(body.operator,20),expected=clean(body.expected,300),schedule=clean(body.schedule,30),remediationOwner=clean(body.remediationOwner,200);if(!name||!sourceId||!controlRefs||!["exists","eq","gte","lte","contains"].includes(operator))return json({error:"Kural alanları geçersiz veya eksik."},400);if(!await env.DB.prepare("SELECT id FROM evidence_automation_sources WHERE id=?").bind(sourceId).first())return json({error:"Kanıt kaynağı bulunamadı."},404);const policy=validateContinuousControl({schedule,freshnessHours:body.freshnessHours,failureThreshold:body.failureThreshold,remediationDueDays:body.remediationDueDays,autoFinding:body.autoFinding}),id=crypto.randomUUID(),now=new Date();await env.DB.prepare("INSERT INTO evidence_automation_rules(id,name,source_id,control_refs,json_path,operator,expected,schedule,enabled,created_at,updated_at,updated_by,freshness_hours,failure_threshold,consecutive_failures,auto_finding,remediation_owner,remediation_due_days,next_run_at) VALUES(?,?,?,?,?,?,?,?,1,?,?,?,?,?,0,?,?,?,?)").bind(id,name,sourceId,controlRefs,jsonPath,operator,expected,schedule,now.toISOString(),now.toISOString(),actorEmail,policy.freshnessHours,policy.failureThreshold,policy.autoFinding?1:0,remediationOwner||actorEmail,policy.remediationDueDays,nextControlRun(schedule,now)).run();return json({ok:true,ruleId:id,message:"Sürekli kontrol kuralı ve çalışma takvimi kaydedildi."})}
 if(action==="test-source"){const id=clean(body.sourceId,80),source=await env.DB.prepare("SELECT * FROM evidence_automation_sources WHERE id=?").bind(id).first<SourceRow>();if(!source)return json({error:"Kaynak bulunamadı."},404);const now=new Date().toISOString();try{await requestSource(source,env,false);await env.DB.prepare("UPDATE evidence_automation_sources SET last_test_status='success',last_test_at=?,updated_at=? WHERE id=?").bind(now,now,id).run();return json({ok:true,message:"API bağlantısı ve JSON yanıtı doğrulandı."})}catch(error){await env.DB.prepare("UPDATE evidence_automation_sources SET last_test_status='error',last_test_at=?,updated_at=? WHERE id=?").bind(now,now,id).run();throw error}}
 if(action==="discover-source"){const id=clean(body.sourceId,80),source=await env.DB.prepare("SELECT * FROM evidence_automation_sources WHERE id=?").bind(id).first<SourceRow>();if(!source)return json({error:"Kaynak bulunamadı."},404);const now=new Date().toISOString();try{const payload=await requestSource(source,env,true),detected=discoverJsonPaths(payload),suggestedControls=await suggestControls(env.DB,source,detected.paths);await env.DB.prepare("UPDATE evidence_automation_sources SET last_test_status='success',last_test_at=?,updated_at=? WHERE id=?").bind(now,now,id).run();return json({ok:true,sourceId:id,message:"Bağlantı doğrulandı; JSON yapısı ve kontrol adayları keşfedildi.",detected,suggestedControls})}catch(error){await env.DB.prepare("UPDATE evidence_automation_sources SET last_test_status='error',last_test_at=?,updated_at=? WHERE id=?").bind(now,now,id).run();throw error}}
 if(action==="run-rule"){const ruleId=clean(body.ruleId,80),result=await executeRule(env,ruleId,actorEmail,"manual"),reconciled=await reconcileApprovedRetests(env.DB);return json({ok:true,message:result.status==="pass"?"Kanıt toplandı ve doğrulama başarılı.":result.status==="fail"?"Kanıt toplandı; bulgu ve düzeltme akışı değerlendirildi.":"Kaynağa erişilemedi; çalışma ve bulgu kaydı oluşturuldu.",reconciledAssuranceWork:reconciled,...result})}
 if(action==="run-due"){const due=await env.DB.prepare("SELECT id FROM evidence_automation_rules WHERE enabled=1 AND (next_run_at IS NULL OR next_run_at<=?) ORDER BY COALESCE(next_run_at,'') LIMIT 20").bind(new Date().toISOString()).all<{id:string}>(),results=[];for(const item of due.results)results.push(await executeRule(env,item.id,actorEmail,"scheduler"));const reconciled=await reconcileApprovedRetests(env.DB);return json({ok:true,message:`${results.length} zamanı gelen kontrol çalıştırıldı.`,reconciledAssuranceWork:reconciled,results})}
 if(action==="toggle-rule"){const id=clean(body.ruleId,80),enabled=body.enabled===true?1:0,now=new Date().toISOString();const rule=await env.DB.prepare("SELECT schedule FROM evidence_automation_rules WHERE id=?").bind(id).first<{schedule:string}>();if(!rule)return json({error:"Kural bulunamadı."},404);await env.DB.prepare("UPDATE evidence_automation_rules SET enabled=?,next_run_at=?,updated_at=?,updated_by=? WHERE id=?").bind(enabled,enabled?nextControlRun(rule.schedule,new Date(now)):null,now,actorEmail,id).run();return json({ok:true,message:enabled?"Sürekli kontrol etkinleştirildi.":"Sürekli kontrol duraklatıldı."})}
 if(action==="acknowledge-finding"){const id=clean(body.findingId,80),now=new Date().toISOString();const result=await env.DB.prepare("UPDATE evidence_automation_findings SET status='acknowledged',acknowledged_by=?,acknowledged_at=?,updated_at=? WHERE id=? AND status='open'").bind(actorEmail,now,now,id).run();if(!Number(result.meta?.changes||0))return json({error:"Açık bulgu bulunamadı."},404);return json({ok:true,message:"Bulgu sahiplenildi ve düzeltme takibine alındı."})}
 if(action==="close-finding"){const id=clean(body.findingId,80),note=clean(body.note,1200),evidenceRef=clean(body.evidenceReference,500),hash=clean(body.evidenceSha256,64).toLowerCase(),confirmation=clean(body.confirmation,80);if(note.length<10||!evidenceRef||!/^[a-f0-9]{64}$/.test(hash)||confirmation!=="BULGUYU KAPAT")return json({error:"Kapanış notu, kanıt referansı, SHA-256 ve BULGUYU KAPAT onayı gerekli."},400);const finding=await env.DB.prepare("SELECT * FROM evidence_automation_findings WHERE id=? AND status!='closed'").bind(id).first<FindingRow>();if(!finding)return json({error:"Açık bulgu bulunamadı."},404);if(finding.acknowledged_by===actorEmail)return json({error:"Bulguyu sahiplenen kişi aynı bulguyu kapatamaz."},409);const now=new Date().toISOString();await env.DB.prepare("UPDATE evidence_automation_findings SET status='closed',closure_note=?,closure_evidence_ref=?,closure_evidence_sha256=?,closed_by=?,closed_at=?,updated_at=? WHERE id=?").bind(note,evidenceRef,hash,actorEmail,now,now,id).run();const record=await env.DB.prepare("SELECT data_json FROM simple_grc_records WHERE id=?").bind(id).first<{data_json:string}>();if(record){const data=JSON.parse(record.data_json);data.status="Kapalı";data.closureNote=note;data.closureEvidence=evidenceRef;data.closureEvidenceSha256=hash;await env.DB.prepare("UPDATE simple_grc_records SET data_json=?,updated_at=? WHERE id=?").bind(JSON.stringify(data),now,id).run()}return json({ok:true,message:"Bulgu bağımsız kanıtla kapatıldı."})}
 return json({error:"Geçersiz işlem."},400)
 }catch(error){return json({error:error instanceof Error?error.message:"Kanıt otomasyonu işlemi başarısız."},502)}}

async function executeRule(env:Env,ruleId:string,actor:string,triggerType:"manual"|"scheduler"){
 const rule=await env.DB.prepare("SELECT * FROM evidence_automation_rules WHERE id=?").bind(ruleId).first<RuleRow>();if(!rule)throw new Error("Kural bulunamadı.");if(!rule.enabled&&triggerType==="scheduler")return {ruleId,status:"skipped"};const source=await env.DB.prepare("SELECT * FROM evidence_automation_sources WHERE id=?").bind(rule.source_id).first<SourceRow>();if(!source)throw new Error("Kanıt kaynağı bulunamadı.");const started=Date.now(),now=new Date(),nowIso=now.toISOString(),runId=crypto.randomUUID();
 try{const payload=await requestSource(source,env,true),raw=JSON.stringify(payload),responseHash=await sha256(raw),value=pick(payload,rule.json_path),passed=evaluate(value,rule.operator,rule.expected),evidenceId=`EVD-AUTO-${crypto.randomUUID()}`,status=passed?"pass":"fail",detail=`${rule.json_path||"$"} = ${String(value).slice(0,160)}; ${rule.operator} ${rule.expected||"(değer var)"}`,failures=passed?0:rule.consecutive_failures+1;await env.DB.prepare("INSERT INTO evidence_automation_runs(id,rule_id,rule_name,source_name,status,score,detail,response_hash,evidence_id,created_at,actor,trigger_type,duration_ms) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(runId,rule.id,rule.name,source.name,status,passed?100:0,detail,responseHash,evidenceId,nowIso,actor,triggerType,Date.now()-started).run();const evidence={evidenceTitle:rule.name,controlRef:rule.control_refs,owner:actor,period:nowIso.slice(0,10),source:source.name,collectionMethod:"API",validationStatus:status,validationDetail:detail,responseHash,collectedAt:nowIso,freshUntil:new Date(now.getTime()+rule.freshness_hours*60*60_000).toISOString(),rawSnapshot:raw.slice(0,200000),status:passed?"Güncel":"İnceleme Gerekli"};await env.DB.prepare("INSERT INTO simple_grc_records(id,module,data_json,created_at,updated_at) VALUES(?,?,?,?,?)").bind(evidenceId,"Kanıtlar",JSON.stringify(evidence),nowIso,nowIso).run();await env.DB.prepare("UPDATE evidence_automation_rules SET last_status=?,last_run_at=?,last_evidence_at=?,consecutive_failures=?,next_run_at=?,updated_at=?,updated_by=? WHERE id=?").bind(status,nowIso,nowIso,failures,nextControlRun(rule.schedule,now),nowIso,actor,rule.id).run();if(!passed&&rule.auto_finding&&failures>=rule.failure_threshold)await upsertFinding(env,rule,evidenceId,detail,actor,now);return {ruleId,runId,evidenceId,status,failures}}
 catch(error){const message=error instanceof Error?error.message:"Kaynak toplama hatası",failures=rule.consecutive_failures+1;await env.DB.prepare("INSERT INTO evidence_automation_runs(id,rule_id,rule_name,source_name,status,score,detail,response_hash,evidence_id,created_at,actor,trigger_type,duration_ms,error_code) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(runId,rule.id,rule.name,source.name,"error",0,message,await sha256(message),null,nowIso,actor,triggerType,Date.now()-started,"SOURCE_REQUEST_FAILED").run();await env.DB.prepare("UPDATE evidence_automation_rules SET last_status='error',last_run_at=?,consecutive_failures=?,next_run_at=?,updated_at=?,updated_by=? WHERE id=?").bind(nowIso,failures,nextControlRun(rule.schedule,now),nowIso,actor,rule.id).run();if(rule.auto_finding&&failures>=rule.failure_threshold)await upsertFinding(env,rule,null,message,actor,now);return {ruleId,runId,status:"error",failures,errorCode:"SOURCE_REQUEST_FAILED"}}
}

async function upsertFinding(env:Env,rule:RuleRow,evidenceId:string|null,detail:string,actor:string,now:Date){const existing=await env.DB.prepare("SELECT * FROM evidence_automation_findings WHERE rule_id=? AND status!='closed'").bind(rule.id).first<FindingRow>(),nowIso=now.toISOString();if(existing){await env.DB.prepare("UPDATE evidence_automation_findings SET evidence_id=?,detail=?,occurrence_count=occurrence_count+1,updated_at=? WHERE id=?").bind(evidenceId,detail,nowIso,existing.id).run();return existing.id}const id=`CCM-${crypto.randomUUID()}`,owner=rule.remediation_owner||actor,dueDate=remediationDueDate(rule.remediation_due_days,now),severity=rule.consecutive_failures+1>=Math.max(3,rule.failure_threshold)?"critical":"high",title=`Sürekli kontrol başarısız: ${rule.name}`;await env.DB.prepare("INSERT INTO evidence_automation_findings(id,rule_id,evidence_id,title,severity,owner,due_date,status,detail,occurrence_count,created_at,updated_at) VALUES(?,?,?,?,?,?,?,'open',?,1,?,?)").bind(id,rule.id,evidenceId,title,severity,owner,dueDate,detail,nowIso,nowIso).run();const risk={title,category:"Compliance",owner,status:"Açık",riskLevel:severity==="critical"?"Kritik":"Yüksek",asset:"Continuous Control Monitoring",description:detail,treatment:`${rule.control_refs} kontrolleri için kaynağı ve doğrulama eşiğini düzeltin.`,nextReview:dueDate,source:"Continuous Control Monitoring",sourceRef:rule.id,evidenceRef:evidenceId||"",inherentLikelihood:"4",inherentImpact:severity==="critical"?"5":"4",calculatedImpact:severity==="critical"?"20":"16"};await env.DB.prepare("INSERT INTO simple_grc_records(id,module,data_json,created_at,updated_at) VALUES(?,?,?,?,?)").bind(id,"Risk Assessment",JSON.stringify(risk),nowIso,nowIso).run();return id}

async function requestSource(source:SourceRow,env:Env,keepPayload:boolean){const cfg=JSON.parse(source.config_json||"{}") as Record<string,string>,url=safeHttpUrl(cfg.baseUrl,privateAllowed(env));if(!url)throw new Error("Kaynak adresi güvenlik politikasına uygun değil.");let secret="";if(source.secret_ciphertext){const key=envText(env,"FORNOST_SETTINGS_ENCRYPTION_KEY");if(!key)throw new Error("Entegrasyon şifreleme anahtarı eksik.");secret=await decryptSecret(source.secret_ciphertext,key)}const headers:Record<string,string>={accept:"application/json","user-agent":"Fornost-GRC-Evidence-Collector/1.0"};if(cfg.authType==="bearer"&&secret)headers.authorization=`Bearer ${secret}`;else if(cfg.authType==="api-key"&&secret)headers[cfg.headerName||"x-api-key"]=secret;else if(cfg.authType==="basic"&&secret)headers.authorization=`Basic ${btoa(secret)}`;const response=await fetch(url,{method:"GET",headers,redirect:"error",signal:AbortSignal.timeout(12_000)});if(!response.ok)throw new Error(`Kaynak API yanıt vermedi (${response.status}).`);const type=response.headers.get("content-type")||"";if(!type.includes("json"))throw new Error("Kaynak JSON yanıtı döndürmedi.");const text=await response.text();if(text.length>1_000_000)throw new Error("API yanıtı 1 MB sınırını aşıyor.");const payload=JSON.parse(text);return keepPayload?payload:{ok:true}}
