import { NextRequest, NextResponse } from "next/server";
import { requireRole } from "../auth/security";
import { clean, decryptSecret, encryptSecret, safeHttpUrl } from "../integrations/security";

type Env = Record<string,unknown> & { DB:D1Database };
type SourceRow={id:string;name:string;vendor:string;category:string;driver:string;enabled:number;config_json:string;secret_ciphertext:string|null;last_test_status:string|null;last_test_at:string|null};
type RuleRow={id:string;name:string;source_id:string;control_refs:string;json_path:string;operator:string;expected:string;schedule:string;enabled:number;last_status:string|null;last_run_at:string|null};
const schema=[
`CREATE TABLE IF NOT EXISTS evidence_automation_sources(id TEXT PRIMARY KEY,name TEXT NOT NULL,vendor TEXT NOT NULL,category TEXT NOT NULL,driver TEXT NOT NULL,enabled INTEGER NOT NULL DEFAULT 1,config_json TEXT NOT NULL,secret_ciphertext TEXT,last_test_status TEXT,last_test_at TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,updated_by TEXT NOT NULL)`,
`CREATE TABLE IF NOT EXISTS evidence_automation_rules(id TEXT PRIMARY KEY,name TEXT NOT NULL,source_id TEXT NOT NULL,control_refs TEXT NOT NULL,json_path TEXT NOT NULL,operator TEXT NOT NULL,expected TEXT NOT NULL,schedule TEXT NOT NULL,enabled INTEGER NOT NULL DEFAULT 1,last_status TEXT,last_run_at TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,updated_by TEXT NOT NULL)`,
`CREATE TABLE IF NOT EXISTS evidence_automation_runs(id TEXT PRIMARY KEY,rule_id TEXT NOT NULL,rule_name TEXT NOT NULL,source_name TEXT NOT NULL,status TEXT NOT NULL,score INTEGER NOT NULL,detail TEXT NOT NULL,response_hash TEXT NOT NULL,evidence_id TEXT,created_at TEXT NOT NULL,actor TEXT NOT NULL)`,
`CREATE TABLE IF NOT EXISTS simple_grc_records(id TEXT PRIMARY KEY,module TEXT NOT NULL,data_json TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL)`,
];
async function runtime(){const {env}=await import("cloudflare:workers");return env as unknown as Env}
async function ready(db:D1Database){for(const sql of schema)await db.prepare(sql).run()}
function json(data:unknown,status=200){return NextResponse.json(data,{status,headers:{"cache-control":"no-store"}})}
function envText(env:Env,key:string){return String(env[key]??"").trim()}
function privateAllowed(env:Env){return ["true","1"].includes(envText(env,"FORNOST_ALLOW_PRIVATE_CONNECTORS").toLowerCase())}
function config(body:Record<string,unknown>){return {baseUrl:clean(body.baseUrl,2048),authType:clean(body.authType,30)||"bearer",headerName:clean(body.headerName,80)||"x-api-key"}}
async function sha256(value:string){const bytes=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value));return [...new Uint8Array(bytes)].map(x=>x.toString(16).padStart(2,"0")).join("")}
function pick(input:unknown,path:string){if(!path||path==="$"||path===".")return input;return path.replace(/^\$\.?/,"").split(".").filter(Boolean).reduce<unknown>((value,key)=>value&&typeof value==="object"?(value as Record<string,unknown>)[key]:undefined,input)}
function evaluate(value:unknown,operator:string,expected:string){if(operator==="exists")return value!==undefined&&value!==null&&value!=="";if(operator==="eq")return String(value)===expected;if(operator==="contains")return String(value).toLowerCase().includes(expected.toLowerCase());const actual=Number(value),target=Number(expected);if(!Number.isFinite(actual)||!Number.isFinite(target))return false;return operator==="gte"?actual>=target:operator==="lte"?actual<=target:false}
function publicSource(row:SourceRow){return {id:row.id,name:row.name,vendor:row.vendor,category:row.category,driver:row.driver,enabled:!!row.enabled,config:JSON.parse(row.config_json||"{}"),hasSecret:!!row.secret_ciphertext,lastTestStatus:row.last_test_status,lastTestAt:row.last_test_at}}

export async function GET(req:NextRequest){const access=await requireRole(req,["Admin","Editor","Viewer"]);if(access.response)return access.response;const env=await runtime();await ready(env.DB);const [sources,rules,runs]=await Promise.all([env.DB.prepare("SELECT * FROM evidence_automation_sources ORDER BY name").all<SourceRow>(),env.DB.prepare("SELECT * FROM evidence_automation_rules ORDER BY name").all<RuleRow>(),env.DB.prepare("SELECT id,rule_name,source_name,status,score,detail,evidence_id,created_at FROM evidence_automation_runs ORDER BY created_at DESC LIMIT 100").all<Record<string,unknown>>()]);return json({sources:sources.results.map(publicSource),rules:rules.results.map(r=>({id:r.id,name:r.name,sourceId:r.source_id,controlRefs:r.control_refs,jsonPath:r.json_path,operator:r.operator,expected:r.expected,schedule:r.schedule,enabled:!!r.enabled,lastStatus:r.last_status,lastRunAt:r.last_run_at})),runs:runs.results.map(r=>({id:r.id,ruleName:r.rule_name,sourceName:r.source_name,status:r.status,score:r.score,detail:r.detail,evidenceId:r.evidence_id,createdAt:r.created_at}))})}

export async function POST(req:NextRequest){if(Number(req.headers.get("content-length")||0)>65_536)return json({error:"İstek boyutu çok büyük."},413);const body=await req.json().catch(()=>({})) as Record<string,unknown>,action=clean(body.action,40),roles=action==="run-rule"?["Admin","Editor"]:["Admin"];const access=await requireRole(req,roles);if(access.response)return access.response;const env=await runtime();await ready(env.DB);try{
 if(action==="save-source"){const name=clean(body.name,150),vendor=clean(body.vendor,150)||name,category=clean(body.category,80),driver=clean(body.driver,40)||"rest-json",cfg=config(body),secret=clean(body.secret,4096);if(!name||!safeHttpUrl(cfg.baseUrl,privateAllowed(env)))return json({error:"Kaynak adı ve güvenli bir API adresi gerekli."},400);let encrypted:string|null=null;if(secret){const key=envText(env,"FORNOST_SETTINGS_ENCRYPTION_KEY");if(!key)return json({error:"Entegrasyon şifreleme anahtarı yapılandırılmamış."},503);encrypted=await encryptSecret(secret,key)}const id=crypto.randomUUID(),now=new Date().toISOString();await env.DB.prepare("INSERT INTO evidence_automation_sources(id,name,vendor,category,driver,enabled,config_json,secret_ciphertext,created_at,updated_at,updated_by) VALUES(?,?,?,?,?,1,?,?,?,?,?)").bind(id,name,vendor,category,driver,JSON.stringify(cfg),encrypted,now,now,access.actor.email).run();return json({ok:true,message:"Kanıt kaynağı güvenli biçimde kaydedildi."})}
 if(action==="save-rule"){const name=clean(body.name,150),sourceId=clean(body.sourceId,80),controlRefs=clean(body.controlRefs,1000),jsonPath=clean(body.jsonPath,300),operator=clean(body.operator,20),expected=clean(body.expected,300),schedule=clean(body.schedule,30);if(!name||!sourceId||!controlRefs||!["exists","eq","gte","lte","contains"].includes(operator)||!["hourly","daily","weekly","monthly"].includes(schedule))return json({error:"Kural alanları geçersiz veya eksik."},400);if(!await env.DB.prepare("SELECT id FROM evidence_automation_sources WHERE id=?").bind(sourceId).first())return json({error:"Kanıt kaynağı bulunamadı."},404);const id=crypto.randomUUID(),now=new Date().toISOString();await env.DB.prepare("INSERT INTO evidence_automation_rules(id,name,source_id,control_refs,json_path,operator,expected,schedule,enabled,created_at,updated_at,updated_by) VALUES(?,?,?,?,?,?,?,?,1,?,?,?)").bind(id,name,sourceId,controlRefs,jsonPath,operator,expected,schedule,now,now,access.actor.email).run();return json({ok:true,message:"Toplama ve doğrulama kuralı kaydedildi."})}
 if(action==="test-source"){const id=clean(body.sourceId,80),source=await env.DB.prepare("SELECT * FROM evidence_automation_sources WHERE id=?").bind(id).first<SourceRow>();if(!source)return json({error:"Kaynak bulunamadı."},404);await requestSource(source,env,false);const now=new Date().toISOString();await env.DB.prepare("UPDATE evidence_automation_sources SET last_test_status='success',last_test_at=?,updated_at=? WHERE id=?").bind(now,now,id).run();return json({ok:true,message:"API bağlantısı ve JSON yanıtı doğrulandı."})}
 if(action==="run-rule"){const ruleId=clean(body.ruleId,80),rule=await env.DB.prepare("SELECT * FROM evidence_automation_rules WHERE id=?").bind(ruleId).first<RuleRow>();if(!rule)return json({error:"Kural bulunamadı."},404);const source=await env.DB.prepare("SELECT * FROM evidence_automation_sources WHERE id=?").bind(rule.source_id).first<SourceRow>();if(!source)return json({error:"Kanıt kaynağı bulunamadı."},404);const payload=await requestSource(source,env,true),raw=JSON.stringify(payload),value=pick(payload,rule.json_path),passed=evaluate(value,rule.operator,rule.expected),now=new Date().toISOString(),evidenceId=`EVD-AUTO-${crypto.randomUUID()}`,runId=crypto.randomUUID(),status=passed?"pass":"fail",detail=`${rule.json_path||"$"} = ${String(value).slice(0,160)}; ${rule.operator} ${rule.expected||"(değer var)"}`;await env.DB.prepare("INSERT INTO evidence_automation_runs(id,rule_id,rule_name,source_name,status,score,detail,response_hash,evidence_id,created_at,actor) VALUES(?,?,?,?,?,?,?,?,?,?,?)").bind(runId,rule.id,rule.name,source.name,status,passed?100:0,detail,await sha256(raw),evidenceId,now,access.actor.email).run();const evidence={evidenceTitle:rule.name,controlRef:rule.control_refs,owner:access.actor.email,period:now.slice(0,10),source:source.name,collectionMethod:"API",validationStatus:status,validationDetail:detail,responseHash:await sha256(raw),collectedAt:now,rawSnapshot:raw.slice(0,200000),status:passed?"Uygun":"İnceleme Gerekli"};await env.DB.prepare("INSERT INTO simple_grc_records(id,module,data_json,created_at,updated_at) VALUES(?,?,?,?,?)").bind(evidenceId,"Kanıtlar",JSON.stringify(evidence),now,now).run();await env.DB.prepare("UPDATE evidence_automation_rules SET last_status=?,last_run_at=?,updated_at=? WHERE id=?").bind(status,now,now,rule.id).run();return json({ok:true,message:passed?"Kanıt toplandı ve doğrulama başarılı.":"Kanıt toplandı; sonuç inceleme gerektiriyor.",evidenceId,status})}
 return json({error:"Geçersiz işlem."},400)
 }catch(error){return json({error:error instanceof Error?error.message:"Kanıt otomasyonu işlemi başarısız."},502)}}

async function requestSource(source:SourceRow,env:Env,keepPayload:boolean){const cfg=JSON.parse(source.config_json||"{}") as Record<string,string>,url=safeHttpUrl(cfg.baseUrl,privateAllowed(env));if(!url)throw new Error("Kaynak adresi güvenlik politikasına uygun değil.");let secret="";if(source.secret_ciphertext){const key=envText(env,"FORNOST_SETTINGS_ENCRYPTION_KEY");if(!key)throw new Error("Entegrasyon şifreleme anahtarı eksik.");secret=await decryptSecret(source.secret_ciphertext,key)}const headers:Record<string,string>={accept:"application/json","user-agent":"Fornost-GRC-Evidence-Collector/1.0"};if(cfg.authType==="bearer"&&secret)headers.authorization=`Bearer ${secret}`;else if(cfg.authType==="api-key"&&secret)headers[cfg.headerName||"x-api-key"]=secret;else if(cfg.authType==="basic"&&secret)headers.authorization=`Basic ${btoa(secret)}`;const response=await fetch(url,{method:"GET",headers,redirect:"error",signal:AbortSignal.timeout(12_000)});if(!response.ok)throw new Error(`Kaynak API yanıt vermedi (${response.status}).`);const type=response.headers.get("content-type")||"";if(!type.includes("json"))throw new Error("Kaynak JSON yanıtı döndürmedi.");const text=await response.text();if(text.length>1_000_000)throw new Error("API yanıtı 1 MB sınırını aşıyor.");const payload=JSON.parse(text);return keepPayload?payload:{ok:true}}
