export type DemoModule="Risk Assessment"|"BIA"|"Varlık Envanteri"|"Uyum"|"Tedarikçiler"|"Kontroller"|"Kanıtlar"|"Denetim Yönetimi";
export type DemoSeed=[string,DemoModule,Record<string,unknown>];

const units=["Bilgi Teknolojileri","Bilgi Güvenliği","Dijital Kanallar","Finans","İnsan Kaynakları","Operasyon","Hukuk ve Uyum","Satın Alma","Müşteri Hizmetleri","Lojistik","Kurumsal İletişim","Veri ve Analitik"];
const owners=["IAM Ekibi","SOC Ekibi","Uygulama Güvenliği","Altyapı Operasyon","Finansal Kontrol","İK Operasyon","Uyum Ekibi","Tedarikçi Yönetimi","İş Sürekliliği","Veri Platformu","Ağ Güvenliği","İç Denetim"];
const assets=["Microsoft Entra ID","E-Ticaret Platformu","SAP ERP","M365 Tenant","Müşteri Veri Ambarı","Cortex XDR","FortiGate Kümesi","Nessus Expert","Sentinel SIEM","Bordro SaaS","GitHub Enterprise","Yedekleme Platformu"];
const processes=["Kimlik ve Erişim Yönetimi","E-Ticaret Sipariş Yönetimi","Finansal Kapanış","Çalışan Yaşam Döngüsü","Güvenlik Olay Yönetimi","Tedarikçi Yönetimi","Zafiyet Yönetimi","Yedekleme ve Kurtarma","Müşteri Destek","Lojistik Operasyon","Yazılım Teslimatı","Regülasyon Raporlama"];
const refs=["A.5.15","A.5.16","A.5.23","A.5.24","A.5.30","A.8.7","A.8.8","A.8.13","A.8.15","A.8.16","CC6.1","CC7.2"];
const titles=["Erişim kontrolü","Kimlik yönetimi","Bulut hizmetleri güvenliği","Olay yönetimi","ICT süreklilik hazırlığı","Kötücül yazılım koruması","Zafiyet yönetimi","Bilgi yedekleme","Loglama","İzleme faaliyetleri","Mantıksal erişim","Güvenlik olaylarını izleme"];
const risks=["Ayrıcalıklı hesap suistimali","Kimlik avı ile hesap ele geçirilmesi","Kritik servis kesintisi","Hassas veri paylaşımı","Zafiyetlerin gecikmesi","Tedarikçi veri ihlali","Yedekten dönüş başarısızlığı","Güvenlik logu kaybı","Yetkisiz üretim değişikliği","Fidye yazılımı yayılımı","Kişisel verinin fazla saklanması","Denetim kanıtı eksikliği"];
const vendors=["Bulut Altyapı Sağlayıcısı","Bordro SaaS","MDR Hizmeti","E-İmza Servisi","Çağrı Merkezi","Kargo Entegrasyonu","Yazılım Firması","Yedekleme Hizmeti","Ödeme Servisi","İK Danışmanlığı","SMS Sağlayıcısı","Denetim Kuruluşu"];
const audits=["ISO 27001 Gözetim","SOC 2 Hazırlık","KVKK Uyum","İç Kontrol","Tedarikçi Güvence","PCI DSS Kapsam","İş Sürekliliği","Erişim Yetkileri","Zafiyet Yönetimi","Olay Yönetimi","Bulut Güvenliği","Yönetim Gözden Geçirme"];
const demoImages=["/demo-evidence/identity-access.svg","/demo-evidence/security-monitoring.svg","/demo-evidence/vulnerability-scan.svg","/demo-evidence/backup-restore.svg"];
const id=(p:string,i:number)=>`${p}-${String(i+1).padStart(3,"0")}`;
const date=(m:number,d:number)=>`2026-${String(m).padStart(2,"0")}-${String(d).padStart(2,"0")}`;

export const demoSeeds:DemoSeed[]=[
 ...processes.map((process,i):DemoSeed=>[id("BIA",i),"BIA",{process,businessUnit:units[(i+2)%12],owner:owners[(i+8)%12],criticality:["Kritik","Yüksek","Orta"][i%3],rto:[2,4,8,12,24,48][i%6],rpo:[1,2,4,8,12,24][i%6],mtpd:[4,8,12,24,48,72][i%6],financial:1+i%5,operational:1+(i+2)%5,legal:1+(i+1)%5,reputation:1+(i+3)%5,customer:1+(i+4)%5,dataImpact:1+(i+2)%5,asset:assets[i],dependencies:"Kimlik, ağ ve kritik tedarikçi",manualWorkaround:i%3?"Kısıtlı manuel işlem":"Manuel alternatif yok",drStatus:["Hazır","Kısmi","Planlanıyor"][i%3],lastTestDate:date(2+i%5,10+i),testResult:["Başarılı","Kısmi Başarılı","Test Bekliyor"][i%3],nextTestDate:date(9+i%3,10+i)}]),
 ...assets.map((title,i):DemoSeed=>[id("AST",i),"Varlık Envanteri",{title,assetType:["Bulut Servisi","Uygulama","Veritabanı","Güvenlik Ürünü","Ağ Cihazı","SaaS"][i%6],businessUnit:units[i],owner:owners[(i+3)%12],technicalOwner:owners[(i+4)%12],criticality:["Kritik","Yüksek","Orta"][i%3],dataClassification:["Çok Gizli","Gizli","Şirket İçi","Genel"][i%4],environment:i%3?"Üretim":"Test",location:i%2?"Azure / Türkiye":"Şirket Veri Merkezi",ip:`demo-${i+1}.example.invalid`,internetFacing:i%3===0?"Evet":"Hayır",personalData:i%2===0?"Evet":"Hayır",criticalService:i%3!==2?"Evet":"Hayır",eolDate:date(11,10+i),backupStatus:["Kapsamda","Kısmi","Kapsam Dışı"][i%3],edrStatus:["Kapsamda","Uygulanamaz","Eksik"][i%3],siemStatus:["Kapsamda","Kısmi","Eksik"][i%3],vulnScan:["Aylık","Haftalık","Kapsam Dışı"][i%3],status:["Aktif","Aktif","İyileştirme Gerekli"][i%3]}]),
 ...risks.map((title,i):DemoSeed=>[id("RSK",i),"Risk Assessment",{title,businessUnit:units[i],owner:owners[i],ownerEmail:`demo-owner-${i+1}@example.invalid`,asset:assets[i],processLink:id("BIA",i),category:["IAM","Siber Güvenlik","İş Sürekliliği","Veri Koruma","Uyum","Tedarikçi"][i%6],threat:["Yetki suistimali","Sosyal mühendislik","Teknik arıza","Hatalı konfigürasyon"][i%4],event:title,consequence:"Hizmet, veri, finans veya uyum hedeflerinde olumsuz etki",inherentLikelihood:1+i%5,inherentImpact:1+(i+2)%5,existingControls:id("CTL",i),treatment:["Azalt","Kabul Et","Kaçın","Transfer Et"][i%4],plannedAction:"Kontrolü doğrula ve iyileştirmeyi tamamla",actionOwner:owners[(i+1)%12],targetDate:date(10+i%3,5+i),status:["Açık","Devam Ediyor","İzlemede","Kabul Edildi"][i%4],lastReview:date(7,1+i),nextReview:date(10+i%3,1+i)}]),
 ...refs.map((standardRef,i):DemoSeed=>[id("CTL",i),"Kontroller",{controlRef:id("CTL",i),standardRef,controlTitle:titles[i],owner:owners[i],frequency:["Sürekli","Günlük","Haftalık","Aylık","Üç Aylık","Yıllık"][i%6],frameworks:i<10?"ISO/IEC 27001:2022":"SOC 2",implementation:["Uygulanıyor","Kısmi","Planlandı"][i%3],lastTestDate:date(6+i%3,2+i),testResult:["Etkili","Kısmen Etkili","Test Bekliyor"][i%3],status:["Aktif","İyileştirme Gerekli","Taslak"][i%3]}]),
 ...refs.map((controlRef,i):DemoSeed=>[id("CMP",i),"Uyum",{framework:i<10?"ISO/IEC 27001:2022":"SOC 2 Type II",controlRef,controlTitle:titles[i],owner:owners[(i+6)%12],implementation:["Uygulanıyor","Kısmi","Uygulanmıyor","Uygulanamaz"][i%4],status:["Uyumlu","Kısmi","Uyumsuz","Uygulanamaz"][i%4],controlLink:id("CTL",i),evidenceRef:id("EVD",i),notes:"Kurgusal demo değerlendirmesi"}]),
 ...vendors.map((title,i):DemoSeed=>[id("VEN",i),"Tedarikçiler",{title,vendorType:["SaaS","Managed Service","Profesyonel Hizmet","Kritik Altyapı"][i%4],service:processes[(i+3)%12],owner:owners[i],criticality:["Kritik","Yüksek","Orta"][i%3],riskLevel:["Yüksek","Orta","Düşük"][i%3],contractEnd:date(12,10+i),contact:`demo-vendor-${i+1}@example.invalid`,status:["Aktif","İncelemede","İyileştirme Gerekli"][i%3],riskRef:id("RSK",i),controlRef:id("CTL",i)}]),
 ...refs.map((_,i):DemoSeed=>[id("EVD",i),"Kanıtlar",{evidenceTitle:`${titles[i]} - 2026 doğrulama kanıtı`,controlRef:id("CTL",i),owner:owners[i],period:["2026 Q1","2026 Q2","2026 Q3","2026 Yıllık"][i%4],frameworks:i<10?"ISO/IEC 27001:2022":"SOC 2",status:["Güncel","İncelemede","Süresi Yaklaşıyor"][i%3],evidenceType:"Ekran Görüntüsü",demoImage:demoImages[i%demoImages.length],fileName:`nexora-demo-evidence-${i+1}.svg`,fileType:"image/svg+xml",source:"Kurgusal demo kaynağı",notes:"Gerçek dosya veya şirket verisi içermez"}]),
 ...refs.map((requirementRef,i):DemoSeed=>[id("AUD",i),"Denetim Yönetimi",{auditName:audits[i],auditType:["Dış Denetim","İç Denetim","Öz Değerlendirme"][i%3],auditor:i%3===0?"Bağımsız Demo Denetçi":"İç Denetim",auditOwner:"Bilgi Güvenliği",startDate:date(9+i%3,1+i),endDate:date(9+i%3,10+i),requirementRef,requirementTitle:titles[i],owner:owners[i],businessUnit:units[i],dueDate:date(9+i%3,8+i),status:["Planlandı","Devam Ediyor","Tamamlandı","Gecikmiş"][i%4],progress:[0,25,50,75,100][i%5],evidenceStatus:["Kanıt Bekleniyor","İncelemede","Kabul Edildi"][i%3],controlRef:id("CTL",i),riskRef:id("RSK",i),evidenceRef:id("EVD",i),finding:i%4===3?"İyileştirme gerekli":"Bulgu yok / inceleme sürüyor"}]),
];
