import asvsCatalog from "./catalog-data/owasp-asvs.json";
import { nistRequirementCatalogs } from "./nist-catalogs";
import { nistCsf2Requirements } from "./nist-csf2-catalog";
export type FrameworkRequirement = { ref: string; title: string; category: string; owner?: string; statement?: string; guidance?: string; assessment?: string; parentRef?: string };

const rows = (category: string, owner: string, values: Array<[string, string]>): FrameworkRequirement[] =>
  values.map(([ref, title]) => ({ ref, title, category, owner }));

// Requirement-level overview only: no synthetic subrequirement numbers.
export const pciDssRequirements = rows("PCI DSS — ana gereksinimler", "Bilgi Güvenliği", [
["1","Ağ güvenliği kontrollerinin kurulması ve sürdürülmesi"],["2","Güvenli yapılandırmalar"],["3","Saklanan hesap verisinin korunması"],["4","Açık ağlarda aktarımın güçlü kriptografiyle korunması"],["5","Kötü amaçlı yazılımlara karşı koruma"],["6","Güvenli sistem ve yazılımların geliştirilmesi ve sürdürülmesi"],["7","İş ihtiyacına göre erişimin kısıtlanması"],["8","Kullanıcı kimliği ve erişimin doğrulanması"],["9","Fiziksel erişimin kısıtlanması"],["10","Erişimin kaydedilmesi ve izlenmesi"],["11","Güvenliğin düzenli test edilmesi"],["12","Kurumsal politika ve programla bilgi güvenliğinin desteklenmesi"]
]);

export const frameworkTemplateCatalogs: Record<string, FrameworkRequirement[]> = {
  ...nistRequirementCatalogs,
  [asvsCatalog.name]: asvsCatalog.requirements,
  "PCI DSS 4.0.1": pciDssRequirements,
  "NIST Cybersecurity Framework (CSF) 2.0": nistCsf2Requirements,
  "CIS Controls v8.1": rows("CIS Controls", "Siber Güvenlik", [
    ["CIS-1","Kurumsal varlıkların envanteri ve kontrolü"],["CIS-2","Yazılım varlıklarının envanteri ve kontrolü"],["CIS-3","Veri koruma"],["CIS-4","Kurumsal varlık ve yazılımların güvenli yapılandırılması"],["CIS-5","Hesap yönetimi"],["CIS-6","Erişim kontrolü yönetimi"],["CIS-7","Sürekli zafiyet yönetimi"],["CIS-8","Denetim kayıtlarının yönetimi"],["CIS-9","E-posta ve web tarayıcı korumaları"],["CIS-10","Kötü amaçlı yazılım savunmaları"],["CIS-11","Veri kurtarma"],["CIS-12","Ağ altyapısı yönetimi"],["CIS-13","Ağ izleme ve savunma"],["CIS-14","Güvenlik farkındalığı ve beceri eğitimi"],["CIS-15","Hizmet sağlayıcı yönetimi"],["CIS-16","Uygulama yazılımı güvenliği"],["CIS-17","Olay müdahale yönetimi"],["CIS-18","Sızma testi"],
  ]),
  "ISO 22301:2019": rows("İş Sürekliliği Yönetim Sistemi", "İş Sürekliliği", [["4","Kuruluşun bağlamı"],["5","Liderlik"],["6","Planlama"],["7","Destek"],["8.1","Operasyonel planlama ve kontrol"],["8.2","İş etki analizi ve risk değerlendirmesi"],["8.3","İş sürekliliği stratejileri ve çözümleri"],["8.4","İş sürekliliği planları ve prosedürleri"],["8.5","Tatbikat programı"],["8.6","Dokümantasyon ve yetenek değerlendirmesi"],["9","Performans değerlendirmesi"],["10","İyileştirme"]]),
  "ISO/IEC 27701:2019": rows("Gizlilik Bilgi Yönetimi", "Veri Koruma", [["5","PIMS’e özgü BGYS gereksinimleri"],["6","PIMS’e özgü bilgi güvenliği kontrolleri"],["7.2","Kişisel veri sorumlusu koşulları"],["7.3","İlgili kişi yükümlülükleri"],["7.4","Privacy by design ve varsayılan gizlilik"],["7.5","Kişisel veri paylaşımı, aktarımı ve açıklanması"],["8.2","Veri işleyen koşulları"],["8.3","Müşteri talimatları ve yükümlülükler"],["8.4","Kişisel veri paylaşımı, aktarımı ve açıklanması"]]),
  "ISO/IEC 27017:2015": rows("Bulut Güvenliği", "Bulut Güvenliği", [["CLD.1","Bulut sorumluluklarının paylaşımı"],["CLD.2","Bulut hizmeti müşteri varlıklarının kaldırılması"],["CLD.3","Sanal ortamların ayrılması"],["CLD.4","Sanal makinelerin güçlendirilmesi"],["CLD.5","Bulut yönetim operasyonları"],["CLD.6","Bulut faaliyetlerinin izlenmesi"],["CLD.7","Sanal ve bulut ağlarının uyumu"]]),
  "ISO/IEC 27018:2019": rows("Bulutta Kişisel Veri", "Veri Koruma", [["PII.1","Amaç ve rıza yönetimi"],["PII.2","Kişisel veri minimizasyonu"],["PII.3","İlgili kişi hakları"],["PII.4","Geçici dosyaların güvenli silinmesi"],["PII.5","Kişisel verinin iadesi, aktarımı ve imhası"],["PII.6","Açıklama ve alt işleyen yönetimi"],["PII.7","Veri ihlali bildirimi"],["PII.8","İşleme lokasyonu ve sınır ötesi aktarım"],["PII.9","Müşteri denetimi ve şeffaflık"]]),
  "ISO/IEC 27701:2025": rows("Yerel hazırlık konuları — normatif madde değildir", "Veri Koruma", [["LOCAL-PIMS-01","Gizlilik yönetim sistemi kapsamını ve sorumluluklarını belirle"],["LOCAL-PIMS-02","Veri sorumlusu ve veri işleyen faaliyetlerini değerlendir"],["LOCAL-PIMS-03","Lisanslı 2025 metniyle gereksinim eşlemesini tamamla"]]),
  "ISO/IEC 27017:2026": rows("Yerel hazırlık konuları — normatif madde değildir", "Bulut Güvenliği", [["LOCAL-CLOUD-01","Bulut hizmeti kapsamını ve paylaşılan sorumlulukları belirle"],["LOCAL-CLOUD-02","Lisanslı 2026 metniyle kontrol eşlemesini tamamla"]]),
  "ISO/IEC 27018:2025": rows("Yerel hazırlık konuları — normatif madde değildir", "Veri Koruma", [["LOCAL-PII-01","Bulutta kişisel veri işleme kapsamını belirle"],["LOCAL-PII-02","Lisanslı 2025 metniyle kontrol eşlemesini tamamla"]]),
  "COBIT 2019": [
    ...rows("Evaluate, Direct and Monitor", "Üst Yönetim", [["EDM01","Yönetişim çerçevesi"],["EDM02","Fayda teslimi"],["EDM03","Risk optimizasyonu"],["EDM04","Kaynak optimizasyonu"],["EDM05","Paydaş katılımı"]]),
    ...rows("Align, Plan and Organize", "BT Yönetimi", Array.from({length:14},(_,i)=>[`APO${String(i+1).padStart(2,"0")}`,`APO${String(i+1).padStart(2,"0")} yönetim hedefi`] as [string,string])),
    ...rows("Build, Acquire and Implement", "BT Yönetimi", Array.from({length:11},(_,i)=>[`BAI${String(i+1).padStart(2,"0")}`,`BAI${String(i+1).padStart(2,"0")} yönetim hedefi`] as [string,string])),
    ...rows("Deliver, Service and Support", "BT Operasyon", Array.from({length:6},(_,i)=>[`DSS${String(i+1).padStart(2,"0")}`,`DSS${String(i+1).padStart(2,"0")} yönetim hedefi`] as [string,string])),
    ...rows("Monitor, Evaluate and Assess", "İç Denetim", Array.from({length:4},(_,i)=>[`MEA${String(i+1).padStart(2,"0")}`,`MEA${String(i+1).padStart(2,"0")} yönetim hedefi`] as [string,string])),
  ],
  "DORA (EU 2022/2554)": rows("Dijital Operasyonel Dayanıklılık", "Bilgi Güvenliği", [["Art.5-6","Yönetişim ve ICT risk yönetim çerçevesi"],["Art.7-9","ICT sistemleri, protokoller, araçlar ve koruma"],["Art.10-11","Tespit ve müdahale"],["Art.12","Yedekleme, geri yükleme ve kurtarma"],["Art.13-14","Öğrenme, gelişim ve iletişim"],["Art.15-16","Uyumlaştırılmış standartlar ve basitleştirilmiş çerçeve"],["Art.17-23","ICT olay yönetimi, sınıflandırma ve raporlama"],["Art.24-27","Dijital operasyonel dayanıklılık testleri"],["Art.28-30","ICT üçüncü taraf risk yönetimi ve sözleşmeler"],["Art.31-44","Kritik ICT sağlayıcılarının gözetimi"],["Art.45","Bilgi ve istihbarat paylaşımı"]]),
  "NIS2 (EU 2022/2555)": rows("NIS2", "Bilgi Güvenliği", [["Art.20","Yönetim organlarının sorumluluğu"],["Art.21.1","Risk yönetimi yaklaşımı"],["Art.21.2.a","Risk analizi ve bilgi sistemi güvenliği politikaları"],["Art.21.2.b","Olay yönetimi"],["Art.21.2.c","İş sürekliliği, yedekleme ve kriz yönetimi"],["Art.21.2.d","Tedarik zinciri güvenliği"],["Art.21.2.e","Sistem edinme, geliştirme, bakım ve zafiyet yönetimi"],["Art.21.2.f","Kontrollerin etkinliğini değerlendirme"],["Art.21.2.g","Siber hijyen ve eğitim"],["Art.21.2.h","Kriptografi politikaları"],["Art.21.2.i","İnsan kaynakları, erişim ve varlık yönetimi"],["Art.21.2.j","MFA ve güvenli iletişim"],["Art.23","Önemli olayların bildirimi"],["Art.27-28","Kayıtlar ve alan adı verileri"],["Art.29-30","Siber güvenlik bilgi paylaşımı"]]),
  "KVKK (6698)": rows("Kişisel Verilerin Korunması", "KVKK / Hukuk", [["Md.4","Genel ilkeler"],["Md.5","Kişisel veri işleme şartları"],["Md.6","Özel nitelikli kişisel veriler"],["Md.7","Silme, yok etme veya anonimleştirme"],["Md.8","Kişisel verilerin aktarılması"],["Md.9","Yurt dışına aktarım: yeterlilik, uygun güvenceler ve istisnai aktarım şartları"],["Md.9/5","Standart sözleşmenin imzadan itibaren beş iş günü içinde Kuruma bildirilmesi"],["Md.10","Aydınlatma yükümlülüğü"],["Md.11","İlgili kişinin hakları"],["Md.12","Veri güvenliği yükümlülükleri"],["Md.13","Veri sorumlusuna başvuru"],["Md.16","VERBİS yükümlülükleri"],["LOCAL-KVKK-01","Saklama ve imha politikası"],["LOCAL-KVKK-02","Kişisel veri ihlali bildirimi"],["LOCAL-KVKK-03","Teknik ve idari tedbirlerin takibi"]]),
  "GDPR (EU 2016/679)": rows("GDPR", "Privacy / Hukuk", [["Art.5","Kişisel veri işleme ilkeleri"],["Art.6","İşlemenin hukuka uygunluğu"],["Art.7-8","Rıza koşulları ve çocukların verisi"],["Art.9-10","Özel nitelikli veri ve mahkûmiyet verisi"],["Art.12-14","Şeffaflık ve bilgilendirme"],["Art.15-22","İlgili kişi hakları"],["Art.24","Veri sorumlusunun sorumluluğu"],["Art.25","Privacy by design ve varsayılan gizlilik"],["Art.26-28","Ortak sorumluluk ve veri işleyen yönetimi"],["Art.30","İşleme faaliyetleri kayıtları"],["Art.32","İşleme güvenliği"],["Art.33-34","Veri ihlali bildirimi"],["Art.35-36","DPIA ve ön danışma"],["Art.37-39","Veri koruma görevlisi"],["Art.44-49","Uluslararası veri aktarımları"],["Art.50","Uluslararası iş birliği"],["Art.83","İdari para cezaları"]]),
};

export { automaticAuditTemplates } from "../../framework-templates";
