// Generated from the consultant-authored ODINE_SOC2_TypeII_Detayli_Mapping.xlsx.
// Preserve the original wording; publish updates as a new template version.
export type Soc2TemplateControl = {
  tscId: string;
  tscCategory: string;
  expectation: string;
  exampleControls: string;
  performingControls: string;
  controlOwner: string;
  frequency: string;
  controlType: string;
  nature: string;
  isoAnnex: string;
  isoControlTitles: string;
  isoClauses: string;
  iso22301: string;
  expectedEvidence: string;
  typeIITestApproach: string;
  currentDocuments: string;
  gapNote: string;
  requiredAction: string;
  consultantStatus: string;
  source: string;
};

export const soc2TemplateMeta = {
  "id": "soc2-odine-v1",
  "name": "SOC 2 Type II – ODINE Mapping v1",
  "framework": "SOC 2 Type II",
  "auditName": "SOC 2 Type II – 2026",
  "startDate": "2026-01-01",
  "endDate": "2026-12-31",
  "scope": [
    "Security",
    "Availability",
    "Confidentiality"
  ],
  "phaseTwo": [
    "Processing Integrity",
    "Privacy"
  ],
  "sourceFile": "ODINE_SOC2_TypeII_Detayli_Mapping.xlsx",
  "authoringBasis": "GRC danışmanı tarafından hazırlanan uzman başlangıç değerlendirmesi"
} as const;

export const soc2TemplateControls: Soc2TemplateControl[] = [
  {
    "tscId": "CC1.1",
    "tscCategory": "Security / Control Environment",
    "expectation": "Etik değerler ve dürüstlük kültürü oluşturulur ve sürdürülür.",
    "exampleControls": "Etik kurallar, davranış ilkeleri ve bilgi güvenliği politikaları yönetimce onaylanır; çalışanlara duyurulur.",
    "performingControls": "1) Etik ve bilgi güvenliği politikaları yönetim onayı ile yayımlanır. 2) İşe girişte politika kabulü alınır. 3) Yıllık farkındalık eğitimi tamamlanır. 4) İhlaller disiplin ve olay yönetimi süreçleriyle ele alınır.",
    "controlOwner": "Üst Yönetim / HR / BGYS",
    "frequency": "Yıllık + işe girişte",
    "controlType": "Preventive / Detective",
    "nature": "Manual / IT-dependent Manual",
    "isoAnnex": "A.5.1; A.6.3; A.6.4",
    "isoControlTitles": "Bilgi güvenliği politikaları; Bilgi güvenliği farkındalığı, eğitim ve öğretim; Disiplin süreci",
    "isoClauses": "5.2; 5.3; 7.2; 7.3; 7.5",
    "iso22301": "5.2; 5.3; 7.2; 7.3",
    "expectedEvidence": "Politika onay kayıtları, eğitim katılım kayıtları, çalışan kabul kayıtları, disiplin kayıtları",
    "typeIITestApproach": "Dönem boyunca politika versiyonları ve örnek çalışan eğitim/kabul kayıtları örneklenir.",
    "currentDocuments": "Bilgi Güvenliği Politikası; Eğitim Kayıtları",
    "gapNote": "",
    "requiredAction": "Yıllık kabul/eğitim kanıtlarının merkezi saklanması",
    "consultantStatus": "Uygun",
    "source": "https://www.aicpa-cima.com/resources/download/2017-trust-services-criteria-with-revised-points-of-focus-2022"
  },
  {
    "tscId": "CC1.2",
    "tscCategory": "Security / Control Environment",
    "expectation": "Yönetimden bağımsız gözetim ve kontrol sorumluluğu tesis edilir.",
    "exampleControls": "Yönetim, BGYS/SOC 2 kontrol ortamını düzenli gözden geçirir; iç denetim sonuçları bağımsız biçimde raporlanır.",
    "performingControls": "1) YGG ve iç denetim planlı yürütülür. 2) Bulgular üst yönetime raporlanır. 3) Düzeltici faaliyetlerin kapanışı izlenir. 4) SOC 2 kontrol sahipleri ve sorumlulukları atanır.",
    "controlOwner": "Üst Yönetim / BGYS",
    "frequency": "En az yıllık + olay bazlı",
    "controlType": "Detective / Corrective",
    "nature": "Manual",
    "isoAnnex": "A.5.35; A.5.36",
    "isoControlTitles": "Bilgi güvenliğinin bağımsız gözden geçirilmesi; Politika/kurallara uygunluk",
    "isoClauses": "5.1; 5.3; 9.2; 9.3; 10.1",
    "iso22301": "5.1; 5.3; 9.2; 9.3; 10.1",
    "expectedEvidence": "YGG tutanakları, iç denetim raporları, DÖF kayıtları, görev atamaları",
    "typeIITestApproach": "Denetim dönemi içindeki YGG, iç denetim ve bulgu kapatma örnekleri test edilir.",
    "currentDocuments": "YGG; İç Denetim Prosedürü",
    "gapNote": "",
    "requiredAction": "SOC 2 kontrol sahipliği matrisi oluşturulmalı",
    "consultantStatus": "Kısmi",
    "source": "https://www.aicpa-cima.com/resources/download/2017-trust-services-criteria-with-revised-points-of-focus-2022"
  },
  {
    "tscId": "CC1.3",
    "tscCategory": "Security / Control Environment",
    "expectation": "Yetki, raporlama hattı ve organizasyon yapısı kontrol hedeflerini destekler.",
    "exampleControls": "Organizasyon şeması, görev tanımları ve kritik güvenlik rollerinin sorumlulukları dokümante edilir.",
    "performingControls": "1) Organizasyon şeması güncel tutulur. 2) BT, güvenlik, yazılım ve operasyon rolleri için görev tanımları vardır. 3) Yetki çatışmaları görevler ayrılığı ile yönetilir.",
    "controlOwner": "HR / BGYS / IT",
    "frequency": "Yıllık + değişiklikte",
    "controlType": "Preventive",
    "nature": "Manual",
    "isoAnnex": "A.5.2; A.5.3; A.5.4",
    "isoControlTitles": "Bilgi güvenliği rolleri ve sorumlulukları; Görevlerin ayrılığı; Yönetim sorumlulukları",
    "isoClauses": "5.3; 7.1; 7.2",
    "iso22301": "5.3; 7.1; 7.2",
    "expectedEvidence": "Organizasyon şeması, görev tanımları, atama yazıları, SoD matrisi",
    "typeIITestApproach": "Dönem içindeki organizasyon değişiklikleri ve rol atamaları örneklenir.",
    "currentDocuments": "Organizasyon Şeması; Görev Tanımları",
    "gapNote": "",
    "requiredAction": "SOC 2 kritik rol/SoD matrisi teyit edilmeli",
    "consultantStatus": "Kısmi",
    "source": "https://www.aicpa-cima.com/resources/download/2017-trust-services-criteria-with-revised-points-of-focus-2022"
  },
  {
    "tscId": "CC1.4",
    "tscCategory": "Security / Control Environment",
    "expectation": "Yetkin personel çekilir, geliştirilir ve elde tutulur.",
    "exampleControls": "İşe alım, yetkinlik, eğitim ve performans süreçleri güvenlik sorumluluklarını destekler.",
    "performingControls": "1) Pozisyon yetkinlikleri tanımlıdır. 2) Kritik roller için eğitim planlanır. 3) Farkındalık ve teknik eğitimler kayıt altına alınır. 4) Performans değerlendirmelerinde görev gereklilikleri izlenir.",
    "controlOwner": "HR / Bölüm Yöneticileri",
    "frequency": "Yıllık + işe girişte",
    "controlType": "Preventive",
    "nature": "Manual",
    "isoAnnex": "A.6.1; A.6.3",
    "isoControlTitles": "Eleme; Bilgi güvenliği farkındalığı, eğitim ve öğretim",
    "isoClauses": "7.2; 7.3",
    "iso22301": "7.2; 7.3",
    "expectedEvidence": "İşe alım kontrolleri, CV/yetkinlik kayıtları, eğitim planı ve katılım kayıtları",
    "typeIITestApproach": "Yeni işe alınan ve mevcut personelden örneklem seçilerek yetkinlik/eğitim kanıtları incelenir.",
    "currentDocuments": "Eğitim Prosedürü; HR kayıtları",
    "gapNote": "",
    "requiredAction": "Kritik SOC 2 rollerine özel yetkinlik matrisi eklenmeli",
    "consultantStatus": "Kısmi",
    "source": "https://www.aicpa-cima.com/resources/download/2017-trust-services-criteria-with-revised-points-of-focus-2022"
  },
  {
    "tscId": "CC1.5",
    "tscCategory": "Security / Control Environment",
    "expectation": "Kontrol sorumlulukları için hesap verebilirlik sağlanır.",
    "exampleControls": "KPI, görev tanımı, kontrol sahipliği ve uygunsuzluk yönetimi ile sorumluluklar izlenir.",
    "performingControls": "Kontrol sahipleri tanımlanır; geciken kontroller, bulgular ve risk aksiyonları raporlanır; gerektiğinde düzeltici faaliyet başlatılır.",
    "controlOwner": "Üst Yönetim / BGYS / Kontrol Sahipleri",
    "frequency": "Aylık/Çeyreklik",
    "controlType": "Detective / Corrective",
    "nature": "Manual",
    "isoAnnex": "A.5.2; A.5.36",
    "isoControlTitles": "Bilgi güvenliği rolleri ve sorumlulukları; Uygunluk",
    "isoClauses": "5.3; 9.1; 10.1",
    "iso22301": "5.3; 9.1; 10.1",
    "expectedEvidence": "Kontrol matrisi, KPI raporları, aksiyon listeleri, DÖF kayıtları",
    "typeIITestApproach": "Kontrol frekansına göre örneklem alınarak zamanında icra ve takip kanıtı incelenir.",
    "currentDocuments": "Risk/YGG/DÖF kayıtları",
    "gapNote": "",
    "requiredAction": "Kontrol sahipliği ve evidence owner alanları netleştirilmeli",
    "consultantStatus": "Kısmi",
    "source": "https://www.aicpa-cima.com/resources/download/2017-trust-services-criteria-with-revised-points-of-focus-2022"
  },
  {
    "tscId": "CC2.1",
    "tscCategory": "Security / Communication",
    "expectation": "Kontrollerin işleyişini destekleyen kaliteli bilgi elde edilir ve kullanılır.",
    "exampleControls": "Varlık, risk, olay, değişiklik ve performans verileri güvenilir kaynaklardan toplanır.",
    "performingControls": "Varlık envanteri, risk kayıtları, SIEM/log, ticket, EDR ve izleme sistemlerinden kontrol verisi üretilir; kayıtların bütünlüğü ve erişimi yönetilir.",
    "controlOwner": "BGYS / IT / NOC",
    "frequency": "Sürekli + periyodik gözden geçirme",
    "controlType": "Preventive / Detective",
    "nature": "Automated / IT-dependent Manual",
    "isoAnnex": "A.5.9; A.5.33; A.8.15; A.8.16",
    "isoControlTitles": "Varlık envanteri; Kayıtların korunması; Loglama; İzleme faaliyetleri",
    "isoClauses": "7.5; 9.1",
    "iso22301": "7.5; 9.1",
    "expectedEvidence": "Varlık envanteri, SIEM/log çıktıları, ticket kayıtları, KPI raporları",
    "typeIITestApproach": "Dönem boyunca veri kaynaklarının çalıştığı ve kayıtların saklandığı örneklenir.",
    "currentDocuments": "Varlık Envanteri; Log Yönetimi",
    "gapNote": "",
    "requiredAction": "Kanıt kaynakları/evidence repository standardize edilmeli",
    "consultantStatus": "Kısmi",
    "source": "https://www.aicpa-cima.com/resources/download/2017-trust-services-criteria-with-revised-points-of-focus-2022"
  },
  {
    "tscId": "CC2.2",
    "tscCategory": "Security / Communication",
    "expectation": "İç iletişim, kontrol sorumluluklarının anlaşılmasını sağlar.",
    "exampleControls": "Politikalar, olay eskalasyonu, değişiklikler ve güvenlik duyuruları uygun personele iletilir.",
    "performingControls": "Politika ve prosedürler merkezi platformda yayımlanır; güvenlik duyuruları/eğitimler yapılır; olay ve değişiklik eskalasyon kanalları tanımlıdır.",
    "controlOwner": "BGYS / HR / IT",
    "frequency": "Sürekli / gerektiğinde",
    "controlType": "Preventive",
    "nature": "Manual / IT-dependent Manual",
    "isoAnnex": "A.5.1; A.5.24; A.6.3",
    "isoControlTitles": "Politikalar; Bilgi güvenliği olay yönetimi planlama/hazırlık; Farkındalık",
    "isoClauses": "7.3; 7.4; 7.5",
    "iso22301": "7.3; 7.4; 7.5",
    "expectedEvidence": "Duyurular, politika yayın kayıtları, eğitim kayıtları, eskalasyon listeleri",
    "typeIITestApproach": "Dönemden örnek duyuru/değişiklik/olay seçilerek ilgili taraflara iletişim doğrulanır.",
    "currentDocuments": "İletişim kayıtları; Olay Prosedürü",
    "gapNote": "",
    "requiredAction": "SOC 2 kapsamındaki iletişim kanalları matrisi hazırlanmalı",
    "consultantStatus": "Kısmi",
    "source": "https://www.aicpa-cima.com/resources/download/2017-trust-services-criteria-with-revised-points-of-focus-2022"
  },
  {
    "tscId": "CC2.3",
    "tscCategory": "Security / Communication",
    "expectation": "Dış taraflarla kontrol hedeflerini destekleyen iletişim yürütülür.",
    "exampleControls": "Müşteri, tedarikçi, düzenleyici ve diğer ilgili taraflarla güvenlik/SLA/olay iletişimi yönetilir.",
    "performingControls": "Sözleşme ve SLA gereklilikleri kayıt altındadır; müşteri güvenlik bildirimleri ve tedarikçi iletişimleri yetkili kanallardan yürütülür.",
    "controlOwner": "Satış / Hukuk / BGYS / Operasyon",
    "frequency": "Sözleşme/olay bazlı",
    "controlType": "Preventive / Detective",
    "nature": "Manual",
    "isoAnnex": "A.5.19; A.5.20; A.5.31; A.5.5",
    "isoControlTitles": "Tedarikçi ilişkileri; Tedarikçi anlaşmalarında güvenlik; Yasal/sözleşmesel gereklilikler; Otoritelerle temas",
    "isoClauses": "4.2; 7.4; 8.1",
    "iso22301": "4.2; 7.4; 8.1",
    "expectedEvidence": "SLA, sözleşmeler, müşteri bildirimleri, tedarikçi güvenlik şartları",
    "typeIITestApproach": "Sözleşme ve olay örnekleri üzerinden taahhütlerin iletişimi ve uygulanması incelenir.",
    "currentDocuments": "SLA/Sözleşmeler",
    "gapNote": "",
    "requiredAction": "Müşteri güvenlik taahhütleri envanteri oluşturulmalı",
    "consultantStatus": "Kısmi",
    "source": "https://www.aicpa-cima.com/resources/download/2017-trust-services-criteria-with-revised-points-of-focus-2022"
  },
  {
    "tscId": "CC3.1",
    "tscCategory": "Security / Risk Assessment",
    "expectation": "Kontrol hedeflerini destekleyecek uygun ve ölçülebilir hedefler tanımlanır.",
    "exampleControls": "Güvenlik, hizmet, erişilebilirlik ve uyum hedefleri politika/SLA/risk kriterleriyle belirlenir.",
    "performingControls": "SOC 2 kapsam hedefleri; bilgi güvenliği hedefleri, SLA'lar, RTO/RPO ve risk kabul kriterleri ile ilişkilendirilir.",
    "controlOwner": "Üst Yönetim / BGYS / Operasyon",
    "frequency": "Yıllık + değişiklikte",
    "controlType": "Preventive",
    "nature": "Manual",
    "isoAnnex": "A.5.1; A.5.31",
    "isoControlTitles": "Politikalar; Yasal/sözleşmesel gereklilikler",
    "isoClauses": "6.2; 9.1",
    "iso22301": "6.2; 6.3; 8.2",
    "expectedEvidence": "BGYS hedefleri, SLA, RTO/RPO, risk kriterleri",
    "typeIITestApproach": "Hedeflerin dönem başında tanımlı ve izlenebilir olduğu; sonuçların ölçüldüğü doğrulanır.",
    "currentDocuments": "Hedefler; SLA; BIA",
    "gapNote": "",
    "requiredAction": "SOC 2 TSC hedefleri ile mevcut KPI'lar eşleştirilmeli",
    "consultantStatus": "Kısmi",
    "source": "https://www.aicpa-cima.com/resources/download/2017-trust-services-criteria-with-revised-points-of-focus-2022"
  },
  {
    "tscId": "CC3.2",
    "tscCategory": "Security / Risk Assessment",
    "expectation": "Hedeflere yönelik riskler tanımlanır ve analiz edilir.",
    "exampleControls": "Kurumsal ve bilgi güvenliği risk değerlendirmesi düzenli yürütülür.",
    "performingControls": "Risk değerlendirmesi en az yıllık ve önemli değişikliklerde güncellenir; iç/dış tehditler, tedarikçi, bulut, yazılım, erişim ve süreklilik riskleri değerlendirilir.",
    "controlOwner": "BGYS / Risk Sahipleri",
    "frequency": "Yıllık + önemli değişiklikte",
    "controlType": "Preventive / Detective",
    "nature": "Manual",
    "isoAnnex": "A.5.7; A.5.9; A.5.19; A.8.8",
    "isoControlTitles": "Tehdit istihbaratı; Varlık envanteri; Tedarikçi güvenliği; Teknik açıklıkların yönetimi",
    "isoClauses": "6.1.2; 8.2",
    "iso22301": "6.1; 8.2",
    "expectedEvidence": "Risk metodolojisi, risk register, risk işleme planı, onaylar",
    "typeIITestApproach": "Denetim dönemi risk değerlendirmesi ve seçilen risklerin aksiyonları test edilir.",
    "currentDocuments": "Risk Yönetimi Prosedürü; Risk Analizi",
    "gapNote": "",
    "requiredAction": "SOC 2 kontrol hedefleri risk register ile ilişkilendirilmeli",
    "consultantStatus": "Kısmi",
    "source": "https://www.aicpa-cima.com/resources/download/2017-trust-services-criteria-with-revised-points-of-focus-2022"
  },
  {
    "tscId": "CC3.3",
    "tscCategory": "Security / Risk Assessment",
    "expectation": "Hile/fraud riski risk değerlendirmesinde dikkate alınır.",
    "exampleControls": "Yetki kötüye kullanımı, ayrıcalıklı hesaplar, sahte talep, kayıt manipülasyonu ve çıkar çatışması değerlendirilir.",
    "performingControls": "SoD, PAM, onay akışları, loglama ve erişim gözden geçirmeleri ile fraud/insider riskleri kontrol edilir.",
    "controlOwner": "BGYS / IT / HR / Finans",
    "frequency": "Yıllık + olay bazlı",
    "controlType": "Preventive / Detective",
    "nature": "Manual / Automated",
    "isoAnnex": "A.5.3; A.5.18; A.8.2; A.8.15",
    "isoControlTitles": "Görevlerin ayrılığı; Erişim hakları; Ayrıcalıklı erişim; Loglama",
    "isoClauses": "6.1.2; 8.2",
    "iso22301": "6.1",
    "expectedEvidence": "Fraud/insider risk kayıtları, PAM logları, SoD matrisi, erişim review",
    "typeIITestApproach": "Risk değerlendirmesinde fraud senaryoları ve ilgili kontrollerin dönemsel çalışması örneklenir.",
    "currentDocuments": "Risk Analizi; PAM kayıtları",
    "gapNote": "",
    "requiredAction": "Fraud/insider threat senaryoları açıkça eklenmeli",
    "consultantStatus": "Eksik",
    "source": "https://www.aicpa-cima.com/resources/download/2017-trust-services-criteria-with-revised-points-of-focus-2022"
  },
  {
    "tscId": "CC3.4",
    "tscCategory": "Security / Risk Assessment",
    "expectation": "Önemli değişikliklerin kontrol ortamına etkisi değerlendirilir.",
    "exampleControls": "Yeni ürün, altyapı, bulut, organizasyon, mevzuat ve tehdit değişiklikleri risk sürecine alınır.",
    "performingControls": "Change/ticket sistemi üzerinden önemli değişiklikler onaylanır; güvenlik etkisi ve gerekirse risk değerlendirmesi yapılır; politika/kontrol seti güncellenir.",
    "controlOwner": "IT / DevOps / BGYS",
    "frequency": "Her önemli değişiklikte",
    "controlType": "Preventive",
    "nature": "IT-dependent Manual",
    "isoAnnex": "A.5.8; A.8.32",
    "isoControlTitles": "Proje yönetiminde bilgi güvenliği; Değişiklik yönetimi",
    "isoClauses": "6.3; 8.1; 8.2",
    "iso22301": "6.3; 8.1",
    "expectedEvidence": "Change kayıtları, risk değerlendirmeleri, CAB/onay kayıtları",
    "typeIITestApproach": "Dönemden değişiklik örnekleri seçilerek güvenlik etkisi, test ve onay kanıtları incelenir.",
    "currentDocuments": "Değişiklik Yönetimi",
    "gapNote": "",
    "requiredAction": "Değişiklik formunda SOC 2/güvenlik etkisi alanı bulunmalı",
    "consultantStatus": "Kısmi",
    "source": "https://www.aicpa-cima.com/resources/download/2017-trust-services-criteria-with-revised-points-of-focus-2022"
  },
  {
    "tscId": "CC4.1",
    "tscCategory": "Security / Monitoring",
    "expectation": "Kontrollerin mevcut ve çalışır durumda olduğu sürekli/periyodik değerlendirmelerle izlenir.",
    "exampleControls": "İç denetim, güvenlik izleme, KPI ve kontrol öz değerlendirmeleri uygulanır.",
    "performingControls": "SIEM/EDR/monitoring sürekli çalışır; BGYS iç denetimi ve kontrol testleri periyodik yürütülür; bulgular kaydedilir.",
    "controlOwner": "BGYS / SOC-NOC / IT",
    "frequency": "Sürekli + yıllık/çeyreklik",
    "controlType": "Detective",
    "nature": "Automated / Manual",
    "isoAnnex": "A.5.35; A.5.36; A.8.16",
    "isoControlTitles": "Bağımsız gözden geçirme; Uygunluk; İzleme faaliyetleri",
    "isoClauses": "9.1; 9.2",
    "iso22301": "9.1; 9.2",
    "expectedEvidence": "İç denetim raporu, SIEM/EDR alarmları, KPI, kontrol test kayıtları",
    "typeIITestApproach": "Type II döneminde sürekli kontroller için sistem çıktısı; periyodik kontroller için örnek dönemler test edilir.",
    "currentDocuments": "İç Denetim; SIEM/EDR",
    "gapNote": "",
    "requiredAction": "SOC 2 control testing takvimi oluşturulmalı",
    "consultantStatus": "Kısmi",
    "source": "https://www.aicpa-cima.com/resources/download/2017-trust-services-criteria-with-revised-points-of-focus-2022"
  },
  {
    "tscId": "CC4.2",
    "tscCategory": "Security / Monitoring",
    "expectation": "Kontrol eksiklikleri zamanında değerlendirilir ve sorumlulara bildirilir.",
    "exampleControls": "Bulgu, olay, zafiyet ve uygunsuzluklar risk seviyesine göre takip edilir ve kapatılır.",
    "performingControls": "Ticket/DÖF sistemi ile bulgular atanır; kritik zafiyet ve olaylar eskale edilir; kapanış kanıtı BGYS/yönetimce izlenir.",
    "controlOwner": "BGYS / IT / Kontrol Sahipleri",
    "frequency": "Sürekli / aylık takip",
    "controlType": "Corrective / Detective",
    "nature": "IT-dependent Manual",
    "isoAnnex": "A.5.24; A.5.27; A.8.8",
    "isoControlTitles": "Olay yönetimi; Olaylardan öğrenme; Teknik açıklıkların yönetimi",
    "isoClauses": "9.1; 10.1; 10.2",
    "iso22301": "9.1; 10.1",
    "expectedEvidence": "DÖF, zafiyet kayıtları, olay kayıtları, kapanış kanıtları",
    "typeIITestApproach": "Dönem içi bulgulardan örneklemle SLA, atama, düzeltme ve kapanış doğrulanır.",
    "currentDocuments": "DÖF; Zafiyet/Olay kayıtları",
    "gapNote": "",
    "requiredAction": "Bulgu yaşlandırma ve SLA raporu eklenmeli",
    "consultantStatus": "Kısmi",
    "source": "https://www.aicpa-cima.com/resources/download/2017-trust-services-criteria-with-revised-points-of-focus-2022"
  },
  {
    "tscId": "CC5.1",
    "tscCategory": "Security / Control Activities",
    "expectation": "Riskleri azaltacak kontrol faaliyetleri seçilir ve geliştirilir.",
    "exampleControls": "Riskler uygun teknik/organizasyonel kontrollerle eşleştirilir.",
    "performingControls": "Risk işleme planlarında kontrol, sorumlu, termin ve kalan risk tanımlanır; ISO 27001 Ek A ve SOC 2 kontrolleri ile izlenir.",
    "controlOwner": "BGYS / Risk Sahipleri",
    "frequency": "Yıllık + risk bazlı",
    "controlType": "Preventive",
    "nature": "Manual",
    "isoAnnex": "A.5.1-A.8.34 (uygulanabilir kontroller)",
    "isoControlTitles": "Uygulanabilir bilgi güvenliği kontrolleri",
    "isoClauses": "6.1.3; 8.3",
    "iso22301": "6.1; 8.3",
    "expectedEvidence": "SoA, risk işleme planı, kontrol matrisi",
    "typeIITestApproach": "Seçilen risklerden kontrole izlenebilirlik ve uygulama kanıtı test edilir.",
    "currentDocuments": "SoA; Risk İşleme Planı",
    "gapNote": "",
    "requiredAction": "SOC 2-TSC-SoA üçlü eşleştirme tamamlanmalı",
    "consultantStatus": "Kısmi",
    "source": "https://www.aicpa-cima.com/resources/download/2017-trust-services-criteria-with-revised-points-of-focus-2022"
  },
  {
    "tscId": "CC5.2",
    "tscCategory": "Security / Control Activities",
    "expectation": "Teknolojiye ilişkin genel kontroller hedefleri destekleyecek şekilde seçilir ve geliştirilir.",
    "exampleControls": "Erişim, değişiklik, operasyon, güvenlik izleme, yedekleme ve zafiyet kontrolleri uygulanır.",
    "performingControls": "IAM/MFA/PAM, ticket/change, SIEM, EDR, vulnerability scanning, backup ve monitoring kontrolleri işletilir.",
    "controlOwner": "IT / DevOps / BGYS",
    "frequency": "Sürekli / tanımlı frekanslarda",
    "controlType": "Preventive / Detective",
    "nature": "Automated / IT-dependent Manual",
    "isoAnnex": "A.5.15-A.5.18; A.8.2-A.8.9; A.8.13; A.8.15; A.8.16; A.8.32",
    "isoControlTitles": "Erişim ve kimlik; teknik güvenlik; yedekleme; loglama/izleme; değişiklik",
    "isoClauses": "8.1",
    "iso22301": "8.1; 8.4",
    "expectedEvidence": "IAM, PAM, SIEM, EDR, scanner, backup, change kayıtları",
    "typeIITestApproach": "Her teknoloji kontrolü için konfigürasyon ve dönemsel çalışma örnekleri incelenir.",
    "currentDocuments": "BT prosedürleri ve sistem kayıtları",
    "gapNote": "",
    "requiredAction": "Kontrol konfigürasyon baseline'ları evidence olarak saklanmalı",
    "consultantStatus": "Kısmi",
    "source": "https://www.aicpa-cima.com/resources/download/2017-trust-services-criteria-with-revised-points-of-focus-2022"
  },
  {
    "tscId": "CC5.3",
    "tscCategory": "Security / Control Activities",
    "expectation": "Kontrol faaliyetleri politika ve prosedürlerle işletime alınır.",
    "exampleControls": "Politikalar kontrolün kim, ne zaman ve nasıl yapılacağını tanımlar.",
    "performingControls": "Politika/prosedürler doküman yönetim sistemiyle kontrollü tutulur; sorumluluk, frekans, kayıt ve gözden geçirme şartları tanımlanır.",
    "controlOwner": "BGYS / Süreç Sahipleri",
    "frequency": "Yıllık gözden geçirme",
    "controlType": "Preventive",
    "nature": "Manual",
    "isoAnnex": "A.5.1; A.5.37",
    "isoControlTitles": "Bilgi güvenliği politikaları; Dokümante işletim prosedürleri",
    "isoClauses": "5.2; 7.5; 8.1",
    "iso22301": "5.2; 7.5; 8.1",
    "expectedEvidence": "Politika/prosedürler, revizyon/onay kayıtları",
    "typeIITestApproach": "Dönem boyunca yürürlükteki doküman sürümleri ve revizyon/onay izi doğrulanır.",
    "currentDocuments": "Doküman Yönetimi",
    "gapNote": "",
    "requiredAction": "SOC 2 kontrollerinde frekans ve kanıt şartları prosedürlere eklenmeli",
    "consultantStatus": "Kısmi",
    "source": "https://www.aicpa-cima.com/resources/download/2017-trust-services-criteria-with-revised-points-of-focus-2022"
  },
  {
    "tscId": "CC6.1",
    "tscCategory": "Security / Logical & Physical Access",
    "expectation": "Mantıksal ve fiziksel erişimi koruyacak mekanizmalar uygulanır.",
    "exampleControls": "Kimlik doğrulama, MFA, ağ güvenliği, fiziksel erişim ve yetkilendirme uygulanır.",
    "performingControls": "Kurumsal IAM/AD, MFA, VPN, firewall, PAM ve fiziksel erişim kontrolleri kullanılır; erişimler yetki ihtiyacına göre verilir.",
    "controlOwner": "IT / BGYS / İdari İşler",
    "frequency": "Sürekli",
    "controlType": "Preventive",
    "nature": "Automated / IT-dependent Manual",
    "isoAnnex": "A.5.15; A.5.16; A.5.17; A.7.2; A.8.5; A.8.20",
    "isoControlTitles": "Erişim kontrolü; Kimlik yönetimi; Kimlik doğrulama; Fiziksel giriş; Güvenli kimlik doğrulama; Ağ güvenliği",
    "isoClauses": "8.1",
    "iso22301": "8.1; 8.4",
    "expectedEvidence": "IAM/MFA/VPN/PAM ayarları, firewall kuralları, fiziksel giriş logları",
    "typeIITestApproach": "Konfigürasyon ve kullanıcı örnekleriyle erişim mekanizmalarının dönem boyunca işlediği test edilir.",
    "currentDocuments": "Erişim Kontrol Prosedürü",
    "gapNote": "",
    "requiredAction": "Kritik sistem erişim envanteri tamamlanmalı",
    "consultantStatus": "Kısmi",
    "source": "https://www.aicpa-cima.com/resources/download/2017-trust-services-criteria-with-revised-points-of-focus-2022"
  },
  {
    "tscId": "CC6.2",
    "tscCategory": "Security / Logical Access",
    "expectation": "Yeni kullanıcı kimlikleri ve erişim hakları onaylı süreçle oluşturulur.",
    "exampleControls": "Joiner süreci ticket/onay ile yürütülür; least privilege uygulanır.",
    "performingControls": "HR tetiklemeli hesap açılışı ticket sistemi ile yürütülür; yönetici/sistem sahibi onayı alınır; rol bazlı minimum yetki atanır; MFA aktive edilir.",
    "controlOwner": "HR / IT / Sistem Sahibi",
    "frequency": "Her işe giriş/rol değişiminde",
    "controlType": "Preventive",
    "nature": "IT-dependent Manual",
    "isoAnnex": "A.5.16; A.5.18; A.8.2; A.8.3",
    "isoControlTitles": "Kimlik yönetimi; Erişim hakları; Ayrıcalıklı erişim; Bilgi erişim kısıtlaması",
    "isoClauses": "8.1",
    "iso22301": "8.1",
    "expectedEvidence": "Hesap açma ticketları, onaylar, IAM kayıtları, rol matrisi",
    "typeIITestApproach": "Dönemde açılan hesaplardan örneklem seçilerek talep-onay-atama zinciri test edilir.",
    "currentDocuments": "Erişim kayıtları",
    "gapNote": "",
    "requiredAction": "Joiner örneklemi için merkezi kanıt saklama",
    "consultantStatus": "Kısmi",
    "source": "https://www.aicpa-cima.com/resources/download/2017-trust-services-criteria-with-revised-points-of-focus-2022"
  },
  {
    "tscId": "CC6.3",
    "tscCategory": "Security / Logical Access",
    "expectation": "Erişim değişiklikleri ve kaldırılması zamanında ve kontrollü yapılır.",
    "exampleControls": "Mover/leaver süreçleri HR ve IT arasında entegre yürütülür.",
    "performingControls": "İşten ayrılışta hesaplar tanımlı sürede kapatılır; rol değişiminde eski yetkiler kaldırılır; ayrıcalıklı ve üçüncü taraf erişimleri ayrıca kontrol edilir.",
    "controlOwner": "HR / IT / Sistem Sahibi",
    "frequency": "Her ayrılış/rol değişiminde",
    "controlType": "Preventive",
    "nature": "IT-dependent Manual",
    "isoAnnex": "A.5.18; A.6.5",
    "isoControlTitles": "Erişim hakları; İş akdi sonrası/değişiklik sorumlulukları",
    "isoClauses": "8.1",
    "iso22301": "8.1",
    "expectedEvidence": "Offboarding kayıtları, hesap disable logları, ticketlar, erişim revizyonları",
    "typeIITestApproach": "Dönem ayrılan/değişen personel örneklerinde zamanında erişim kaldırma test edilir.",
    "currentDocuments": "İK çıkış süreci; IAM kayıtları",
    "gapNote": "",
    "requiredAction": "Offboarding SLA'sı açıkça tanımlanmalı",
    "consultantStatus": "Kısmi",
    "source": "https://www.aicpa-cima.com/resources/download/2017-trust-services-criteria-with-revised-points-of-focus-2022"
  },
  {
    "tscId": "CC6.4",
    "tscCategory": "Security / Physical Access",
    "expectation": "Fiziksel erişim yalnızca yetkili kişilerle sınırlandırılır ve kaldırılır.",
    "exampleControls": "Kartlı geçiş/ziyaretçi yönetimi ve kritik alan kontrolleri uygulanır.",
    "performingControls": "Ofis/sistem alanlarına fiziksel erişim yetkiye göre verilir; ziyaretçiler kayıt/eskort ile yönetilir; ayrılan personelin erişimi iptal edilir.",
    "controlOwner": "İdari İşler / IT / HR",
    "frequency": "Sürekli + değişiklikte",
    "controlType": "Preventive / Detective",
    "nature": "Automated / Manual",
    "isoAnnex": "A.7.1; A.7.2; A.7.3",
    "isoControlTitles": "Fiziksel güvenlik çevreleri; Fiziksel giriş; Ofis/oda güvenliği",
    "isoClauses": "8.1",
    "iso22301": "8.1",
    "expectedEvidence": "Kart geçiş logları, ziyaretçi kayıtları, yetkili liste, CCTV politika/kayıtları",
    "typeIITestApproach": "Dönem fiziksel erişim listesi ve örnek ziyaretçi/ayrılan personel kayıtları incelenir.",
    "currentDocuments": "Fiziksel Güvenlik Prosedürü",
    "gapNote": "",
    "requiredAction": "Fiziksel erişim periyodik review kaydı teyit edilmeli",
    "consultantStatus": "Kısmi",
    "source": "https://www.aicpa-cima.com/resources/download/2017-trust-services-criteria-with-revised-points-of-focus-2022"
  },
  {
    "tscId": "CC6.5",
    "tscCategory": "Security / Asset Disposal",
    "expectation": "Bilgi ve varlıklar imha/elden çıkarma öncesinde korunur ve güvenli şekilde silinir.",
    "exampleControls": "Güvenli silme ve medya imha süreci uygulanır.",
    "performingControls": "Disk, cihaz ve medya yeniden kullanım/elden çıkarma öncesi güvenli silinir veya fiziksel imha edilir; işlem kayıt altına alınır.",
    "controlOwner": "IT / İdari İşler",
    "frequency": "Olay bazlı",
    "controlType": "Preventive",
    "nature": "Manual / IT-dependent Manual",
    "isoAnnex": "A.7.10; A.7.14; A.8.10",
    "isoControlTitles": "Depolama ortamı; Ekipmanın güvenli imhası/yeniden kullanımı; Bilginin silinmesi",
    "isoClauses": "8.1",
    "iso22301": "8.1",
    "expectedEvidence": "İmha tutanakları, silme logları/sertifikaları, varlık kayıtları",
    "typeIITestApproach": "Dönemde elden çıkarılan varlıklardan örneklemle silme/imha kanıtı test edilir.",
    "currentDocuments": "Varlık Yönetimi",
    "gapNote": "",
    "requiredAction": "Silme yöntemi ve kanıt standardı tanımlanmalı",
    "consultantStatus": "Kısmi",
    "source": "https://www.aicpa-cima.com/resources/download/2017-trust-services-criteria-with-revised-points-of-focus-2022"
  },
  {
    "tscId": "CC6.6",
    "tscCategory": "Security / Boundary Protection",
    "expectation": "Sistem sınırları ve dış erişim noktaları yetkisiz erişime karşı korunur.",
    "exampleControls": "Firewall, VPN, segmentasyon, WAF ve güvenli protokoller uygulanır.",
    "performingControls": "Internet ve müşteri bağlantıları firewall/WAF/VPN üzerinden yönetilir; ağ segmentasyonu uygulanır; kurallar onaylı değişiklik sürecine tabidir; periyodik rule review yapılır.",
    "controlOwner": "Network / BGYS",
    "frequency": "Sürekli + 6 aylık/çeyreklik review",
    "controlType": "Preventive / Detective",
    "nature": "Automated / IT-dependent Manual",
    "isoAnnex": "A.8.20; A.8.21; A.8.22; A.8.24",
    "isoControlTitles": "Ağ güvenliği; Ağ hizmetlerinin güvenliği; Ağların ayrılması; Kriptografi",
    "isoClauses": "8.1",
    "iso22301": "8.1; 8.4",
    "expectedEvidence": "Firewall/WAF/VPN config, network diagram, rule review, change kayıtları",
    "typeIITestApproach": "Dönemden firewall değişiklikleri ve rule review kanıtı; konfigürasyon örneği test edilir.",
    "currentDocuments": "Ağ Güvenliği Politikası",
    "gapNote": "",
    "requiredAction": "Dış erişim noktaları envanteri ve veri akış diyagramı tamamlanmalı",
    "consultantStatus": "Kısmi",
    "source": "https://www.aicpa-cima.com/resources/download/2017-trust-services-criteria-with-revised-points-of-focus-2022"
  },
  {
    "tscId": "CC6.7",
    "tscCategory": "Security / Data Transmission",
    "expectation": "Veri iletimi sırasında yetkisiz erişim ve ifşaya karşı korunur.",
    "exampleControls": "TLS/VPN/SFTP ve kriptografik anahtar yönetimi uygulanır.",
    "performingControls": "Müşteri ve yönetim trafiğinde güvenli protokoller kullanılır; zayıf protokoller devre dışı bırakılır; sertifika/anahtar yaşam döngüsü yönetilir.",
    "controlOwner": "IT / DevOps / Network",
    "frequency": "Sürekli",
    "controlType": "Preventive",
    "nature": "Automated",
    "isoAnnex": "A.5.14; A.8.24",
    "isoControlTitles": "Bilgi transferi; Kriptografi kullanımı",
    "isoClauses": "8.1",
    "iso22301": "8.1",
    "expectedEvidence": "TLS/sertifika ayarları, VPN config, transfer prosedürü, anahtar kayıtları",
    "typeIITestApproach": "Konfigürasyon örnekleriyle şifreli iletişim ve sertifika geçerliliği doğrulanır.",
    "currentDocuments": "Kriptografi/Transfer Politikası",
    "gapNote": "",
    "requiredAction": "Kripto envanteri ve sertifika expiry izleme kanıtı eklenmeli",
    "consultantStatus": "Kısmi",
    "source": "https://www.aicpa-cima.com/resources/download/2017-trust-services-criteria-with-revised-points-of-focus-2022"
  },
  {
    "tscId": "CC6.8",
    "tscCategory": "Security / Malicious Software",
    "expectation": "Kötücül yazılımın sisteme girmesi, çalışması ve yayılması önlenir/tespit edilir.",
    "exampleControls": "EDR/antimalware, e-posta/web filtreleme, uygulama kontrolleri ve patching uygulanır.",
    "performingControls": "Kurumsal endpointlerde EDR/antivirus merkezi yönetilir; imza/agent durumu izlenir; e-posta güvenliği ve web filtreleme uygulanır; alarmlar olay sürecine aktarılır.",
    "controlOwner": "IT / BGYS",
    "frequency": "Sürekli",
    "controlType": "Preventive / Detective",
    "nature": "Automated",
    "isoAnnex": "A.8.7; A.8.8; A.8.19",
    "isoControlTitles": "Kötücül yazılımlara karşı koruma; Teknik açıklıklar; Yazılım kurulumu",
    "isoClauses": "8.1",
    "iso22301": "8.1",
    "expectedEvidence": "EDR konsol çıktıları, coverage raporu, malware olayları, patch kayıtları",
    "typeIITestApproach": "Dönem boyunca EDR coverage ve alarm örnekleri; istisnalar test edilir.",
    "currentDocuments": "Antivirüs/EDR Politikası",
    "gapNote": "",
    "requiredAction": "EDR coverage KPI ve istisna takibi formalize edilmeli",
    "consultantStatus": "Kısmi",
    "source": "https://www.aicpa-cima.com/resources/download/2017-trust-services-criteria-with-revised-points-of-focus-2022"
  },
  {
    "tscId": "CC7.1",
    "tscCategory": "Security / System Operations",
    "expectation": "Sistem ve bileşenler potansiyel zafiyet ve yanlış yapılandırmalar için izlenir.",
    "exampleControls": "Vulnerability scanning, patching, hardening ve güvenlik değerlendirmeleri uygulanır.",
    "performingControls": "Periyodik vulnerability scan yapılır; kritik bulgular SLA içinde giderilir; sistem baseline/hardening uygulanır; gerektiğinde penetration test yapılır.",
    "controlOwner": "BGYS / IT / DevOps",
    "frequency": "Aylık/çeyreklik + yıllık pentest",
    "controlType": "Detective / Corrective",
    "nature": "Automated / IT-dependent Manual",
    "isoAnnex": "A.8.8; A.8.9; A.8.29",
    "isoControlTitles": "Teknik açıklıkların yönetimi; Konfigürasyon yönetimi; Geliştirme/kabulde güvenlik testi",
    "isoClauses": "8.1; 9.1",
    "iso22301": "8.1; 9.1",
    "expectedEvidence": "Scan raporları, remediation ticketları, pentest, hardening kayıtları",
    "typeIITestApproach": "Scan frekansı, kritik bulgu SLA'sı ve kapanış örnekleri dönem boyunca test edilir.",
    "currentDocuments": "Zafiyet Yönetimi",
    "gapNote": "",
    "requiredAction": "SLA bazlı vulnerability aging dashboard önerilir",
    "consultantStatus": "Kısmi",
    "source": "https://www.aicpa-cima.com/resources/download/2017-trust-services-criteria-with-revised-points-of-focus-2022"
  },
  {
    "tscId": "CC7.2",
    "tscCategory": "Security / Monitoring",
    "expectation": "Anomaliler ve güvenlik olayları zamanında tespit edilir.",
    "exampleControls": "Merkezi log/SIEM, EDR ve altyapı izleme alarm üretir.",
    "performingControls": "Kritik sistem logları SIEM'e alınır; use-case/alert kuralları çalışır; NOC/SOC alarmları izler ve ticket/incident oluşturur.",
    "controlOwner": "BGYS / SOC-NOC / IT",
    "frequency": "7x24 / sürekli",
    "controlType": "Detective",
    "nature": "Automated / IT-dependent Manual",
    "isoAnnex": "A.8.15; A.8.16; A.8.17",
    "isoControlTitles": "Loglama; İzleme faaliyetleri; Saat senkronizasyonu",
    "isoClauses": "8.1; 9.1",
    "iso22301": "8.1; 9.1",
    "expectedEvidence": "SIEM log source list, alert kayıtları, monitoring dashboard, NTP config",
    "typeIITestApproach": "Dönem boyunca log kaynağı coverage ve alarm örnekleri incelenir; alert-to-ticket izi doğrulanır.",
    "currentDocuments": "Log Yönetimi; SIEM",
    "gapNote": "",
    "requiredAction": "SIEM use-case ve log source coverage matrisi hazırlanmalı",
    "consultantStatus": "Kısmi",
    "source": "https://www.aicpa-cima.com/resources/download/2017-trust-services-criteria-with-revised-points-of-focus-2022"
  },
  {
    "tscId": "CC7.3",
    "tscCategory": "Security / Event Evaluation",
    "expectation": "Tespit edilen olaylar değerlendirilir ve güvenlik olayı olup olmadığı belirlenir.",
    "exampleControls": "Triyaj, sınıflandırma, önem derecesi ve eskalasyon kriterleri uygulanır.",
    "performingControls": "SIEM/EDR/NOC alarmları tanımlı severity kriterleriyle triage edilir; gerçek olaylar incident kaydına dönüştürülür ve sorumlu ekibe eskale edilir.",
    "controlOwner": "BGYS / SOC-NOC",
    "frequency": "Her olayda",
    "controlType": "Detective",
    "nature": "IT-dependent Manual",
    "isoAnnex": "A.5.25; A.5.26",
    "isoControlTitles": "Bilgi güvenliği olaylarının değerlendirilmesi ve kararı; Olaylara müdahale",
    "isoClauses": "8.1",
    "iso22301": "8.1",
    "expectedEvidence": "Alert/incident kayıtları, severity matrisi, eskalasyon kayıtları",
    "typeIITestApproach": "Dönem olay örneklerinde tespit-triyaj-sınıflandırma zamanları ve karar kanıtı incelenir.",
    "currentDocuments": "Olay Yönetimi Prosedürü",
    "gapNote": "",
    "requiredAction": "Severity ve SOC 2 impact alanları ticketlarda teyit edilmeli",
    "consultantStatus": "Kısmi",
    "source": "https://www.aicpa-cima.com/resources/download/2017-trust-services-criteria-with-revised-points-of-focus-2022"
  },
  {
    "tscId": "CC7.4",
    "tscCategory": "Security / Incident Response",
    "expectation": "Güvenlik olaylarına müdahale edilir, etkileri sınırlandırılır ve hizmet geri kazanılır.",
    "exampleControls": "Incident response planı; containment, eradication, recovery ve iletişim adımlarını içerir.",
    "performingControls": "IR ekibi tanımlıdır; olaylar izole edilir, kök neden analizi yapılır, recovery yürütülür; müşteri/yönetim bildirimi gereklilikleri uygulanır.",
    "controlOwner": "BGYS / IT / Operasyon / Yönetim",
    "frequency": "Her olayda + yıllık tatbikat",
    "controlType": "Corrective",
    "nature": "Manual / IT-dependent Manual",
    "isoAnnex": "A.5.24; A.5.26; A.5.29; A.5.30",
    "isoControlTitles": "Olay yönetimi hazırlığı; Müdahale; Kesinti sırasında bilgi güvenliği; ICT sürekliliği",
    "isoClauses": "8.1; 10.1",
    "iso22301": "8.4; 8.5",
    "expectedEvidence": "Incident kayıtları, IR planı, RCA, iletişim kayıtları, tatbikat raporu",
    "typeIITestApproach": "Gerçek olaylar ve yıllık tatbikat üzerinden müdahale süreleri ve aksiyonlar test edilir.",
    "currentDocuments": "Olay Müdahale Planı; BCP",
    "gapNote": "",
    "requiredAction": "Yıllık tabletop/IR tatbikatı ve lessons learned kanıtı zorunlu tutulmalı",
    "consultantStatus": "Kısmi",
    "source": "https://www.aicpa-cima.com/resources/download/2017-trust-services-criteria-with-revised-points-of-focus-2022"
  },
  {
    "tscId": "CC7.5",
    "tscCategory": "Security / Recovery",
    "expectation": "Olay sonrası sistemler geri kazanılır ve tekrarını önleyici iyileştirmeler yapılır.",
    "exampleControls": "Recovery, RCA, lessons learned ve düzeltici faaliyet süreci işletilir.",
    "performingControls": "Incident kapanışında kök neden ve tekrar önleyici aksiyonlar kaydedilir; gerektiğinde risk, prosedür, SIEM use-case ve teknik kontroller güncellenir.",
    "controlOwner": "BGYS / IT / Süreç Sahibi",
    "frequency": "Her önemli olayda",
    "controlType": "Corrective",
    "nature": "Manual",
    "isoAnnex": "A.5.27; A.5.30",
    "isoControlTitles": "Bilgi güvenliği olaylarından öğrenme; ICT'nin iş sürekliliğine hazır oluşu",
    "isoClauses": "10.1; 10.2",
    "iso22301": "8.4; 10.1",
    "expectedEvidence": "RCA, lessons learned, DÖF, risk güncellemesi, recovery kayıtları",
    "typeIITestApproach": "Dönem önemli olaylarında kapanış ve takip aksiyonlarının tamamlanması test edilir.",
    "currentDocuments": "Olay/DÖF kayıtları",
    "gapNote": "",
    "requiredAction": "Post-incident review şablonu standardize edilmeli",
    "consultantStatus": "Kısmi",
    "source": "https://www.aicpa-cima.com/resources/download/2017-trust-services-criteria-with-revised-points-of-focus-2022"
  },
  {
    "tscId": "CC8.1",
    "tscCategory": "Security / Change Management",
    "expectation": "Altyapı, veri, yazılım ve prosedür değişiklikleri yetkili ve kontrollü şekilde gerçekleştirilir.",
    "exampleControls": "Talep, etki/risk analizi, onay, test, geri dönüş planı ve production deployment kayıt altındadır.",
    "performingControls": "Değişiklikler ticket sistemi üzerinden açılır; yetkili onay, test ve gerektiğinde rollback planı olmadan production'a alınmaz; acil değişiklikler sonradan gözden geçirilir.",
    "controlOwner": "IT / DevOps / Ürün / BGYS",
    "frequency": "Her değişiklikte",
    "controlType": "Preventive / Detective",
    "nature": "IT-dependent Manual / Automated",
    "isoAnnex": "A.8.25; A.8.29; A.8.31; A.8.32",
    "isoControlTitles": "Güvenli geliştirme yaşam döngüsü; Güvenlik testi; Ortamların ayrılması; Değişiklik yönetimi",
    "isoClauses": "8.1",
    "iso22301": "8.1; 8.4",
    "expectedEvidence": "Change ticketları, PR/MR, test sonuçları, approvals, deployment logları",
    "typeIITestApproach": "Dönem normal/acil değişiklik örnekleriyle onay-test-deploy ayrımı ve kanıtı test edilir.",
    "currentDocuments": "Değişiklik Yönetimi; SDLC",
    "gapNote": "",
    "requiredAction": "Acil değişiklik retrospektif onay kontrolü netleştirilmeli",
    "consultantStatus": "Kısmi",
    "source": "https://www.aicpa-cima.com/resources/download/2017-trust-services-criteria-with-revised-points-of-focus-2022"
  },
  {
    "tscId": "CC9.1",
    "tscCategory": "Security / Risk Mitigation",
    "expectation": "İş kesintileri dahil riskleri azaltacak faaliyetler tasarlanır ve uygulanır.",
    "exampleControls": "BIA, BCP/DR, yedekleme, kapasite ve alternatif çalışma düzenleri uygulanır.",
    "performingControls": "Kritik hizmetler BIA ile belirlenir; RTO/RPO tanımlanır; yedekleme/DR ve iş sürekliliği planları uygulanır ve test edilir.",
    "controlOwner": "BCM / IT / Operasyon",
    "frequency": "Yıllık + sürekli backup",
    "controlType": "Preventive / Corrective",
    "nature": "Manual / Automated",
    "isoAnnex": "A.5.29; A.5.30; A.8.13; A.8.14",
    "isoControlTitles": "Kesinti sırasında bilgi güvenliği; ICT sürekliliği; Yedekleme; İşleme tesislerinin yedekliliği",
    "isoClauses": "6.1; 8.1",
    "iso22301": "8.2; 8.3; 8.4; 8.5",
    "expectedEvidence": "BIA, BCP/DR, backup raporları, restore/DR testleri, RTO/RPO",
    "typeIITestApproach": "Dönem backup job örnekleri ve en az bir restore/DR testinin sonucu incelenir.",
    "currentDocuments": "ISO 22301 BIA/BCP/DR",
    "gapNote": "",
    "requiredAction": "SOC 2 hizmetleri ile BIA kapsamı birebir eşleştirilmeli",
    "consultantStatus": "Kısmi",
    "source": "https://www.aicpa-cima.com/resources/download/2017-trust-services-criteria-with-revised-points-of-focus-2022"
  },
  {
    "tscId": "CC9.2",
    "tscCategory": "Security / Vendor Risk",
    "expectation": "Tedarikçi ve iş ortaklarından kaynaklanan riskler değerlendirilir ve yönetilir.",
    "exampleControls": "Tedarikçi due diligence, sözleşmesel güvenlik şartları, periyodik değerlendirme ve çıkış kontrolleri uygulanır.",
    "performingControls": "Kritik tedarikçiler risk bazlı değerlendirilir; güvenlik/SLA/veri koruma şartları sözleşmeye alınır; performans ve güvenlik periyodik gözden geçirilir.",
    "controlOwner": "Satınalma / BGYS / Hukuk / Sistem Sahibi",
    "frequency": "Onboarding + yıllık",
    "controlType": "Preventive / Detective",
    "nature": "Manual",
    "isoAnnex": "A.5.19; A.5.20; A.5.21; A.5.22; A.5.23",
    "isoControlTitles": "Tedarikçi ilişkileri; anlaşmalarda güvenlik; ICT tedarik zinciri; tedarikçi hizmetlerini izleme; bulut hizmetleri",
    "isoClauses": "6.1.2; 8.1",
    "iso22301": "8.1",
    "expectedEvidence": "Tedarikçi envanteri, risk değerlendirmesi, sözleşmeler, review kayıtları, SOC/ISO raporları",
    "typeIITestApproach": "Kritik tedarikçi örneklerinde onboarding, sözleşme ve dönemsel review kanıtı incelenir.",
    "currentDocuments": "Tedarikçi Yönetimi",
    "gapNote": "",
    "requiredAction": "Kritiklik sınıflandırması ve yıllık security review standardize edilmeli",
    "consultantStatus": "Kısmi",
    "source": "https://www.aicpa-cima.com/resources/download/2017-trust-services-criteria-with-revised-points-of-focus-2022"
  },
  {
    "tscId": "A1.1",
    "tscCategory": "Availability",
    "expectation": "Erişilebilirlik hedeflerini desteklemek için mevcut ve gelecekteki kapasite yönetilir.",
    "exampleControls": "Kapasite eşikleri, trendler, kaynak kullanımı ve büyüme tahminleri izlenir.",
    "performingControls": "Monitoring sistemi CPU/RAM/storage/network ve servis metriklerini izler; eşik aşımlarında alarm üretir; kapasite trendleri ve ihtiyaçlar periyodik değerlendirilir.",
    "controlOwner": "IT / NOC / Operasyon",
    "frequency": "Sürekli + aylık/çeyreklik review",
    "controlType": "Preventive / Detective",
    "nature": "Automated / IT-dependent Manual",
    "isoAnnex": "A.8.6; A.8.14; A.8.16",
    "isoControlTitles": "Kapasite yönetimi; İşleme tesislerinin yedekliliği; İzleme faaliyetleri",
    "isoClauses": "8.1; 9.1",
    "iso22301": "8.3; 8.4",
    "expectedEvidence": "Monitoring dashboard, kapasite raporları, alarm/ticket kayıtları",
    "typeIITestApproach": "Dönem boyunca monitoring coverage ve kapasite review örnekleri test edilir.",
    "currentDocuments": "Kapasite Planlama Prosedürü",
    "gapNote": "",
    "requiredAction": "SOC 2 hizmetleri için kapasite KPI/eşik listesi teyit edilmeli",
    "consultantStatus": "Kısmi",
    "source": "https://www.aicpa-cima.com/resources/download/2017-trust-services-criteria-with-revised-points-of-focus-2022"
  },
  {
    "tscId": "A1.2",
    "tscCategory": "Availability",
    "expectation": "Çevresel tehditlere karşı sistemlerin erişilebilirliği korunur.",
    "exampleControls": "Elektrik, iklimlendirme, yangın, fiziksel güvenlik ve veri merkezi dayanıklılığı yönetilir.",
    "performingControls": "Kritik altyapı/data center hizmetlerinde UPS/jeneratör/iklimlendirme/yangın ve fiziksel güvenlik kontrolleri kuruluş veya sağlayıcı kontrolleriyle güvence altına alınır; sağlayıcı raporları izlenir.",
    "controlOwner": "IT / İdari İşler / Tedarikçi Sahibi",
    "frequency": "Sürekli + yıllık review",
    "controlType": "Preventive / Detective",
    "nature": "Automated / Manual",
    "isoAnnex": "A.7.5; A.7.11; A.7.12; A.8.14",
    "isoControlTitles": "Fiziksel/çevresel tehditler; Destekleyici altyapı; Kablolama; Yedeklilik",
    "isoClauses": "8.1",
    "iso22301": "8.4",
    "expectedEvidence": "DC sertifikaları/SOC raporları, bakım kayıtları, UPS/jeneratör testleri, fiziksel kontroller",
    "typeIITestApproach": "İç kontrol veya subservice organization kanıtları dönem için incelenir.",
    "currentDocuments": "BCP/DR; Tedarikçi kayıtları",
    "gapNote": "",
    "requiredAction": "Subservice organization yaklaşımı (inclusive/carve-out) denetçiyle netleştirilmeli",
    "consultantStatus": "Eksik",
    "source": "https://www.aicpa-cima.com/resources/download/2017-trust-services-criteria-with-revised-points-of-focus-2022"
  },
  {
    "tscId": "A1.3",
    "tscCategory": "Availability",
    "expectation": "Erişilebilirlik olaylarında kurtarma ve süreklilik planları test edilir.",
    "exampleControls": "BCP/DR ve restore testleri yapılır; sonuçlara göre iyileştirme gerçekleştirilir.",
    "performingControls": "RTO/RPO bazlı DR senaryoları ve backup restore testleri planlı yapılır; başarısızlıklar DÖF/risk aksiyonuna dönüştürülür.",
    "controlOwner": "BCM / IT / Operasyon",
    "frequency": "En az yıllık + restore periyodik",
    "controlType": "Corrective / Detective",
    "nature": "Manual / Automated",
    "isoAnnex": "A.5.30; A.8.13; A.8.14",
    "isoControlTitles": "ICT sürekliliği; Yedekleme; Yedeklilik",
    "isoClauses": "8.1; 9.1; 10.1",
    "iso22301": "8.4; 8.5; 9.1; 10.1",
    "expectedEvidence": "DR/BCP test planı, restore sonuçları, tatbikat raporu, aksiyonlar",
    "typeIITestApproach": "Denetim döneminde gerçekleşen testin kapsamı, başarı kriterleri ve kapanış aksiyonları incelenir.",
    "currentDocuments": "ISO 22301 tatbikat/test kayıtları",
    "gapNote": "",
    "requiredAction": "Testlerin SOC 2 kapsam sistemlerini kapsadığı açıkça gösterilmeli",
    "consultantStatus": "Kısmi",
    "source": "https://www.aicpa-cima.com/resources/download/2017-trust-services-criteria-with-revised-points-of-focus-2022"
  },
  {
    "tscId": "C1.1",
    "tscCategory": "Confidentiality",
    "expectation": "Gizli bilgi tanımlanır, sınıflandırılır ve korunmasına ilişkin gereksinimler belirlenir.",
    "exampleControls": "Veri sınıflandırma, etiketleme, erişim ve kriptografi kuralları uygulanır.",
    "performingControls": "Bilgiler sınıflandırma politikasına göre etiketlenir; müşteri/gizli bilgiye erişim need-to-know esaslıdır; aktarım ve saklama korumaları sınıfa göre uygulanır.",
    "controlOwner": "BGYS / Veri Sahipleri / IT",
    "frequency": "Sürekli + yıllık review",
    "controlType": "Preventive",
    "nature": "Manual / Automated",
    "isoAnnex": "A.5.12; A.5.13; A.5.14; A.8.3; A.8.24",
    "isoControlTitles": "Bilgi sınıflandırma; Etiketleme; Bilgi transferi; Erişim kısıtlama; Kriptografi",
    "isoClauses": "6.1; 8.1",
    "iso22301": "8.1",
    "expectedEvidence": "Sınıflandırma politikası, veri envanteri, etiket örnekleri, erişim/şifreleme kayıtları",
    "typeIITestApproach": "Gizli veri örneklerinde sınıflandırma, erişim ve koruma kontrolleri test edilir.",
    "currentDocuments": "Bilgi Sınıflandırma Politikası",
    "gapNote": "",
    "requiredAction": "SOC 2 kapsamındaki müşteri verileri için data inventory/data flow tamamlanmalı",
    "consultantStatus": "Kısmi",
    "source": "https://www.aicpa-cima.com/resources/download/2017-trust-services-criteria-with-revised-points-of-focus-2022"
  },
  {
    "tscId": "C1.2",
    "tscCategory": "Confidentiality",
    "expectation": "Gizli bilgi, saklama süresi sonunda güvenli biçimde imha edilir.",
    "exampleControls": "Saklama/imha takvimi ve güvenli silme mekanizmaları uygulanır.",
    "performingControls": "Sözleşme, yasal ve iş gereksinimlerine göre saklama süreleri tanımlanır; süre sonunda sistem/backup/medya dahil uygun yöntemle silme veya anonimleştirme uygulanır ve kayıt tutulur.",
    "controlOwner": "Veri Sahibi / IT / Hukuk / BGYS",
    "frequency": "Periyodik + olay bazlı",
    "controlType": "Preventive / Corrective",
    "nature": "Manual / IT-dependent Manual",
    "isoAnnex": "A.5.33; A.7.14; A.8.10",
    "isoControlTitles": "Kayıtların korunması; Ekipmanın güvenli imhası; Bilginin silinmesi",
    "isoClauses": "7.5; 8.1",
    "iso22301": "7.5; 8.1",
    "expectedEvidence": "Saklama-imha tablosu, silme ticket/logları, imha sertifikaları",
    "typeIITestApproach": "Dönem silme/imha örneklerinde onay, yöntem ve tamamlanma kanıtı test edilir.",
    "currentDocuments": "Kayıtların Kontrolü / Veri İmha",
    "gapNote": "",
    "requiredAction": "Backup üzerindeki silme/retention yaklaşımı dokümante edilmeli",
    "consultantStatus": "Kısmi",
    "source": "https://www.aicpa-cima.com/resources/download/2017-trust-services-criteria-with-revised-points-of-focus-2022"
  }
];
