import { NextRequest, NextResponse } from "next/server";
import { requireRole } from "../../auth/security";
import { AI_OBLIGATION_FRAMEWORKS, AI_OBLIGATION_PRIORITIES, nextObligationDueDate, obligationSchedule, validateAiObligation, validateObligationAction } from "@/app/ai/obligations";
import { cleanAiText } from "@/app/ai/security";
import { aiRuntime, recordAiEvent } from "@/app/ai/storage";

const json=(data:unknown,status=200)=>NextResponse.json(data,{status,headers:{"cache-control":"no-store"}}),
  cell=(value:unknown)=>{const raw=String(value??""),safe=/^[=+\-@]/.test(raw)?`'${raw}`:raw;return `"${safe.replace(/"/g,'""')}"`;},
  map=(row:Record<string,unknown>)=>{const schedule=obligationSchedule(String(row.status),String(row.priority),String(row.due_date));return{id:row.id,modelId:row.model_id,profileId:row.profile_id,renewalOfId:row.renewal_of_id,cycleNumber:Number(row.cycle_number||1),framework:row.framework,obligationCode:row.obligation_code,title:row.title,description:row.description,owner:row.owner,reviewer:row.reviewer,dueDate:row.due_date,priority:row.priority,evidencePlan:row.evidence_plan,recurringDays:Number(row.recurring_days||0),status:row.status,state:schedule.state,daysRemaining:schedule.daysRemaining,reminderLevel:schedule.reminderLevel,actionNote:row.action_note,evidenceReference:row.evidence_reference,evidenceSha256:row.evidence_sha256,verificationEvidenceReference:row.verification_evidence_reference,verificationEvidenceSha256:row.verification_evidence_sha256,createdBy:row.created_by,submittedBy:row.submitted_by,verifiedBy:row.verified_by,updatedAt:row.updated_at};};

export async function GET(req:NextRequest){
  const access=await requireRole(req,["Admin","Editor","Viewer"]);if(access.response)return access.response;
  const{DB}=await aiRuntime(),[models,profiles,result]=await Promise.all([
    DB.prepare("SELECT id,system_name,model_name,status FROM ai_model_inventory WHERE status!='retired' ORDER BY system_name LIMIT 500").all<Record<string,unknown>>(),
    DB.prepare("SELECT id,model_id,classification,status FROM ai_regulatory_profiles WHERE status!='retired' ORDER BY updated_at DESC LIMIT 500").all<Record<string,unknown>>(),
    DB.prepare("SELECT * FROM ai_regulatory_obligations ORDER BY CASE priority WHEN 'Critical' THEN 0 WHEN 'High' THEN 1 WHEN 'Medium' THEN 2 ELSE 3 END,due_date,updated_at DESC LIMIT 1000").all<Record<string,unknown>>(),
  ]),obligations=(result.results||[]).map(map);
  if(req.nextUrl.searchParams.get("format")){if(access.actor.role!=="Admin")return json({error:"Yükümlülük kanıt çıktısı yalnız Admin tarafından alınabilir."},403);const reminderOnly=req.nextUrl.searchParams.get("format")==="reminders",exportRows=reminderOnly?obligations.filter(item=>item.reminderLevel!=="none"&&item.status!=="completed"):obligations,rows=[["Yükümlülük","Model","Profil","Dönem","Önceki dönem","Çerçeve","Kod","Başlık","Öncelik","Sahip","Doğrulayıcı","Son tarih","Kalan gün","Uyarı","Durum","Kanıt","SHA-256"],...exportRows.map(item=>[item.id,item.modelId,item.profileId||"",item.cycleNumber,item.renewalOfId||"",item.framework,item.obligationCode,item.title,item.priority,item.owner,item.reviewer,item.dueDate,item.daysRemaining,item.reminderLevel,item.state,item.evidenceReference||"",item.evidenceSha256||""])];await recordAiEvent(DB,{actor:access.actor.email,action:reminderOnly?"ai-obligation-reminder-export":"ai-obligation-export",contextRefs:exportRows.map(item=>String(item.id)).slice(0,80),status:"success",detail:`${exportRows.length} bounded records; formula-safe csv`});return new NextResponse(`\uFEFF${rows.map(row=>row.map(cell).join(",")).join("\n")}`,{headers:{"cache-control":"no-store","content-type":"text/csv; charset=utf-8","content-disposition":`attachment; filename=fornost-ai-${reminderOnly?"obligation-reminders":"regulatory-obligations"}.csv`}});}
  return json({frameworks:AI_OBLIGATION_FRAMEWORKS,priorities:AI_OBLIGATION_PRIORITIES,models:(models.results||[]).map(row=>({id:row.id,systemName:row.system_name,modelName:row.model_name,status:row.status})),profiles:(profiles.results||[]).map(row=>({id:row.id,modelId:row.model_id,classification:row.classification,status:row.status})),obligations,reminders:obligations.filter(item=>item.reminderLevel!=="none"&&item.status!=="completed").slice(0,100),summary:{total:obligations.length,open:obligations.filter(item=>item.status!=="completed").length,verification:obligations.filter(item=>item.status==="verification").length,due30:obligations.filter(item=>item.state==="due-30").length,due15:obligations.filter(item=>item.state==="due-15").length,due7:obligations.filter(item=>item.state==="due-7").length,overdue:obligations.filter(item=>item.state==="overdue").length,blocking:obligations.filter(item=>item.status!=="completed"&&(["High","Critical"].includes(String(item.priority))||item.state==="overdue")).length,completed:obligations.filter(item=>item.status==="completed").length}});
}

export async function POST(req:NextRequest){
  const access=await requireRole(req,["Admin","Editor"]);if(access.response)return access.response;if(Number(req.headers.get("content-length")||0)>32_768)return json({error:"Yükümlülük isteği çok büyük."},413);
  const body=await req.json().catch(()=>({}));let value;try{value=validateAiObligation(body);}catch(error){return json({error:error instanceof Error?error.message:"Yükümlülük doğrulanamadı."},400);}
  const{DB}=await aiRuntime();if(!(await DB.prepare("SELECT id FROM ai_model_inventory WHERE id=? AND status!='retired'").bind(value.modelId).first()))return json({error:"Etkin AI modeli bulunamadı."},409);
  if(value.profileId&&!(await DB.prepare("SELECT id FROM ai_regulatory_profiles WHERE id=? AND model_id=? AND status!='retired'").bind(value.profileId,value.modelId).first()))return json({error:"Regülasyon profili bu AI modeline ait değil."},409);
  const id=`AIOB-${crypto.randomUUID()}`,now=new Date().toISOString();try{await DB.prepare("INSERT INTO ai_regulatory_obligations(id,model_id,profile_id,framework,obligation_code,title,description,owner,reviewer,due_date,priority,evidence_plan,recurring_days,status,created_by,created_at,updated_by,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,'open',?,?,?,?)").bind(id,value.modelId,value.profileId||null,value.framework,value.obligationCode,value.title,value.description,value.owner,value.reviewer,value.dueDate,value.priority,value.evidencePlan,value.recurringDays,access.actor.email,now,access.actor.email,now).run();}catch{return json({error:"Bu model, çerçeve ve kod için açık yükümlülük zaten var."},409);}
  await recordAiEvent(DB,{actor:access.actor.email,action:"ai-obligation-create",contextRefs:[value.modelId,value.profileId||"",id],status:"success",detail:`${value.framework}; ${value.obligationCode}; ${value.priority}; due ${value.dueDate}`});return json({id},201);
}

export async function PATCH(req:NextRequest){
  const access=await requireRole(req,["Admin","Editor"]);if(access.response)return access.response;const body=await req.json().catch(()=>({})),id=cleanAiText(body.id,100);let action;try{action=validateObligationAction(body);}catch(error){return json({error:error instanceof Error?error.message:"İşlem geçersiz."},400);}
  const{DB}=await aiRuntime(),row=await DB.prepare("SELECT * FROM ai_regulatory_obligations WHERE id=?").bind(id).first<Record<string,unknown>>();if(!row)return json({error:"AI yükümlülüğü bulunamadı."},404);
  const transitions:Record<string,Record<string,string>>={open:{start:"in-progress"},"in-progress":{submit:"verification"},verification:{verify:"completed",reopen:"in-progress"},completed:{reopen:"in-progress"}},next=transitions[String(row.status)]?.[action.action];if(!next)return json({error:`${action.action} işlemi ${row.status} durumundan uygulanamaz.`},409);
  if(["verify","reopen"].includes(action.action)&&access.actor.role!=="Admin")return json({error:"Doğrulama ve yeniden açma yalnız Admin tarafından yapılabilir."},403);if(action.action==="verify"&&(row.submitted_by===access.actor.email||row.created_by===access.actor.email))return json({error:"Kaydı oluşturan veya doğrulamaya gönderen kişi aynı yükümlülüğü doğrulayamaz."},409);if(action.action==="reopen"&&await DB.prepare("SELECT id FROM ai_regulatory_obligations WHERE model_id=? AND framework=? AND obligation_code=? AND status!='completed' AND id!=?").bind(row.model_id,row.framework,row.obligation_code,id).first())return json({error:"Aynı yükümlülük için başka bir açık kayıt var."},409);
  const now=new Date().toISOString(),submittedBy=action.action==="submit"?access.actor.email:row.submitted_by,submittedAt=action.action==="submit"?now:row.submitted_at,verifiedBy=action.action==="verify"?access.actor.email:action.action==="reopen"?null:row.verified_by,verifiedAt=action.action==="verify"?now:action.action==="reopen"?null:row.verified_at,reopenedBy=action.action==="reopen"?access.actor.email:row.reopened_by,reopenedAt=action.action==="reopen"?now:row.reopened_at,
    update=DB.prepare("UPDATE ai_regulatory_obligations SET status=?,action_note=?,evidence_reference=?,evidence_sha256=?,verification_evidence_reference=?,verification_evidence_sha256=?,updated_by=?,updated_at=?,submitted_by=?,submitted_at=?,verified_by=?,verified_at=?,reopened_by=?,reopened_at=? WHERE id=?").bind(next,action.note,action.action==="submit"?action.evidenceReference:row.evidence_reference,action.action==="submit"?action.evidenceSha256:row.evidence_sha256,action.action==="verify"?action.evidenceReference:row.verification_evidence_reference,action.action==="verify"?action.evidenceSha256:row.verification_evidence_sha256,access.actor.email,now,submittedBy,submittedAt,verifiedBy,verifiedAt,reopenedBy,reopenedAt,id);
  let renewalId:string|null=null,nextDueDate:string|null=null;
  if(action.action==="verify"&&Number(row.recurring_days||0)>0){renewalId=`AIOB-${crypto.randomUUID()}`;nextDueDate=nextObligationDueDate(String(row.due_date),Number(row.recurring_days),now.slice(0,10));const renewal=DB.prepare("INSERT INTO ai_regulatory_obligations(id,model_id,profile_id,renewal_of_id,cycle_number,framework,obligation_code,title,description,owner,reviewer,due_date,priority,evidence_plan,recurring_days,status,created_by,created_at,updated_by,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,'open',?,?,?,?)").bind(renewalId,row.model_id,row.profile_id,id,Number(row.cycle_number||1)+1,row.framework,row.obligation_code,row.title,row.description,row.owner,row.reviewer,nextDueDate,row.priority,row.evidence_plan,row.recurring_days,access.actor.email,now,access.actor.email,now);await DB.batch([update,renewal]);}else await update.run();
  await recordAiEvent(DB,{actor:access.actor.email,action:`ai-obligation-${action.action}`,promptHash:(["submit","verify"].includes(action.action)?action.evidenceSha256:String(row.evidence_sha256||""))||undefined,contextRefs:[String(row.model_id),String(row.profile_id||""),id,...(renewalId?[renewalId]:[])],status:"success",detail:`${row.framework}; ${row.obligation_code}; ${row.status}->${next}; separation-of-duties${renewalId?`; renewal ${renewalId} due ${nextDueDate}`:""}`});return json({ok:true,status:next,renewalId,nextDueDate});
}
