import {NextRequest,NextResponse} from "next/server";
import {requireRole} from "../auth/security";
import {clean} from "../integrations/security";
import {incidentAttention,validateIncident,validateIncidentAction} from "../../incidents/domain";
type Env=Record<string,unknown>&{DB:D1Database};
const schema=[
`CREATE TABLE IF NOT EXISTS enterprise_incidents(id TEXT PRIMARY KEY NOT NULL,code TEXT NOT NULL UNIQUE,title TEXT NOT NULL,category TEXT NOT NULL,severity TEXT NOT NULL,detected_date TEXT NOT NULL,description TEXT NOT NULL,business_impact TEXT NOT NULL,owner TEXT NOT NULL,commander TEXT NOT NULL,reviewer TEXT NOT NULL,asset_refs TEXT NOT NULL,risk_ref TEXT,bia_ref TEXT,data_classification TEXT NOT NULL,personal_data INTEGER NOT NULL DEFAULT 0,status TEXT NOT NULL DEFAULT 'declared',root_cause TEXT,lessons_learned TEXT,notification_decision TEXT NOT NULL DEFAULT 'pending',notification_rationale TEXT,evidence_reference TEXT,evidence_sha256 TEXT,declared_by TEXT NOT NULL,declared_at TEXT NOT NULL,updated_by TEXT NOT NULL,updated_at TEXT NOT NULL,closed_by TEXT,closed_at TEXT,reopen_count INTEGER NOT NULL DEFAULT 0)`,
`CREATE INDEX IF NOT EXISTS enterprise_incidents_status_severity_idx ON enterprise_incidents(status,severity,detected_date)`,
`CREATE TABLE IF NOT EXISTS enterprise_incident_events(id TEXT PRIMARY KEY NOT NULL,incident_id TEXT NOT NULL,action TEXT NOT NULL,from_status TEXT,to_status TEXT,detail TEXT NOT NULL,evidence_reference TEXT,evidence_sha256 TEXT,actor TEXT NOT NULL,created_at TEXT NOT NULL)`,
`CREATE INDEX IF NOT EXISTS enterprise_incident_events_incident_date_idx ON enterprise_incident_events(incident_id,created_at)`];
async function runtime(){const{env}=await import("cloudflare:workers");return env as unknown as Env}async function ready(db:D1Database){for(const sql of schema)await db.prepare(sql).run()}
const json=(data:unknown,status=200)=>NextResponse.json(data,{status,headers:{"cache-control":"no-store"}}),csvCell=(value:unknown)=>{const raw=String(value??""),safe=/^[=+\-@]/.test(raw)?`'${raw}`:raw;return`"${safe.replace(/"/g,'""')}"`};
async function audit(db:D1Database,input:{incidentId:string;action:string;from?:string;to?:string;detail:string;evidenceReference?:string;evidenceSha256?:string;actor:string}){await db.prepare("INSERT INTO enterprise_incident_events(id,incident_id,action,from_status,to_status,detail,evidence_reference,evidence_sha256,actor,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)").bind(crypto.randomUUID(),input.incidentId,input.action,input.from||null,input.to||null,input.detail.slice(0,3000),input.evidenceReference||null,input.evidenceSha256||null,input.actor,new Date().toISOString()).run()}
function map(row:Record<string,unknown>){return{id:row.id,code:row.code,title:row.title,category:row.category,severity:row.severity,detectedDate:row.detected_date,description:row.description,businessImpact:row.business_impact,owner:row.owner,commander:row.commander,reviewer:row.reviewer,assetRefs:row.asset_refs,riskRef:row.risk_ref,biaRef:row.bia_ref,dataClassification:row.data_classification,personalData:Boolean(row.personal_data),status:row.status,rootCause:row.root_cause,lessonsLearned:row.lessons_learned,notificationDecision:row.notification_decision,notificationRationale:row.notification_rationale,evidenceReference:row.evidence_reference,reopenCount:Number(row.reopen_count||0),updatedAt:row.updated_at,attention:incidentAttention(String(row.status),String(row.severity),String(row.detected_date))}}

export async function GET(req:NextRequest){const access=await requireRole(req,["Admin","Editor","Viewer"]);if(access.response)return access.response;const env=await runtime();await ready(env.DB);const[records,events]=await Promise.all([env.DB.prepare("SELECT * FROM enterprise_incidents ORDER BY CASE severity WHEN 'critical' THEN 0 WHEN 'high' THEN 1 WHEN 'medium' THEN 2 ELSE 3 END,detected_date DESC,updated_at DESC LIMIT 3000").all<Record<string,unknown>>(),env.DB.prepare("SELECT * FROM enterprise_incident_events ORDER BY created_at DESC LIMIT 1000").all<Record<string,unknown>>()]);const incidents=records.results.map(map),summary={total:incidents.length,active:incidents.filter(x=>x.status!=="closed").length,critical:incidents.filter(x=>x.severity==="critical"&&x.status!=="closed").length,breached:incidents.filter(x=>String(x.attention).includes("breach")).length,contained:incidents.filter(x=>x.status==="contained").length,recovery:incidents.filter(x=>["eradicated","recovered"].includes(String(x.status))).length,review:incidents.filter(x=>x.status==="review").length,personalData:incidents.filter(x=>x.personalData&&x.status!=="closed").length};
 if(req.nextUrl.searchParams.get("format")==="csv"){if(access.actor.role!=="Admin")return json({error:"Olay çıktısı yalnız Admin tarafından alınabilir."},403);const rows=[["Kod","Başlık","Kategori","Önem","Durum","Tespit","Sahip","Commander","Reviewer","Varlıklar","Risk","BIA","Kişisel Veri","Bildirim","Dikkat"],...incidents.map(x=>[x.code,x.title,x.category,x.severity,x.status,x.detectedDate,x.owner,x.commander,x.reviewer,x.assetRefs,x.riskRef||"",x.biaRef||"",x.personalData?"yes":"no",x.notificationDecision,x.attention])];await audit(env.DB,{incidentId:"EXPORT",action:"incident-export",detail:`${incidents.length} bounded formula-safe records`,actor:access.actor.email});return new NextResponse(`\uFEFF${rows.map(row=>row.map(csvCell).join(",")).join("\n")}`,{headers:{"cache-control":"no-store","content-type":"text/csv; charset=utf-8","content-disposition":"attachment; filename=fornost-security-incidents.csv"}})}
 return json({incidents,events:events.results.map(x=>({id:x.id,incidentId:x.incident_id,action:x.action,fromStatus:x.from_status,toStatus:x.to_status,detail:x.detail,actor:x.actor,createdAt:x.created_at})),summary})}

export async function POST(req:NextRequest){if(Number(req.headers.get("content-length")||0)>262_144)return json({error:"İstek boyutu çok büyük."},413);const body=await req.json().catch(()=>({})) as Record<string,unknown>,action=clean(body.action,40),access=await requireRole(req,["Admin","Editor"]);if(access.response)return access.response;const env=await runtime();await ready(env.DB);try{
 if(action==="create"){const x=validateIncident(body),id=`INC-${crypto.randomUUID()}`,code=`INC-${new Date().getUTCFullYear()}-${crypto.randomUUID().replace(/-/g,"").slice(0,8).toUpperCase()}`,now=new Date().toISOString();await env.DB.prepare("INSERT INTO enterprise_incidents(id,code,title,category,severity,detected_date,description,business_impact,owner,commander,reviewer,asset_refs,risk_ref,bia_ref,data_classification,personal_data,status,declared_by,declared_at,updated_by,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?, 'declared',?,?,?,?)").bind(id,code,x.title,x.category,x.severity,x.detectedDate,x.description,x.businessImpact,x.owner,x.commander,x.reviewer,x.assetRefs,x.riskRef||null,x.biaRef||null,x.dataClassification,x.personalData?1:0,access.actor.email,now,access.actor.email,now).run();await audit(env.DB,{incidentId:id,action:"incident-declare",to:"declared",detail:`${code}; ${x.category}; ${x.severity}; ${x.assetRefs}`,actor:access.actor.email});return json({id,code,message:"Güvenlik olayı ilan edildi."},201)}
 if(action==="transition"){const id=clean(body.incidentId,100),a=validateIncidentAction(body),x=await env.DB.prepare("SELECT * FROM enterprise_incidents WHERE id=?").bind(id).first<Record<string,unknown>>();if(!x)return json({error:"Olay bulunamadı."},404);const status=String(x.status),now=new Date().toISOString(),flow:Record<string,{from:string[];to:string}>={triage:{from:["declared"],to:"triage"},contain:{from:["triage"],to:"contained"},eradicate:{from:["contained"],to:"eradicated"},recover:{from:["eradicated"],to:"recovered"},review:{from:["recovered"],to:"review"},close:{from:["review"],to:"closed"},reopen:{from:["closed"],to:"triage"}},step=flow[a.operation];if(!step||!step.from.includes(status))return json({error:"Olay yaşam döngüsü geçişi geçersiz."},409);
  if(a.operation==="close"){if(access.actor.role!=="Admin"||x.reviewer!==access.actor.email)return json({error:"Olayı yalnız atanmış bağımsız Admin reviewer kapatabilir."},403);if([x.declared_by,x.owner,x.commander].includes(access.actor.email))return json({error:"Maker-checker: ilan eden, olay sahibi veya commander olayı kapatamaz."},409)}else if(a.operation!=="reopen"&&access.actor.role!=="Admin"&&![x.owner,x.commander].includes(access.actor.email))return json({error:"Olayı yalnız atanmış ekip veya Admin ilerletebilir."},403);else if(a.operation==="reopen"&&access.actor.role!=="Admin")return json({error:"Kapalı olayı yalnız Admin yeniden açabilir."},403);
  const updates=["status=?","updated_by=?","updated_at=?"],values:unknown[]=[step.to,access.actor.email,now];if(a.evidenceReference){updates.push("evidence_reference=?","evidence_sha256=?");values.push(a.evidenceReference,a.evidenceSha256)}if(a.operation==="review"){updates.push("root_cause=?","lessons_learned=?","notification_decision=?","notification_rationale=?");values.push(a.rootCause,a.lessonsLearned,a.notificationDecision,a.notificationRationale)}if(a.operation==="close"){updates.push("notification_decision=?","notification_rationale=?","closed_by=?","closed_at=?");values.push(a.notificationDecision,a.notificationRationale,access.actor.email,now)}if(a.operation==="reopen"){updates.push("reopen_count=reopen_count+1","closed_by=NULL","closed_at=NULL")}values.push(id);await env.DB.prepare(`UPDATE enterprise_incidents SET ${updates.join(",")} WHERE id=?`).bind(...values).run();await audit(env.DB,{incidentId:id,action:a.operation,from:status,to:step.to,detail:a.note,evidenceReference:a.evidenceReference,evidenceSha256:a.evidenceSha256,actor:access.actor.email});return json({message:"Olay yaşam döngüsü güncellendi.",status:step.to})}
 return json({error:"Geçersiz işlem."},400)}catch(error){return json({error:error instanceof Error?error.message:"İşlem tamamlanamadı."},400)}}
